REQUIRE
bin/loadmeta.jl

Packages were all using the upper bound of Julia v"0.6.0-" which meant that no packages were available to install when using the Julia v"0.6.0" release.

Support Julia 0.6.0 release

---

ext/TOML/src/TOML.jl

This causes Pkg3 to precompile. If we want that, it should probably be in the Pkg3.jl file.

remove precompile from internalized toml

---

README.md

add information I was missing when installing and remove remark about precompilation, which doesn't seem to be true anymore.

no precompilation remark, add pkg3 clone, pkg dir

---

src/Pkg3.jl

Otherwise loading precompiled packages does not work (funnily enough).

enable precompilation for Pkg3

---

ext/TerminalMenus/README.md
ext/TerminalMenus/src/AbstractMenu.jl
ext/TerminalMenus/src/TerminalMenus.jl
ext/TerminalMenus/src/config.jl
ext/TerminalMenus/src/util.jl
ext/TerminalMenus/test/multiselect_menu.jl
ext/TerminalMenus/test/radio_menu.jl
ext/TerminalMenus/test/runtests.jl
src/Pkg3.jl

E.g when including a file with:
```jl
import Example
import Crayons
```
gives:
```jl
julia> include("/Users/kristoffer/Documents/mpkg.jl")
Could not find package Example, do you want to install it?
yes
> yes (remember)
no
no (remember)
INFO: Resolving package versions
INFO: Installing Compat
INFO: Updating "../Project.toml"
[7876af07] + Example v0.4.1
INFO: Updating "../Manifest.toml"
[34da2185] ↑ Compat v0.31.0 ⇒ v0.34.0
[7876af07] + Example v0.4.1
INFO: Resolving package versions
INFO: Installing Crayons
INFO: Updating "../Project.toml"
[a759f4b9] + TimerOutputs v0.3.0
INFO: Updating "../Manifest.toml"
[a8cc5b0e] + Crayons v0.4.0
[a759f4b9] + TimerOutputs v0.3.0
INFO: Recompiling stale cache file /Users/kristoffer/.julia/lib/v0.6/TimerOutputs.ji for module TimerOutputs.
```
Also, update …

 query for install if package exists in registry but not found locally 

---

bin/loadmeta.jl
bin/sha1map.jl
src/Operations.jl
src/Pkg2/Pkg2.jl
src/Pkg2/query.jl
src/Pkg2/reqs.jl
src/Pkg2/resolve.jl
src/Pkg2/resolve/fieldvalue.jl
src/Pkg2/resolve/interface.jl
src/Pkg2/resolve/maxsum.jl
src/Pkg2/resolve/versionweight.jl
src/Pkg2/types.jl
src/Pkg3.jl
src/Types.jl

PR made on top of #16, relevant commit for this PR is https://github.com/StefanKarpinski/Pkg3.jl/pull/37/commits/682cef5ab72b00084aa2dde5d120e64f2dbdd9a8
Passes a UUID-to-name dictionary to the dependency pruner and resolver and uses that to look up the name, e.g:
```
pkg> add StaticArrays @0.23.0
INFO: Resolving package versions
ERROR: Unsatisfiable requirements detected for package StaticArrays [90137ffa]:
└─version range [0.23.0,0.23.1) set by an explicit requirement
The intersection of the requirements is [0.23.0,0.23.1).
None of the available versions can satisfy this requirement.
```
Fixes #12, fixes #10

show pkg name on resolution failure

---

bin/loadmeta.jl
bin/sha1map.jl
src/Operations.jl
src/Pkg2/Pkg2.jl
src/Pkg2/query.jl
src/Pkg2/reqs.jl
src/Pkg2/resolve.jl
src/Pkg2/resolve/fieldvalue.jl
src/Pkg2/resolve/interface.jl
src/Pkg2/resolve/maxsum.jl
src/Pkg2/resolve/versionweight.jl
src/Pkg2/types.jl
src/Pkg3.jl
src/Types.jl

This makes Pkg3 (including the registry generation) work without using Base.Pkg.
Since Base.Pkg will be removed, this needs to happen at some point, and it is good to see how much code that we rely on from Pkg2.
I have tried this on a locally built Julia 0.6 with Base.Pkg removed (except Pkg.dir because it is needed for code loading) and things seem to work fine.

internalize the needed parts from Pkg2

---

src/API.jl
src/Operations.jl
src/REPLMode.jl
src/Types.jl
test/runtests.jl

As a response to #34, this shows a possible implementation.
Any command can be called as `preview cmd` and the effects of the command will go through but with (hopefully) no side effects. This removes downloading, building, and writing to any Project or Manifest files.
Example:

add preview mode

---

src/API.jl
src/Operations.jl
src/Pkg3.jl
src/REPLMode.jl
test/runtests.jl

Put most of the scaffolding in place for doing `pkg> test Pakcage`.
What is left (to match Pkg2) is to do resolution and support test only dependencies.

start implementing REPL test command

---

ext/TOML/src/TOML.jl
src/API.jl
src/Pkg3.jl
src/REPLMode.jl
src/Types.jl
test/runtests.jl

Implements the command `gc` that deletes all packages that are not reachable from an environment (manifest) that has not been within a time period.
TODO:
- Set a period from the REPL
- ~Perhaps we should write how much space was gced.~ Done
- (More) Tests

implement gc

---

Project.toml
src/API.jl
src/Operations.jl
src/Pkg3.jl
src/REPLMode.jl
src/Types.jl
test/operations.jl

On its way to solve #40. The idea is to never automatically create a local env, instead you can run `init` which will create that env in the current folder or the base of a git folder.
WIP because it needs tests and more cleanup. cc @fredrikekre

WIP force explicit init using `init` for local env

---

src/REPLMode.jl

I find `^C` to be a convenient way to exit the pkg repl mode. That is how other repl modes behave too (help, shell, cxx etc). What was the reason for explicitly removing this?

exit pkg repl mode with ^C

---

src/Pkg3.jl
src/Types.jl

Dates.format is slow to infer / compile, same with all the TerminalMenus stuff.
Before PR:
JSON precompilation time: 20 sec
JSON load time: 9.2 sec
After PR:
JSON precompilation time: 9.2 sec
JSON load time: 2.0 sec
This will be needed when using this in 0.7 because this method (`_find_package`) has to be very quickly inferred.
Best looked at with whitespace off: https://github.com/JuliaLang/Pkg3.jl/pull/76/files?w=1

help inference by hiding a method and not using Dates.format

---

README.md

I edited the package URL for cloning. I think it points now to the official package

Update package URL in README.md

---

src/Types.jl

Packages(with same name and uuid) can exist in two different registries, where package in one is behind the other.
Example:
Package 'Actors' with different versions(same UUID), v0.0.1 in MyRegistry and v0.1.0 in Uncurated.  
```
julia> import Pkg3
pkg> add Actors
There are multiple registered `Actors` packages, choose one:
> Registry: MyRegistry - Path: https://github.com/daqcore/Actors.jl.git
Registry: Uncurated - Path: https://github.com/daqcore/Actors.jl.git
INFO: Resolving package versions
INFO: Updating "~/.julia/environments/v0.6/Project.toml"
[1c4bc1b3] + Actors v0.0.1
INFO: Updating "~/.julia/environments/v0.6/Manifest.toml"
[1c4bc1b3] + Actors v0.0.1
[03a36d30] + EasyPkg v0.3.0
pkg> rm Actors
INFO: Updating "~/.julia/environments/v0.6/Project.toml"
[1c4bc1b3] - Actors v0.0.1 …
```

Support for packages with same UUID(and same name) in multiple registries

---

src/Types.jl

when JULIA_ENV is set with value which ends with `.toml`, instead of file `Project.toml`, directory Project.toml is created.

Fix errors when JULIA_ENV ends with .toml

---

src/GraphType.jl
src/Resolve.jl
src/Types.jl
src/resolve/MaxSum.jl
test/resolve.jl

(This is done on top of #83. I guess I could rebase it on top of #81 instead if the review of cloning/freeing needs more time.)
This greatly improves the ability to see what `resolve` does. Examples are at the bottom. Essentially, it logs everything. In case of errors, the log is represented in tree form, starting from the package with unsatisfiable conditions, like before. Otherwise, in case of success, the full log can be seen in different ways - the tree view, a plain view in which events are grouped by package, and a chronological view which shows a journal. This can very well be the basis for a "why" API command if the user wants to understand why some package is not getting updated etc. (or something along those lines). Cf. https://github.com/JuliaLang/julia/issues/13340 (cc …

Resolution log - looking into what the solver is doing, and why

---

bin/Pkg2/types.jl
src/GraphType.jl
src/Resolve.jl
src/resolve/FieldValues.jl
src/resolve/MaxSum.jl
test/NastyGenerator.jl
test/resolve.jl

With this change, the solver is now exact, at least for what concerns SAT/UNSAT discrimination, i.e. it should always find a solution if it exists, and fail only when it doesn't, producing a reasonable log trace in that case. (Ok to be perfectly honest the exactness claim relies on a conjecture that I haven't proven yet. But I think it should hold. It certainly does in all the cases that I tested.)
Optimality - finding the best solution among those that exist - is still based on a heuristic, unless the solution is found by the greedy solver, which is quite improved as well anyway - so much so that I had to explicitly add a new generator of nasty test instances just to trick it.
Of course, the problem being NP-hard in general, this means that in principle the solver could now take ages to …

Add backtracking to max-sum, improve greedy solver; the solver is now exact

---

src/GraphType.jl
src/Operations.jl

Fixes a problem in julia 0.7
Also a minor fix to keep the julia name in `uuid_to_name`.
Ref #99.

Use `transpose` instead of `'` syntax

---

src/API.jl
src/Operations.jl

Previously ```build``` command was not building dependent packages.
Added support for varargs in `Pkg3.API.build,` as present in `Pkg.build`
```
julia> Pkg3.build("PyCall", "DataFrames")
INFO: Resolving package versions
INFO: Building Conda [b26546424d5f3ac3]...
INFO:  → /home/osboxes/.julia/packages/N8e4/u0lj/deps/build.log
INFO: Building PyCall [2ba54612238a85ee]...
INFO:  → /home/osboxes/.julia/packages/mbAM/vGCc/deps/build.log
INFO: Building SpecialFunctions [a052147e601e7926]...
INFO:  → /home/osboxes/.julia/packages/FTLa/YKDc/deps/build.log
```

 Build dependent packages and support varargs in API.build

---

ext/TOML/src/parser.jl

Make the `deps_graph!` loop that collects dependencies take 0.9 seconds instead of 1.6 seconds when doing `add DifferentialEquations`. Shaving off 0.7 seconds is pretty good compared to the total runtime ~3s.

parameterize IO in TOML parser

---

src/GraphType.jl
src/Operations.jl
src/Types.jl

From profiling, a large bottleneck was found in creating the `Graph`. This is because broadcasting (while convenient) actually has a significant overhead when used on small arrays. This was frequently the case here.
Before the changes here, creating the `Graph` took 0.93 seconds when adding DifferentialEquations with a total time for `Pkg3.add` of 2.0 seconds.
After the changes, `Graph`takes 0.30 seconds and total time 1.36 seconds.
The changes to Operations.jl are for readability, was hard to me to keep the nested generators in my head (also this way we only do one loop).

Significantly improve performance by not using broadcasting for very small arrays

---

src/Operations.jl
src/Pkg3.jl
src/PlatformEngines.jl

We dont really want to run the probing everytime Julia starts, only when Pkg3 is actually used.

lazily probe for platform engines

---

src/API.jl
src/Display.jl
src/GraphType.jl
src/Operations.jl
src/Pkg3.jl
src/REPLMode.jl
src/Types.jl
test/operations.jl

This contains settings and state that needs to be passed around
Removes the `GLOBAL_SETTINGS` struct.
Based on the comment in #122:
> A pretty large amount of options and state need to be passed around between all of these functions and that will only grow as we add more functionality to the interface. We should probably bite the bullet and have an type that wraps all of the options which can also have input, output and error streams in it.

thread a "PkgContext" through most of the Operations.

---

src/API.jl
src/Operations.jl
src/Types.jl

Does this make sense to you @carlobaldassi.
Basically, these just gives the standard library a version (the same one as the current julia version, and then ignores any dependencies they have).

do not resolve standard libraries, these are automatically satisfied

---

src/API.jl
src/Display.jl
src/GraphType.jl
src/Operations.jl
src/Pkg3.jl
src/REPLMode.jl
src/Resolve.jl
src/Types.jl
src/resolve/MaxSum.jl
test/operations.jl
test/resolve.jl

* Refactors the parsing for REPLMode. Instead of each token being a `Tuple{Symbol, Vararg{Any}}` it is now just a `Token` which is defined as `const Token = Union{Command, Option, VersionRange, String}`. `Command` is a struct representing a command like `add`, `Option` is a struct representing an option like `--path=foo` or `--manifest`. There is no more `pkg`-token because it is not up to the lexer to decide if a word is a path or a package because it is context sensitive. Instead just lex those as a `String` and try to parse it as a package when it is expected in different commands. This makes the quotes not needed in paths and urls anymore.
Also uses enums instead of symbols in more places where there are a finite set of choices.
Also fixes not printing some stuff when using `status` …

refactor parsing using enums and structs and use enums in more places

---

bin/loadmeta.jl
src/API.jl
src/Display.jl
src/GraphType.jl
src/Operations.jl
src/Pkg2/Pkg2.jl
src/Pkg2/reqs.jl
src/Pkg2/types.jl
src/Pkg3.jl
src/REPLMode.jl
src/Types.jl
test/pkg.jl

Backwards compatible with REQUIRE files. Can choose branch and path to checkout to. Perhaps repo should be choosable too...
There seems to be some problem with finding the Test module when testing a checked out package. Building works fine though:
```
pkg> checkout Example
[ Info: Checking out Example [7876af07]
[ Info: Cloning Example from https://github.com/JuliaLang/Example.jl.git to /Users/kristoffer/.julia/dev
[ Info: Resolving package versions
[ Info: Updating "~/.julia/environments/v0.7/Project.toml"
[7876af07] + Example v0.5.1+ [/Users/kristoffer/.julia/dev/Example]
[ Info: Updating "~/.julia/environments/v0.7/Manifest.toml"
[7876af07] + Example v0.5.1+ [/Users/kristoffer/.julia/dev/Example]
pkg> test Example
[ Info: Testing Example located at /Users/kristoffer/.julia/dev/Example …
```

implement checkout

---

src/API.jl
src/Operations.jl
src/Types.jl

Allows checked out packages that depend on stdlibs to load. Temporarily in place to ease the transition to Project files.

find stdlibs in checked out packages using regex

---

.travis.yml
src/API.jl
src/Operations.jl
src/Types.jl

Fixes #152 cc @bicycle1885 @StefanKarpinski 
```
pkg> add EzXML
[ Info: Resolving package versions
[ Info: Installed Compat ───────── v0.54.0
[ Info: Installed BinaryProvider ─ v0.2.3
[ Info: Installed DataStructures ─ v0.7.4
[ Info: Installed EzXML ────────── v0.6.1
[ Info: Updating "~/.julia/environments/v0.7/Project.toml"
[8f5d6c58] + EzXML v0.6.1
[ Info: Updating "~/.julia/environments/v0.7/Manifest.toml"
[b99e7846] + BinaryProvider v0.2.3
[8f5d6c58] + EzXML v0.6.1
[ Info: Building EzXML [e021a23d]...
[ Info:  → /Users/kristoffer/.julia/packages/EzXML/taEy/deps/build.log
pkg> test EzXML
[ Info: Testing EzXML located at /Users/kristoffer/.julia/packages/EzXML/taEy
[DEPRECATIONS...]
Test Summary: | Pass  Total
Error         |   88     88
....
```

allow packages to load dependencies at top level when building or testing

---

src/API.jl
src/Operations.jl
src/Types.jl

Creates a temporary environment where the test dependencies are added to. This is pretty ugly but it is just to support old REQUIRE files, should be much simpler when the packages themselves have their Project files.
For example:
```
julia> Pkg3.test("JSON")
[ Info: Testing JSON located at /Users/kristoffer/.julia/dev/JSON
[ Info: Resolving package versions
[ Info: Updating "/var/folders/64/76tk_g152sg6c6t0b4nkn1vw0000gn/T/tmpFKTx5l/Project.toml"
[864edb3b] + DataStructures v0.7.4
[53c48c17] + FixedPointNumbers v0.4.6
[6fe1bfb0] + OffsetArrays v0.5.0
[ Info: Updating "/var/folders/64/76tk_g152sg6c6t0b4nkn1vw0000gn/T/tmpFKTx5l/Manifest.toml"
[864edb3b] + DataStructures v0.7.4
[53c48c17] + FixedPointNumbers v0.4.6
[6fe1bfb0] + OffsetArrays v0.5.0
[DEPRECATIONS]
Test Summary: | Pass  Total …
```

resolve with test/REQUIRE if it exists when a package is being tested

---

src/Operations.jl

Fixing building e.g. Homebrew which does
```
using Homebrew
Homebrew.update()
```

allow package to load themselves when building themselves

---

src/Operations.jl
test/pkg.jl
test/repl.jl

Test for downloading registered packages with LibGit2 had gone missing and, of course, is now broken. Fix this and add the test.

test and fix libgit2 download of registered packages

---

src/REPLMode.jl
test/repl.jl

This significantly improves the autocompletion code by re-using `tokenize`. Also fixes https://github.com/JuliaLang/Pkg3.jl/issues/213 and works around https://github.com/JuliaLang/Pkg3.jl/issues/200 by only showing short-form completions (for commands and options) if you've typed absolutely nothing yet:
```
pkg>
+         ?          dev        gc         install    rm         test       upgrade
-         add        develop    generate   pin        search     uninstall
.         build      find       help       preview    st         up
/         checkout   free       init       remove     status     update
pkg> s
search status
```
This also means that typing `r\tab` completes to `remove` instead of showing a selector.
Let me know what you guys think!

Rework autocompletion

---

src/REPLMode.jl

Closes https://github.com/JuliaLang/Pkg3.jl/issues/226.
A little bit hacky but I found no better way to get a handle to the shell prompt.
`]` in shell mode doesn't bring you back to Pkg3 mode but maybe it shouldn't.

enter shell mode on ; in Pkg3 REPL Mode

---

bin/utils.jl
src/API.jl
src/Display.jl
src/GitTools.jl
src/Operations.jl
src/Pkg2/reqs.jl
src/Pkg3.jl
src/PlatformEngines.jl
src/REPLMode.jl
src/Types.jl
test/pkg.jl

In the spirit of https://github.com/JuliaLang/Pkg3.jl/issues/89.
http://www.giphy.com/gifs/2rAET3llXUjR9pfUVO
Requires https://github.com/JuliaLang/julia/pull/26387
cc @jperla

show a progress bar when cloning git repos

---

src/Pkg3.jl

Without this my custom REPL settings from `.julia/config/startup.jl` get overwritten, because keybinding customization is done by calling `REPL.setup_interface` too, cf. https://docs.julialang.org/en/latest/stdlib/REPL/#Customizing-keybindings-1, and it runs before Pkg3 is loaded.

Avoid overwriting user-defined settings in REPL

---

src/GraphType.jl

This should hopefully avoid some overly eager assertion errors.
ref. https://github.com/JuliaLang/Pkg3.jl/issues/228#issuecomment-379300115

Slightly relax GraphType.check_constraints

---

src/Operations.jl
test/repl.jl

Follow up to #245. That only fixed it when writing the Manifest but we also (of course) need it for the resolution.

use Project to find dependencies for packages with projects

---

src/API.jl

Do you like this @StefanKarpinski? It seems people sometimes get confused when they add packages and not get the latest version because they haven't run `up` in a long time. Perhaps just updating the registry even when adding makes sense.

update registries when adding

---

src/Display.jl
src/Types.jl

```
(Pkg3) pkg> add Literate#b57e6cc
...
Updating `Project.toml`
[98b081ad] ~ Literate v0.1.0+ #master ⇒ v0.1.0+ #b57e6cc
Updating `Manifest.toml`
[98b081ad] ~ Literate v0.1.0+ #master ⇒ v0.1.0+ #b57e6cc
(Pkg3) pkg> add Revise#master
...
Updating `Project.toml`
[295af30f] ~ Revise v0.3.0+ #7350aff ⇒ v0.3.0+ #master
Updating `Manifest.toml`
[295af30f] ~ Revise v0.3.0+ #7350aff ⇒ v0.3.0+ #master
```
Fixes #271

fix some printing inconsistencies

---

src/Operations.jl

Does this make sense to you @carlobaldassi? We have already collected the dependencies for the fixed versions, no need to go to the registry at all and collect dependencies for other versions?
Fixes #270.
```
(Pkg3) pkg> dev DataStreams
Downloaded WeakRefStrings ─ v0.4.6
Downloaded Nullables ────── v0.0.5
Downloaded JSON ─────────── v0.17.2
Downloaded Missings ─────── v0.2.9
Downloaded DataStructures ─ v0.8.1
Updating `Project.toml`
[9a8bc11e] + DataStreams v0.3.4+ [`~/.julia/dev/DataStreams`]
Updating `Manifest.toml`
[9a8bc11e] + DataStreams v0.3.4+ [`~/.julia/dev/DataStreams`]
[e1d29d7a] + Missings v0.2.9
[ea10d353] + WeakRefStrings v0.4.6
```

no longer collect dependencies from the registry for fixed packages

---

.travis.yml
appveyor.yml
docs/src/index.md
src/API.jl
src/Display.jl
src/Operations.jl
src/Pkg3.jl
src/REPLMode.jl
test/repl.jl

can be used to instantiate a manifest without going through the resolver
also, show warning in status output about non downloaded packages
Closes https://github.com/JuliaLang/Pkg3.jl/issues/208

implement instantiate

---

src/Operations.jl

Since we don't do any validation of the archives, downloading based on tag presents a potential security hole whereby a compromised repository retags a version.
This should fix that by downloading the archive for the tree directly. Note that the documentation (https://developer.github.com/v3/repos/contents/#get-archive-link) says that it should be a valid git reference, but using hashes seems to work as well.

Download archives by tree hash instead of tag

---

src/resolve/FieldValues.jl
src/resolve/MaxSum.jl

https://github.com/JuliaLang/julia/pull/25654

indmax -> argmax

---

src/API.jl
src/Pkg.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/294.
It's annoying to have to do the whole registry update when you are adding another package just after another. `update` will always update it so I think this is a nice balance.

only update the registry on add once per session

---

src/Pkg2/types.jl

Fixes #293 
```
(Pkg) pkg> add https://github.com/JuliaComputing/Deprecations.jl
[ Info: Assigning UUID 5a972732-6268-11e8-288b-df1ad7efd8ef to Deprecations
Updating registry at `~/.julia/registries/Uncurated`
Updating git-repo `https://github.com/JuliaRegistries/Uncurated.git`
Downloaded Tokenize ────── v0.4.2
Downloaded AbstractTrees ─ v0.1.0
Downloaded CSTParser ───── v0.3.5
```
@carlobaldassi seems ok to you?
Problem was that when using old REQUIRE files things like `0.1.0 0.1.0+` gave empty version ranges.

fix versionrange with old ranges of the type 0.1.0 0.1.0+

---

src/Operations.jl
src/generate.jl
test/test_packages/BigProject/Project.toml
test/test_packages/BigProject/SubModule/Project.toml
test/test_packages/BigProject/SubModule2/Project.toml
test/test_packages/BigProject/test/LibFoo.jl/Manifest.toml
test/test_packages/BigProject/test/LibFoo.jl/Project.toml
test/test_packages/BigProject/test/LibFoo.jl/src/LibFoo.jl
test/test_packages/BigProject/test/LibFoo.jl/test/runtests.jl
test/test_packages/BigProject/test/runtests.jl
test/test_packages/PackageWithBuildSpecificTestDeps/test/runtests.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/306. cc @staticfloat

 fix using local projects when testing

---

test/pkg.jl

Couple missing branch paths here ... most of these types don't define a `==` so I went digging into their fields, because that seems better than adding new methods just for these tests.

Some more tests for union! and isjoinable

---

src/Operations.jl
test/repl.jl
test/test_packages/BigProject/Manifest.toml
test/test_packages/BigProject/Project.toml

This allows one to write e.g.
```
[targets.test.deps]
Example = "7876af07-990d-54b4-ab0e-23690620f79a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
```
to load these only when testing.
WIP because the way TOML.jl prints this back in the Project file is something like:
```
[targets.test.deps]
[targets.test]
[targets.test.deps]
Example = "7876af07-990d-54b4-ab0e-23690620f79a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
```

WIP: support test-dependencies

---

docs/src/index.md

Some `^`s were called "tilde" and vice-versa.  One example in that section was fixed.

unmixup `^` and `~` in "Version specifier format"

---

src/REPLMode.jl
test/repl.jl

Supersedes JuliaLang/julia#27391 -- opening it against the correct repo now. The change is identical to the original PR which was working, but I have not actually tested it within Pkg.jl.
---
Calling `pkg> generate` without arguments on master / 0.7.0-alpha throws a somewhat unhelpful error at the moment:
```
(v0.7) pkg> generate
ERROR: UndefVarError: pkg not defined
Stacktrace:
[1] do_generate!(::Pkg.Types.Context, ::Array{Union{Pkg.Types.VersionRange, String, Pkg.REPLMode.Command, Pkg.REPLMode.Option, Pkg.REPLMode.Rev},1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/Pkg/src/REPLMode.jl:751
...
```
This adds a `cmderror` call with a nicer error message:
```
(v0.7) pkg> generate
ERROR: `generate` requires a project name as an argument
```
I was also …

Throw cmderror for no-argument pkg> generate

---

src/Operations.jl

Should fix https://github.com/JuliaLang/Pkg.jl/issues/343 but I need a good test.

allow packages to depend on unregistered packages that exist in the project

---

src/Types.jl

Small bug; `Project.toml` was hardcoded as the project file.
All tests passing locally.

`Project.toml` is not always the project file

---

src/Types.jl

Should fix https://github.com/JuliaLang/Pkg.jl/pull/402#issuecomment-398176050 point 9.
Would be good with a test but I don't want to spend too much time adding test for things that are just for compatibility with REQUIRE.

give packages without project uuids based on their name instead of a random uuid

---

docs/src/index.md
src/API.jl
src/Pkg.jl
src/REPLMode.jl

This PR removes `pkg> deactivate` in favor of no-arg `pkg> activate`. To activate the environment in `pwd()` you instead ahve to do `pkg> activate .` I think it is cleaner to use only one command, which now works similar to `cd` in that we jump back to something default with no arguments. Another reason why this change makes sense to me is that `pkg> deactivate` does not deactivate environments, it just activates another one (kinda).
I think this behaviour, in combination with `@:` in the default `LOAD_PATH`, results in an intuitive behaviour. Thoughts?

[RFC] fold deactivate into no-arg activate

---

src/Types.jl

For #437. 
I think by that point, the rev we want to target is already determined, so we just have to store it.

Record rev in all cases

---

src/Operations.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/427 cc @omus 
With this, the Mocking.jl tests pass with `Dates` as a test only dependency.
Would be good if you could confirm.

put target deps inside deps of package when running the target

---

src/Pkg.jl
test/repl.jl
test/utils.jl

This testset was failing locally because it was reading `Pkg`'s manifest file instead of a newly generated one.

Fix for improperly isolated testset

---

src/API.jl

https://github.com/JuliaLang/Pkg.jl/pull/451 changed the error type so we failed to catch this.

do not throw when failing to fetch a registry

---

src/REPLMode.jl
test/repl.jl

This is also significantly faster, probably (but haven't checked) because regex performance went down the drain with https://github.com/JuliaLang/julia/pull/26731.
Fixes #520.

filter packages based on current julia version

---

src/Operations.jl
src/Types.jl
test/pkg.jl
test/test_packages/BigProject/Project.toml

Instead of writing
```toml
[deps]
Required = "<uuid>"
[targets.build.deps]
Compiler = "<uuid>"
[targets.test.deps]
Test = "<uuid>"
QuickCheck = "<uuid>"
```
with this design one would write:
```toml
[deps]
Compiler = "<uuid>"   # build-only
Required = "<uuid>"   # required
Test = "<uuid>"       # test-only 
QuickCheck = "<uuid>" # test-only
[targets]
build = ["Compiler"]
test = ["Test", "QuickCheck"]
```
In other words:
- all dependencies are listed with their UUIDs in the main `[deps]` section
- the `[targets]` section is just about defining subsets of these dependencies
- if you ignore `[targets]` you can resolve anything that any target might load
- the `main` target is everything that's not explicitly in any other target
- the dependencies of a target are the `main` targets plus the …

RFC: new targets design

---

src/REPLMode.jl
src/Types.jl

It seems a bit silly that tab completion is allowed to fully TOML parse all the registries (and it does so very fast), while we are constructing this big regular expression to avoid parsing it for the resolver (where there is much more of other stuff going on). It also ties us to using a custom regex parser which might break if someone outputs TOML in another format.
We can also introduce a cache here so that we only need to reparse Registry.toml in case it is updated. This means that often it is only required to be parsed a single time during the session.

Stop trying to be lazy

---

src/REPLMode.jl
test/repl.jl

Rework the meaning of `pkg> activate Foo` to do the following:
1. If Foo is an existing path, activate that
2. If Foo is a developed dependency of the current environment, activate that
3. Activate the (non-existing) directory Foo
To sidestep 2. above, and activate a non-existing directory Foo even though there is a developed dependency Foo, use `pkg> activate ./Foo`.

Rework the meaning of `pkg> activate Foo`

---

docs/src/index.md
src/Operations.jl
src/Types.jl
test/pkg.jl
test/test_packages/BigProject/Project.toml

This is an alternative to defining the main deps as the ones that are not mentioned in any target in the [targets] section. Instead this puts extra dependencies in an [extras] section which has the same layout as [deps]. cc @KristofferC, @fredrikekre; this is similar to Fredrik's proposal in response to #526 but I didn't like the name `[targetdeps]` so I called it `[extras]` instead.

RFC: move extra deps into [extras] section

---

src/Display.jl
src/Operations.jl
src/Types.jl

We used to print the diff vs the current project when testing a dependency. This was typically always very spammy and non-interesting. This instead just shows the "absolute" (non-diff) dependencies that are used when testing.

improve printing when running tagets

---

Project.toml
src/Operations.jl
test/pkg.jl
test/test_packages/BigProject/SubModule/Project.toml
test/test_packages/BigProject/SubModule2/Project.toml

also put deps in Manifest even for stdlibs and use them in the resolver

don't allow loading packages from LOAD_PATH when testing or building

---

src/REPLMode.jl
test/repl.jl

Likely left when pwd had some importance to the project being used.
Fixes #547

fix unneeded use of pwd in REPL prompt function

---

src/API.jl
src/REPLMode.jl
test/api.jl
test/pkg.jl
test/repl.jl

Just moves the logic from REPLMode to API and make the REPL mode call API.

Make `Pkg.activate(path)` behave like `pkg> activate path`.

---

src/REPLMode.jl
src/Types.jl
test/repl.jl

1. make APIOptions a `Dict{Symbol, Any}` : this one allows the REPL to more easily look inside / change its contents / etc before it hits the API (it used to be a `Vector{Symbol,Any}`)
2. don't require commands declarations to specify a `do_<>!` function : this is mainly for REPL specific commands (e.g. `help`, `preview`) that shouldn't be tightly coupled with the API
3. don't require `do_<>!` functions to require a context parameter : some API function don't require one
4. `ctx` is a dictionary until it hits the API (at which point it gets converted to a `Context`) : a `Context` object used to be created right at the start of `do_cmd!`, but as @fredrikekre pointed out, this doesn't always make sense. Using a dictionary allows the REPL to figure things out until it ready to create one. …

Refactor some REPL issues

---

src/API.jl

I assume this was the intention. I don't think we wanted to print a whole dictionary.

Fix `instantiate` error message

---

src/Operations.jl
src/Pkg.jl
src/Types.jl

When `DEPOT_PATH` is empty, this throws a better error message compared to a `BoundsError`.

`depots()[1]` -> `depots1()`

---

src/Types.jl

```
(Pkg) pkg> dev .
Updating `~/.julia/dev/Pkg/Project.toml`
[b4f34e82] + Distances v0.7.0 [`~/.julia/dev/Pkg/../Distances`]
```

use full path for local paths when determining package name

---

src/API.jl
src/Pkg.jl
src/REPLMode.jl
test/repl.jl

This is my first naive/minimal attempt to add a `--shared` option to `activate`.
The idea here is that one could use this to have some sort of global environment at a default path.
```
julia> Pkg.pkg"activate --shared Foo"
(Foo) pkg> status
Status `~/.julia/enviroments/Foo/Project.toml`
```
Is this something we would like to pursue further? Its a feature that I personally would like to have, and I'd be happy to do my best to develop it further with a little guidance. I tried to mirror how `dev` is handling `--shared` and `--local`

add --shared option for activate

---

src/Pkg.jl
src/REPLMode.jl
src/Types.jl
test/api.jl
test/pkg.jl

Also fixes https://github.com/JuliaLang/Pkg.jl/issues/556. Seems this chunk of code was copy pasted and occurred in two different places @00vareladavid

allow using a path kword arg to PackageSpec

---

src/API.jl
src/GitTools.jl
src/Operations.jl
src/Pkg.jl
src/REPLMode.jl
src/Types.jl
src/generate.jl
test/pkg.jl
test/repl.jl
test/resolve.jl

CommandError is not really what this is currently used for. It is used when an error happens that is not "Pkg"s fault in the sense that it was something external that failed. When this happens in the REPL mode, we do not show .a backtrace.

rename CommandError to PkgError

---

docs/src/index.md
src/API.jl
src/REPLMode.jl
src/Types.jl
test/pkg.jl
test/repl.jl

Doing `dev Foo#branch1` and then `dev Foo#branch2` and then not get a change of branch is confusing. For now, just allow downloading the repo at the main branch and then one can just use git to get the repo in whatever state is desired.

remove ability to give a git revision to devved packages

---

src/Operations.jl
src/Types.jl

This is completely the wrong place to assign versions to packages, that takes place just before calling the resolver.
Only have crappy mobile internet so we'll see what CI says, didn't run locally.
Fixes https://github.com/JuliaLang/Pkg.jl/issues/645
Fixes https://github.com/JuliaLang/Pkg.jl/issues/606
Tests for this are quite hard to make because the code is so stupid.

remove unnecessary version handling when dealing with repos

---

src/REPLMode.jl
test/repl.jl

These are only triggered if there's a path separator in the string to be completed, which I think is a pretty sensible behaviour.
If you want to test this locally, call `Pkg.REPLMode.repl_init(Base.active_repl)` after `import Pkg`.
Fixes #408

add path completions to add/dev in repl

---

src/API.jl
src/Operations.jl
src/Types.jl
test/repl.jl

Fix a bug where the path was stored as relative because `devdir()` happened to be in the project. The path should only be relative if the user used `--local`.

Fix a bug where the path was stored as relative

---

src/API.jl
src/Display.jl
src/Operations.jl
src/Types.jl
test/pkg.jl

Packages that are tracked by path now just print the path (without trying to be clever about where the project is, or what pwd is). Also print stdlib paths, e.g. when testing, as `@stdlib/Test`, fix #605 .
bors try

Better path printing

---

test/pkg.jl

Basically it was the `mv` in these tests that threw the "unlink" error. Instead of renaming the files this way, I copy them to a new directory and rename them during the copy. I still have no idea why the `mv` throws an error in the first place...
Fixes #705

Rewrite `JuliaProject.toml` test to avoid AppVeyor error

---

src/REPLMode.jl
src/Types.jl
test/repl.jl

Expand `~` in `path` for `activate path`, `Pkg.activate(path)`, `add path`, `develop path` and `PackageSpec(path = path)`.

Expand ~ in path for activate develop and add

---

src/REPLMode.jl

Pretty sure it is a typo. It git blames back to me..

Fix typo in help docs

---

src/API.jl
test/pkg.jl

Currently, `Pkg.add` modifies the argument `pkg::Vector{PackageSpec}` passed to it in-place even though the name does not end with `!`:
```julia
julia> VERSION
v"1.0.0"
julia> packages = [PackageSpec("JSON")]
1-element Array{Pkg.Types.PackageSpec,1}:
PackageSpec(name=JSON)
julia> Pkg.add(packages)
Updating git-repo `https://github.com/JuliaRegistries/General.git`
julia> packages
158-element Array{Pkg.Types.PackageSpec,1}:
PackageSpec(name=JSON, uuid=682c06a0-de6a-54ab-a142-c8b1cf79cde6, v=v"0.19.0")
PackageSpec(name=Documenter, uuid=e30172f5-a6a5-5a46-863b-614d45cd2de4, v=v"0.19.6")
```
I propose to `deepcopy` it before passing it to the destructive internal function.  Note that this PR adds a function …

Don't mutate argument passed to Pkg.add

---

src/GitTools.jl
test/pkg.jl

This is a minimalistic change to support the use of `Pkg.setprotocol!("ssh")` to fix #653.
My naive reasoning here is that since "github" is hardcoded anyway, one might as well adapt the URL string for when using the ~~"git"~~ "ssh" protocol.
Note though that this only works if the repo has not been cloned into ".julia/clones"  already using the defaul setting (i.e. https). If that is the case then `dev Example` will say
```
Updating git-repo `git@github.com:JuliaLang/Example.jl.git`
```
while `git remote -v` in that new dev-ed directory will still show `origin` using the `https` version.
Not sure where to fix that.

add support for "ssh" protocol

---

src/Types.jl

The error message is so so but it is at least an improvement over the status quo where this will just block.

only do a radiomenu if we are in interactive mode

---

src/API.jl
src/Operations.jl
test/pkg.jl

Closes #32.
Test fail for me locally with a JSON error, but hopefully that's just because an existing JSON installation or something. Tests passed at https://github.com/JuliaLang/julia/pull/29439, for whatever that is worth.
Error:
```julia
ERROR: LoadError: LoadError: LoadError: Unsatisfiable requirements detected for package JSON [682c06a0]:
JSON [682c06a0] log:
├─possible versions are: [0.1.0-0.1.1, 0.2.0-0.2.4, 0.3.0-0.3.9, 0.4.0-0.4.6, 0.5.0-0.5.4, 0.6.0-0.6.1, 0.7.0-0.7.1, 0.8.0-0.8.3, 0.9.0-0.9.1, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 0.14.0, 0.15.0-0.15.2, 0.16.0-0.16.4, 0.17.1-0.17.2, 0.18.0, 0.19.0] or uninstalled
├─restricted to versions 0.16.0-0.16 by an explicit requirement, leaving only versions 0.16.0-0.16.4
└─restricted by julia compatibility requirements to versions: [0.18.0, …
```

Make package files read-only for Pkg.add

---

src/Types.jl
test/pkg.jl

This adds an environment variable, tentatively called `JULIA_PKG_CONCURRENCY`, which allows the user to control the number of concurrent downloads that Pkg uses when installing packages, using the previous default of 8 if the variable is not specified.
Setting the number of concurrent downloads to 1 using this variable provides a temporary workaround for #795.
Currently this PR does not document the variable. Suggestions for where that documentation should live would be welcome.

Add an environment variable to control concurrency

---

src/Types.jl

Also escapes the forward slash at the beginning, although this appears to not have been an issue.
Fixes #719

Allow trailing backslash in regex

---

src/REPLMode.jl
test/repl.jl

This replaces the old tuples with keyword vectors.
Advantages:
- delegates work to Julia's keyword argument mechanism
- more readable (IMO)
- order doesn't matter
- allow for defaults (e.g. if a command doesn't take flags, just omit the `:option_spec` keyword pair)
Note that this change should only affect the declarative interface and does not change the internal "Spec" structs (other than one small tweak)

Refactor command declarations

---

src/Display.jl

See #745. Example of new behavior:
```julia
julia> Pkg.status()
Status `~/Documents/projects/Pkg/test/TestPkg/Project.toml`
[empty environment]
(TestPkg) pkg> st
Status `~/Documents/projects/Pkg/test/TestPkg/Project.toml`
[empty environment]
```
I didn't see any testing of `Pkg` output, so I haven't added any tests. Point me in the right direction if you would like a test.

Add a message for empty project deps

---

src/REPLMode.jl
test/repl.jl

Changes:
- move option parsing to `parse`: it is purely syntactical and does not depend on the command specs
- remove redundant option check
- fold `enforce_argument_order` into `parse_pkg`: `enforce_argument_order` was needlessly abstract
- break up `arg_spec` into `arg_count` and `arg_parser`.
- Omitting `arg_parser` means "don't do any special parsing on the arguments" (i.e. the "parser" is just `identity`).
- Omitting `arg_count` means "this command does not take arguments".
- added some docstrings and comments

Refactor option and argument parsing

---

src/Types.jl
test/pkg.jl

I have symlinked `environments/v1.0` and`environments/v1.1` to `environments/v1`. #548 removed a call to `realpath` in `promptf` with the result that the symlink was shown in the prompt.
Note the expanded symlink in the prompt, but not for the project file.
```
(v1) pkg> st
Status `~/.julia/environments/v1.0/Project.toml`
```
None of the links expanded
```
(v1.0) pkg> st
Status `~/.julia/environments/v1.0/Project.toml`
```
This PR restores the pre-#548 behavior (which I liked better) and additionally expands the symlink for the displayed path, the result with this PR is thus
```
(v1) pkg> st
Status `~/.julia/environments/v1/Project.toml`
```
Opinions?

Expand symlinks in find_project_file.

---

bin/gitmeta.jl
src/API.jl
src/Display.jl
src/GitTools.jl
src/GraphType.jl
src/Operations.jl
src/REPLMode.jl
src/Resolve.jl
src/Types.jl
src/resolve/MaxSum.jl

In all these cases we're merely rethrowing the existing exception, so it
seems simpler and clearer just to use `rethrow()` without arguments.
Companion to https://github.com/JuliaLang/julia/pull/29794

Replace trivial uses of rethrow(exc) with rethrow()

---

src/REPLMode.jl
test/repl.jl

Iterative path completion for `activate`. Also includes support for `activate --shared`.
Examples:
```
(Pkg) pkg> activate --shared 
foobar v1.0
(Pkg) pkg> activate /
sys/      opt/       root/      lib64/     lib/       mnt/       bin/       run/       var/       tmp/
nix/      boot/      usr/       proc/      home/      dev/       etc/       srv/       .emacs.d/  sbin/
```
Includes a small fix for #839.
Should resolve #834.

Add completion support for `activate`

---

.gitignore
CHANGELOG.md
docs/src/api.md
docs/src/registries.md
src/API.jl
src/GitTools.jl
src/Pkg.jl
src/REPLMode.jl
src/Registry.jl
src/Types.jl
test/pkg.jl
test/registry.jl
test/repl.jl
test/runtests.jl
test/utils.jl

This adds some registry functionality.
| REPL | API |
|:-----|:-----|
| `pkg> registry add General` | `Pkg.Registry.add("General")` |
| `pkg> registry add General=uuid` | `Pkg.Registry.add(RegistrySpec(name="General", uuid = uuid))` |
| `pkg> registry add www.registry.com` | `Pkg.Registry.add(RegistrySpec(url="www.registry.com")` |
and similar with `registry up`/`Pkg.Registry.up` and `registry rm`/`Pkg.Registry.rm`
This also differentiates registries based on uuid, instead of just name. This means that registries are now stored in `.julia/registries/name/uuidslug` instead of just `.julia/registries/name`.
```
pkg> registry add General
Cloning registry from "https://github.com/JuliaRegistries/General.git"
Added registry `General` to `~/.julia/registries/General`
pkg> registry add …
```

Registry functionality with REPL and API support

---

src/Types.jl
test/registry.jl

Don't prompt the user for a choice when the same package name is found in multiple registries if they share the same uuid.
fix #711

 fix #711: multiple registries with the same package

---

CHANGELOG.md
src/API.jl
src/Display.jl
src/Operations.jl
src/Pkg.jl
src/REPLMode.jl
test/api.jl
test/repl.jl

I gave #575 a try. There is also this related [discourse thread](https://discourse.julialang.org/t/pkg-repl-mode-filter-status-list/17087).
This PR adds `pkg> status [pkg]`, where `pkg` can be one or multiple package names. It will actually just filter the full `status` list for the given package names.
It's my first Pkg.jl PR. Looking forward to comments!
WIP because I (at least) have to add some tests.

pkg> status SomePackage

---

src/Operations.jl
src/Pkg.jl

This is meant as an alternative to PR #866 for resolving issue #865

Transfer can_inline to subprocess

---

src/API.jl
src/Display.jl
src/Operations.jl
src/REPLMode.jl
src/Types.jl
test/pkg.jl
test/repl.jl
test/utils.jl

Data flow:
`read_project`: file -> raw Dict 
`Project`: raw Dict -> Project struct
[Pkg Operations]
`destructure`: Project struct -> raw Dict
`write_env`: raw Dict -> file
A small step in the right direction I hope. It should at least be clear where we expect `String` data v typed data. And it should reduce the number of overall data conversions (e.g. no `UUID(uuid)` all over the place).
I left the `compat` as a `Dict{String,String}` (and not `Dict{String,VersionSpec}`) because `String` -> `VersionSpec` is a many-to-one mapping (I think).

Structured Project data

---

src/Types.jl

Pretty basic change - just add a line to the top of `Manifest.toml`.

Add comment about Manifest being machine-generated; fixes #859

---

src/Types.jl
test/repl.jl

Define read_project for IO types, fix #904.
Remove unnecessary GC.gc() call on Windows.

Define read_project for IO types, fix #904.

---

src/Operations.jl
src/Types.jl

I believe these are necessary. @vtjnash, can you take a quick look and verify?

add two missing GC.@preserve calls

---

src/API.jl
src/Display.jl
src/Operations.jl
src/Types.jl
src/generate.jl
test/repl.jl

In the spirit of #857, structured manifest data.
As discussed earlier, a Manifest should really be `Dict{UUID, PackageEntry}`.
Analogous to Project data, `Manifest!` takes in a raw TOML dict and returns a `Manifest` data structure.
`destructure` works in the reverse direction.
I have tried to keep the changes minimal, except where the new data structure provides a clearly better alternative (e.g. `manifest_by_uuid` is no longer needed).

Structured Manifest Data

---

ext/TOML/src/parser.jl
src/generate.jl

Someone on slack hit a call to `hex` which was supposed to be deprecated.
Root cause of the issue was that `generate` did not properly escape the `authors` field.
I think just piping through `TOML.print` should do the trick.
Note I couldn't figure out how to keep the empty `deps` field when generating a project, so I just avoid printing it. Is it just there for aesthetic purposes? We don't care to preserve it when `rm`ing all dependencies...

Properly escape TOML fields in `generate`

---

src/Types.jl
test/manifest/not_unique_names.toml
test/manifest/simple.toml
test/pkg.jl
test/project/pkg.toml
test/project/simple.toml

I broke `Pkg` by merging #894 last night. I hadn't realized that we save the `deps` section differently depending on whether all the dependencies have unique names.
I added tests to ensure that `write_manifest(read_manifest(x)) == x`. Also added the equivalent tests for `Project.toml`.

Properly handle Manifest dependencies (Fix #894)

---

src/REPLMode.jl
src/Types.jl
test/pkg.jl

I noticed we where reading through the stdlib directory when creating each `Context` object. Unless I'm missing something, this is unnecessary (and expensive!). Caching the dict makes creating a `Context` object roughly an order of magnitude faster.
I also hope we can completely remove the `stdlibs` field from `Context`. For now, I just left as is, and run a `Base.deepcopy` on the cached dict.
I did make two steps towards removing the `stdlibs` field: rewrite `stdlib_resolve` to not depend on a `Context` object, and replace `keys(ctx.stdlibs)` with `stdlib_uuids`.
Finally, tests for the `stdlib_resolve!` rewrite. They should be useful even if there is disagreement over the PR.

Cache stdlib dict

---

bors.toml

`cut_body_after` lets us control what ends up in the merge commit message, whats before `---` will be in there, and whats after will be removed.
---
This should thus not go in the commit message, but maybe bors uses the toml file on master so this might not work for this PR.
bors try

Add cut_body_after to bors.toml.

---

src/Types.jl
test/pkg.jl

fix #913: only remove the path if it was a temp-path.

---

docs/src/creating-packages.md

Bring back package naming guidelines, fix #945.

---

src/Operations.jl
test/registry.jl

Implement support for yanking versions in a package registry.
---
Very WIP, but this allows us to blacklist releases on the registry level. They can not be installed, but they can still be used, and you can `instantiate` a `Project.toml` + `Manifest.toml` with it, so it should not break working code. Here https://github.com/fredrikekre/Registry/blob/97919d39c95a3d917ea3b69e78aad68c7c02bf7c/I/ImportMacros/Versions.toml I have blacklisted version 0.2.0 of ImportMacros, and consequently:
```
(v1) pkg> add ImportMacros
Updating git-repo `https://github.com/JuliaRegistries/General.git`
Updating registry at `~/.julia/registries/Registry`
Updating git-repo `https://github.com/fredrikekre/Registry.git`
Updating …
```

Implement option to yank/blacklist a release.

---

src/API.jl

This should not really happen but it seems to happen anyway, so at least give a better error message for it.

better error message when we cant find uuid in manifest

---

docs/src/basedocs.md

This snippet will be included in Julia's manual, essentially just the getting started section, and a pointer to the full manual.

Add basedocs for the base julia manual.

---

src/API.jl
src/Display.jl
src/Operations.jl
src/Pkg.jl
src/REPLMode.jl
src/Types.jl
test/api.jl
test/pkg.jl
test/registry.jl
test/repl.jl

1. Refactor types for consistency across codebase (e.g. sometimes we do `isempty(name)` and other times we do `name === nothing`, `PackageEntry` should have a `GitRepo` field, ...)
2. Split `PackageSpec` constructor into an internal constructor and a user-facing constructor (inspired by #872). It really is two different use cases: one is "create this object and set these fields", the other needs to do hand holding and error checking.
It was difficult to do one without the other, so that's why I included them together.

Refactor types

---

src/API.jl
src/Display.jl
src/REPLMode.jl

Print the status of pkg's deps in manifest/combined mode, i.e.
pkg> st -m pkg
fix #915

fix #915: status -m Package prints status of Package's deps

---

test/utils.jl

Otherwise `pkg> test Pkg` fail if you have set this.
bors r+

Reset JULIA_PKG_DEVDIR when testing.

---

ext/TOML/src/TOML.jl
ext/TOML/src/print.jl
src/Types.jl

TOML files should store Booleans as Booleans instead of their string versions.
Fixes a bug introduced in #894.

Fixed `pinned`

---

src/API.jl
test/pkg.jl

Fix `gc`: `git_tree_sha` should be `repo.tree_sha`

---

src/Operations.jl
src/Types.jl

I missed this in #857. `nothing`, not the empty string, represents the absence of a value.

`registered_name` should return `nothing` when UUID is not registered

---

src/API.jl
src/Operations.jl
src/Types.jl
test/api.jl

I started off just trying to break down `handle_repos_add` (it was a beast!) but the refactoring allowed two bugs to be fixed along the way.
Fixes #951. In the first stage (`resolve_repo_add!`) we make sure certain fields of the `PackageSpec` are filled out (`name`, `uuid`, `repo.url`, `repo.rev`). This means we can have more consistent logic for the rest of the operation. In particular, once we have the UUID, it is simple to check if the package is pinned.
Fixes #614. I added a test which simply makes sure that the `mtime` for the source is the same after an `add` by URL.
In terms of refactoring, moving all git-heavy operations into their own functions helps to clarify the `add`-specific logic. Also, `handle_repos_add!` was being called from many places. It turns out those calls just …

Fix repo handling

---

src/REPLMode.jl

Sort commands within each super-spec instead of globally when displaying help.
---
This will display:
```
activate
[...]
update
registry-add
[...]
registry-update
```
instead of 
```
activate
[...]
preview
registry-add
[...]
registry-update
remove
[...]
update
```
i.e. group all `package` commands together first, and then all `registry` commands.
bors try

Pkg REPL: sort commands within each super-spec

---

src/Operations.jl
test/pkg.jl

fixes #876 
Thanks @fredrikekre for getting it down to a minimal repro.

fix rm: `project.extras` also contains dependency names

---

ext/TOML/src/print.jl

Fixes the first error in: https://github.com/JuliaLang/Pkg.jl/issues/820

Escape non-code dateformat characters

---

src/API.jl
src/GitTools.jl
src/Pkg.jl
test/pkg.jl

Allows gitlab urls to be normalized by a separate protocol.

Normalize Gitlab urls

---

src/Operations.jl

Don't throw for missing Versions.toml in the registry, instead consider that the same as no versions, i.e. an empty existing file.

Don't throw for missing Versions.toml in the registry

---

src/REPLMode.jl

This makes help syntax consistent with the command syntax for compound commands e.g. `pkg> registry add` and `pkg> help registry add`.
Also provides filtered and sorted help for "partial" commands e.g. `pkg> help registry`
Resolves #988

Provide more intuitive help interface

---

src/Operations.jl
src/Types.jl
src/versions.jl

Remove a case of type piracy

---

src/Operations.jl

We were printing the status for the context where you call `pkg> test` instead of the environment where the testing is happening.

Display status for the correct environment when testing.

---

src/Operations.jl

paths was previously given as relative the project file
fixes https://github.com/JuliaLang/Pkg.jl/issues/1047

fix absolutifying path when looking for deps

---

src/Pkg.jl

A few changes to help strings for `pin`, `free`.
Correct case for `PackageSpec`
Add examples for `pin`

Update doc strings for pin, free

---

src/Types.jl
test/pkg.jl

Overload Base.showerror instead of Base.show for PkgError.

---

src/Operations.jl
test/pkg.jl

Handle stdlibs explicitly in `update_package_add!`, `update_package_pin!`
and `update_package_test!`, since they are not versioned like other packages,
fixes #1077.
---
bors try

fix #1077: handle stdlibs in update_package_add and friends

---

.gitignore
Project.toml
docs/generate.jl
docs/make.jl
docs/src/api.md
docs/src/creating-packages.md
docs/src/glossary.md
ext/TOML/src/print.jl
src/API.jl
src/Operations.jl
src/Pkg.jl
src/REPLMode.jl
src/Types.jl
test/pkg.jl
test/test_packages/BuildProjectFixedDeps/.gitignore
test/test_packages/BuildProjectFixedDeps/Manifest.toml
test/test_packages/BuildProjectFixedDeps/Project.toml
test/test_packages/BuildProjectFixedDeps/deps/build.jl
test/test_packages/BuildProjectFixedDeps/src/BuildProjectFixedDeps.jl

Backports for Pkg 1.1.3

---

docs/src/creating-packages.md

Both before and after the build step, the log file contents were displayed

Print contents of build.jl in the documentation

---

src/Operations.jl
test/sandbox.jl
test/test_packages/Sandbox_PreserveTestDeps/Manifest.toml
test/test_packages/Sandbox_PreserveTestDeps/Project.toml
test/test_packages/Sandbox_PreserveTestDeps/dev/Foo/Project.toml
test/test_packages/Sandbox_PreserveTestDeps/dev/Foo/src/Foo.jl
test/test_packages/Sandbox_PreserveTestDeps/dev/Foo/test/Manifest.toml
test/test_packages/Sandbox_PreserveTestDeps/dev/Foo/test/Project.toml
test/test_packages/Sandbox_PreserveTestDeps/dev/Foo/test/runtests.jl
test/test_packages/Sandbox_PreserveTestDeps/src/Sandbox_PreserveTestDeps.jl

After much discussion(#1030), we agreed to make the sandbox mechanism more flexible; specifically when it comes to testing. 
This change simply collects the test environment direct dependencies and tries to preserve them. This is in addition to the dependencies which are specified by `Pkg.test("SomeDep")`
---
I still believe there is merit to a more structured workflow, but that requires more reflection and feedback from users. It will be interesting to see how the relationship between `Pkg` and testing develops. But refining the technical aspects of the sandbox is more important at this point.

Make sandbox isolation more flexible

---

src/API.jl
src/Operations.jl
src/REPL/command_declarations.jl

Adds API and REPL support for a `--strict` option, which simply preserves the whole, existing dependency graph.
Resolves #1107

Add `--strict` option to `add` and `dev`

---

Project.toml

Sometimes I use Pkg to modify Pkg's project file. It ends up putting the project file's top-level entries in a different order. This puts them in the order that Pkg wants them in.

Pkg should use it's own standard Project file order

---

src/Operations.jl
src/backwards_compatible_isolation.jl

---
We were using `@info` when installing from git and `printpkgstyle` when installing from a tarball.
bors r+

Fix printing when installing from git.

---

ext/TOML/src/print.jl
ext/TOML/test/runtests.jl

Wanted to use `by = VersionNumber` in https://github.com/JuliaComputing/Registrator.jl/pull/95, but had to workaround it with `by = x -> VersionNumber(x)`.

TOML.print: remove unnecessary ::Function restriction on by kwarg.

---

bin/gen_project.jl

The 'defined behaviour' as far as I am aware is:
> You call it with ARGS as directories where packages live. If the first argument is `-f` then it will overwrite existing `Project.toml` files, otherwise it will refuse to do so. It generates a `[compat]` section that approximates the bounds in the REQUIRE file as closely as possible, but unfortunately since the `[compat]` section doesn’t support version ranges this translation can be a bit messy. It is strongly encouraged that you manually review the `[compat]` section and edit by hand as appropriate.
(from Stefan's comment on Discourse).

Make `gen_project.jl` exit on finding Project.toml

---

bin/normalize.jl
src/versions.jl

This PR includes two things:
1. A script that normalizes all the `Compat.toml` files in `General` by loading then and then reapplying the version compression on both the keys and values en masse, thereby "normalizing" anything that's deviated for whatever reason from the standard way to express this.
2. A new version of `compress_versions` that is careful to produce a `VersionSpec` that respects gaps between versions that are considered "potentially breaking" according to semver. For example, if `A` claims compatibility with `B` versions `0.7.0`, `0.7.1`, `0.8.0`, `0.8.1` and `1.0.0` and those are the only versions that exist, then this will get compressed to `0.7-0.8, 1` whereas previously it would get compressed to `0.7-1` since there were no intervening incompatible versions.
We should …

semantic version compression & compat normalization script

---

src/generate.jl

---
@StefanKarpinski suggested on slack that `uuid4` is the recommended function for generating packages' UUID, so let's follow this recommendation in `Pkg.generate()`.

generate: use uuid4() instead of uuid1()

---

src/versions.jl

Previously `0.20` would sometimes get rendered as `0.20.0-0.20` which is technically correct, but not how we want to print it. This normalizes that to `0.20` upon VersionRange construction.

VersionRange: combine upper/lower in more cases

---

bin/recompress.jl

Since we're not normalizing compat RHS values anymore, this changes the `bin/normalize.jl` script to match, but then the name is no longer appropriate, so I also renamed it to `bin/recompress.jl`.

rename bin/{normalize => recompress}.jl, don't normalize

---

src/project.jl

Fixes #1120 
Tested manually. Not really sure how to make the TOML parser fail in the right way to automate the test though :grimacing:

Check for composite exception before iterating (fix 1120)

---

src/REPL/command_declarations.jl

---
I believe there is a bug in the markdown parser that leave extra empty code blocks when the `md` block ends with a code block, e.g.
````
julia> md"""
hello
""".content
1-element Array{Any,1}:
Markdown.Paragraph(Any["hello"])
julia> md"""
hello
""".content
1-element Array{Any,1}:
Markdown.Paragraph(Any["hello"])
julia> md"""
```
hello
```
""".content
1-element Array{Any,1}:
Markdown.Code("", "hello")
julia> md"""
```
hello
```
""".content
2-element Array{Any,1}:
Markdown.Code("", "hello")
Markdown.Code("", "")          < ----- ??
````

Consistent spacing for REPL mode help.

---

src/manifest.jl
src/project.jl

Write out `Project.toml` and `Manifest.toml` to a temporary
`IOBuffer`, before modifying the file on disk, fixes #1202.

Safer Project.toml and Manifest.toml printing

---

src/Types.jl
test/api.jl

Make sure we have found the registry path when developing packages, fixes #1206.

Make sure we have found the registry path when developing

---

src/API.jl
test/pkg.jl
test/test_packages/ExtraDirectDep/Manifest.toml
test/test_packages/ExtraDirectDep/Project.toml

So #1106 occurred because of an inconsistency between the toml files. This just explicitly checks for this case.

Check for consistent toml files before `instantiate`ing

---

docs/src/creating-packages.md

It might be nicer if `pkg> generate MyPackage` automatically ran `gen_project.jl` for an existing package, but at least we should document this.

Document gen_project.jl

---

src/API.jl
test/pkg.jl

Fix gc when unexpected files are located in package directories, fixes #1228.

Fix gc when unexpected files are located in package directories

---

src/API.jl
src/Display.jl
src/Pkg.jl
src/REPL/command_declarations.jl
src/REPLMode.jl
test/api.jl
test/pkg.jl
test/registry.jl
test/repl.jl
test/utils.jl

---
I think the current behaviour causes too much confusion, and you often just want to see the absolute status anyway. See e.g. https://discourse.julialang.org/t/pkg-status-and-project-toml-out-of-sync/24473, https://stackoverflow.com/questions/56050364/how-to-prevent-pkg-jl-to-hold-state-beyond-project-toml-and-manifest-toml etc.
Edit: https://github.com/JuliaLang/Pkg.jl/pull/1205/files?w=1 for easier review.

Require --diff for diff output in status

---

docs/src/compatibility.md

I tend to forget the difference between the tilde and caret specifier behaviour when the major version is 0. I believe this is the behaviour but let me know if my understanding is incorrect.

Add tilde examples using a major version of 0

---

docs/src/creating-packages.md

Add notes about interaction between Project.toml, test/Project.toml and their Manifest.tomls.
---
I think we want to add a note like this since currently `test/Manifest.toml` is completelly ignored, and we have not resolved https://github.com/JuliaLang/Pkg.jl/issues/1233 yet.

Add notes about interaction between Project.toml, test/Project.toml

---

README.md

@notriddle and I created a "Bors enabled" badge that can be added to README files, similar to "Travis build passing" badges, "Dependabot enabled" badges, etc.
The Bors badge looks like this:
<p><a href="https://app.bors.tech/repositories/2953"><img alt="Bors enabled" src="https://bors.tech/images/badge_small.svg"></a></p>
This pull request adds the Bors badge to the "Build Status" section of the Pkg.jl README.

Add "Bors enabled" badge to README

---

src/API.jl

Fix error message when adding a package with the same name or UUID as project

---

src/Types.jl

Otherwise we put an entry into the manifest with the wrong casing and code loading uses case sensitivity which means that we will fail to load the package,

use case sensitive isdir when deving

---

src/API.jl
src/Operations.jl
src/Pkg.jl
src/backwards_compatible_isolation.jl
test/api.jl

Before:
```julia
Pkg.test(julia_args=[`--compiled-modules=no`, `--compile=min`], test_args=["foo", "bar"])
```
After:
```julia
Pkg.test(julia_args=`--compiled-modules=no --compile=min`, test_args=`foo bar`)
```
close #1278

Use Cmd for {julia,test}_args keyword arguments

---

src/API.jl
src/Pkg.jl
src/REPL/command_declarations.jl
test/pkg.jl
test/repl.jl

This PR adds `verbose` option to `Pkg.instantiate`.  This is useful, for example,if you want to set up multiple projects in installation step of CI.  Using `Pkg.build(verbose=true)` would invoke unnecessary redundant builds while `Pkg.instantiate()` prints only very minimum log.  It can be fixed by supporting `verbose` in `Pkg.instantiate`.

Add verbose option to Pkg.instantiate

---

.travis.yml
appveyor.yml

Only run CI for 1.3 and nightly on master, this version of Pkg will not ship with earlier Julia anyway.

Only run CI for LTS, 1.3 and nightly on master

---

src/Artifacts.jl
src/GitTools.jl
src/PlatformEngines.jl
test/artifacts.jl
test/artifacts/bad/incorrect_gitsha.toml
test/artifacts/bad/incorrect_sha256.toml
test/binaryplatforms.jl
test/platformengines.jl
test/test_packages/ArtifactInstallation/Artifacts.toml

This branch contains a set of improvements to Artifacts/PlatformEngines:
* Fix "porous" platform support; there is one method (`ensure_all_artifacts_installed()`) that will break if a multi-platform artifact doesn't have support for the current platform.  Oops.
* Fix artifact verification; when downloading, I was not verifying that the artifact's git tree sha actually was what the `Artifact.toml` advertised; there's an issue here where one package could list the incorrect tree hash, then put something completely different in that location (because the download happened directly, rather than to a temporary directory, verified, then moved into place).  This plugs that hole, so there is now one fewer ways we can get the wrong thing in the right place.
* Fix broken symlink support; As part of …

Artifacts: fix porous platform support

---

src/Operations.jl
test/api.jl
test/pkg.jl

#1217 suggests there is some confusing behavior in `pin`.
More consistent behavior would be:
- `pkg> pin Example@x` means "Try to pin the package to the given registered version, if it exists"
- error out when either the package or the version is unregistered
- `pkg> pin Example` means "Preserve the package at whatever state it happens to be in"
- error out for stdlibs since stdlibs can not really be mutated in the way other packages can
---
close #1217

Adjustments to `pin` API

---

src/Types.jl
test/pkg.jl

If a new project is created using "JuliaProject.toml" instead of
"Project.toml", the corresponding manifest file should be named
"JuliaManifest.toml" instead of "Manifest.toml".
Locally, even without my proposed changes, I get
```
Got exception outside of a @test
KeyError: key "uuid" not found
```
for
* [instantiate should respect tree hash](https://github.com/jonas-schulze/Pkg.jl/blob/default-manifest-name/test/pkg.jl#L753),
* [instantiate checks for consistent dependency graph](https://github.com/jonas-schulze/Pkg.jl/blob/default-manifest-name/test/pkg.jl#L771) and
* [up should prune manifest](https://github.com/jonas-schulze/Pkg.jl/blob/default-manifest-name/test/pkg.jl#L779)
Are those relevant/related?

Update default manifest file name

---

docs/src/api.md
src/API.jl
src/Operations.jl
src/Pkg.jl
src/Types.jl
test/pkg.jl
test/repl.jl

This provides a low-level interface that handles queries about the dependency graph.

Query interface

---

src/Operations.jl
src/backwards_compatible_isolation.jl
test/api.jl
test/test_packages/BasicCompat/Project.toml
test/test_packages/BasicCompat/src/BasicCompat.jl

`rm` should also remove from `compat`

---

docs/src/api.md
src/Pkg.jl

---
So I noticed just after merging that the formatting was a little weird :sweat_smile:.
@fredrikekre would you happen to know why `Pkg.project` doesn't appear in the API docs? I admit that I'm not clear on how the docs are generated, I just tried following the same format as the other API functions.

Tweak API docs for `dependencies` and `project`

---

src/PlatformEngines.jl

Messages like
```
[ Info: Downloading https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.6+0/Bzip2.v1.0.6.x86_64-linux-gnu.tar.gz to /tmp/jl_QkNkzY-download.gz...
```
does not seem very useful to users.

Set quiet_download to true by default.

---

docs/src/artifacts.md
src/Artifacts.jl
src/Operations.jl
test/artifacts.jl

---
Currently, e.g. adding this fork of `JuliaBinaryWrappers/Zlib_jll.jl` with `Artifacts.toml` changed to `JuliaArtifacts.toml`
```
pkg> add https://github.com/fredrikekre/Zlib_jll.jl
```
doesn't download artifacts at install time.

Fully support JuliaArtifacts.toml filename everywhere.

---

src/Types.jl
test/api.jl

The behavior that a user expected in #1098 is reasonable. Basically they want to resolve the pkg against the manifest, which already has all the necessary information. This also adds an error message for `Pkg.develop(PackageSpec(uuid=unregistered_uuid))`.
Note that we can't go from `add`->`dev` in the same way until we merge something like #492.
---
resolve #1098
resolve #328
Example:
```
(afdasf) pkg> add https://github.com/00vareladavid/Unregistered.jl
Updating git-repo `https://github.com/00vareladavid/Unregistered.jl`
Updating git-repo `https://github.com/00vareladavid/Unregistered.jl`
Updating `/tmp/afdasf/Project.toml`
[dcb67f36] + Unregistered v0.1.0 #master (https://github.com/00vareladavid/Unregistered.jl)
Updating `/tmp/afdasf/Manifest.toml` …
```

Make `develop` resolve more flexible

---

src/API.jl
src/Operations.jl
src/Registry.jl
src/Types.jl
src/backwards_compatible_isolation.jl
src/generate.jl

Print more stuff to `ctx.io`, which now defaults to `stderr` except when the user has explicitly asked for the output (e.g. `pkg> status`, `pkg> registry status` and `pkg> help`).

More printing updates

---

src/manifest.jl
test/manifest/bad/bad_dep_name.toml

This enhances error messages from the manifest parsing logic.
---
Fix #1318 
The error from #1318 will now read:
```
ERROR: `DocStringExtensions=ffbed154-4ef7-542d-bbb7-c09d3a79fcae` depends on `Pkg=748391e3-3ea3-41aa-8037-d96b5d03e7c6`, but entry with UUID `748391e3-3ea3-41aa-8037-d96b5d03e7c6` has name `Pkg2`.
```

More informative error messages when parsing manifest files.

---

docs/src/managing-packages.md

Highlight a bit more the posibility of relative paths

---

src/versions.jl
test/pkg.jl

This is not a permanent fix, it's to paper over the fact that we have
two, slightly incompatible concepts of a `VersionNumber` within `Pkg`;
the `VersionNumber` and the `VersionBound`.  The latter does not support
`build` or `prerelease` specifiers, which causes much confusion within
`compress_versions()` when it attempts to compare equality of
`VersionNumber` objects with their supposedly-equivalent `VersionBound`
objects.  To fix this, we explcitly strip those pieces of information
before doing any comparisons.

Fix `compress_versions()` confusion with build number VersionNumber's

---

src/Artifacts.jl
test/artifacts.jl

Otherwise, it ignores your selection of `platform` when testing to see if the artifact even exists.

Properly Plumb Platform kwarg for `ensure_artifact_installed()`

---

docs/src/managing-packages.md
src/API.jl
src/Operations.jl
src/REPLMode/REPLMode.jl
src/REPLMode/command_declarations.jl
src/REPLMode/completions.jl
src/Types.jl
src/backwards_compatible_isolation.jl
src/generate.jl
src/manifest.jl
src/project.jl
test/pkg.jl
test/repl.jl

`preview` had good intentions. By allowing to check what happened when executing a command without it taking effect, it was intended for the user to avoid pkg commands that mess up their project. However, in practice, no one think they will do a mistake so no one uses preview. It is also quite invasive in the code base. You constantly need to think if you are running things in preview mode and in that case try to emulate the normal usage but at the same time don't do any persistent mutations.
What is needed is instead `undo` + `redo`. This just removes `preview` and I will implement `undo` + `redo` to replace it (unless someone beats me to it)

remove preview command

---

src/API.jl
src/Operations.jl
src/Pkg.jl
src/REPLMode/REPLMode.jl
src/REPLMode/command_declarations.jl
src/Types.jl
test/api.jl
test/test_packages/ShouldPreserveAll/Manifest.toml
test/test_packages/ShouldPreserveAll/Project.toml
test/test_packages/ShouldPreserveDirect/Manifest.toml
test/test_packages/ShouldPreserveDirect/Project.toml
test/test_packages/ShouldPreserveNone/Manifest.toml
test/test_packages/ShouldPreserveNone/Project.toml
test/test_packages/ShouldPreserveSemver/Manifest.toml
test/test_packages/ShouldPreserveSemver/Project.toml
test/utils.jl

---
Fix #110
Pretty much what Kristoffer recommends in #1274.
Example:
```
afdwer) pkg> status
Status `/tmp/afdwer/Project.toml`
[295af30f] Revise v1.1.0
(afdwer) pkg> add MagneticReadHead@0.2.2
Updating git-repo `https://github.com/JuliaRegistries/General.git`
Resolve_Tier All dependency versions.
Resolve_Tier Direct dependency versions.
Resolve_Tier Direct dependency semver constraints.
ERROR: Unsatisfiable requirements detected for package MagneticReadHead [63dd013e]:
<stacktrace here>
(afdwer) pkg> add --preserve=none MagneticReadHead@0.2.2
Installed MagneticReadHead ─ v0.2.2
Installed Cassette ───────── v0.2.6
Updating `/tmp/afdwer/Project.toml`
[63dd013e] + MagneticReadHead …
```

Introduce support for tiered resolver

---

src/API.jl
src/REPLMode/argument_parsers.jl
src/REPLMode/command_declarations.jl
test/repl.jl

This checking is necessary in the API layer, so there is no need to duplicate it in the REPL layer. Also tweaked the API error handling to be a bit more clear/verbose.
---
fix #1257 
Example:
```
(foobar) pkg> dev JSON Example#master
ERROR: It is invalid to specify a git revision. git revision `master` was specified for package `Example`.
```
close #589
Example:
```
(v1.0) pkg> dev /tmp/idonotexist
[ Info: Resolving package identifier `/tmp/idonotexist` as a URL.
Cloning git-repo `/tmp/idonotexist`
ERROR: failed to clone from /tmp/idonotexist, error: GitError(Code:ERROR, Class:Net, unsupported URL protocol)
```

Offload `PackageSpec` checking from REPL to API layer

---

src/Types.jl
test/pkg.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/1345.
We assert later that we both have a name and uuid for example so this seems good.
Also I removed the `"Please specify by known name=uuid" because it is completely non-obvious how to use that and it won't even fix any of the problems when this is reported. Better to not give false hope.

also check that name is resolved

---

src/Display.jl
src/Operations.jl
src/Types.jl
src/backwards_compatible_isolation.jl
src/manifest.jl
src/project.jl

I didn't like how we passed in `env.project, env, old_env, ctx` to one function (all of this can be gotten from `ctx` and the first argument `project` was immediately overwritten etc) and also options like `display_diff = true` seems to indicate that that part should just be in its own function. Therefore, factor out the project diff printing into a new function into `Display` and call that function.
Also, slight refactoring to the `write_manifest` and `write_project` to make them look more similar to each other.

small refactor of write_env functions

---

test/artifacts.jl

This causes us to have the wrong Project file when exiting the Artifact tests. This means that in latter test modules it is possible that we load the sysimg baked Pkg instead of the one we are testing.

fix not returning to project in artifact test

---

test/api.jl
test/artifacts.jl
test/binaryplatforms.jl
test/pkg.jl
test/platformengines.jl
test/registry.jl
test/repl.jl
test/resolve.jl
test/runtests.jl
test/sandbox.jl
test/utils.jl

- Be more careful about not importing a "global" Pkg in modules. If our project is messed up we will use the stdlib Pkg which is bad. Instead, only `import Pkg` in the `runtests.jl` and refer everything to that Pkg with `import ..Pkg`.
- Make `Utils` a module so that we don't need to include (and recompile it) in all submodules.
- Move some test files that were included in the end of `pkg.jl` out into `runtests.jl`.
- Define some of the variables in `temp_pkg_dir` outside the try block.

Some small test improvements

---

docs/src/creating-packages.md

There were two broken links to `gen_project.jl` in the documentation.
https://github.com/JuliaLang/Pkg.jl/pull/1369 fixed one of the broken links but not the other.
This PR fixes the other.
cc: @fredrikekre @KristofferC

Fix broken link to `gen_project.jl`

---

src/Operations.jl
src/Types.jl

Make files read only when installing a given git revision, and when installing a package because of a dependency from a Pkg.develop'd package, fixes #729, fixes #1313, fixes #1382.

Make files read only more often

---

src/Display.jl
src/Types.jl
src/manifest.jl
src/project.jl

Instead of having to reparse Project + Manifest again just before we write out the new ones. I think this makes more sense (avoids reparsing the manifest + project and is not sensitive for writing the diff before the files update). I wanted this for the undo/redo stuff but factored out this change here.

store the initial manifest and project in the envcache

---

docs/src/managing-packages.md
src/API.jl
src/Display.jl
src/GitTools.jl
src/Operations.jl
src/REPLMode/argument_parsers.jl
src/Types.jl
src/backwards_compatible_isolation.jl
src/manifest.jl
test/api.jl
test/pkg.jl
test/repl.jl
test/utils.jl

Goals:
- Treat relative paths consistently for `dev` and `add`. `dev` does this correctly, but the behavior for `add` is confusing (see #1215).
- Refactor `handle_repos_*` in hopes of making the internal structure more clear.
- Prevent an unnecessary cache update on `add` (fix #1343).
- Prevent an unnecessary update of cached clone on instantiate. We should only fetch if the tree does not already exist in the clone.
---
close #709

Rework repo handling

---

docs/src/compatibility.md

The new "Pre-1.0 behavior" section clarifies many things with examples but I find that the "directionality" of the compatibility became less clear.  So, I suggest merging back some points from the old sentence.

Clarify pre-1.0 compatibility

---

docs/src/compatibility.md
docs/src/toml-files.md

... as discussed in #1417.
close #1417

Clarify backward-compatible feature additions require only minor bump in pre-1.0 packages

---

src/API.jl
src/GitTools.jl
src/Operations.jl
src/Types.jl
test/utils.jl

I was working on adding subdir support (multiple packages in the same repo) but even with https://github.com/JuliaLang/Pkg.jl/pull/1372 I found the repo handling code a bit tricky to follow.
This is an attempt to go through the code, add some comments, and arguably clean up some things when going through the code again.
It ended up with about -100 lines which I think is a good indication that it is arguably a bit simpler now.
Some things I did in no particular order:
- Push the `GitRepo` uses "up the stack" so we don't open and close it in all small helper functions.
- Move uses of `CredentialsCache` inside `GitTools.fetch` and `GitTools.clone` instead of creating them all over the place
- Rename some things to be a bit more precise / consistent with other uses, for example:
- …

WIP: refactor some of the repo handling code

---

test/utils.jl

Previously:
```jl
julia> Utils.with_temp_env("env1") do
@show Base.active_project()
Utils.with_temp_env("env2") do
@show Base.active_project()
end
@show Base.active_project()
end
Base.active_project() = "/tmp/jl_pQ0ImW/env1/Project.toml"
Base.active_project() = "/tmp/jl_WXMcOy/env2/Project.toml"
Base.active_project() = "/home/kc/Pkg.jl/Project.toml"
```
In other words, we didn't go back to the previous project before.

properly return to the previous project in with_envs

---

docs/src/compatibility.md

When I first looked at this section i thought it was about pre-Julia 1.0 behavour,
and was intended to be related to how Project.toml differs from REQUIRE.
I quickly saw my mistake but  I figure a this tiny change can make this a little better.

Retitle Pre-1.0 behavior re-compat

---

src/PlatformEngines.jl

This was accidentally dropped when I abandoned my previous 7z rework PR.  This needs to be merged into 1.3 to complete the fixes for https://github.com/JuliaLang/julia/pull/33505

Change direct path to `7z` to point toward `libexec`, not `bin`

---

src/API.jl
test/pkg.jl

Fixes the precompilation problems in https://github.com/JuliaLang/julia/pull/33536.

Only add undo snapshot in __init__ if we have a project to snapshot.

---

src/Operations.jl
src/backwards_compatible_isolation.jl

One annoying thing that can happen when one runs a process that redirects stdin / stdout and that process runs Pkg.test is that output gets interleaved. The way that happens is that some output to stdout is still buffered (and haven't been commited to the redirected stdout), then Pkg.test runs, which starts a new process, and when the process finishes it flushes all its stdout to the redirected stream. Then we continue with the Pkg process which will at some point commit its buffered stuff to stdin. The stuff that was buffered before Pkg.test was called will thus come out in the wrong order.
Since we started directing much of our stuff to stderr, this is less important since stderr is (I think!) usually unbuffered but this makes sense to do anyway.

flush stdout before spawning new processes

---

src/API.jl
src/Pkg.jl
src/Types.jl
test/pkg.jl

Move save of initial snapshot to `EnvCache` constructor instead of doing it from `__init__`.
Should fix the remaining problems of https://github.com/JuliaLang/julia/pull/33536

Move save of initial snapshot to EnvCache constructor

---

ext/TOML/src/TOML.jl
src/API.jl
src/Artifacts.jl
src/BinaryPlatforms.jl
src/Display.jl
src/GitTools.jl
src/Operations.jl
src/Pkg.jl
src/PlatformEngines.jl
src/REPLMode/REPLMode.jl
src/Resolve/graphtype.jl
src/Types.jl
src/backwards_compatible_isolation.jl
src/generate.jl
src/versions.jl

This is helpful to the compiler, since e.g. `DataValue(nothing) == nothing` is true.

use `===` for comparison to `nothing` and Symbols

---

src/REPLMode/completions.jl
test/repl.jl

This just catches any parsing errors and refuses to complete.
Fix #1453.

do not throw errors when autocompleting

---

src/API.jl
src/Types.jl

I'm experimenting if I can use the latest Pkg.jl without rebuilding `julia`.  The idea is to have a "shim" package like this:
```julia
module LatestPkg
include("PATH/TO/Pkg/src/Pkg.jl")
using .Pkg
end
```
For full code, see: https://github.com/tkf/LatestPkg.jl
It turned out this works once I fixed a few non-relative imports in Pkg.jl.  I'm not sure how much usable it is yet.  But I guess it still makes sense, even just for consistency reason?

Use relative import everywhere (to use latest Pkg.jl without rebuilding julia)

---

src/Artifacts.jl

Kristoffer's work on PackageCompiler (And subsequent despair at the lack of relocatability within JLL packages) inspired me to migrate much of the `Artifact.toml` parsing work to compile-time, hopefully eradicating the last bit of non-relocatable logic from JLL packages (and indeed all packages using `@artifact_str`.

Relocatable `@artifact_str`

---

src/Artifacts.jl
src/Operations.jl
src/Pkg.jl
src/PlatformEngines.jl
src/Types.jl

First steps towards implementing https://github.com/JuliaLang/Pkg.jl/issues/1377.

allow using Pkg protocol to get packages, artifacts & registries

---

src/GitTools.jl
test/artifacts.jl
test/new.jl

Git only looks at the user's executable bit. This seems to be causing issues for users with strict umasks: https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/527.

fix GitTools.tree_hash executableness criterion

---

src/GitTools.jl
test/artifacts.jl

When testing for directories to exclude from hashing, we must exclude
not only empty directories, but also directories that themselves contain
nothing but empty directories; in essence, we suppress adding
directories that have no files contained within their entire subtree.
While fixing this, it seemed prudent to eliminate the `names` argument
to `tree_hash()`, especially as it was not actually used to iterate
over.
This will fix the error reported in https://github.com/JuliaLang/julia/pull/33979#issuecomment-561041847

Fix tree hashing with nested empty directories

---

src/PlatformEngines.jl

People are getting complaints from `tar` that their mtimes are in the future: https://discourse.julialang.org/t/artifacts-toml-timestamp-is-in-the-future/32047. We don't actually care about mtimes at all, so we should pass the `-m` flag to tar when extracting to tell it to just create files with natural system mtimes based on their actual time of modification.

PlatformEngines: use `tar -m` to ignore mtimes

---

src/PlatformEngines.jl

WIP. The first commit reverts the API part of header support, which was broken anyway since only `download` actually used the headers argument—I forgot to pass it through in all the other functions. Testing fail.

Pkg Protocol: client authentication support (part 2)

---

src/REPLMode/REPLMode.jl
src/REPLMode/argument_parsers.jl
src/REPLMode/command_declarations.jl
src/REPLMode/completions.jl
test/new.jl

Introduces a new syntax for shared/named environments. Includes autocompletion support and the nicer printing Stefan mentioned in #930.
Example:
```
(Pkg) pkg> activate @
@Example   @Profiling  @SomeEnv    @v1.0       @v1.1       @v1.2       @v1.3
(Pkg) pkg> activate @Profiling
Activating environment at `~/.julia/environments/Profiling/Project.toml`
(@Profiling) pkg> 
```
Close #930

Introduce special REPL syntax for shared environments

---

src/PlatformEngines.jl

The only information this provides over what we can get just by clients connecting is:
* Client UUID: randomly generated, totally anonymous UUID which allows correlating requests from the same Julia install over time.
* Project path hash: secure hash of the project path, which allows correlating requests from this client that are associated with the same project.
Regarding privacy: as long the secret salt value isn't leaked, it's impossible to work out what the project path was—even if by brute force, since you don't know what the salt values is. Even if the salt value is leaked, you'd still have to reverse a secure hash. The other purpose of the secret salt is so that if the same project path is used by different Julia installs, they won't have the same hash.
Telemetry files are …

Pkg protocol: basic anonymous opt-out telemetry

---

src/PlatformEngines.jl

I meant to do this before merging the telemetry PR. Should go in 1.4.

telemetry: remove commit header

---

Project.toml
src/Artifacts.jl
src/BinaryPlatforms.jl
src/Pkg.jl
test/FakeTerminals.jl
test/api.jl

After spending some quality time with `--trace-compile=stderr` and `@snoopi`, I have found a fairly minimal set of changes that speeds up loading of [`TestGtkMegaJLL.jl`](https://github.com/giordano/TestGtkMegaJLL.jl) from `2.12s` to `0.69s` on my machine.  It's all essentially nonspecialization hacks.

Disable needless specialization in Artifacts code

---

src/PlatformEngines.jl

When extracting files as `root`, `tar` will attempt to set ownership, which doesn't make much sense when moving from one machine to another.  (Props to Stefan for calling this out in the `Tar.jl` readme at the exact same time as it was reported in an issue).
Should fix https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/555

Do not ever attempt to set owner when extracting tarballs

---

src/Operations.jl
test/new.jl

reintroduces some functionality I missed in #1427 
close #1550

provide a fallback when sandboxing a package with no Project.toml

---

src/Operations.jl
src/Pkg.jl
src/Types.jl
test/new.jl

I think this makes `Pkg.dependencies` a bit nicer to work with.
Also, is it possible for this to go into 1.4 or is it too late?

use more consistent naming for PackageInfo fields

---

src/Operations.jl
test/new.jl
test/test_packages/CompatOutOfSync/Manifest.toml
test/test_packages/CompatOutOfSync/Project.toml

`tiered_resolve` treats `ResolverError`s as a signal to retry with different version constraints. I think this is ok because no other code outside of `Resolve` cares about the distinction between `PkgError` v `ResolveError`.
An alternative fix is to check for the error message in `tiered_resolve` but I think that is uglier at this point.

treat compat errors as `ResolverError`s

---

test/new.jl
test/test_packages/SameNameDifferentUUID/Manifest.toml
test/test_packages/SameNameDifferentUUID/Project.toml
test/test_packages/SameNameDifferentUUID/dev/Example/Project.toml
test/test_packages/SameNameDifferentUUID/dev/Example/src/Example.jl
test/test_packages/SameNameDifferentUUID/dev/Example/test/runtests.jl
test/test_packages/SameNameDifferentUUID/dev/Unregistered/Project.toml
test/test_packages/SameNameDifferentUUID/dev/Unregistered/README.md
test/test_packages/SameNameDifferentUUID/dev/Unregistered/src/Unregistered.jl
test/test_packages/SameNameDifferentUUID/src/SameNameDifferentUUID.jl

this should prevent a regressions for this case: https://discourse.julialang.org/t/cant-test-package-in-manifest-but-not-in-project/32663

test: `Pkg.test` on dependencies with same name but different UUID

---

src/Artifacts.jl
test/test_packages/ArtifactInstallation/src/ArtifactInstallation.jl

We need to properly escape a macro input variable.  This should fix https://github.com/JuliaLang/Pkg.jl/issues/1579

Properly `esc()` variable in `@artifact_str`

---

src/Operations.jl
test/new.jl

This fixes a bug for `up --fixed`. When this flag is enabled, we actually want to do the inverse operation and *not* preserve any version information for the unspecified direct dependencies.

[WIP] fix `fixed` option for `Pkg.update`

---

src/Operations.jl

This seems accidentally left in?
This causes an ugly
```
rr = ProcessFailedException(Base.Process[Process(`/opt/julia/bin/julia -Cnative -J/opt/julia/lib/julia/sys.so -g1 --code-coverage=none --color=no --compiled-modules=yes --check-bounds=yes --inline=yes --startup-file=no --track-allocation=none --eval 'append!(empty!(Base.DEPOT_PATH), ["/home/pkgeval/.julia", "/opt/julia/local/share/julia", "/opt/julia/share/julia", "/usr/local/share/julia"])
append!(empty!(Base.DL_LOAD_PATH), String[])
cd("/home/pkgeval/.julia/packages/AbstractNumbers/VWdQ8/test")
append!(empty!(ARGS), String[])
include("/home/pkgeval/.julia/packages/AbstractNumbers/VWdQ8/test/runtests.jl")
'`, ProcessExited(1))])
```
when `Pkg.test` fails.

remove @show debug output when test fails

---

src/GitTools.jl
test/new.jl

When hashing, we were accidentally excluding directories that contained
only symlinks that pointed to other directories.  This fixes that, and
adds a regression test

Include directories that contain only symlinks to other directories

---

src/PlatformEngines.jl

Always a good idea to version your protocol. This is separate from the Julia version because the Julia version leaks more information: multiple different Julia versions could use the same version of the protocol, this only sends information about what protocol features the client supports. We could conceivably even backport the Pkg protocol onto older versions of Julia, in which case you could have situations where an older Julia supports a newer Pkg protocol, so versioning separately is a good idea. Even though this header is added by the telemetry function, it's not really telemetry, it's part of the protocol, so it's sent unconditionally.

Pkg protocol: always include protocol version number

---

src/BinaryPlatforms.jl
test/binaryplatforms.jl

It turns out we can actually build Julia for `armv6l` architectures (for use on things like the Raspberry Pi Zero W).  Unfortunately, I had been led to believe that the only 32-bit arm architecture Julia would ever run on would be `armv7l`, so we went for the shortcut of identifying tarballs as `arm-linux-gnueabihf` instead of the full `armv7l-linux-gnueabihf` (since many other projects did this as well).
It turns out, we should have just done the correct, if slightly harder thing, first.  So this PR changes us to emitting `armv7l-linux-gnueabihf` and `armv6l-linux-gnueabihf` by default, but still parsing `arm-linux-gnueabihf` as `armv7l`, so as to maintain backward compatibility (and compatibility with other systems).

BinaryPlatforms: Add `armv6l` architecture

---

src/Artifacts.jl

`download_info` can be a vector of tuples, not the other way around.
Fixes: https://github.com/JuliaLang/Pkg.jl/issues/1463

fix bind_artifact! docstring for download_info

---

src/Pkg.jl

Update precompile script to properly block cloning of the General registry, fixes #1320.

Update precompile script to block cloning of registry

---

src/PlatformEngines.jl

This is helpful for distinguishing one-time users from deployed systems
which install a set of packages a single time and then run until a VM is
spun down. Users will usually be in the REPL.

telemetry: send whether Julia is interactive

---

src/Artifacts.jl
src/Operations.jl
src/PlatformEngines.jl
src/Types.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/1600, fixes https://github.com/JuliaLang/Pkg.jl/issues/1554
I didn't really like how the artifact download looked for some reasons:
- It printed `Downloading artifacts...` unconditionally.
- It used an `@info` log to print download url and location which showed some temp directory and (for a user) garbage hash name
- It kept the progress bar even after the download was finished.
This is a (arguably) ugly attempt to remedy this. The download now looks like:

make artifact download more similar to rest of Pkg "theme"

---

src/PlatformEngines.jl

Alternative to https://github.com/JuliaLang/Pkg.jl/pull/1625. Write the telemetry file to a temp file and then move it into place.

make telemetry file writing more likely to be atomic

---

src/PlatformEngines.jl
test/platformengines.jl

This PR adds a hook into `get_auth_header` which is called when Pkg can't find authentication for the current package server.
```    
register_auth_error_handler(f)
Registers `f` as the topmost handler for failures in package server authentication.
`f` must be a function that takes three input arguments `(url, pkgserver, err)`, where `url` is the
URL currently being downloaded, `pkgserver = Pkg.pkg_server()` the current package server, and
`err` is one of `no-auth-file`, `insecure-connection`, `malformed-file`, `no-access-token`,
`no-refresh-key`, `insecure-refresh-url`,  `malformed-file`, or `no-access-token`.
The handler `f` needs to return a tuple of `Bool`s `(handled, should_retry)`. If `handled` is `false`,
the next handler in the stack will be called, otherwise `get_auth_header` is …
```

Authentication Hooks

---

src/PlatformEngines.jl

We need to make the erroring implementation have the same signature as
the non-erroring implementations.
Fixes https://github.com/JuliaLang/Pkg.jl/issues/1616

Fix `gen_unpack_cmd()` signature inconsistency

---

src/Types.jl

This is a frequent source of annoying bugs which are pretty much impossible to resolve for a user if you don't know how to (remove `.julia/clones`). Since the cache doesn't work, remove it.
Fixes https://github.com/JuliaLang/Pkg.jl/issues/465

remove the cache for devved packages

---

src/PlatformEngines.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/1640.
`mktemp` doesn't make sense to me if we want to move the whole file after, and also, `mktemp` means that we have the file open and Windows might not like to move opened files.

fix not trying to delete moved file in load_telemetry_file

---

src/Pkg.jl
src/PlatformEngines.jl

The tests in #1671 are removed since this branch doesn't have "Authentication Header Hooks" testset yet. I've tested it locally using the following servers:
* `http://juliapkg.lflab.cn`
* `https://mirrors.lflab.cn/julia` and `http://mirrors.lflab.cn/julia`

backport: Allow pkg server in scheme://server/path format (#1671)

---

src/Types.jl

`mktempdir` shows an error if the dir is removed in the `do` block:
```
┌ Error: mktempdir cleanup
│   exception =
│    IOError: chmod: no such file or directory (ENOENT)
│    Stacktrace:
│     [1] uv_error at .\libuv.jl:97 [inlined]
│     [2] #chmod#21(::Bool, ::typeof(chmod), ::String, ::UInt16) at .\file.jl:888
│     [3] chmod at .\file.jl:887 [inlined]
│     [4] #rm#9(::Bool, ::Bool, ::typeof(rm), ::String) at .\file.jl:258
│     [5] #rm at .\none:0 [inlined]
│     [6] #mktempdir#18(::String, ::typeof(mktempdir), ::Pkg.Types.var"#113#116"{String}, ::String) at .\file.jl:637
│     [7] mktempdir(::Function, ::String) at .\file.jl:632 (repeats 2 times)
│     [8] #update_registries#111(::Bool, ::typeof(Pkg.Types.update_registries), ::Pkg.Types.Context, ::Array{Pkg.Types.RegistrySpec,1}) …
```

`cp` instead of `mv` in `update_registries`

---

src/API.jl
src/Operations.jl
src/Types.jl
test/new.jl

This manifested itself that the registry got updated when doing `Pkg.instantiate` even though everything was installed if you had a relative path in the manifest and were not in the directory of the project file.

fix bug in Operations.source_path with paths relative to project

---

src/PlatformEngines.jl

The boolean variable that is set to true when running a GitHub action is plural. The singular is the ID of the action.

Pkg telemetry headers: GITHUB_ACTION => GITHUB_ACTIONS

---

src/Operations.jl
test/new.jl
test/pkg.jl
test/test_packages/ExtraDirectDep/src/ExtraDirectDep.jl

@SimonDanisch posted an error message that didn't make sense to me:
```
(AbstractPlotting) pkg> add MakieGallery#master
ERROR: Unsatisfiable requirements detected for package FreeTypeAbstraction [663a7486]:
FreeTypeAbstraction [663a7486] log:
├─possible versions are: 0.6.0 or uninstalled
├─FreeTypeAbstraction [663a7486] is fixed to version 0.6.0
└─found to have no compatible versions left with AbstractPlotting [537997a7] 
└─AbstractPlotting [537997a7] log:
├─possible versions are: 0.9.0-0.9.21 or uninstalled
└─restricted to versions 0.9.16-0.9 by MakieGallery [dbd62bd0], leaving only versions 
```
The weirdness here is:
- Why is the resolver saying that the possible versions for `AbstractPlotting` is `0.9.0-0.9.21` when AbstractPlotting is the active project and should thus have a fixed …

Add current project as a Fixed package for the resolver and fix a bug when developed packages had cycles in paths

---

src/API.jl
src/REPLMode/command_declarations.jl
test/new.jl

Resolve #1201 
I find myself needing this often as well.
Example:
```
Activating new environment at `/tmp/tmpVtb1OR/Project.toml`
```

Introduce `temp` option for `activate`

---

src/REPLMode/REPLMode.jl
src/REPLMode/command_declarations.jl

This document "short name" aliases of commands
1. in the main help text, e.g:
```
update, up: update packages in manifest
```
2. in the help text of the command, e.g. 
```
[up|update] [-p|--project]  [opts] pkg[=uuid] [@version] ...
```
I don't insist on both points, one of them could be enough.
For 2), I'm not sure how to do this in a less ugly way. Maybe just a paragraph on itself saying "Alias: up". But this is not great when there are already 2 paragraphs for 2 distinct usages, like for help:
```
help
List available commands along with short descriptions.
help cmd
If cmd is a partial command, display help for all subcommands. If cmd is a full command, display help for cmd.
```
So maybe, just keep point 1).

document command aliases

---

test/artifacts.jl

When doing Artifact tests, we need to be resilient to strange umasks
that we have inherited from our environment, screwing up git tree hash
calculations.  To do this, we have a `walkdir()` -> `chmod()` wrapper
function that started setting permissions on what it thought were files
(due to the fixed `follow_symlink == false` behavior in
https://github.com/JuliaLang/julia/pull/35006) but were actually
directories.  This caused `chmod()` to apply `0o664` permissions to
directories, which were then inaccessible to `rm()` as it tried to
delete them.
This fixes https://github.com/JuliaLang/Pkg.jl/issues/1716

Ignore symlinks when fixing permissions during artifacts tests

---

docs/src/creating-packages.md

Suggest not prefixing package names with `Ju` as it is redundant, just like we already suggest not using `Julia` in the package name.
It is generally ok to use `Julia` in a github org name.  I am not sure if this is the right place to mention that.

Update package naming guidelines

---

src/Pkg.jl

This pull request fixes a small typo in the docstring for `Pkg.dependencies`.

Fix a small typo in the docstring for `Pkg.dependencies`

---

src/Pkg.jl

fix issue #1732 Pkg.dependencies docstring not rendering underscore. 

---

src/Resolve/graphtype.jl
src/Types.jl
test/resolve.jl

This is for #1750. The code is actually considerably simpler since the resolver internally already used a representation of the dependencies based in version numbers rather than version ranges.
It only solves the resolve tests, the "new.jl" test is still broken (I think it's unrelated to the resolver, if not let me know and I'll investigate).
@KristofferC

Fix resolve tests (for new deps internal format)

---

ext/TOML/src/TOML.jl
src/Operations.jl
src/Types.jl
src/manifest.jl

Reading a bunch of small things from a file tends to be much slower than just reading the whole file in one chunk and operating on memory (especially with Julia now locking the stream for every read). None of the files we parse are big enough that operating on a file makes sense.
Benchmark:
```jl
function parse_registry()
path = joinpath(homedir(), ".julia/registries/General")
for (root, dirs, files) in walkdir(path)
for file in files
if endswith(file, ".toml")
TOML.parsefile(joinpath(root, file))
end
end
end
end
``` 
Before:
```jl
696.417 ms (2111063 allocations: 157.45 MiB)
```
After:
``` jl
355.687 ms (2164815 allocations: 166.51 MiB)
```

improve performance of TOML parsing by reading from memory instead of from file

---

src/Artifacts.jl

This enables more interactive usage of `@artifact_str` from the REPL.

`artifact"name"` should search the current directory when run from the REPL

---

src/Operations.jl
src/REPLMode/completions.jl
src/Resolve/graphtype.jl
src/Types.jl
test/new.jl
test/resolve.jl

This "uncompresses" the version ranges that each registry provides using the known versions of the package in that registry. So for example, if the registry says
```
[0]
"Foo" = 0.1
v"0.3" => ...
v"0.4" => ...
```
this is then uncompressed to
```
v"0.3" => ("Foo" => 0.1, ...)
v"0.4" => ("Foo" => 0.1, ...)
```
TODO:
- Write a test
- ~Change the resolver tests to understand that they should now provide a version number (pretty annoying to fix...)~
cc @carlobaldassi 
Fixes #1434

Fix that version ranges in keys for one registry also applies to versions in another registry

---

src/API.jl
src/Operations.jl
test/new.jl
test/test_packages/Status/Manifest.toml
test/test_packages/Status/Project.toml
test/utils.jl

A possible alternative to #1656.
This attempts to rectify the concerns in #1621. 
Some example output:
```
(demo0) pkg> status
Status `/tmp/demo0/Project.toml` (empty project)
(demo0) pkg> status --manifest
Status `/tmp/demo0/Manifest.toml` (empty manifest)
(demo0) pkg> status --diff
No Changes to `/tmp/demo0/Project.toml`
(demo0) pkg> status --diff --manifest
No Changes to `/tmp/demo0/Manifest.toml`
(demo0) pkg> add Example
Updating `/tmp/demo0/Project.toml`
[7876af07] + Example v0.5.3
Updating `/tmp/demo0/Manifest.toml`
[7876af07] + Example v0.5.3
(demo0) pkg> add Example
No Changes to `/tmp/demo0/Project.toml`
No Changes to `/tmp/demo0/Manifest.toml`
(demo0) pkg> status
Status `/tmp/demo0/Project.toml`
[7876af07] Example …
```

`Pkg.status` improvements

---

.travis.yml

No point running on nightly since it sometimes break (like right now).

run docs on 1.4

---

src/API.jl
src/Operations.jl
src/Pkg.jl
src/Types.jl
src/manifest.jl
test/pkg.jl
test/test_packages/MainRepo/SubDir/Project.toml
test/test_packages/MainRepo/SubDir/src/SubDir.jl

```
julia> Pkg.add(PackageSpec(path="MainRepo", subdir="SubDir.jl"))
Updating git-repo `/home/kc/Documents/JuliaTests/MainRepo`
Updating `~/Pkg.jl/Project.toml`
[900e8cb0] + SubDir v0.1.0 #master (/home/kc/Documents/JuliaTests/MainRepo[/SubDir.jl])
Updating `~/Pkg.jl/Manifest.toml`
[900e8cb0] + SubDir v0.1.0 #master (/home/kc/Documents/JuliaTests/MainRepo[/SubDir.jl])
```

add subdir functionality

---

src/Operations.jl
test/test_packages/TestArguments/test/runtests.jl

If https://github.com/JuliaLang/julia/pull/35362 is merged, adding `--depwarn=yes` by default will be important for continuity. See @tkf's comment https://github.com/JuliaLang/julia/pull/35362#issuecomment-611818361 for more detail.
(Even without merging that PR in Base, merging this PR should be harmless: it's currently the default in Julia and users can still disable it with `julia_args`.)

Ensure --depwarn=yes by default in Pkg.test

---

src/Operations.jl

This doesn't only happen when there are cycles. It also happens if you have a dependency graph like
```
A -> [B, C]
B -> [C]
```
then `C` will be inside `developed` when parsing dependencies for `B`.
This actually removes a O(n^2) behavior that I hit today when you have a dependency graph like a triangle above.

remove incorrect debug message

---

src/Types.jl

Fix a bug where Pkg.Registry.add("General") would not use the PkgServer since the uuid was not set correctly.

Correctly set the uuid for default registries

---

src/GitTools.jl
test/pkg.jl

**Before**:
```
(@v1.5) pkg> add https://github.com/JuliaLang/Example.jl.git
```
adds `Example` as expected, whereas adding a trailing slash asks for username and password:
```
(@v1.5) pkg> add https://github.com/JuliaLang/Example.jl.git/
Updating git-repo `https://github.com/JuliaLang/Example.jl.git/`
Username for 'https://github.com': 
Password for 'https://github.com': 
ERROR: failed to fetch from https://github.com/JuliaLang/Example.jl.git/, error: GitError(Code:EUSER, Class:Callback, Aborting, user cancelled credential request.)
```
**After**:
Both without and with trailing slash add `Example`.
If you think that this is the wrong way to solve the problem, please object.

Remove trailing slash from URL.

---

docs/src/creating-packages.md
docs/src/toml-files.md

Also fix a typo in one example that used `author` instead of `authors`

Document authors field in Project.toml

---

docs/src/compatibility.md
docs/src/managing-packages.md
test/resolve.jl
test/resolve_utils.jl

A lot of people seem to struggle with understanding what the error message means and how to fix it. I figured it was time to have some docs about this.
The approach I've taken here is one step shy of a real doctest: I am trying to generate the actual error message, though its form is untested due to the difficulty of setup and the fact that the means to generate the error is unrelated to how this would be triggered in ordinary usage. (Documenter doesn't seem to let you test the output without showing the input, and here I don't want to show the input.) I then repeat the message via copy/paste in chunked form as I go through the pieces stepwise and help interpret what they mean. If someone changes the presentation of the message without updating the documentation, these two will be …

Docs for interpreting "Unsatisfiable requirement"

---

src/Operations.jl
src/utils.jl
test/pkg.jl
test/test_packages/TestFailure/Project.toml
test/test_packages/TestFailure/src/TestFailure.jl
test/test_packages/TestFailure/test/runtests.jl

Reports some details about `Pkg.test` subprocess failures such as the signal the process received or the exit code. This information is useful in assisting in debugging process level failures such as having a process killed due by the OS' OOM reaper.
Fixes: https://github.com/JuliaLang/Pkg.jl/issues/1789

Reveal subprocess failure details

---

ext/TOML/src/print.jl
src/Types.jl

This is a companion PR to https://github.com/JuliaLang/julia/pull/35714 and accounts for a subset of the gains reported there. The more specific implementations of `==` and `hash` avoid a `collect`;
that branch prevents many `collect`-induced invalidations via the `iteratorsize` trick, but this change is probably a good idea anyway.
The more important and subtle one is the one in `TOML._print`. This is used by a large number of methods in Pkg, so it's important to prevent it from being invalidated. Do to nospecialize markers, this method gets inferred for partially-specified types, and the `a` is typically just `AbstractDict`. However, `Iterators.Pairs` is also an AbstractDict, and the return type of `keys` cannot be inferred from the parameters of `AbstractDict{K,V}` because the `itr` …

Reduce footprint for invalidation

---

src/REPLMode/command_declarations.jl
src/Registry.jl
src/Types.jl
test/registry.jl

Background discussion: https://github.com/JuliaPackaging/PkgServer.jl/issues/26
This only makes a difference if you have a `JULIA_PKG_SERVER` that serves at least one registry that is not the General registry.
Without this PR, the only way to install such a registry is by UUID, e.g.
```
pkg> registry add 1e95ee64-cd1a-42e9-a29a-16f7a437e6bf
```
With this PR it is installed automatically, in the same way that General is installed automatically today. More precisely all registries served by the pkg server are installed automatically.

Automatically install all registries available from pkg server.

---

src/API.jl
src/Pkg.jl
test/new.jl
test/pkg.jl

When using the `Pkg.API` calls and wanting to e.g. add something by URL, it is a bit verbose to have to write
```jl
Pkg.add(PackageSpec(url = "..."))
```
Now it is possible to write
```jl
Pkg.add(url = "...")
```
in other words, relevant keyword arguments gets passed directly to the PackageSpec constructor. For multiple packages we can use a Vector of NamedTuples where each named tuple gets passed:
```jl
Pkg.add([(url = "...",), (url = "...",)])
```
Previously, all keyword arguments were passed directly to the `Context!` modifier but that is a real waste because no one uses that.
I need to expand the docs a bit and ideally this should be added for the `Pkg.Registry` module as well but that might be a later project...

Add a more concise way to call the API functions

---

src/Pkg.jl
src/REPLMode/REPLMode.jl

Add `[offline]` to prompt in offline mode and make it possible to use `JULIA_PKG_OFFLINE=true` to run in offline mode conveniently across sessions.
I think the main usecase here is when you are offline for a longer time (flights, public transport etc) and it might be annoying to have to `using Pkg; Pkg.offline()` every Julia startup so I think it is nice to be able to configure this outside of Julia for multiple sessions. Also, in order to remember that you have indeed set this variable, this adds `[offline]` to the Pkg prompt:
```
(@v1) [offline] pkg>
```

Add [offline] to prompt in offline mode

---

src/REPLMode/REPLMode.jl
src/REPLMode/completions.jl

Toyed around with https://github.com/timholy/MethodAnalysis.jl a bit and found this.
Not sure why the `SPECS` variable is a ref of a union. Seems like it isn't needed?

REPL: make SPECS a normal variable

---

src/GitTools.jl

What's the point of specifying a different hash type if it reverts to the default in the recursive calls?

Pass on HashType while recursing.

---

ext/TOML/src/parser.jl
ext/TOML/src/print.jl
src/Artifacts.jl
src/PlatformEngines.jl

This is a better fix for #1806, one that resolves the inference problems. A big part of the problem is the dreaded 15276.
Addresses concerns in https://github.com/JuliaLang/www.julialang.org/pull/794#discussion_r424454133.

Improve inference of call chains to TOML.print

---

src/Operations.jl
src/versions.jl

Benchmark is `@btime Pkg.add("DifferentialEquations")` in the Pkg project.
Before: `215.759 ms (2557554 allocations: 189.00 MiB)`
After: `180.268 ms (1958939 allocations: 152.31 MiB)`

some perf improvements

---

src/PlatformEngines.jl

Because PlatformEngines assumes you may want to verify a tarball later, it spits out `.sha256` files to optimize for hashing in the future.  This is fine when you're downloading to a permanent location or a directory that was created by `mktempdir()`, but if your download location is just a file sitting in `/tmp` which you clean up manually afterward, you need to clean up that `.sha256` file as well.

Clean up `jl_XXX-download.gz.sha256` files

---

src/Registry.jl

Fix bug which made `registry up` a no-op instead of updating all user-registries.
Caused by  #1384.

Fix bug which made `registry up` a no-op

---

src/Pkg.jl
src/PlatformEngines.jl

* print legal notice first time talking to each pkg server
* generate and send HyperLogLog estimator values
* use ~/.julia/servers/telemetry.toml for defaults
This allows, for example, a user to do
echo 'telemetry = false' >> ~/.julia/servers/telemetry.toml
and opt out of all telemetry for all servers they might connect to. If they
only want to opt out of sending any telemetry that is based on a client
UUID, then they can do
echo 'client_uuid = false' >> ~/.julia/servers/telemetry.toml
This can be done anywhere in the depot path, so if a sysadmin wants to set
up a shared system so that all users default to sending no telemetry, they
can do that. A user can opt back into telemetry by Putting an empty default
`telemetry.toml` file in their own depot.

telemetry: print legal notice first time talking to each pkg server

---

docs/src/artifacts.md

I had a bit of a challenge getting started with Pkg.  Perhaps a usage section such as this might help.  Thank you for the lovely feature, it's a significant improvement from what we did ~2 years ago.

Improve Artifacts documentation by adding a Basic Usage section

---

src/PlatformEngines.jl

The `secret_salt` should be as hard to guess as possible, so that has some security implication. The HyperLogLog samples should be random so that estimates aren't skewed by any non-randomness.

telemetry: use RandomDevice for random values

---

.travis.yml
src/API.jl
src/Artifacts.jl
src/BinaryPlatforms.jl
src/Operations.jl
src/PlatformEngines.jl
src/REPLMode/REPLMode.jl
src/Registry.jl
src/Resolve/graphtype.jl
src/Types.jl
src/generate.jl
src/manifest.jl

This is the Pkg part of what I found in my investigations of invalidations due to extending `==`, c.f. https://github.com/JuliaLang/julia/pull/36282. This also requires https://github.com/JuliaLang/julia/pull/36280, so if that's not on nightly yet this wiil fail tests. (It also requires https://github.com/JuliaLang/julia/pull/36188, but I imagine that's on nightly by now.)
This will be easiest to review ignoring whitespace changes, due to some big `let` blocks from circumventing more cases of the infamous 15276.

Yet more inference/invalidation fixes

---

ext/TOML/src/print.jl
src/Operations.jl

Somehow, I think I convinced myself early on that the OrderedCollections invalidations were unfixable. That is most assuredly false, and this PR gets rid of them all. That seems pretty useful, because if memory serves more than half the Julia ecosystem loads OrderedCollections.
The major source of invalidations come from `print_status`; I don't know why I didn't fix this properly before. (Note that the double type-specification in each comprehension seems necessary, if we want to get rid of all the vulnerabilities, since there's a `Union` involved---the `Tuple{T,S,S}[comp...]` ensures we get the right element type and `[(x,y,z)::Tuple{T,S,S}...` eliminates a call to `convert`.) Additionally, `TOML._print` calls itself, with apparently-noninferrable types, so we force runtime dispatch to …

Fix invalidations from loading OrderedCollections

---

src/PlatformEngines.jl

`CI_SERVER` is set by [GitLab](https://docs.gitlab.com/ce/ci/variables/predefined_variables.html).
`PKGEVAL` and `JULIA_PKGEVAL` are set by [NewPkgEval](https://github.com/JuliaComputing/NewPkgEval.jl/blob/master/src/run.jl).
`JULIA_REGISTRYCI_AUTOMERGE` is set by [RegistryCI](https://github.com/JuliaRegistries/RegistryCI.jl/pull/257).

Telemetry CI variables: add CI_SERVER, JULIA_PKGEVAL, JULIA_REGISTRYCI_AUTOMERGE, and PKGEVAL

---

src/BinaryPlatforms.jl
test/binaryplatforms.jl

Also normalize arm64 -> aarch64, c.f.
https://lists.gnu.org/archive/html/config-patches/2020-07/msg00002.html

BinaryPlatforms: Recognize MacOS(:aarch64)

---

src/REPLMode/command_declarations.jl
src/generate.jl
test/new.jl

This PR deprecates the REPL command `] generate` but leaves `Pkg.generate` untouched.
@StefanKarpinski @KristofferC

Deprecate the REPL command `] generate`

---

src/PlatformEngines.jl

Add missing `project` back in, accidentally dropped in 2acb2f9ca7f8b908954d6fdde074b65e30b8395f
This pretty much broke downloading PkgServer resources, so we should update the Pkg on master ASAP.

Fix PkgServer download failures

---

src/Operations.jl

Adds a notice to indicate that tests are starting. There are two motivations behind this change:
1. Adds a clear demarcation between resolving test dependencies and starting tests (was more relevant back with Julia 1.3)
2. Provides an easy string to search for in the test output logs to find the start of test execution

Add running tests notice

---

src/Resolve/graphtype.jl
src/Types.jl
src/versions.jl
test/pkg.jl

This does one of the suggestions from https://github.com/JuliaLang/Pkg.jl/issues/1855
I think it is a big improvement.
```julia
julia> using Pkg; pkg"add DataFrames@0.17 CSV@0.5"
#...
ERROR: Unsatisfiable requirements detected for package CSV [336ed68f]:
CSV [336ed68f] log:
├─possible versions are: [0.3.0-0.3.1, 0.4.0-0.4.3, 0.5.0-0.5.26, 0.6.0-0.6.2] or uninstalled
├─restricted to versions 0.5 by an explicit requirement, leaving only versions 0.5.0-0.5.26
└─restricted by compatibility requirements with DataFrames [a93c6f00] to versions: [0.3.0-0.3.1, 0.4.0-0.4.3] or uninstalled — no versions left
└─DataFrames [a93c6f00] log:
├─possible versions are: [0.11.7, 0.12.0, 0.13.0-0.13.1, 0.14.0-0.14.1, 0.15.0-0.15.2, 0.16.0, 0.17.0-0.17.1, 0.18.0-0.18.4, 0.19.0-0.19.4, 0.20.0-0.20.2, …
```

Compress compat version in compat logs

---

src/Resolve/Resolve.jl
src/Resolve/fieldvalues.jl
src/Resolve/graphtype.jl
src/Resolve/maxsum.jl
src/Resolve/versionweights.jl
src/Types.jl

These are results for `Pkg.update` in an environment where I added a bunch of big packages (Plots, Makie, DifferentialEquations, ApproxFun etc).
Master:
```
ENV["JULIA_PKGRESOLVE_ACCURACY"] = 1
966.591 ms (6843000 allocations: 1.01 GiB)
ENV["JULIA_PKGRESOLVE_ACCURACY"] = 2
2.124 s (11577823 allocations: 3.01 GiB)
```
PR:
```
ENV["JULIA_PKGRESOLVE_ACCURACY"] = 1
602.627 ms (5432062 allocations: 301.72 MiB)
ENV["JULIA_PKGRESOLVE_ACCURACY"] = 2
1.308 s (7230777 allocations: 368.51 MiB)
```
The performance improvements here only matter when the greedy solver fails.
The reason for this is that https://github.com/JuliaLang/Pkg.jl/issues/1949 suggests that we might want to bump the resolver accuracy but it would be a bit sad if we lost performance from doing that. The optimized resolver is now …

some microoptimizations for the resolver

---

src/PlatformEngines.jl

I used this invalidation as a demonstration in a [new video](https://www.youtube.com/watch?v=7VbXbI6OmYo). But now that it's fixed, there's no good reason to leave this "open."

Fix an invalidation from overloading `broadcasted`

---

src/PlatformEngines.jl

The current implementation seems to vacillate between integer and floating-point representations, this adopts float consistently.

Adopt consistent Float64 in auth expiration time

---

src/PlatformEngines.jl
src/REPLMode/command_declarations.jl
src/Resolve/graphtype.jl
src/versions.jl

This is the array equivalent of #1968. Reduces the number of backedges to `promote_rule`.

Avoid unnecessary eltype promotion of various array containers

---

src/GitTools.jl
test/new.jl

Encoding the HashType as a keyword argument tends to cause inference to lose any type parameters due to https://github.com/JuliaLang/julia/issues/36454 and its interaction with `NamedTuple`. Making it a positional argument fixes this problem.

Redesign the HashType handling for better inference

---

src/API.jl
src/Artifacts.jl
src/BinaryPlatforms.jl
src/Operations.jl
src/REPLMode/REPLMode.jl
src/Resolve/graphtype.jl
src/Types.jl
test/artifacts.jl
test/binaryplatforms.jl
test/pkg.jl
test/repl.jl
test/resolve_utils.jl

This defines some aliases and otherwise increases consistency in Dict types. Note that in some cases the final result is no different, but this avoids an unnecessary conversion by creating the Dict to be of the correct type at the outset. Essentially the Pkg equivalent of https://github.com/JuliaLang/julia/pull/37088.

Improve consistency of Dict types & construction

---

src/REPLMode/argument_parsers.jl
test/repl.jl

This PR adjusts the regex which is used to match a git repository URL. Now, ".git" must be at the end of the URL. It should resolve #1935. Please, check the added test since I was not very sure about that.

REPL: Fix parsing git URLs

---

src/API.jl
src/REPLMode/command_declarations.jl

Prints this by default:
````
(Pkg) pkg> gc --all
Active manifest files: 2 found
Active artifact files: 4 found
Active scratchspaces: 0 found
Deleted 115 package installations (106.439 MiB)
Deleted 21 artifact installations (117.880 MiB)
````
and this with `--verbose` (the previous default):
````
(Pkg) pkg> gc --all -v
Active manifest files: 2 found
`~/dev/Pkg/Manifest.toml`
`/tmp/tmp.RWwVK3rml9/environments/v1.6/Manifest.toml`
Active artifact files: 4 found
`/tmp/tmp.RWwVK3rml9/packages/Zlib_jll/8tl5W/Artifacts.toml`
`/tmp/tmp.RWwVK3rml9/packages/CUDA/xGgiY/Artifacts.toml`
`/tmp/tmp.RWwVK3rml9/packages/CompilerSupportLibraries_jll/kmL78/Artifacts.toml`
`/tmp/tmp.RWwVK3rml9/packages/OpenSpecFun_jll/HMSwk/Artifacts.toml`
Active scratchspaces: 0 found
Deleted …
```

Pkg.gc: only print active manifests/artifacts in verbose mode.

---

src/PlatformEngines.jl

Resolved itself as
```
┌ Warning: could not download https://pkg.julialang.org/registries
└ @ Pkg.Types ~/JuliaPkgs/Pkg.jl/src/Types.jl:952
```
Good ol' `try catch` programming.

fix typo from moving to TOML stdlib

---

src/Resolve/graphtype.jl
test/new.jl

This adds color to the log, to enhance readability, per another point in  #1855 
`pkgID`s are set using modulo of their  `hash`
Which I think is nice, because it avoids having global state to track which colors we have used, and means seeing the same package in different conflicts has a persistant recognizable hue.
On the downside there is the chance that package colors would conflict, so we could do it in order instead. Seems less fun.
TODO:

Add Color to the conflict log

---

src/PlatformEngines.jl

I noticed that using wget the output is very verbose. For artifacts it is even worse because of the forwarding. It prints a screen full of amazon urls (see P.S.). Before:
```julia
julia> Pkg.PlatformEngines.gen_download_cmd("https://file-examples-com.github.io/uploads/2017/02/zip_10MB.zip", "/dev/null")
`wget --tries=5 -c -O /dev/null https://file-examples-com.github.io/uploads/2017/02/zip_10MB.zip`
julia> run(ans)
--2020-09-03 16:12:01--  https://file-examples-com.github.io/uploads/2017/02/zip_10MB.zip
Auflösen des Hostnamens file-examples-com.github.io (file-examples-com.github.io) … 185.199.108.153, 185.199.109.153, 185.199.110.153, ...
Verbindungsaufbau zu file-examples-com.github.io (file-examples-com.github.io)|185.199.108.153|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort …
```

Try to improve output of wget

---

src/API.jl
src/Artifacts.jl
src/Operations.jl
src/PlatformEngines.jl
src/REPLMode/REPLMode.jl
src/REPLMode/argument_parsers.jl
src/REPLMode/completions.jl
src/Resolve/graphtype.jl
src/Types.jl
src/manifest.jl

The companion PR to https://github.com/JuliaLang/julia/pull/37163
The message in the first commit mentions this, but perhaps worth repeating: using `Vector` rather than `Array` in certain places allows inference to know that `size(A)` is a `Tuple{Int}`, and that ends up fixing some otherwise hard-to-solve problems in inference with the `similar` pipeline.

Improve inference for paths leading to `similar`

---

src/Artifacts.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/1870.
API design like this (keyword function where default values are used everywhere) is sometimes problematic for this reason. It is easy to miss passing through a keyword through the whole call chain and you will not get an error. For that reason, I only typically give default values at the most "toplevel" API (https://github.com/JuliaLang/PackageCompiler.jl/blob/e560504d4dc7feaaed3e0585c6d0a7b79d5d3fc7/src/PackageCompiler.jl#L362-L373) and then turning off the defaults for inner functions (https://github.com/JuliaLang/PackageCompiler.jl/blob/e560504d4dc7feaaed3e0585c6d0a7b79d5d3fc7/src/PackageCompiler.jl#L190-L197).

fix propagating quiet_downloads to non windows downloads

---

docs/Project.toml
docs/generate.jl
docs/src/assets/custom.css

Various updates to doc-build:
- fix REPL mode docstring generation;
- fix CSS for logo size;
- remove unnecessary CSS for compat admonitions;
- upgrade Documenter to 0.25.

Various updates and fixes to doc-build

---

src/API.jl
src/Types.jl

Pkg on julia master:
```
(dev) pkg> st
Status `~/Documents/dev/Project.toml`
[0c46a032] DifferentialEquations v6.15.0
[91a5bcdd] Plots v1.6.3
julia> @time Pkg.precompile()
[ Info: Precompiling DifferentialEquations [0c46a032-eb83-5123-abaf-570d42b7fbaa]
[ Info: Precompiling Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]
312.061599 seconds (133.69 k allocations: 9.246 MiB)
```
This PR (same project, with `.julia/compiled` emptied out): 
```
julia> @time Pkg.precompile()
[ Info: Precompiling Reexport [189a3867-3050-52da-a836-e630ba90ab69]
[ Info: Precompiling x264_jll [1270edf5-f2f9-52d2-97e9-ab00b5d0237a]
...
[ Info: Precompiling DifferentialEquations [0c46a032-eb83-5123-abaf-570d42b7fbaa]
87.851553 seconds (4.25 M allocations: 216.406 MiB, …
```

Parallelize Pkg.precompile

---

src/Types.jl
test/new.jl
test/pkg.jl

This has been fixed upstream: https://github.com/JuliaLang/julia/pull/30989.
Ref #795
cc @ararslan

remove the env var for setting download concurrency

---

src/Operations.jl
test/new.jl

This puts build logs in Pkg's scratchspace and sets the building package as the owner. This makes sure that the build log is deleted when the package is garbage collected.
The reason for this is that I am implementing https://github.com/JuliaLang/Pkg.jl/issues/1717 and want to verify the content, but currently we pollute the package directory with the build log.

Place Pkg.build logs in Pkg's scratchspace.

---

src/API.jl

Runs `Pkg.precompile()` after `Pkg.add()`, `instantiate()`, `update()`
Enabled by setting `ENV["JULIA_PKG_PRECOMPILE_AUTO"]=1` etc.

Add opt-in auto precompilation after Pkg.add, instantiate, update

---

src/API.jl
src/Pkg.jl

Edit: The mechanism below has now been removed from this PR, given a better approach of allowing failures for indirect dependencies
----
Builds on #2018 to add the option to revert to the old-style `Pkg.precompile()` behavior if the user just wants/needs to precompile dependencies that are loaded.
```
julia> Pkg.precompile(parallel=false)
[ Info: Precompiling DifferentialEquations [0c46a032-eb83-5123-abaf-570d42b7fbaa]
[ Info: Precompiling Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]
```
```
julia> Pkg.precompile()
[ Info: Precompiling DocStringExtensions [ffbed154-4ef7-542d-bbb7-c09d3a79fcae]
[ Info: Precompiling PoissonRandom [e409e4f3-bfea-5376-8464-e040bb5c01ab]
...
[ Info: Precompiling Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]
...
[ …
```

Allow failures of indirect dependencies during parallel precompillation

---

src/API.jl

I wasn't familiar with the generated Pkg.API functions when doing #2033 
I think this is actually the correct launch point.
Works as expected for:
```
pkg> add Foo
pkg> pin Foo
pkg> free Foo
pkg> update
pkg> update Foo
pkg> build
pkg> build Foo
pkg> instantiate
```
Activated with `ENV["JULIA_PKG_PRECOMPILE_AUTO"]=1`

Launch opt-in auto precompilation from appropriate gen funcs

---

src/API.jl
src/Operations.jl

Don't print precomp message when precompile is a no-op.
Makes for a cleaner experience when precompilation is auto-enabled

Precomp Tweaks: Don't print precomp message when no-op + Suspend precomp on pkgs that have errored, until they change

---

src/BinaryPlatforms_compat.jl
test/binaryplatforms.jl

We momentarily broke the MacOS (and FreeBSD, although I'm not sure that
was actually noticed ;P) ecosystem by changing slightly the rules around
`triplet(::Platform)`.  `Base.BinaryPlatforms` keeps track of the
`os_version` and appends it to the end of the triplet for `MacOS` and
`FreeBSD`, but on older versions of julia they are always expected to be
`14` and `11.1`, respectively.  This PR maintains that willful ignorance
when an old package calls `Pkg.BinaryPlatforms.triplet()`, but for new
packages that are ready to wake up and stop living in a simulation, they
can use `Base.BinaryPlatforms.triplet()` to get the full, glorious,
properly-versioned triplet string.

[BinaryPlatforms]: fix triplet breakage

---

test/testgroups

This prevents the `resolve` tests from being run during base julia's `make testall`.
@KristofferC do you know why we were running the `resolve` tests by themselves during `make testall`?  Alternatively, should we fix Base's `testall` so that these modules can actually find `Pkg`?  Without this, we get the very strange errors of:
```
Error in testset Pkg/resolve:
Error During Test at /buildworker/worker/tester_linux32/build/share/julia/stdlib/v1.6/Pkg/test/resolve.jl:428
Got exception outside of a @test
UndefVarError: Pkg not defined
Stacktrace:
[1] temp_pkg_dir(fn::Main.Test33Main_Pkg_resolve.ResolveTest.var"#1#3"; rm::Bool)
@ Main.Test33Main_Pkg_resolve.ResolveTest.Utils /buildworker/worker/tester_linux32/build/share/julia/stdlib/v1.6/Pkg/test/utils.jl:81
[2] temp_pkg_dir(fn::Function)
@ …
```

Remove `resolve` from `test/testgroups`

---

src/API.jl

With f1430b5dbbdeb09236a77faf755275a611690a93 and https://github.com/JuliaLang/julia/commit/f6d1032763cfa160c117f0a5de25ba3370a3dca4, I get an error with `Pkg.precompile`:
```
ERROR: TaskFailedException
nested task error: MethodError: no method matching compilecache(::Base.PkgId, ::String, ::Bool)
compilecache(::Base.PkgId, ::Base.TOMLCache, ::Bool) at loading.jl:1247
compilecache(::Base.PkgId, ::String) at loading.jl:1255
compilecache(::Base.PkgId, ::String, ::Base.TOMLCache) at loading.jl:1255
...
Stacktrace:
[1] macro expansion
@ ~/.julia/dev/Pkg/src/API.jl:985 [inlined]
[2] (::LatestPkg.Pkg.API.var"#203#211"{LatestPkg.Pkg.Types.Context, Base.TOMLCache, Dict{Base.PkgId, Bool}, Dict{Base.PkgId, Base.Event}, Vector{Base.PkgId}, Base.Semaphore, Vector{Base.PkgId}, …
```

Fix how Base.compilecache is called

---

src/BinaryPlatforms_compat.jl
test/artifacts.jl

This first fixes the BinaryPlatforms shims (e.g. the `Linux` and `MacOS` objects) by adding a better `==` operator, which solves https://github.com/JuliaLang/Pkg.jl/issues/2050, then removes their usage in the tests to use the new `Base.BinaryPlatforms` objects.

[Artifacts] add equality operator for `BinaryPlatforms` shims

---

src/API.jl

Not seen on my system, but by others. It seems `printpkgstyle` has a yield point or two, so better to set the bool before

Fix multiple print of `precompiling project...`

---

.travis.yml
test/pkg-uuid.jl

Fixes #2064 
This pull request adds a test to make sure that the UUID in the Pkg.jl `Project.toml` file has not changed. The test only runs on Travis CI.

Travis CI: test that the Pkg UUID has not been changed

---

src/API.jl
test/api.jl

Circular deps could deadlock the parallel `Pkg.precompile` process, which may be what was happening in #2057 
This adds a lightweight check to detect and suspend any circular deps within the full dep tree (not just first level, as in the case below)
Warnings are only printed only during  explicit `pkg> precompile` calls, not when `precompile` is automatically called.
These new checks added ~0.006 seconds in my case, for an environment with 333 dependencies in the manifest, which was insignificant even in the no-op case.
```
(@v1.6) pkg> precompile
┌ Warning: Circular dependency detected. Precompilation skipped for CircularDep2 [206312f7-dc9c-4d80-acd8-43a486edfa59]
└ @ Pkg.API ~/Documents/GitHub/Pkg.jl/src/API.jl:959
┌ Warning: Circular dependency detected. Precompilation skipped for …
```

Precompilation: detect and suspend precomp for circular deps

---

src/Operations.jl
src/REPLMode/completions.jl
src/versions.jl

Takes the benchmark of
```jl
using TOML
using Pkg
using UUIDs
using Pkg.Operations: load_package_data, VersionSpec, load_versions
const ctx = Pkg.Types.Context()
function bench_load_package()
reg = joinpath(homedir(), ".julia/registries/General/")
d = TOML.parsefile(joinpath(reg, "Registry.toml"))
for (uuid, pkg) in d["packages"]
pkgpath = pkg["path"] #
path = joinpath(reg, pkgpath)
version_info = load_versions(ctx, path)
versions = sort!(collect(keys(version_info)))
deps_data = load_package_data(UUID, joinpath(path, "Deps.toml"), versions)
compat_data = load_package_data(VersionSpec, joinpath(path, "Compat.toml"), versions)
end
end
```
from 407 ms, 339 Mib, to 330 ms, 248 Mib. For `Pkg.add("DifferentialEquations")` the impact is around 10-13% improvement.,

some performance improvements to uncompressing registry data

---

.travis.yml
test/runtests.jl

This prints a message so that if someone is having a hard time diagnosing test failures on CI, they can see exactly which Pkg server CI uses.
cc: @staticfloat 
---
E.g. on my machine:
```julia
julia> if (server = Pkg.pkg_server()) !== nothing && Sys.which("curl") !== nothing
s = read(`curl -sLI $(server)`, String);
@info "Pkg Server metadata:\n$s"
end
┌ Info: Pkg Server metadata:
│ HTTP/2 301
│ server: Varnish
│ retry-after: 0
│ location: https://us-east2.pkg.julialang.org/
│ x-geo-continent: NA
│ x-geo-country: US
│ x-geo-region: RI
│ accept-ranges: bytes
│ date: Wed, 07 Oct 2020 08:07:58 GMT
│ via: 1.1 varnish
│ x-served-by: cache-ewr18161-EWR
│ x-cache: HIT
│ x-cache-hits: 0
│ x-timer: S1602058078.462363,VS0,VE0
│ content-length: 0
│
│ HTTP/1.1 200 OK
│ Server: nginx/1.19.2
│ Date: …
```

Test suite: print a message with info on the current Pkg server

---

src/API.jl

By popular request
I think this is nicer, yeah

Precompile: move icons during precomp to left for alignment

---

Project.toml
src/API.jl
src/Operations.jl

Two things:
- This changes `Pkg.precompile()` to not throw. The error messages presented are high-level success or failure, hence I don't think they are informative enough to own the throw. The user or script should go-on to code loading and get the nicer stack trace.
@simonbyrne, it was mentioned by @KristofferC that you changed `precompile` to throw in the past. Is there a particular reason we should be aware of?
- Fixes an unintended auto precomp call during `Pkg.test` #2110 
Fixes #2110 
Fixes #2112 
Fixes #2118
Fixes #2116

Precompile: Throw errors properly, disable auto during `Pkg.test`, remove trailing new line, remember suspensions for projects and after restart

---

src/Operations.jl

This doesn't really make sense to me. Why would there be a project without a version that is in the registry? And why would picking the latest version be correct?

remove using latest registry version when no version in Project

---

src/PlatformEngines.jl

This is useful because there may be redirection going on and it may not be clear how someone got to a particular pkg server. Setting this header is not a risk even though it captures the content of the `JULIA_PKG_SERVER` environment variable, because if the content of the variable happens to be something sensitive instead of the address of a package server, then the request will never reach the package server in the first place, let alone the header.

send Pkg server value itself as a header to the Pkg server

---

docs/src/compatibility.md

Compat warnings seem to always come _after_ the relevant section in Julia docs ([example](https://docs.julialang.org/en/v1/base/parallel/#Base.Threads.Condition), [example](https://docs.julialang.org/en/v1/base/file/#Base.Filesystem.readdir), [example](https://docs.julialang.org/en/v1/base/multi-threading/#Base.Threads.@spawn)). It is important that these messages are never missed, so training Julia docs readers where to look is useful!

Docs: moved Julia 1.4 compat below the section

---

bors.toml

We no longer use Bors, so this file is unnecessary.

Delete the `bors.toml` file

---

src/API.jl
src/Operations.jl
test/api.jl

The project-specific retention of auto-precompile suspended packages wasn't quite right, and was missing tests
As for burden, the addition of `recall_suspended_packages` to the first Pkg API call adds very little on my system: `0.000206 seconds (92 allocations: 6.750 KiB)` on my machine

Precompile: Fix and test per-project precomp suspension state retention

---

src/API.jl

- Improves specificity of error handling ~~with a new `Base.PrecompileFailedException` type thrown by `Base.compilecache`. Dependent on https://github.com/JuliaLang/julia/pull/38109~~
- Hides cursor during pretty printing

Precomp: Better error handling, hide cursor during print

---

src/PlatformEngines.jl

Missing change from https://github.com/JuliaLang/Pkg.jl/pull/2078

fix get_auth_header: headers are now string pairs

---

src/Operations.jl

Fixes #2154 
Closes #2161 
@KristofferC Would this be sufficient to fix #2154?

Don't error if a package does not have a `version`

---

src/API.jl

Note that this function is only available in Julia 1.6+

Use `Base.Filesystem.prepare_for_deletion()` instead of defining our own

---

src/API.jl
src/Artifacts.jl
src/GitTools.jl
src/Operations.jl
src/Pkg.jl

I've noticed ansi cursor codes being printed as text in CI, and it may be happening in IJulia etc.
This introduces a general setting for whether ansi overprinting and more advance cursor movements should be used, based on the heuristic:
```
(io isa Base.TTY) && (get(ENV, "CI", nothing) != "true")
```

Only do fancy ansi printing in terminals that support it, specifically not on CI

---

docs/make.jl
ext/LazilyInitializedFields/LazilyInitializedFields.jl
ext/update.jl
src/API.jl
src/Operations.jl
src/Pkg.jl
src/REPLMode/REPLMode.jl
src/REPLMode/completions.jl
src/RegistryHandling.jl
src/Resolve/graphtype.jl
src/Types.jl
src/Versions.jl
test/new.jl
test/pkg.jl
test/repl.jl
test/resolve.jl
test/runtests.jl

Some background: Pkg is a little bit of spaghetti now and it is hard to know where things for a certain area is done. For example (relevant for this PR) where is the code that handles the registry? Well, it's a bit all over the place, depending on what the function needs, it might even go and parse some files in the registry and get what it wants. I (mostly) blame myself for this but in my defense when I did most of the stuff on Pkg there was little time until 1.0 and a lot of features to implement to get to feature parity with the old package manager. Now when things are calmed down I think it would be good to re-evaluate a bit on how things are structured.
As a start, I want to look exactly at the way we access the information in the registries. As I said, right now, there are callees …

more structured Registry handling

---

src/Types.jl

Since untarring a tarball like the registry is so slow on Windows,
we prefer to git clone registries instead. Git is slow on Windows
as well, but git updates are faster since git only updates the
files that need to be modified, which is much faster than unpacking
a whole new registry.

Windows: prefer git cloning registries (close #2014)

---

src/Operations.jl
src/REPLMode/completions.jl
src/RegistryHandling.jl
src/Resolve/graphtype.jl
src/Types.jl
src/Versions.jl
test/resolve_utils.jl

The registry has two files `Deps.toml` and `Compat.toml`. This is (I presume!) to make it easier for a human to read the `Compat.toml` file since one can read package names and mostly ignore UUIDs. However, this has also "leaked" into the implementation in Pkg where two dictionaries are created and passed along, and then finally in the Resolver the mapping is done to achieve the finally desired `UUID => VersionRange` compat. This changes it so that the uncompression creates this final data structure at once instead of having the resolver do that work.

change the way compat is uncompressed

---

src/API.jl
src/REPLMode/command_declarations.jl

Removes the env var tip that was shown each time auto precomp ran. 
Adds a note about it to the pkg repl help

Auto-precompilation: Remove tip, add env var note to pkg repl help

---

src/Types.jl
test/api.jl
test/new.jl

Makes a significant impact on CI time (and probably on user time) on especially Windows.

remove duplicated tests and move registry into place instead of copying

---

test/utils.jl

Takes off another chunk on mac builder CI time. Let's see how it does on Windows.

CI: make registry available in temp_pkg_dir

---

src/Operations.jl
src/Resolve/graphtype.jl
test/resolve_utils.jl

the compat data now contains all versions so it shouldn't be needed anymore

get rid of `all_versions` dict to resolver

---

appveyor.yml

This pull request temporarily disables Codecov submission from AppVeyor.
We will still have Codecov reports from GitHub Actions on macOS and Linux.

AppVeyor: temporarily disable submitting to Codecov

---

src/API.jl

Fixes #2195 
I also tweaked the message for `?` precomp errors, which are usually because the package is loaded and thus not in a precompilable state, but that's not the only reason.. so the advice is to try restarting julia which will usually fix it.

Don't do autoprecomp after Pkg.dev

---

test/artifacts.jl

This Artifacts test relied upon the lazy installation of non-lazy
Artifacts, which is not permitted anymore.
Fixes #2239

Remove bad Artifacts test

---

src/API.jl
test/api.jl

In documentation and other prose, we often refer to Julia packages as "PackageName.jl". So I think it is understandable that a user would try to do `Pkg.add("PackageName.jl")`.
This PR prints an instructive message if a user tries to do that.

If user does e.g. `Pkg.add("Foo.jl")`, instruct them to do `Pkg.add("Foo")` instead

---

.github/workflows/test.yml
appveyor.yml

Closes #2237 
This pull request re-enables testing both with and without Pkg server.
This applies to:
- Linux (GitHub Actions)
- macOS (GitHub Actions)
- Windows (AppVeyor)

CI: Re-enable testing on Pkg server

---

docs/src/managing-packages.md
src/Pkg.jl

The default for `JULIA_PKG_DEVDIR` is *not* `.julia/dev` but `joinpath(DEPOT_PATH[1],"dev")`. This is important: users are currently not warned in [the documentation of `JULIA_DEPOT_PATH`](https://docs.julialang.org/en/v1/manual/environment-variables/#JULIA_DEPOT_PATH) that changing the first element of that environment variable will change the default of `JULIA_PKG_DEVDIR` as well.

correct documentation of default value for JULIA_PKG_DEVDIR

---

src/API.jl

This solves part 2 of #2247 and looks like an obvious correction. Possibly `repo_source` was inadvertently changed back to `pkg.repo.source` in #1419.

Use repo_source when cloning.

---

src/PlatformEngines.jl

My regex analysis indicates that this is the last case of this.

PlatformEngines: fix last case of passing header as string

---

src/API.jl

While experimenting with non-precompiled stdlibs, I found that a
`Project.toml` that has no `version` entry set will cause `precompile()`
to fail in a nasty way.
Fixes https://github.com/JuliaLang/Pkg.jl/issues/2146

Work around precompiling packages with no `version` entry

---

src/Operations.jl

Replace a "massive text dump" error with an informative warning

---

appveyor.yml

It is too slow and has too limited parallelism.

stop running AV without pkg server

---

src/API.jl
test/api.jl

#2251 missed one place where a missing version would break precomp.
Also, the errors weren't throwing due to coming from async tasks, so they now print via `@error`

Precomp: Missing fix from #2251 (Work around precompiling packages with no `version` entry)

---

src/GitTools.jl
test/new.jl

Since our libuv now understands file permissions better on windows, we can finally use `Sys.isexecutable()` on Windows.  :)

Use Sys.isexecutable() to calculate git hashes

---

src/GitTools.jl

Supercedes #2271
@KristofferC I think this is a better solution; it will keep windows improved (and hopefully allow us to no longer have hash mismatches when users create artifacts on Windows then use them on Linux) while keeping the behavior we have had on Linux/MacOS.  My initial guess right now is that `Sys.isexecutable()` (which uses `access()` internally) has corner cases on MacOS that we don't know about yet, so we should just stay away from using that for now and keep using what we've been using so far.

Only use `Sys.isexecutable()` on Windows

---

src/API.jl

Some unnecessary code duplication was hiding some more edge cases where the new stdlib jll's could break precomp due to no version

Precomp: remove duplicated pkgspec conversion code and fix

---

.github/CODEOWNERS

This pull requests sets the @JuliaLang/github-actions team as the code owners for GitHub Actions workflow files, i.e. all files in the `/.github/workflows/` directory.
(The @JuliaLang/github-actions team is a subteam of the @JuliaLang/infrastructure team.)
We are working on a GitHub Action that implements a finite state machine for tracking the progress of pull requests made by non-committers (i.e. pull requests made from forks). A high-level description of the state machine is available in [this Discourse comment](https://discourse.julialang.org/t/suggestion-to-slightly-improve-julia-development/50916/82).
Changes to repo automation workflow files can have unintended consequences, and it can be easy to miss a small workflow file change in a large pull request. Designating the …

Set the `@JuliaLang/github-actions` team as the code owners for GitHub Actions workflow files

---

src/manifest.jl
test/new.jl

This solves part 1 of #2247, adds a test for part 1, and modifies a test so that it captures part 2 and would have failed without #2249.

Canonicalize repo url when writing manifest.

---

src/utils.jl
test/artifacts.jl

`set_readonly` is supposed to set only files as read-only, but in practice if
there is a link to a directory it'll set the target directory as read-only,
causing the files inside it to be unremovable without first fixing permissions
of the directory.
This prevents `set_readonly` from changing the mode of any link.

Do not set links as read-only with `set_readonly`

---

src/Versions.jl

Even cmd has very good support for unicode, so this isn't necessary.

Use the same empty symbol regardless of platform

---

docs/src/creating-packages.md

With this change, the subsections should show up in the documentation side bar. 
This would make the appearance similar to the other pages and helps in discovering the subsections.

Show subsections in docs sidebar for creating packages page 

---

docs/src/glossary.md

These used to be in the registry but were removed a long time ago.

Remove glossary's claims about registry metadata that is not in the registry

---

docs/src/glossary.md

This is marked future work.
I think that future work is now down and we call the result an artifact, or perhaps a JLL-package.
Whatever the answer, I think this content is outdated enough that leaving it in the glossary promotes confusion

Delete library from glossary

---

src/Artifacts.jl
test/artifacts.jl

Move artifact to the expected location when tree hash computation goes wrong, fixes #2317.
~Probably need to update some tests.~ Nope, but added one.

Move artifact to the expected location

---

src/API.jl

If the source file couldn't be found some status messaging was missing, resulting in a deadlock.
I think this is the deadlock we've been seeing, like @simeonschaub's case in #2321 and #2331 
Fixes #2331 
```
Activating new environment at `/var/folders/_6/1yf6sj0950vcg4t91m9ltb5w0000gn/T/jl_m94iSi/Project.toml`
(jl_m94iSi) pkg> add Literate
Updating `/private/var/folders/_6/1yf6sj0950vcg4t91m9ltb5w0000gn/T/jl_m94iSi/Project.toml`
[98b081ad] + Literate v2.7.0
Updating `/private/var/folders/_6/1yf6sj0950vcg4t91m9ltb5w0000gn/T/jl_m94iSi/Manifest.toml`
[682c06a0] + JSON v0.21.1
[98b081ad] + Literate v2.7.0
[69de0a69] + Parsers v1.0.15
[2a0f44e3] + Base64
[ade2ca70] + Dates
[b77e0a4c] + …
```

Precompile: handle when source file is missing

---

src/Operations.jl
src/utils.jl
test/new.jl

Alignment during printing of status info is inconsistent with the rest of pkg indenting and stands out most when the status prints are embedded within other actions. Notice the two `Updating`'s here
Master
This PR
This PR turns alignment on for all status prints.
That includes for basic `pkg> status` reports, which stood out less given they were the only text printed, which I understand the reasoning for, but it seems better to be consistent?
Master
This PR

Align all status printing

---

src/API.jl
src/Operations.jl
src/Pkg.jl

Auto-precompilation is currently not run during `Pkg.test`, which means if a CI test just relies on `Pkg.test` to install the deps it currently won't benefit from parallel precomp. 
Now that error reporting in `Pkg.precompile` has improved to properly error and show stacktraces the issues around lack of information that led to it being disabled https://github.com/JuliaLang/Pkg.jl/issues/2110 should have been cleared.
Things to note:
- This precomp is done within the correct test sandbox context (not where it was previously done, as discussed in https://github.com/JuliaLang/Pkg.jl/issues/2110)
- It can be disabled either by settting `Pkg.test(... allow_autoprecomp = false)` or `ENV["JULIA_PKG_PRECOMPILE_AUTO"]=0`, and the kwarg could be exposed by the github action

Precompile: Add precomp to Pkg.test

---

src/Registry/Registry.jl

- ~~Don't leave an incomplete registry if mv fails or is interrupted
An attempt to reduce the chances of https://github.com/JuliaLang/Pkg.jl/issues/1667 happening.
Might be a fix, although the move from `cp` to `mv` may have made the likelihood much smaller already?~~
- Use `mv` rather than `cp` when updating the registry. 
`cp` seems A LOT slower on windows than `mv` https://github.com/JuliaLang/Pkg.jl/issues/2348#issuecomment-763346086

Registry: Change update from `cp` to `mv`

---

src/API.jl

While trying to clean up artifacts on Yggdrasil's CI bots, we found that some malformed artifacts (that had things like extremely-deeply-nested directories) would cause `ENAMETOOLONG` in a `stat()` within `walkdir()` itself.  Let's catch these kinds of issues and report them to the user properly.

Catch errors during `recursive_dir_size()`

---

src/API.jl
src/Operations.jl
src/Types.jl

Previously, `is_instantiated()` would only check for the presence of
dependencies, which caused artifacts belonging to the top-level project
itself to be missed in its check.  This rectifies that oversight.

Fix `is_instantiated()`

---

.gitignore
docs/src/artifacts.md
src/Artifacts.jl
src/Operations.jl
test/artifacts.jl
test/test_packages/AugmentedPlatform/.pkg/platform_augmentation.jl
test/test_packages/AugmentedPlatform/.pkg/select_artifacts.jl
test/test_packages/AugmentedPlatform/Project.toml
test/test_packages/AugmentedPlatform/src/AugmentedPlatform.jl

This, combined with the recent overhaul of BinaryPlatforms to give
extended tags to `Platform` objects, enables packages to run arbitrary
(ideally, small) pieces of code to better inform artifact selection.
`Platform`-specific Artifacts can now be tagged with arbitrary metadata,
examples of which are `libc` version, processor microarchitecture, or
CUDA version.  Because we do not want to have to teach Julia how to
autodetect its compatibility with all possible tags, we instead add the
ability for a package to perform the autodetection, and run that code
after the package is installed, but before its artifacts are downloaded.
Cooperating packages will create a `.pkg/platform_augmentation_hook.jl`
file within their package, and that file will return a function as its
final value.  This code …

Add hook to augment `Platform` objects for Artifact selection

---

src/Registry/Registry.jl

Using git for registries on Windows was definitely a big improvement for the vast majority of Windows users, but for Windows users behind firewalls that can't access github.com, it's a problem. This changes the heuristic to using git when on Windows if the pkg server isn't explicitly set. If someone explicitly sets their pkg server then we get the registry from there instead of trying to git clone it. This can be overridden by explicitly git cloning the registry once, after which it will always be git updated. But a very small number of people should need to do that.

only use git on Windows for default pkg server

---

src/Registry/Registry.jl

Even though the core reason for #1667 should be fixed on master & 1.6, that error can happen if a registry dir exists that's missing the `Registry.toml` file, which might happen if people are using newer and older julia versions together.
This changes to checking for the `Registry.toml` directly, rather than the existence of the dir.
If it's missing, the dir is replaced by the new cloned registry.

Registry add: Overwrite registry folders that don't contain a Registry.toml

---

src/API.jl

Hopefully a temporary fix for #2323 
This will mean precomp will be slower on windows, but still a lot faster than <v1.6
Fixes #2323

Precomp: Halve the default number of precompilation tasks in windows to avoid ReadOnlyMemoryError

---

src/API.jl
src/Pkg.jl

By default we prevent failures when precompiling indirect dependencies to throw, with the expectation that if they are used by direct dependencies the failure will be caught then and throw.
However, there seems to be some use cases where there is a need to force failures from indirect dependencies.
Fixes https://github.com/JuliaLang/Pkg.jl/issues/2358

Precompile: add `strict` kwarg to control whether indirect deps throw

---

.github/workflows/test.yml
appveyor.yml

Using random/different uuids across platforms isn't helping debugging of tree hash issues

Use a consistent alternative uuid across CI platforms, to help root tree hash checks

---

.github/workflows/test.yml

Turns out GitHub actions's Windows runner was changing `\n` to `\r\n` which was breaking hashing
Following the advice from https://github.com/actions/checkout/issues/135 to disable this
@staticfloat takes the prize for finding the bug
Fixes #2380

Prevent github actions CI git from changing \n to \r\n

---

Project.toml
src/PlatformEngines.jl

The `p7zip_jll` wrapper defines all sorts of useful environment
variables such as `LD_LIBRARY_PATH` to pick up the `libstdc++` that
Julia bundles with it.  We need to use that if the `7z` we're invoking
comes from that JLL, which it does if we pick it up from the `libexec`
directory of Julia.  So we instead use `p7zip_jll` if it is available on
this platform, and if it's not, we'll pick something up off the `PATH`.

Fix p7zip usage on alpine

---

src/Registry/Registry.jl

See also: #2175, #2364 
Before this PR:
| OS | `JULIA_PKG_SERVER` environment variable | Registry is obtained via | 
| --- | --- | --- | 
| Windows | not set | Git |
| Windows | set to `""` | Git |
| Windows | set to `"pkg.julialang.org"` (or any other valid Pkg server value) | Pkg server |
| Not Windows | not set | **Pkg server** |
| Not Windows | set to `""` | Git |
| Not Windows | set to `"pkg.julialang.org"` (or any other valid Pkg server value) | Pkg server |
After this PR:
| OS | `JULIA_PKG_SERVER` environment variable | Registry is obtained via | 
| --- | --- | --- | 
| Windows | not set | Git |
| Windows | set to `""` | Git |
| Windows | set to `"pkg.julialang.org"` (or any other valid Pkg server value) | Pkg server |
| Not Windows | not set | **Git** |
| Not Windows | set to `""` …

If the `JULIA_PKG_SERVER` environment variable is not set, use Git for cloning registries

---

.github/workflows/test.yml
test/new.jl

I forgot to bring this over from the debug PR #2374
Also added a sanity check that the correct Pkg is being tested, and not the one  from the julia sysimage

Another GHA windows fix: run with bash, fix TEMP fix, add sanity check for correct Pkg under test

---

src/GitTools.jl
test/new.jl

Since tree hashes cause us so much grief, make it easier for us to
figure out what _exactly_ is different between two trees.

Add `tree_hash()` debugging output

---

.github/workflows/test.yml
src/API.jl
src/REPLMode/REPLMode.jl

I noticed that loading Flux was causing Pkg latency, which on investigation seems to be due to `ChainRulesCore`'s necessarily broad `*` methods (https://github.com/JuliaDiff/ChainRulesCore.jl/pull/273) and the use of `*` for string concat in Pkg
Before:
```
julia> using SnoopCompileCore
julia> invalidations = @snoopr using ChainRulesCore;
julia> using SnoopCompile
julia> trees = invalidation_trees(invalidations)
4-element Vector{SnoopCompile.MethodInvalidations}:
inserting convert(::Type{var"#s4"} where var"#s4"<:Tuple, comp::Composite{var"#s3", var"#s2"} where var"#s2"<:Tuple where var"#s3") in ChainRulesCore at /Users/ian/.julia/packages/ChainRulesCore/cpHLu/src/differentials/composite.jl:68 invalidated:
mt_backedges: 1: signature Tuple{typeof(convert), Type{Tuple{DataType, DataType, …
```

Avoid invalidations related to * string concat

---

test/new.jl
test/runtests.jl

The `STDLIBS_BY_VERSION up-to-date` test is currently broken, and as a result, CI is failing on all PRs made to Pkg.jl.
This PR marks the `STDLIBS_BY_VERSION up-to-date` test as broken.
Once we fix that test, we should change the `@test_broken` back to `@test`.
See also:
- https://github.com/JuliaLang/Pkg.jl/pull/2408
- https://github.com/JuliaLang/Pkg.jl/issues/2410
cc: @staticfloat

Mark the "STDLIBS_BY_VERSION up-to-date" test as broken

---

src/Types.jl

some workflows require the ability to inject custom stdlibs when
building Julia, the stdlib cache breaks that. The stdlib cache is now
only used when one wants to resolve something for a custom Julia version
(for example BinaryBuilder).

only use the stdlib version cache if a custom version is given to the resolver

---

src/API.jl

In testing https://github.com/JuliaLang/Pkg.jl/pull/2425 locally I hit a state where the cache deserialized successfully, but somehow the type was invalid.. 
I didn't get to the bottom of it, but the logical thing to do is to make this function safer. It's much better to just forget this cache than to error.

Precomp: safer recall_precompile_state

---

CHANGELOG.md
src/REPLMode/argument_parsers.jl
test/new.jl
test/repl.jl

This PR revives #1636, i.e. interpret `pkg> add Example` as a package name also when you have a directory `Example` in your current directory and require `pkg> add ./Example` if you want the local directory. It differs somewhat though:
* Still accepts the name as a local directory if it's not a valid package name.
* Is more chatty in the ambiguous case.
* Uses `normpath` to normalize the local directory name after parsing. This replaces `./Example` with just `Example`.
I'm open for discussion whether these changes are desired.

Prioritize package name before local directory for REPL add and develop

---

docs/generate.jl
docs/src/api.md
docs/src/index.md
docs/src/registries.md
src/Pkg.jl
src/REPLMode/REPLMode.jl

I am guessing the warning is suggesting script writers to anticipate that their scripts might break if the REPL mode asks a question (cf. `apt-get -y`). I thought it would be clearer to indicate what to do that would reduce the need for caution.
I also tried to improve some consistency in terminology in the docs. I was ambivalent about choosing between "REPL mode"  or "REPL interface".

Suggest functional API in warning, consistency in docs

---

CHANGELOG.md
src/API.jl
src/REPLMode/command_declarations.jl
test/new.jl

Adding `pkg> rm --all` was discussed on slack, then [this discourse post](https://discourse.julialang.org/t/free-all-packages-at-once/57075) for the same with `pkg> free --all` 
So here's all three
```julia
(jl_y3T9Rt) pkg> pin --all
Updating `/private/var/folders/_6/1yf6sj0950vcg4t91m9ltb5w0000gn/T/jl_y3T9Rt/Project.toml`
[336ed68f] ↓ CSV v0.8.4 ⇒ v0.8.4 ⚲
[682c06a0] ↓ JSON v0.21.1 ⇒ v0.21.1 ⚲
Updating `/private/var/folders/_6/1yf6sj0950vcg4t91m9ltb5w0000gn/T/jl_y3T9Rt/Manifest.toml`
[336ed68f] ↓ CSV v0.8.4 ⇒ v0.8.4 ⚲
[682c06a0] ↓ JSON v0.21.1 ⇒ v0.21.1 ⚲
(jl_y3T9Rt) pkg> free --all
Updating `/private/var/folders/_6/1yf6sj0950vcg4t91m9ltb5w0000gn/T/jl_y3T9Rt/Project.toml`
[336ed68f] ↓ CSV v0.8.4 ⚲ ⇒ v0.8.4
[682c06a0] ↓ JSON v0.21.1 ⚲ ⇒ v0.21.1
Updating …
```

add --all option to rm, pin, free

---

CHANGELOG.md
src/Registry/Registry.jl
src/Registry/registry_instance.jl

There was already a cache in place that cached parsing of TOML files.
However, many other parts of the registry handling (like uncompressing the version ranges) were not. In the future, we want to move to keep the registry in its tarred form which means that re-reading it will be expensive, so let's cache it instead.
This takes for example the time to add Plots over and over from 234ms to 150ms.
Ref https://github.com/JuliaLang/Pkg.jl/issues/2435, https://github.com/JuliaLang/Pkg.jl/pull/2431

Cache registry data for PkgServer registries over Pkg invocations

---

src/API.jl
src/Operations.jl
src/Types.jl
src/manifest.jl
test/artifacts.jl
test/subdir.jl
test/utils.jl

`PackageSpec` are inputs from the user. After the resolve step, there should be no need to use these anymore. However, for some reason, we keep passing this vector of `PackageSpec` along into different operations even though we have a perfectly contained environment struct containing the full manifest with all the information we need. This is a start to remove usage of these after the resolve step.

use PackageSpec less after the resolve step, part 1

---

src/Operations.jl
test/new.jl

Fixes #1931
```
(jl_U2Ku8o) pkg> pin Example
Updating `/tmp/jl_U2Ku8o/Project.toml`
[7876af07] ~ Example v0.5.3 ⇒ v0.5.3 ⚲
Updating `/tmp/jl_U2Ku8o/Manifest.toml`
[7876af07] ~ Example v0.5.3 ⇒ v0.5.3 ⚲
(jl_U2Ku8o) pkg> free Example
Updating `/tmp/jl_U2Ku8o/Project.toml`
[7876af07] ~ Example v0.5.3 ⚲ ⇒ v0.5.3
Updating `/tmp/jl_U2Ku8o/Manifest.toml`
[7876af07] ~ Example v0.5.3 ⚲ ⇒ v0.5.3
```

Fix `status` output for pin/free

---

test/repl.jl

Close #1924
I am pretty sure @KristofferC's registry handling refactorings solved this issue. But here is a test just to make sure no regressions occur.

Test: ensure tab completion does not error offline

---

src/REPLMode/command_declarations.jl

The signatures in the help for the activate command were confusing. It seemed to imply that the `activate --shared` and `activate --temp` each took an optional path, when in fact `activate --shared` requires a path and `activate --temp` does not accept a path. This clarifies the command signatures for these two cases.

Clarify activate command signatures

---

src/API.jl

- Hides the progress bar after precomp has finished
- Indents the precomp report to align better as children of the `Precompiling project...` title
Hopefully helps https://github.com/JuliaLang/Pkg.jl/issues/2456 cc. @nickrobinson251
During
After
Previously the progress bar sticks around at 100%

Precompilation: Tidy report at end

---

README.md

Just some explanations and convenience links.
Came from a discussion at https://github.com/JuliaPackaging/BumpStdlibs.jl/issues/33

Add helper notes about syncing with julia repo

---

src/REPLMode/argument_parsers.jl
test/new.jl

fix #2406
The current error message is pretty cryptic. It would be more clear if we detect if a user is trying to add a local path and let the user know early if we can not carry the operation out.
Example:
```
(jl_CLaIt8) pkg> add path/does/not/Exist
ERROR: `path/does/not/Exist` appears to be a local path, but directory does not exist
````

Clarify REPL errors for add/dev

---

src/Operations.jl
test/new.jl

Pass the `io` flag to the test context, otherwise we will not capture the complete output

Fix: capture all `test` printing

---

src/API.jl

There's been some confusion about how to get information on the errors that are counted during auto-precomp but that aren't thrown or detailed.
This adds a helper tip `To see a full report either call 'pkg> precompile' or load the package(s)` that's seen at the top here
(I added an `error()` to FileIO)

Precompilation: add tip to auto-precomp for getting error details

---

src/Types.jl

Remove some unnecessary feedback

---

src/Pkg.jl

added a missing close quotation

docs: tiny typo (missing endquote)

---

CHANGELOG.md
src/API.jl
src/Operations.jl
src/Pkg.jl
src/Types.jl
test/new.jl

@KristofferC I took the liberty of rebasing these changes (the mode field drives me nuts every time I read through the code). I did not want to alter the original PR so I opened this one

rebase 2135

---

src/Operations.jl
src/Types.jl
src/project.jl

Inspired by the discussion in #2469. As stated in the discussion. a VersionSpec is a much more desirable representation because it can be modified more easily.
Changes:
- immediately convert to `VersionSpec` when reading project file
- keep raw string representation to write back out when operations complete

Refactor: use `VersionSpec` as the canonical compat representation

---

src/project.jl

In the future, we may disable `@assert`s by default. But I think this particular error should always be shown.

Don't use the `@assert` macro

---

src/Types.jl
test/new.jl

Should fix the test error in https://github.com/JuliaLang/Pkg.jl/pull/2425
Edit: This still need some tweaks

fix STDLIBS_BY_VERSION on non-latest version of Julia

---

src/REPLMode/command_declarations.jl
test/new.jl

Someone on slack was trying to set `preserve` while `develop`ing, but it hasn't been hooked up to the REPL yet. I am a little surprised it hasn't been pointed out before.

allow `--preserve` option for `develop` in the REPL

---

src/API.jl
test/new.jl

We weren't passing `io` down in `activate` for all cases: this fixes that.
Also adjust `activate` feedback to suggesting in #1761.
Fix #1761, Close #2036

adjust `activate` feedback and hook up to `io` kwarg

---

src/Pkg.jl

Drive by fix for the following issue in the output of the precompile
```
┌ Error: Error in the keymap
│   exception =
│    TOML Parser error:
│    C:\users\keno\Temp\jl_qpEfxR\registries\Registry\T/TestPkg\Package.toml:3:12 error: invalid uncidode scalar
│      repo = "C:\users\keno\Temp\jl_qpEfxR/TestPkg.jl"
│                 ^                                     
│    Stacktrace:
│     [1] parse
│       @ .\toml_parser.jl:441 [inlined]
│     [2] Base.CachedTOMLDict(p::Base.TOML.Parser, path::String)
│       @ Base .\loading.jl:180
│     [3] (::Base.var"#810#811"{String, Base.TOMLCache})()
│       @ Base .\loading.jl:226
└ @ REPL.LineEdit Z:\home\keno\julia-win64\usr\share\julia\stdlib\v1.7\REPL\src\LineEdit.jl:2579
```

precompile: Escape string in toml file

---

src/API.jl
src/Pkg.jl
src/REPLMode/argument_parsers.jl
src/Types.jl
test/artifacts.jl
test/test_packages/ArtifactOverrideLoading/Project.toml

Fix #2282 
I admit that messing with the constructor was a thoroughly terrible idea. The check could be circumvented anyway by manually setting the fields after the constructor call. The checking should be done inside the API.

Refactor: do not use double constructor for PackageSpec

---

.github/workflows/test.yml
src/API.jl
src/Artifacts.jl
src/MiniProgressBars.jl
src/Operations.jl
src/Pkg.jl
src/PlatformEngines.jl
src/REPLMode/REPLMode.jl
src/Types.jl
test/api.jl
test/new.jl
test/test_packages/CompatExtras/Project.toml

Manual cherry-picks
Required a change of approach. See https://github.com/IanButterworth/Pkg.jl/blob/cdf685a6a1f40607df185cbacec8a1db5cec4a7b/src/Types.jl#L1003-L1004

1.6.1 backports

---

src/GitTools.jl
test/new.jl

We missed a `basename()` when comparing `f` to `".git"`, meaning that
embedded `.git` directories get included.

Fix treehash generation

---

src/MiniProgressBars.jl

- Caps the update rate of the bar to 30 Hz
- Print things in one call to the terminal in a few places instead of spreading things out over multiple print calls. This is usually a good idea when writing to a terminal.

small improvements to progress bar

---

src/Pkg.jl

Since these kwargs are only for use in the CompatHelper/Dependabot use case, we can just make them nonpublic (private/internal).
And if they are not public, we can remove them from the documentation.

Remove `force_latest_compatible_version` and `allow_earlier_backwards_compatible_versions` from the docstring for `Pkg.test`

---

test/artifacts/bad/incorrect_sha256.toml

Let's not allow for false-positive results from the PkgServer.

Zero out broken_artifact gitsha
