ext/BinaryProvider/.codecov.yml
ext/BinaryProvider/.gitignore
ext/BinaryProvider/.travis.yml
ext/BinaryProvider/LICENSE.md
ext/BinaryProvider/README.md
ext/BinaryProvider/REQUIRE
ext/BinaryProvider/appveyor.yml
ext/BinaryProvider/src/BinDepsIntegration.jl
ext/BinaryProvider/src/BinaryPackage.jl
ext/BinaryProvider/src/BinaryProvider.jl
ext/BinaryProvider/src/OutputCollector.jl
ext/BinaryProvider/src/PlatformEngines.jl
ext/BinaryProvider/src/PlatformNames.jl
ext/BinaryProvider/src/Prefix.jl
ext/BinaryProvider/src/Products.jl
ext/BinaryProvider/test/LibFoo.jl/.gitignore
ext/BinaryProvider/test/LibFoo.jl/README.md
ext/BinaryProvider/test/LibFoo.jl/deps/build.jl
ext/BinaryProvider/test/LibFoo.jl/src/LibFoo.jl
ext/BinaryProvider/test/LibFoo.jl/test/runtests.jl
ext/BinaryProvider/test/output_tests/fail.sh
ext/BinaryProvider/test/output_tests/kill.sh
ext/BinaryProvider/test/output_tests/long.sh
ext/BinaryProvider/test/output_tests/newlines.sh
ext/BinaryProvider/test/output_tests/simple.sh
ext/BinaryProvider/test/runtests.jl
src/Operations.jl
src/Pkg3.jl

I moved (and changed) the printing a bit because printing inside a task can get pretty confusing.
Build on top of https://github.com/StefanKarpinski/Pkg3.jl/pull/15.
The commit to look at is https://github.com/StefanKarpinski/Pkg3.jl/pull/25/commits/26983596f51b965c069b9ab020ecd479fbc73425.

Asynchronously install packages

---

src/Operations.jl

fix not printing already existing packages

---

src/API.jl
src/Pkg3.jl
src/REPLMode.jl
src/Types.jl
test/runtests.jl

make a basic functional API and add some very basic tests

---

ext/BinaryProvider/REQUIRE
ext/BinaryProvider/src/BinDepsIntegration.jl
ext/BinaryProvider/src/BinaryPackage.jl
ext/BinaryProvider/src/BinaryProvider.jl
ext/BinaryProvider/src/OutputCollector.jl
ext/BinaryProvider/src/PlatformEngines.jl
ext/BinaryProvider/src/PlatformNames.jl
ext/BinaryProvider/src/Prefix.jl
ext/BinaryProvider/src/Products.jl
ext/BinaryProvider/test/runtests.jl
ext/TOML/src/TOML.jl
ext/TOML/src/parser.jl
ext/TOML/test/runtests.jl
ext/TerminalMenus/src/MultiSelectMenu.jl
ext/TerminalMenus/src/RadioMenu.jl
ext/TerminalMenus/src/TerminalMenus.jl
src/Operations.jl
src/Pkg2/query.jl
src/Pkg2/types.jl
src/Pkg3.jl
src/REPLMode.jl
test/runtests.jl

PRs have been filed for removing deprecations to the dependencies.

Upgrade Pkg3 and ext dependencies to 0.7

---

src/API.jl
src/Types.jl

Taken mostly from the Base implementation.

update registries on up

---

src/API.jl
src/Pkg3.jl
src/REPLMode.jl

Fixes https://github.com/JuliaLang/Pkg3.jl/issues/31
Perhaps you can use this @vdayanand

implement build call

---

src/REPLMode.jl

Using the preview command from the REPL mode was broken in 3b8d98be0d43fce884d544ee0d4c6b6ee833d900. E.g.:
```
pkg> preview add Whatever
ERROR: MethodError: no method matching do_cmd!(::Pkg3.Types.EnvCache, ::Array{Tuple{Symbol,Vararg{Any,N} where N},1}, ::Base.REPL.LineEditREPL)
do_cmd!(::Any, ::Any) at /home/carlo/.julia/v0.6/Pkg3/src/REPLMode.jl:123
Stacktrace:
[1] do_preview!(::Pkg3.Types.EnvCache, ::Array{Tuple{Symbol,Vararg{Any,N} where N},1}, ::Base.REPL.LineEditREPL) at /home/carlo/.julia/v0.6/Pkg3/src/REPLMode.jl:162
[2] do_cmd!(::Array{Tuple{Symbol,Vararg{Any,N} where N},1}, ::Base.REPL.LineEditREPL) at /home/carlo/.julia/v0.6/Pkg3/src/REPLMode.jl:144
[3] do_cmd(::Base.REPL.LineEditREPL, ::String) at /home/carlo/.julia/v0.6/Pkg3/src/REPLMode.jl:112
[4] …
```

Fix preview command in the REPL

---

src/Types.jl

fixes https://github.com/JuliaLang/Pkg3.jl/pull/88

fixes Appveyor test broken by #88 

---

Manifest.toml
bin/generate.jl
src/API.jl
src/Display.jl
src/Operations.jl
src/Pkg3.jl

See also: https://github.com/JuliaLang/julia/pull/25734, https://github.com/JuliaRegistries/Uncurated/pull/4

rename hash-sha1 to git-tree-sha1

---

src/Types.jl

These are used in a lot of places and are type unstable everywhere.
This reduces time to do `Pkg.add("DifferentialEquations") by ~10% and reduces time for the first `Pkg.add("DifferentialEquations")`, i.e. including compilation time, with 2 seconds.

improve performance by not parameterizing on tuple length for VersionBound and VersionRange

---

ext/TOML/src/parser.jl

* use `Parser` local `IOBuffer` to write read chars into, instead of creating Char arrays everywhere
* be more careful with using stream seeking operations such as `position`, `mark`, `seek`, these are kinda slow
Benchmark:
```jl
import Pkg3
import Pkg3.TOML
path = "/Users/kristoffer/.julia/registries/Uncurated"
info("Parsing files")
@time for (root, dirs, files) in walkdir(path)
for file in files
if endswith(file, ".toml")
TOML.parsefile(joinpath(root, file))
end
end
end
```
Before PR:
```
3.612417 seconds (2.51 M allocations: 177.444 MiB, 0.70% gc time)
```
After PR:
```
1.041261 seconds (2.05 M allocations: 129.794 MiB, 2.12% gc time)
``` 
There is more room for improvements but hitting diminishing returns now.

 speed up TOML parsing by ~4x

---

src/Operations.jl

Split the install function into two separate ones, one to download from archives and one to download from git.
Use the archive one async, use libgit2 for those that fail synchronously.

refactor installation process, only use LibGit2 synchronously

---

src/Operations.jl

Not sure what the purpose of this function is and it is unused. Something you want to keep around @StefanKarpinski?

delete unused function

---

src/API.jl
src/Operations.jl
src/Types.jl

Merge after https://github.com/JuliaLang/julia/pull/26057

slugs: use Base's SHA1 and version_slug

---

src/Operations.jl

This is a bit weird since it creates a module inside of the package
module that is being built/tested, called `__build__` or `__test__`,
and then evaluates build and test code inside of that "hidden" sub-
module of the package. This causes the build/test code to find the
correct UUID when it loads its dependencies, allowing that code to
load what the package itself can (and not load what it can't).
Requires https://github.com/JuliaLang/julia/pull/26120 to work.

build/test: evaluate in module with the right UUID

---

src/API.jl
src/Display.jl
src/Operations.jl
src/Pkg3.jl
src/REPLMode.jl
src/Types.jl
test/pkg.jl

New and better version of https://github.com/JuliaLang/Pkg3.jl/pull/21. Fixes the TODOs from there.

reimplement freeing and pinning

---

src/API.jl
src/REPLMode.jl

fix init in REPL

---

bin/generate.jl
bin/genstdlib.jl
bin/gitmeta.jl
src/API.jl
src/Operations.jl
src/Types.jl
test/pkg.jl

(cherry picked from commit 9f633a546f7d5fcd98312b4d6aa45d37cd24b89c)

Pkg3: the great bikeshed rename

---

appveyor.yml
src/PlatformEngines.jl

JULIA_HOME -> Sys.BINDIR

---

src/API.jl
src/Display.jl
src/GraphType.jl
src/Operations.jl
src/Pkg2/types.jl
src/Pkg3.jl
src/REPLMode.jl
src/Resolve.jl
src/Types.jl

make imports relative

---

.gitignore
docs/make.jl
docs/src/index.md
src/API.jl
src/Operations.jl
src/Pkg3.jl
src/REPLMode.jl
src/Types.jl
src/generate.jl
test/repl.jl

Very simple package generation so far.

add a command to create a new package, write some docs, add a framework for testing the REPL

---

src/API.jl
src/Display.jl
src/Operations.jl
src/Pkg3.jl
src/REPLMode.jl
src/Types.jl

tweak a bit how things are printed

color consistency

---

docs/src/index.md
src/REPLMode.jl

describe how to leave pkg repl mode

---

src/REPLMode.jl

Fixes https://github.com/JuliaLang/Pkg3.jl/issues/193

warn when using git revisions in upgrade command

---

docs/src/index.md

make clear that `tree` is an external command

---

src/REPLMode.jl
src/Types.jl
test/repl.jl
test/test_packages/RequireDependency/REQUIRE

Closes https://github.com/JuliaLang/Pkg3.jl/issues/192, Closes https://github.com/JuliaLang/Pkg3.jl/issues/19.

Autocomplete

---

src/GitTools.jl

Requires changes in: https://github.com/JuliaLang/julia/pull/26437/commits/6e7b5de9691488b1c1ad899d14fde5ec34b67af9

Use high-level clone/fetch with callback support

---

README.md

remove outdated info from readme

---

docs/src/index.md
src/API.jl
src/GitTools.jl
src/Operations.jl
src/Types.jl
test/repl.jl
test/test_packages/UnregisteredWithoutProject/.gitignore
test/test_packages/UnregisteredWithoutProject/deps/build.jl
test/test_packages/UnregisteredWithoutProject/src/UnregisteredWithoutProject.jl

Fixes #239 
Also upstreams a few commits from the julia repo.

fix building packages that comes from git repos

---

src/Operations.jl
test/test_packages/UnregisteredWithProject/Project.toml
test/test_packages/UnregisteredWithProject/src/UnregisteredWithProject.jl

Fixes #244 cc @smldis
Better diff: https://github.com/JuliaLang/Pkg3.jl/pull/245/files?w=1

check Project file for dependencies in dependencies with a path entry

---

src/Operations.jl

small bugfix with version handling

---

src/Operations.jl
src/Types.jl

Fixes https://github.com/JuliaLang/Pkg3.jl/issues/248

use registry if no version entry exist in project for developed pacakges

---

src/API.jl
src/GitTools.jl
src/Types.jl

Failing to do this actually meant the registry did not get updated. :(

give refspecs to the registry

---

src/Types.jl
test/pkg.jl

fix that adding julia as a package was possible

---

src/API.jl
src/Operations.jl
src/REPLMode.jl
test/repl.jl

Fixes #264, Fixes #265, Fixes #266

fix pin on repo added packages

---

src/GitTools.jl
test/pkg.jl

Fixes https://github.com/JuliaLang/Pkg3.jl/issues/241

use smaller granularity in progressbar when testing

---

src/Operations.jl

Found when testing some packages (Compat) with Pkg3.

small fix for testing projects

---

src/Operations.jl

Fixes the second part of https://github.com/JuliaLang/Pkg.jl/issues/293.

do not clobber entries in uuid_to_name coming from checked out packages

---

src/Operations.jl
test/pkg.jl
test/utils.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/297.

make sure we error on build if a package fails to build

---

src/Operations.jl

make find_stdlib_deps more resiliant when weird things are inside the package folder

---

src/REPLMode.jl
src/generate.jl
test/pkg.jl

fix preview of generate so it does not create any files

---

src/PlatformEngines.jl

no need to execute sh stuff for Pkg

---

src/API.jl
src/Operations.jl

fix preview init to not do anything

---

src/Operations.jl

don't delete build.log file on success

---

src/REPLMode.jl
src/Types.jl
test/pkg.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/324

fix case sensitiveness on adding packages

---

src/GitTools.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/369

use a time interval for printing git progress in non interactive mode

---

docs/src/index.md
src/API.jl
src/Pkg.jl
src/REPLMode.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/376

Backport and fix resolve

---

src/REPLMode.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/200

clean up some REPL commands

---

src/Pkg.jl

So that exploration can be done with `Pkg.`.
cc @andyferris

fix tab completion

---

src/REPLMode.jl
test/repl.jl

How to test this?
Fix https://github.com/JuliaLang/Pkg.jl/issues/321

support git@blabla in add

---

src/REPLMode.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/362

fix repl crashing with invalid env files

---

src/REPLMode.jl
src/Types.jl

@fredrikekre informed me that the REPL prompt function run at every keystroke. Materializing a complete EnvCache (which also records its usage in the log) is a bit excessive for this. Instead, just do what we need to figure out the name of the current project. Also, cache this so we don't need to parse a TOML file at every keystroke.

cache some data for the project prompt printer

---

.travis.yml
appveyor.yml

No need to `instantiate` anymore.

tweak ci scripts

---

src/REPLMode.jl

The help says it's called "create"

generate help string name

---

docs/src/index.md

I feel like the keyword application does not naturally bring to mind the idea of the code I write to do !!SCIENCE!!.
This I think this needs to be specifically called out.
For the most common users of julia this is a much more common type of "application" to create
than a "web-app"

Add example of research code as an application

---

src/GitTools.jl
src/Operations.jl
src/Types.jl
test/pkg.jl

I got some errors (I can try to recreate them, if needed) even after #428, so I went ahead and added some helper functions to get rid of the errors more generally. Also added some tests.

Modularize resolution of project/manifest file paths

---

src/REPLMode.jl

Fix spelling mistake

---

src/Pkg2/types.jl

Fixes #https://github.com/JuliaLang/Pkg.jl/issues/371

use max VersionBound if no upper bound in REQURIE file

---

src/Operations.jl
src/Types.jl
test/repl.jl

Prevents us from getting bad key errors down the line.

make reading packages a bit more robust

---

src/Display.jl
src/Types.jl
test/pkg.jl
test/repl.jl

Some LibGit2 close fixes

---

src/REPLMode.jl
test/pkg.jl
test/repl.jl
test/utils.jl

Clean version of #466 . Note it should also fix the Apple bug.

Add tests for `REPLMode.promptf`

---

.gitignore
src/REPLMode.jl
test/repl.jl

This implements support for 
```
pkg> add Test
rm Random
```
and similarly
```
julia> pkg"""
add Test
rm Random
"""
```

support for multiline input

---

src/API.jl
src/GitTools.jl
test/pkg.jl

change default for setprotocol

---

docs/src/index.md
src/Types.jl
test/repl.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/434

only set the pkg.repo.rev in case of upgrading

---

src/REPLMode.jl
test/repl.jl

Small change. The tests should be useful though.

Refactor `REPLMode.do_generate!`

---

src/Operations.jl
src/PlatformEngines.jl
src/Types.jl
test/pkg.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/391 when passing..

Test tarball downloads

---

src/API.jl
src/Types.jl

Well, that was easier than I thought... (fingers crossed for CI)

Don't update registry when developing a local path

---

docs/src/index.md
src/Operations.jl
src/REPLMode.jl
src/Types.jl
test/repl.jl

Seems to work, but should try to add some tests etc
fix #485

Save dev'd path as given

---

src/API.jl
src/Pkg.jl
test/repl.jl
test/test_packages/UnregisteredWithoutProject/src/UnregisteredWithoutProject.jl

fix #26282
(cherry picked from commit 6026374bce093fbc69ee9a58916505a86a6afe80)

loading: make __precompile__ the default (#26991)

---

src/API.jl
src/REPLMode.jl

Refactor `activate` to avoid complexity in the main method

---

bin/generate.jl
docs/src/index.md
src/Types.jl

To reflect the rename of the registry

rename Uncurated to General

---

src/REPLMode.jl
test/repl.jl

Fix parser (lexer)

---

src/Pkg2/reqs.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/570

stop using PkgError

---

src/Operations.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/566.

ignore julia in test/REQUIRE

---

src/Operations.jl

Thanks to @fredrikekre for pointing out what to change. Not sure how to test this; I couldn't find how other options are being tested.

Propagate track-allocation option to test process.

---

docs/src/index.md
src/API.jl
src/REPLMode.jl
test/pkg.jl
test/repl.jl

Replaces https://github.com/JuliaLang/Pkg.jl/pull/496

only look for Project files in installed

---

bors.toml

Needs someone with the correct access in JuliaLang to accept my request to install Bors (https://github.com/bors-ng/bors-ng).

add bors file

---

.travis.yml
appveyor.yml

stop testing on 0.7

---

src/Pkg.jl
src/REPLMode.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/636

update docs for develop

---

src/REPLMode.jl
test/repl.jl

Should close #590 and close #549

Remove `--env` meta option

---

src/Types.jl
test/pkg.jl
test/repl.jl
test/utils.jl

Fixes #613 
Thanks for the detailed MWE @tkf.

update the repo when the gitobject is not available

---

src/REPLMode.jl

Should resolve #586. Should be merged after #595 (to avoid merge conflicts).

Use max/min instead of a list to specify argument count

---

README.md

update AppVeyor URL

---

docs/src/index.md

ref https://github.com/JuliaLang/julia/pull/28776#issuecomment-414255251

Update Pkg docs to reflect version change to v1.0

---

src/API.jl

No idea why this helps but at least it doesn't crash anymore...

work around strange "Unreachable reached" when the close function for a repo fires when updating registries

---

.gitignore
.travis.yml
docs/Project.toml
docs/make.jl

Use Travis build stages and build docs from master.

---

src/versions.jl
test/pkg.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/750

fix type in isjoinable

---

docs/src/index.md

Adding this PR here instead of [JuliaLang](https://github.com/JuliaLang/julia/pull/28947) per @KristofferC

Update project.toml compat example

---

src/Types.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/667

only look up name from url if it is unset

---

src/Operations.jl

mention what package failed to install

---

src/Pkg.jl

Reword `activate` docs

---

src/API.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/722

do not precompile packages that have opt out to precompilation

---

test/repl.jl

(cherry picked from commit f8b52dab77415a22d28497f48407aca92fbbd4c3)

bump JSON version check to a non-capped version (#29315)

---

src/API.jl

Use pathrepr in pkg> gc.

---

src/REPLMode.jl

ref https://github.com/JuliaLang/Pkg.jl/issues/788

respect color option in REPL

---

src/REPLMode.jl
test/repl.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/801.

fix path completions

---

.travis.yml

Revert "Update .travis.yml (#758)"

---

src/API.jl
src/Operations.jl
src/Pkg.jl
src/REPLMode.jl

Implement `pkg> build (-v|--verbose) Package` and `Pkg.build("Package"; verbose=true)` for verbose build output, fix #665.
bors try

verbose build

---

src/REPLMode.jl
test/repl.jl

Both `--env` and `--preview` were around before. But `activate` was perfered to `--env`. And the only documented syntax for preview is `preview add Plots`.
In light of this, no real use for "meta options" anymore.

Remove support for "meta options"

---

src/Operations.jl
src/Types.jl
test/api.jl
test/pkg.jl
test/repl.jl
test/utils.jl

Cleanup most temporary dirs, fix #704, fix #723.

---

src/PlatformEngines.jl

backport v3

---

src/REPLMode.jl
test/repl.jl

Changes:
- Introduce `completions` field to command declarations. This field declares a function `f : options x string_to_complete -> possible completions`. The intent is to isolate the mechanical (and edge case ridden!) parts from the meaningful.
- share logic between the regular parser and completions parser (this shared logic is now in`core_parse`)
- remove `CompletionCache` object. It introduced quite a bit of state for no noticeable speed benefit
Fixes:
- only complete canonical names for commands (i.e. not the short form) (I didn't know about #200, when I did #603)
- in the same spirit, only complete canonical form for options (e.g. `--manifest` but not `-m`)

Refactor completions

---

test/test_packages/BigProject/test/runtests.jl

Disable startup.jl in BigProject tests, fix #815.

---

src/Types.jl

attempt to mitigate https://github.com/JuliaLang/Pkg.jl/issues/885

write manifest_usage.toml entries in one print call

---

src/GraphType.jl

Use permutedims instead of LinearAlgebra.transpose (via Base), fix #896.

---

src/API.jl
test/api.jl

API shoud accept `AbstractString` arguments

---

src/API.jl
src/GitTools.jl
src/Operations.jl
src/Types.jl
test/api.jl

Thoughts? Some light refactoring + dividing into functions for readability + a few comments.
This would close #668.

Refactor `Types.handle_repos_develop`

---

src/API.jl

This fixes `activate` when the currently active environment is corrupted.
- In the case where we give `activate` a path, we should just set `Base.ACTIVE_PROJECT[]` without doing any extra work.
- In the case where we give `activate` the name of a `develop`ed dependency, we have to be careful when calling `EnvCache` because it will fail if the current environment contains a corrupted project/manifest file.

Fix activate in the case that the active env is corrupted

---

README.md
docs/make.jl
docs/src/api.md
docs/src/assets/custom.css
docs/src/environments.md
docs/src/registries.md
src/Pkg.jl
src/REPLMode.jl
src/Registry.jl

- Remove some TODOs
- Add compatibility notes for some new features
- Better README links
- Add custom.css for compat admonitions
- Documentation for registry REPL commands
---
cc @mortenpi for the compat notes we discussed.

Prepare docs for release:

---

src/REPLMode.jl

Expand tilde in local path completions

---

Project.toml

Will make a branch after merging this (still waiting for some PRs to be merged), and release 1.1.

Set version to 1.1.0.

---

Project.toml
src/API.jl
test/pkg.jl

Backports for 1.1.2

---

docs/src/api.md
docs/src/glossary.md

doc: fix numbering of chapters, fix #944.

---

docs/make.jl

doc: move misplaced versions kwarg from makedocs to deploydocs.

---

docs/generate.jl
src/REPLMode.jl

doc: "registry-add" to "registry add" in documentation, 

---

src/API.jl

Always print the activate environment

---

src/API.jl
src/Pkg.jl

---
replaces #1000 cause that one was autoclosed when I pushed.

Better error message for Pkg.add(url) and Pkg.add(path).

---

docs/src/getting-started.md

This simplifies the existing text and adds more material, in order of increasing complexity.

Expand `Pkg` guide

---

src/Display.jl

Fix #1040, fix #1027, fix #587

Display diff when `path` changes

---

src/Operations.jl

---
#1033 became kinda big and does a lot of things. I think it is better to break it up a bit.

silent activate when testing, fixes #1029.

---

src/API.jl
src/REPL/argument_parsers.jl
src/REPL/command_declarations.jl
src/REPL/completions.jl
src/REPLMode.jl
test/pkg.jl
test/repl.jl

Changes:
- make REPL code more cohesive
- delay full argument parsing
---
I'm splitting this from #1051 so it doesn't rot

Refactor REPL

---

src/versions.jl

fixes https://github.com/JuliaLang/Pkg.jl/issues/1022

fix undefvar when reporting error for version 0.0.0

---

src/Operations.jl
test/pkg.jl

Make sure the package can safely be added/developed
before overwriting existing dependencies, fixes #1066, closes #1069.
In particular this PR checks the following:
- if a package with the same name exist in the project
we assert that they have the same uuid,
- if a package with the same uuid exist in the project
we assert that they have the same name,
- if a package with the same uuid exist in the manifest
we assert that they have the same name.

Make sure the package can safely be added/developed

---

docs/generate.jl
test/pkg.jl

Fix generation of REPL command docstrings.

---

docs/src/basedocs.md

Fix basedocs.md for building Julia's documentation.

---

src/REPL/command_declarations.jl

Accidentally included in #1076.
---
bors r+

Remove help for non-existent activate -.

---

.travis.yml
docs/Project.toml
docs/make.jl

Build a pdf version of the Pkg.jl manual.

---

src/Operations.jl
test/api.jl

fix free on tracked repos.

---

src/Operations.jl

fix a type in a error message

---

src/REPL/command_declarations.jl

Fix outdated develop docstring, fixes #1082.

---

src/Operations.jl
src/Pkg.jl
src/REPLMode.jl
test/pkg.jl
test/test_packages/BuildProjectFixedDeps/.gitignore
test/test_packages/BuildProjectFixedDeps/Manifest.toml
test/test_packages/BuildProjectFixedDeps/Project.toml
test/test_packages/BuildProjectFixedDeps/deps/build.jl
test/test_packages/BuildProjectFixedDeps/src/BuildProjectFixedDeps.jl

Backports for 1.0.

---

Project.toml

---
Will make a `release-1.2` branch after this I guess.

Set version to 1.2.0.

---

src/GraphType.jl

This fixes https://github.com/JuliaRegistries/General/pull/49. I'm rather surprised that this had never came up before...

Fix bug in dependency graph creation

---

src/GraphType.jl

Backport 1.0

---

src/GraphType.jl

Backport 1.1

---

src/API.jl
test/repl.jl

Use printpkgstyle for activate.

---

docs/src/creating-packages.md

Provides link to Registrator and TagBot

Added registering packages section

---

docs/src/api.md
src/Pkg.jl
test/repl.jl

add Pkg.precompile

---

src/Operations.jl
test/pkg.jl
test/test_packages/Unpruned/Manifest.toml
test/test_packages/Unpruned/Project.toml
test/test_packages/Unpruned/src/Unpruned.jl

`up` should prune manifest

---

src/Display.jl
test/pkg.jl

---
Better diff: https://github.com/JuliaLang/Pkg.jl/pull/1199/files?w=1

Wrap reading of project status in HEAD in try-catch, fixes #1180.

---

.gitignore
.travis.yml
test/coverage/Project.toml

Fix coverage submission from master branch.

---

src/Operations.jl
test/pkg.jl

`up` should load complete manifest info

---

docs/src/creating-packages.md

Make note about gen_project a note.

---

src/REPLMode.jl
test/repl.jl

Fix https://github.com/JuliaLang/Pkg.jl/issues/948
(this is much harder than I thought, and maybe I'm still doing something wrong but all tests passed)

allow comma in add, also tests

---

docs/src/compatibility.md
docs/src/creating-packages.md
src/API.jl
test/pkg.jl

Backports for 1.2.0-rc3

---

ext/TOML/src/parser.jl
ext/TOML/test/runtests.jl

This is more efficient in Julia (allows for union splitting).

use triple equals for testing against nothing

---

src/PlatformEngines.jl

Requires https://github.com/JuliaLang/julia/pull/32917

PlatformEngine: respect Base.DOWNLOAD_HOOKS

---

test/pkg.jl

disable the notarealprotocol test

---

src/REPL/completions.jl

fix tab completions for packages not defining any julia compat

---

src/API.jl
src/Pkg.jl
test/api.jl

address https://github.com/JuliaLang/Pkg.jl/pull/1279#issuecomment-517622947

Allow AbstractVector{<:AbstractString} for {julia,test}_args

---

src/Types.jl

fixes https://github.com/JuliaLang/Pkg.jl/issues/806

fix scope of a variable

---

src/API.jl
src/Display.jl
src/GitTools.jl
src/Operations.jl
src/Registry.jl
src/Types.jl
src/backwards_compatible_isolation.jl
src/require.jl
test/registry.jl
test/repl.jl
test/utils.jl

Aiming for #122 with this one.
Basically just add an `io` field to `Context`, thread the `Context` object through a more functions, and make the display stuff use the `io` field by default. I also switched some functions from taking `EnvCache` to `Context`. Most were necessary because they eventually printed, but some I just changed for consistency's sake.
This should also let us test `Display` more easily, which we are not really doing right now.

Capture output

---

src/Pkg.jl

Minor typo in docstring for Pkg.add

---

src/Types.jl

---
More correct if we add more type of name pairs in the future.

 Slightly tweak computation of manifest file name  in case no (Julia)Manifest.toml exist.

---

src/REPLMode/completions.jl
test/repl.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/1336

fix tab completion error with invalid arguments

---

src/REPLMode/completions.jl
test/repl.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/1355

fix "double expanding" homedir on tab complete

---

src/API.jl
src/Pkg.jl
test/manifest/noproject/Manifest.toml
test/pkg.jl
test/utils.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/1091.
~~Not sure if the presence of a manifest file in the current directory is the best way to activate this feature or if we should enforce a flag to instantiate to do it.~~

add support for instantiating lonely manifest

---

docs/src/basedocs.md

Add EditURL to basedocs.md, fixes https://github.com/JuliaLang/julia/issues/33237.
---
borsr+

Add EditURL to basedocs.md

---

src/API.jl
src/Artifacts.jl
src/Operations.jl
src/PlatformEngines.jl
test/artifacts.jl

Also contains the "verbose mode" downloading from a previous PR, now more fully tested.

Fix `instantiate` not installing artifacts

---

src/Operations.jl
test/api.jl
test/test_packages/BasicCompat/Project.toml

`rm` should always preserve `julia` compat

---

appveyor.yml

AV is a big bottleneck in CI times.

only test AV on nightly

---

bin/recompress.jl
src/API.jl
src/Operations.jl
src/Pkg.jl
src/REPLMode/REPLMode.jl
src/REPLMode/argument_parsers.jl
src/Resolve/Resolve.jl
src/Resolve/graphtype.jl
src/Types.jl
src/backwards_compatible_isolation.jl
src/utils.jl
test/api.jl
test/pkg.jl
test/registry.jl
test/resolve.jl

Trying to reduce the size of Types.jl a bit (in preparation for `module Types` to go away). Each commit should hopefully be quite self-explanatory.

Refactoring to get rid of some old stuff and move some types into better place

---

docs/src/api.md
src/API.jl
src/Pkg.jl
src/REPLMode/REPLMode.jl
src/REPLMode/command_declarations.jl
src/Types.jl
src/manifest.jl
src/project.jl
test/pkg.jl

Should be rebased after #1398 goes through.

Implement undo and redo functionality

---

README.md

Point README links for AV to JuliaLang, remove links for BORS.

Update README links.

---

src/PlatformEngines.jl

This should solve the problems in https://github.com/JuliaLang/julia/pull/33499

Look in `bin` for `7z` for in-tree builds

---

docs/src/compatibility.md

improvement on composite leading zero description in docs

---

docs/src/toml-files.md

Document that uuid4 should be used by default.

---

docs/src/api.md

Document IO redirection

---

docs/src/compatibility.md
docs/src/creating-packages.md
docs/src/environments.md
docs/src/getting-started.md
docs/src/managing-packages.md
docs/src/registries.md

All credit should go to Chris Rackauckas, I just updated #765 for the current doc layout we are using.
close #765

(Updated) Remove OS-specific shell commands from Pkg docs

---

Project.toml
docs/src/artifacts.md
ext/TOML/src/TOML.jl
src/API.jl
src/Artifacts.jl
src/BinaryPlatforms.jl
src/Display.jl
src/GitTools.jl
src/GraphType.jl
src/Operations.jl
src/Pkg.jl
src/PlatformEngines.jl
src/REPL/completions.jl
src/REPLMode.jl
src/Types.jl
src/backwards_compatible_isolation.jl
src/generate.jl
src/versions.jl
test/artifacts.jl
test/repl.jl

Backports release-1.3

---

src/PlatformEngines.jl

This is WIP currently. First step is adding the ability to pass headers to download agents.

Pkg client: authentication support

---

src/Operations.jl

Bug fix: Make sure sandbox's temp Project.toml and Manifest.toml files are writable

---

src/API.jl
src/GitTools.jl
src/REPLMode/REPLMode.jl
src/Types.jl
test/new.jl
test/repl.jl

each individual fix is only a handful of lines, mostly to do with error handling and input checking. They should all be uncontroversial, but I've kept the commits separate in case any of them need to be separated out.
- 4d0901e fix #1530
- 8a6387c close #1451
- 37b6853 fix #1255
- 53fdf24 fix #1471
- 0766765 fix #325
- 3f1cf40 fix #1065

a set of small fixes

---

src/API.jl
src/REPLMode/REPLMode.jl
src/REPLMode/command_declarations.jl
test/new.jl

Seems to be the consensus for #1518 
close #1518

Adjust GC delay and add `--all` flag to circumvent delay

---

src/utils.jl

See discussion here:
https://github.com/JuliaLang/julia/issues/33956

Fix `safe_realpath` for shared network drives

---

src/API.jl
src/Display.jl
src/Operations.jl
src/REPLMode/completions.jl
src/Types.jl
test/pkg.jl

more cleaning up that #1427 allows us to do

remove some unnecessary struct fields

---

src/Operations.jl

@omus, can you give this a try and see if it works for you?

fix Pkg.add of non-github URL (fix #1546)

---

Project.toml
src/Pkg.jl

Don't merge until after 1.4 branch.

make Pkg protocol opt-out instead of opt-in

---

src/API.jl
src/Operations.jl

it would definitely be good to have this in 1.4 since a lot of people are having version resolution issues now

hook up `develop` to `tiered_resolve`

---

src/versions.jl
test/pkg.jl

Don’t remove whitespace inside the string

---

src/API.jl
src/Artifacts.jl
src/Operations.jl
src/PlatformEngines.jl
src/Types.jl

This should add a progress bar (and some text about what is being downloaded) for #1554.

Force verbose downloads during `Pkg` operations

---

src/API.jl
src/Operations.jl

Adjust `Pkg.test` printing

---

src/Operations.jl
test/new.jl

not sure if I have permissions to push to the original branch

require handling

---

src/Operations.jl
src/Pkg.jl
src/Types.jl

From looking at PkgEval results: https://docs.google.com/spreadsheets/d/1ngalhKl9FEplWCWAWOfVKamZj-pkt4157pFGimb5wCw/edit#gid=609759912

Some more compat with 1.3

---

src/Pkg.jl

telemetryinfo: function to show what's sent

---

src/Artifacts.jl

use quiet_download when stderr is not a TTY

---

src/Pkg.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/1618.

fix precompile script

---

test/test_packages/BasicSandbox/deps/build.jl

fix package name in sandbox tests

---

src/Types.jl
test/new.jl

relax project file validation

---

src/Types.jl

Fixes #1622 and https://github.com/JuliaLang/Pkg.jl/issues/1622#issuecomment-577614170.

tweak the code for getting the registry from PkgServer

---

src/PlatformEngines.jl

We should probably just lazily to this on-demand but for now, let's give a correct error message.

fix error message for probing

---

src/GitTools.jl

cleaner error when interrupting git clone

---

src/Types.jl

The main fix here is to use TOML.print to generate the new content that is appended to the `manifest_usage.toml` log file, which should correctly escape the TOML key. I also moved the early exit test for the `source_file` not existing earlier so that we don't do any work in that case.

write_env_usage: use proper TOML writer (fix #1681)

---

src/Operations.jl

Should make it possible to unrevert https://github.com/JuliaLang/julia/pull/35294. Alternatively, we wait for https://github.com/JuliaLang/julia/pull/35324 and only conditionally add the color option.

update have color to new API

---

src/Types.jl

It has moved to the Resolve module.

Remove export of ResolverError from the Types module.

---

test/new.jl

Two merged PRs conflicted with eachother.

fix ci on master

---

src/Types.jl
test/runtests.jl
test/subdir.jl

Followup to #1422 and https://github.com/JuliaRegistries/RegistryTools.jl/pull/31 to read `subdir` information from registry.
Demo examples to follow after @DilumAluthge merges https://github.com/DilumAluthge/TestRegistry/pull/1. :-)

Get subdir from registry.

---

src/GitTools.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/1765

doc fix: tree_hash of empty directories

---

src/REPLMode/argument_parsers.jl
src/REPLMode/command_declarations.jl
src/Types.jl
test/subdir.jl

Support subdir from the REPL.

---

src/Operations.jl
src/REPLMode/command_declarations.jl

Update the printing of subdirs and add a compat notice.

Harmonize printing of subdir with REPL syntax.

---

src/API.jl
test/pkg.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/374

also clear out clones in gc

---

src/API.jl
src/REPLMode/argument_parsers.jl
src/Types.jl
src/utils.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/1650

Use non throwing isfile when checking if an active manifest exists

---

src/PlatformEngines.jl

This is the last piece of https://github.com/JuliaLang/julia/pull/35714

More invalidation-related fixes

---

ext/TOML/src/parser.jl

This comment scared me:
https://github.com/JuliaLang/julia/blob/ddf7ce9a595b0c84fbed1a42e8c987a9fdcddaac/base/compiler/params.jl#L20-L21

TOML: dont overload Base.error

---

src/REPLMode/completions.jl
test/repl.jl

Fix ~/nested/path expansion

---

src/Pkg.jl

This shaves off 0.6-1s of "time to first package install" (when it is a nop).

improve precompile execution

---

README.md

README: howto build Julia with git checkout of Pkg

---

docs/src/environments.md

@fonsp asked about how environments stack on #helpdesk in Slack today, and I couldn't find the relevant docs here. He later found it in the code loading section, and I thought maybe it deserved a link from here.

Add link to code loading section of the Julia manual

---

src/Pkg.jl
src/PlatformEngines.jl

Co-authored-by: Kristoffer Carlsson <kcarlsson89@gmail.com>

remove telemetry; do not send client UUIDs

---

src/Operations.jl
test/new.jl
test/utils.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/1907.

fix path returned from find_installed

---

src/Operations.jl
test/new.jl

Make build errors fatal

---

src/API.jl

make Pkg.precompile fatal

---

src/API.jl

This adds another object that must be GC'ed by `Pkg`; scratch spaces.
This commit implements the garbage collection side of https://github.com/JuliaLang/julia/pull/36966

Add Scratch space awareness to `Pkg.gc()`

---

src/API.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/1939.
cc @simonbyrne

try instantiate without updating the registry

---

src/Operations.jl
test/new.jl

Fixes: https://github.com/JuliaLang/Pkg.jl/issues/1778

add project to manifest in case a package depends on it, so that manifest is always complete

---

.travis.yml
src/API.jl
src/Operations.jl
src/PlatformEngines.jl
test/new.jl

Also needs https://github.com/JuliaLang/Pkg.jl/pull/1958

Backports release 1.5

---

src/API.jl

Packages could do things like take away write permissions for the
current user on a directory, causing `Pkg.gc()` to no longer be able to
delete files within that directory.  When deleting things from within
`Pkg.gc()`, let's first normalize the permissions of all directories,
and then empty them out.

[GC]: Fix permissions before attempting deletion

---

src/Types.jl

https://github.com/JuliaLang/Pkg.jl/pull/1981#issuecomment-679938217

Remove unused internal method of clone_registries.

---

src/BinaryPlatforms.jl
test/binaryplatforms.jl

(cherry picked from commit 69cbb81f138445a21a0559ff0d80c81105bfbf11, PR #1809)

Backport MacOS aarch64 platform support

---

src/Pkg.jl
src/PlatformEngines.jl

Closes https://github.com/JuliaLang/Pkg.jl/issues/1902
Closes https://github.com/JuliaLang/Pkg.jl/issues/1901
Closes https://github.com/JuliaLang/Pkg.jl/issues/1900
Closes https://github.com/JuliaLang/Pkg.jl/issues/1899

1.6: remove telemetry; do not send client UUIDs (#1909)

---

src/Operations.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/2051

fix error in status printing when a package goes from non-stdlib -> stdlib and vice versa

---

docs/src/api.md

Fixes https://github.com/JuliaLang/Pkg.jl/issues/2073

remove two outdated docstrings

---

README.md

README: Fix the instructions for using the development version of Pkg.jl

---

src/Operations.jl

Was silently wrong..
Fixes #2077

Fix unsuspending precomp errored pkgs

---

src/API.jl

Thanks to @mirage10 for the (hilarious) stress test in #2105 where 3656 packages, 80% of the general registry, were added to a local environment and told to precompile...
It identified that circularity at lower levels wasn't caught properly (the parallel precomp process will deadlock on circular deps, so we have to skip them). 
i.e.
```
- dep1 -> dep2
- dep2 -> dep3
- dep3 -> dep2
```
This fixes that.
Users can still attempt to precompile such packages via standard code load, and if it's just a case of unused deps listed in Project.toml's, the warnings may prompt devs to fix them.
Fixes #2105

Precompilation: Check for circularity in deps at any depth (fix #2105)

---

src/versions.jl
test/pkg.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/2119

restore parsing of VersionSpecs with v prefix

---

Project.toml
src/Operations.jl
src/PlatformEngines.jl
test/artifacts.jl
test/platformengines.jl

PlatformEngines: replace ad hoc stuff with Downloads & Tar stdlibs

---

src/GitTools.jl
src/Operations.jl
src/utils.jl

Moar progress bars:
https://asciinema.org/a/7yDATKSf7Uo2OO7MMe8swb0P1

show a progress bar for downloads and build

---

src/API.jl

This is a tweak PR into #2128 
@KristofferC the process of figuring out which packages is quick enough for us to just update the progress bar max on the fly. In my testing it happens before the first print is even done, so this works
Note the progress bar is 26/26 rather than 346/346
```
(@v1.6) pkg> precompile
Progress [========================================>]  26/26
✗ CUDA
✗ Flux
24 dependencies successfully precompiled, 2 errored (320 already precompiled)
ERROR: The following direct dependency failed to precompile:
Flux [587475ba-b771-5e3f-ad9e-33799f191a9c]
```

Precomp progress bar: hide already precomped in count (merge into PR #2128)

---

docs/src/managing-packages.md

Add an example for the SSH-based git protocol.

---

src/API.jl
test/api.jl

Should fix the breakage on nightly. https://travis-ci.com/github/JuliaLang/PackageCompiler.jl/jobs/402537410#L551
~Going to add a test.~

prevent bad kwargs from being forwarded to precompile

---

src/Artifacts.jl
src/PlatformEngines.jl

The original PR got lost somehow..

add back the progress bar to Artifact download

---

src/Types.jl

At least I think so... CI will tell.

remove unused Artifact struct

---

src/PlatformEngines.jl

Let's see if the nightlies are new enough for this...

PlatformEngines: use new download progress API

---

src/PlatformEngines.jl

Replacement for https://github.com/JuliaLang/Pkg.jl/pull/2198 and https://github.com/JuliaLang/Pkg.jl/pull/2204.

Allow `7z` selection to pick something up off of the PATH

---

src/Operations.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/2201
Could you try this @fredrikekre

fix default value in registry_info

---

src/API.jl

Reverts JuliaLang/Pkg.jl#2197
I just want to make sure that CI is green on this PR, to confirm that we're not missing something.

Revert "Don't do autoprecomp after Pkg.dev"

---

src/API.jl
test/api.jl

Fixes the test breakage introduced by #2197

Fix autoprecomp test by adding build after develop

---

src/PlatformEngines.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/2213

check for fancy print availability in Platformengines

---

src/API.jl
src/RegistryHandling.jl
src/Types.jl
src/manifest.jl
src/project.jl

Edit: This won't work right now since we mutate the dictionary that we cache... Ugh.

use the TOML invalidation mechanism in Base in more places in Pkg

---

src/Pkg.jl
src/REPLMode/command_declarations.jl

document activate --temp

---

src/Operations.jl
src/Types.jl
test/new.jl

[release-1.6] Align all status printing

---

src/API.jl
src/Operations.jl
src/Pkg.jl

release-1.6 version of https://github.com/JuliaLang/Pkg.jl/pull/2335

[release-1.6] Precompile: Add precomp to Pkg.test

---

src/Registry/Registry.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/2350

Fix reference to PkgError (fixes #2350)

---

src/API.jl
src/Operations.jl
src/Types.jl

- https://github.com/JuliaLang/Pkg.jl/pull/2345
- https://github.com/JuliaLang/Pkg.jl/pull/2338
@staticfloat Do these look right?

[release-1.6] backports

---

src/Operations.jl
test/new.jl

Add test for #2302

---

src/Pkg.jl

Disable autoprecomp if --compiled-modules=no

---

src/REPLMode/command_declarations.jl

Add ``` `--` ``` before ``` `manifest` mode``` to make it have the same meaning in context.

Improve the `update`(REPLMode) document.

---

ext/HistoricaStdlibGenerator/generate_historical_stdlibs.jl
src/HistoricalStdlibs.jl
src/PlatformEngines.jl
test/misc.jl
test/runtests.jl

Not sure about the new "misc.jl" test file, happy to accept suggestions.

Fix invalidations from LatexStrings and PyPlot

---

ext/HistoricaStdlibGenerator/generate_historical_stdlibs.jl
src/API.jl
src/HistoricalStdlibs.jl
src/Operations.jl
src/Pkg.jl
src/PlatformEngines.jl
src/Types.jl
test/misc.jl
test/new.jl
test/runtests.jl

- Add test for #2302 (https://github.com/JuliaLang/Pkg.jl/pull/2352)

[release-1.6] more backport

---

src/API.jl
src/Artifacts.jl
src/Operations.jl
src/PlatformEngines.jl
src/Registry/Registry.jl
test/new.jl

I'm separating this out of #2355 given in that PR I also tried to fix the way download logging is done, which seems to need further thought.
Makes downloads respect the `io` kwarg
```
julia> Pkg.add("Images", io=devnull)
julia> 
```
Fixes #2328

Make downloads respect IO

---

src/API.jl

This adds an environment-specific memory between sessions for packages that need precompilation but couldn't be updated due to being loaded. i.e. those marked as `?`
As described in #2361, the cache invalidation heuristics in base only work for dependents if the dependencies that have changed are loaded, which isn't the case during the `Pkg.precompile` checks, so this memory is needed.
If they succeed or error, they're removed from this new memory, except for if a `?` error occurs again
Fixes https://github.com/JuliaLang/Pkg.jl/issues/2361
```
pkg> add Plots, GR
... # add and fully precompile packages
julia> using Plots
pkg> pin GR@0.52.0 # roll back GR
... # precomp will ? for Plots given it's loaded
```
restart julia
```
pkg> precompile
julia> using Plots
[ Info: Precompiling Plots …
```

Precompile: Remember packages that need precompilation to catch stale dependents

---

src/Pkg.jl

Fix Markdown table formatting

---

src/API.jl
src/Operations.jl
src/Types.jl
test/new.jl

Creating contexts is extra work compared to creating an EnvCache.

remove usage of ctx in status

---

src/MiniProgressBars.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/2436

make progressbar adapt to size of terminal

---

src/Operations.jl

Introduced in https://github.com/JuliaLang/Pkg.jl/pull/2434

fix typo in git_head_env

---

src/Operations.jl

Splitting this up doesn't really increase any clarity

merge two small functions

---

src/Operations.jl

Also, move `signal_name` to where it is used.
Slowly getting rid of these "vectorized" operations.

tweak load_urls to only take a PackageSpec

---

src/Operations.jl
test/new.jl
test/test_packages/CompatExtras/Project.toml

Fix #2419
I forgot to include extras when filtering compat :facepalm:

Do not unnecessarily remove entries from compat

---

README.md

Addressing a suggestion after https://github.com/JuliaLang/Pkg.jl/pull/2459 merged

Reorder readme items

---

docs/src/managing-packages.md

This is #1794.
I was trying to close/open the PR to rerun tests, but it seems the original branch is gone, so I reopened here.

(revive) add pinning commit message

---

src/REPLMode/command_declarations.jl

revived #2070 because it was orphaned and needed one more edit before merging

(revive) document that dev --local path is not supported

---

src/Operations.jl

This reverts commit 4045abd6a15966e2d6b584e1b85c1647affa834e.

Revert "get rid of an unnecessary function (#2443)"

---

src/API.jl

This is about those pesky yellow `?`'s
I believe the current behavior of `Base.compilecache` skipping precompilation of already loaded modules (what it internally refers to as `concrete_deps`) is because for the code-load precompilation path a different version of a package can't actually be loaded, so it decides to skip it and save the time, and precomp would be picked up in a future session.
During Pkg precomp however I don't believe there's any reason why it shouldn't be able to precompile other versions of loaded modules. After all, the precompilation takes place in a separate child session.
Along with https://github.com/JuliaLang/julia/pull/40345, this PR changes that behavior:
```
(jl_YqpHCO) pkg> add CSV
...
[336ed68f] + CSV v0.8.4
...
15 dependencies successfully precompiled in 10 …
```

Precompilation: Don't skip precompilation of different versions of loaded modules

---

docs/src/creating-packages.md

This provides a nice section where we can start to showcase some of the new capabilities in modern Julia versions for package authors.
Closes https://github.com/JuliaLang/Pkg.jl/issues/2478

Add "Best Practices" section to "Creating Packages"

---

src/MiniProgressBars.jl
src/Operations.jl

Ref https://github.com/JuliaLang/Pkg.jl/issues/1915

No longer specify "white" as a color for packages in status and in progress bar

---

src/Registry/Registry.jl

Fixes #2545 
for which the full stack was
```
julia> Pkg.Registry.add(Pkg.Registry.RegistrySpec(path = "/Users/ian/.julia/registries/General"))
Copying registry from `~/.julia/registries/General`
ERROR: IOError: mkdir("/tmp/testdepot/registries/General"; mode=0o777): no such file or directory (ENOENT)
Stacktrace:
[1] uv_error
@ ./libuv.jl:97 [inlined]
[2] mkdir(path::String; mode::UInt16)
@ Base.Filesystem ./file.jl:183
[3] mkdir
@ ./file.jl:176 [inlined]
[4] cptree(src::String, dst::String; force::Bool, follow_symlinks::Bool)
@ Base.Filesystem ./file.jl:335
[5] cp(src::String, dst::String; force::Bool, follow_symlinks::Bool)
@ Base.Filesystem ./file.jl:368
[6] (::Pkg.Registry.var"#27#28"{Base.TTY, String, Pkg.Registry.RegistrySpec})(tmp::String)
@ Pkg.Registry …
```

Make registry dir if missing. Fixes #2545

---

src/Pkg.jl

Closes https://github.com/JuliaLang/Pkg.jl/issues/1697 and https://github.com/JuliaLang/Pkg.jl/issues/1740

Converge `Pkg.gc` and `Pkg.API.gc` docs

---

.codecov.yml

xref https://docs.codecov.io/docs/github-checks#disabling-github-checks-patch-annotations-via-yaml

Turn off codecov annotations

---

src/Operations.jl

Fixes #2602 
If 1.7 is branched before I'm able to get this PR into Julia master, we'll need to backport this PR to 1.7.

Remove unnecessary manifest lookup in `apply_force_latest_compatible_version!`

---

src/manifest.jl

End both sentences in the message with a period.

Add a missing period.

---

src/Pkg.jl

Feel free to edit, merge or close without discussion

Docs: Link to Pkg.project and Pkg.dependencies from Pkg.status

---

src/Operations.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/2616

Automatically upgrade the sandbox manifest format when preserving

---

src/Operations.jl
src/manifest.jl

[release-1.7] 1.7 backports

---

src/REPLMode/REPLMode.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/2630

Cancel pkg install prompt when ^D is entered

---

src/Operations.jl
src/Types.jl
test/new.jl
test/resolve.jl

Revert "release1.7: Revert "Enable installation of versioned historical stdlibs (#2614)""

---

src/Operations.jl
src/Types.jl
test/new.jl
test/resolve.jl

This reverts commit 092703e63641b074de66f02c27d6380fe5e57465.
Let's try this again...

release-1.7: Revert "Enable installation of versioned historical stdlibs (#2614)" take two

---

docs/src/registries.md

with pointers to Registrator, LocalRegistry, and RegistryCI

[docs] add "Creating and maintaining registries"

---

src/API.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/2657
```
Activating new project at `/var/folders/_6/1yf6sj0950vcg4t91m9ltb5w0000gn/T/jl_HuSQWs`
(jl_HuSQWs) pkg> precompile
No Changes to `/private/var/folders/_6/1yf6sj0950vcg4t91m9ltb5w0000gn/T/jl_HuSQWs/Project.toml`
No Changes to `/private/var/folders/_6/1yf6sj0950vcg4t91m9ltb5w0000gn/T/jl_HuSQWs/Manifest.toml`
```

During instantiate don't update the registry if there are no env deps

---

docs/src/getting-started.md

docs: typo warn -> warning

---

src/Registry/Registry.jl

Got broken in https://github.com/JuliaLang/Pkg.jl/pull/2674

fix registry status command after removal of url field

---

docs/src/registries.md

Mention General registry may not be added automatically

---

CHANGELOG.md
src/API.jl
src/Operations.jl
src/Pkg.jl
src/REPLMode/REPLMode.jl
src/REPLMode/command_declarations.jl
test/new.jl

wip: --outdated flag to status

---

docs/src/managing-packages.md

This is introduced by #1783 and we don't have documentation for it.
cc: @GunnarFarneback

add missing subdir instruction

---

src/Registry/Registry.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/2726

fix a typo trying to return a variable that does not exist

---

src/API.jl
src/Pkg.jl
test/manifests.jl

Makes the `upgrade_manifest` tool a bit more useful

Add `upgrade_manifest(manifest_path::String)` for updating explicit manifests

---

src/Pkg.jl

I tried running this with internet turned off and I did not get any warnings. Can anyone confirm? Fixes JuliaLang/julia#43006

prevent internet access during precompile script

---

src/Operations.jl
src/Registry/Registry.jl

This reverts commit d0d3ff344f7f1219ccd2e0324b21af7232ab7194.
https://github.com/JuliaLang/Pkg.jl/pull/2841 is a better fix

Revert "Cache pkg_server_registry_info (#2827)"

---

.gitignore
test/runtests.jl

I guess this was missed in https://github.com/JuliaLang/Pkg.jl/pull/2803/?

remove cleaning up locally cached registry

---

src/API.jl

Closes #2850 
@KristofferC does this look right?

use Base.LOADING_CACHE during Pkg.precompile for stale checks

---

README.md

I believe people will need to make a fork

Update README.md to tell users to make a fork

---

src/API.jl
src/Pkg.jl
src/REPLMode/REPLMode.jl
src/generate.jl

- https://github.com/JuliaLang/Pkg.jl/pull/2870
- https://github.com/JuliaLang/Pkg.jl/pull/2865
- https://github.com/JuliaLang/Pkg.jl/pull/2884
- https://github.com/JuliaLang/Pkg.jl/pull/2816

[release-1.7] Backports

---

src/Types.jl

This reverts commit ebac45fdb43621a3009bd5cf09ee1f53d8b3122f.
This causes issues and might as well revert it until the PID thing is in place

Revert "Make `write_env_usage` atomic (#2661)"

---

src/REPLMode/REPLMode.jl
test/repl.jl

@KristofferC perhaps this is a better fix for https://github.com/JuliaLang/julia/issues/43440 than https://github.com/JuliaLang/julia/pull/43449

Don't return "julia" as an available missing package

---

src/manifest.jl

The suggestion was made to add actionable help on how to populate the julia version here.

Expand manifest warning message

---

src/Types.jl

Closes: https://github.com/JuliaLang/Pkg.jl/issues/2528 
Do I also need to update: https://github.com/JuliaLang/Pkg.jl/blob/b963d05a89cfacaa0fe57752de5f3fb439ccfa43/src/Operations.jl#L203 ?

Update error message to specify project.toml file

---

src/REPLMode/command_declarations.jl
test/repl.jl

Following https://github.com/JuliaLang/Pkg.jl/issues/2868

Add more examples to docs for `pkg> add`

---

src/API.jl
src/GitTools.jl
src/Operations.jl
src/REPLMode/REPLMode.jl
src/Resolve/Resolve.jl
src/Resolve/graphtype.jl
src/manifest.jl
src/utils.jl
test/api.jl
test/misc.jl
test/runtests.jl
test/utils.jl

Trying to help with https://github.com/JuliaLang/Pkg.jl/issues/1097
Fixes #1097

Reduce noise of test suite

---

src/API.jl
src/Operations.jl
test/new.jl

As pointed out in https://github.com/JuliaLang/Pkg.jl/pull/2432#issuecomment-1010301919

Make `free --all` not error if some are free already

---

src/Operations.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/2967

fix st --outdated for packages that are ahead of last version in registry

---

test/new.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/2960, fixes https://github.com/JuliaLang/Pkg.jl/issues/1994

use samefile instead of checking exact path representation

---

test/artifacts.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/2959

better isolate some of the artifacts tests

---

src/Registry/Registry.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/2421

remove incorrect signature for `Registry.add`

---

src/BinaryPlatforms_compat.jl
src/Types.jl

These trigger warnings in Julia's `test/ambiguous.jl`.

Remove stale exports

---

src/Operations.jl

Fix #2989 
Closes #2991 
cc. @fingolfin

Don't warn if showing manifest and outdated indirect deps are hidden

---

src/Types.jl

Paired with https://github.com/JuliaLang/julia/pull/44286

Handle custom manifest name

---

src/Operations.jl

Remove stdin forwarding from Pkg.test

---

src/Operations.jl
test/artifacts.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/2979

ensure that artifacts are installed in e.g. `instantiate` for projects that are not packages

---

CHANGELOG.md
src/REPLMode/argument_parsers.jl
test/new.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/1861

pattern match in Pkg REPL for github branch URL

---

src/Registry/Registry.jl
test/registry.jl

Fxes https://github.com/JuliaLang/Pkg.jl/issues/2915
cc @mkitti

only remove registries from first entry in `DEPOT_PATH`

---

src/Operations.jl

@KristofferC this addresses point 2 in https://github.com/JuliaLang/Pkg.jl/issues/2989#issuecomment-1145753994

Hide usage tips during Pkg.test status prints

---

docs/src/managing-packages.md

This is for Chapter 3 only. I am in the process of reading various manual chapters in my free time, and will submit more changes as I discover them.
New Julia user here, and I must say I am overall very pleased with the documentation. This is hopefully my first of many contributions.

Correct minor spelling and grammatical errors

---

src/Pkg.jl

Because I was looking for registry dependency graphs and this isn't that.

Clarify dependencies() docstring

---

src/Resolve/graphtype.jl

I noticed this appears to be unused

Remove dead code in Graph constructor

---

src/Registry/Registry.jl

Enhance error message when `url` and `path` is set.

Enhance error message

---

docs/src/compatibility.md

This command can be used from Julia version 1.8 onwards....

Mention the command 'compat'

---

src/API.jl
src/MiniProgressBars.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/2502

fix progressbar width when precompiling

---

src/Operations.jl

Tiniest of nits, inspired by https://github.com/JuliaLang/julia/pull/46828.

typeassert on get(io, ...)

---

CHANGELOG.md
docs/src/artifacts.md
docs/src/compatibility.md
docs/src/creating-packages.md
docs/src/glossary.md
docs/src/managing-packages.md

Fix some typos in docs

---

docs/make.jl
docs/src/api.md
docs/src/artifacts.md
docs/src/compatibility.md
docs/src/creating-packages.md
docs/src/environments.md
docs/src/faq.md
docs/src/getting-started.md
docs/src/glossary.md
docs/src/index.md
docs/src/managing-packages.md
docs/src/registries.md
docs/src/toml-files.md
src/API.jl
src/Artifacts.jl
src/Pkg.jl
src/REPLMode/command_declarations.jl
src/Registry/Registry.jl

I went through the documentation and did some updated:
- Removed pre 1.6 compat annotations
- Went through the examples and updated them so that the output corresponds to how it looks on 1.8.
- Restructured and moved a few things around to places where I thought it made more sense.
- A bit of grammar fixups
I still need to do a final read through of the changes here.

refresh some of the documentation

---

.github/workflows/test.yml
src/PlatformEngines.jl
src/Registry/Registry.jl
test/runtests.jl
test/utils.jl

Trying to fix #3238 
cc. @StefanKarpinski

Allow retries for registry git clone & `download_verify` to make CI more robust

---

test/sandbox.jl

Fix failures in https://github.com/JuliaLang/julia/pull/47463

add sandbox manual install for HistoricalStdlibVersions

---

test/runtests.jl
test/sandbox.jl

Reverts #3252 
Makes the check earlier

Check install for HistoricalStdlibVersions earlier

---

src/REPLMode/REPLMode.jl
test/new.jl

fix precompiling list of packages with commas

---

src/API.jl
src/Operations.jl
src/Types.jl
test/project_manifest.jl
test/runtests.jl
test/test_packages/monorepo/Project.toml
test/test_packages/monorepo/packages/B/Project.toml
test/test_packages/monorepo/packages/B/src/B.jl
test/test_packages/monorepo/packages/C/Project.toml
test/test_packages/monorepo/packages/C/src/C.jl
test/test_packages/monorepo/packages/C/test/runtests.jl
test/test_packages/monorepo/packages/D/Project.toml
test/test_packages/monorepo/packages/D/src/D.jl
test/test_packages/monorepo/src/A.jl
test/test_packages/monorepo/test/runtests.jl

Backport PR #3303 ("Respect manifest if provided in Project.toml") to Julia 1.9

---

Project.toml
src/REPLMode/REPLMode.jl
test/repl.jl

Closes JuliaLang/julia#48115 .

truncate long prompt

---

src/API.jl
src/Pkg.jl
test/api.jl

Fixes #3321 by making it behave like the other api functions
I guess this should've been done in https://github.com/JuliaLang/Pkg.jl/pull/2724

Make precompile use the API harness

---

src/API.jl

Helps https://github.com/JuliaLang/julia/issues/48371

precompile: show stderr warnings when process is interrupted

---

src/API.jl

fix `stale_cache` calculation

---

src/API.jl

fixup! #3353, recover `_is_stale!` logic

---

src/API.jl
test/api.jl

Proposal to help with https://github.com/JuliaLang/julia/issues/48506
In non-fancyprint mode, i.e. in CI, if the trailing task warning happens it will warn then start printing stderr in realtime to allow the user to see why it's hanging and cancel the job.
cc. @LilithHafner @timholy

precompile: warn if waiting on trailing task

---

test/api.jl
test/test_packages/RecurringPrecompile/Manifest.toml
test/test_packages/RecurringPrecompile/Project.toml

Adds test for https://github.com/JuliaLang/Pkg.jl/issues/3355
Should have been fixed by #3359 so I've temporarily reverted that commit to check tests fail
cc. @aviatesk

add test for recurring precompile

---

ext/LazilyInitializedFields/LazilyInitializedFields.jl

- use `isexpr` to tidy up branch conditions
- remove unnecessary `@pure` annotation
- add type annotation on `in_lazy_struct`

minor code quality improvements on `LazilyInitializedFields`

---

test/new.jl

@KristofferC a test proposal for https://github.com/JuliaLang/Pkg.jl/pull/3371
I think the correct answer is that in some of these later strategies, the jll version should be updated, so I think this needs changes

add test for JLL build no. fix PR

---

src/API.jl
test/api.jl

add missing autoprecomp to Project instantiate path

---

src/API.jl
src/Pkg.jl
test/extensions.jl

Ref. https://github.com/JuliaLang/julia/pull/49242

Precompile: pass precompile to new Base loading hook

---

src/Pkg.jl

See https://github.com/JuliaLang/julia/pull/49304

Always set Base.PKG_PRECOMPILE_HOOK

---

src/API.jl

Fixes if `Pkg.precompile` during code load precompilation is called for a package that's only in another environment in the stack.
Otherwise:
```
(@v1.10) pkg> st
Status `~/.julia/environments/v1.10/Project.toml`
[336ed68f] CSV v0.10.9
(@v1.10) pkg> activate --temp
Activating new project at `/var/folders/_6/1yf6sj0950vcg4t91m9ltb5w0000gn/T/jl_suKAP4`
julia> using CSV
ERROR: No direct dependencies outside of the sysimage found matching ["CSV"]
julia>
```

precompile: fix code load precomp of dep in other env stack

---

src/API.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/3448
@gzagatti

fix color_string

---

src/Operations.jl
src/Pkg.jl
test/pkg.jl

Fix https://github.com/JuliaLang/Pkg.jl/issues/3147.

keep `path` & `repo` when `pinned`

---

src/API.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/3443

precompile: fix race in precompiling exts

---

src/API.jl

This reverts commit c8249204b52708c916ff9a4752b04386c28de46b.
Given https://github.com/JuliaLang/Pkg.jl/issues/3461

Revert "precompile: fix race in precompiling exts (#3456)"

---

src/Pkg.jl

from the docstring of PackageSpec

remove double backquote

---

src/API.jl

Closes https://github.com/JuliaLang/Pkg.jl/pull/3486

[release-1.9] Reland "precompile: fix race in precompiling exts (#3456)" (#3465)

---

src/API.jl

This reverts commit c3b9d3ee16a7e75aa0470dfba8f95931338a0cd0.
Caused by confusion due to 1.9.1 not actually having #3465
The circ dep detection problems seen on backport-release-1.9 aren't seen on master with #3465

Revert "Revert "Reland "precompile: fix race in precompiling exts (#3456)" (#3465)" (#3485)"

---

src/Operations.jl

Fixes https://github.com/JuliaLang/julia/issues/50001

force run artifact selection hooks with one thread

---

src/Types.jl
test/pkg.jl

Fixes #3491
A more general fix that could also be done is https://github.com/JuliaLang/Pkg.jl/pull/3454

handle if a usage file is missing a "time" entry

---

src/Operations.jl
src/Pkg.jl
src/REPLMode/command_declarations.jl
src/Types.jl
test/pkg.jl

- #3492 
- #3501 
- #3502 
- #3148 
- #3302 
- #3492

[release-1.9] 1.9 backports

---

test/runtests.jl

Ref https://github.com/JuliaLang/julia/issues/50055

Test suite: activate a temp project if we need to install HistoricalStdlibVersions during the test suite

---

src/API.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/3516

sort compat entries in `pkg> compat`

---

src/Operations.jl

Fixes bug reported at https://github.com/JuliaLang/Pkg.jl/pull/3606#issuecomment-1716727635
Verified with a julia build pointing at this commit

fix active project of test precompilation

---

src/API.jl
src/MiniProgressBars.jl

[release-1.9] Backports 1.9

---

src/Pkg.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/3632

Make auto GC message use printpkgstyle

---

test/new.jl

See https://github.com/JuliaRegistries/General/pull/93526

Pin registry for MetaGraph tests

---

src/API.jl

See https://github.com/JuliaLang/julia/pull/51714
Needs to wait for https://github.com/JuliaLang/julia/pull/51714

cache pidlock tweaks

---

src/Operations.jl

Stop manually propagate flags that julia_cmd will propagate

---

src/Operations.jl

Fixes https://github.com/JuliaLang/julia/issues/51820

add Pkg to test env as a dep rather than via LOAD_PATH

---

src/API.jl

Otherwise it gives the impression it's another process

Precompile: Highlight when the lock is held by the same process

---

src/API.jl

I think I'm seeing a case where Pkg.precompile is slow to start (50s) on CI on nightly, so this adds some debug logs to highlight when steps are done.

Add debug logs for Pkg.precompile timing

---

src/precompile.jl

Fix #3691 for real
We probably should also create a test

Only precompile Pkg.jl when generating output

---

src/precompile.jl
test/repl.jl
test/runtests.jl
test/subdir.jl

fix non-reverting cd's

---

src/Pkg.jl

Added accidentally in https://github.com/JuliaLang/Pkg.jl/pull/3378

rm incorrect kwargs in add docstring

---

src/API.jl
test/api.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/3739

respect --color=no in Pkg.precompile

---

src/Types.jl

Noticed while working on something else.

remove an unused argument from `resolve_projectfile!`

---

test/artifacts.jl

@staticfloat could this be why we're seeing https://github.com/JuliaLang/julia/issues/52679
More discussion here https://github.com/JuliaLang/julia/pull/52899

Reset overrides after artifact tests

---

src/Artifacts.jl
test/artifacts.jl

[release-1.10] 1.10 backports

---

src/Types.jl
src/project.jl

Code loading has support for this so Pkg should too
https://github.com/JuliaLang/julia/blob/c5d7b87a35b5beaef9d4d3aa53c0a2686f3445b9/base/loading.jl#L722-L725

support the "path" key in Project.toml,

---

Project.toml
ext/REPLExt/REPLExt.jl
ext/REPLExt/compat.jl
ext/REPLExt/completions.jl
ext/REPLExt/precompile.jl
src/API.jl
src/Operations.jl
src/Pkg.jl
src/REPLMode/REPLMode.jl
src/REPLMode/command_declarations.jl
src/Registry/Registry.jl
src/Types.jl
src/fuzzysorting.jl
src/precompile.jl
test/repl.jl
test/runtests.jl

Made on top of #3776
cc @mkitti, thoughts about this? I used your PR as a base but moved less stuff over to the extension to allow `pkgstr` to still work.
Co-authored-by: Mark Kittisopikul

make the REPL specific code into an extension 

---

src/REPLMode/REPLMode.jl
test/runtests.jl

Will make https://github.com/JuliaLang/Pkg.jl/pull/3724 easier.

make `pkgstr` independent of REPL

---

docs/src/toml-files.md

Documenting JuliaLang/Julia#43845
I don't know if its already in the docs somewhere, this is where i expected to find it.
And when I didn't I had to go look at the News.md

Explain about Manifest.toml per julia version

---

src/API.jl

Requires https://github.com/JuliaLang/julia/pull/53456

tidy up delayed_delete_dir during Pkg.gc

---

src/Operations.jl

Fixes https://github.com/JuliaLang/julia/issues/53473

do not use UnstableIO for subprocess (in e.g. Pkg.test)

---

src/precompile.jl

re-enable Pkg precompilation

---

src/Types.jl

Left over from https://github.com/JuliaLang/Pkg.jl/pull/3820

remove unused PkgPrecompileError type

---

docs/generate.jl
docs/make.jl
docs/src/api.md
docs/src/artifacts.md
docs/src/basedocs.md
docs/src/compatibility.md
docs/src/creating-packages.md
docs/src/glossary.md
docs/src/registries.md
docs/src/toml-files.md

Reverts JuliaLang/Pkg.jl#3690
See: https://github.com/JuliaLang/julia/pull/53509

Revert "Move "Creating Packages" to Julia docs"

---

docs/src/creating-packages.md

This PR fixes the following missing section number.

Add missing section number `**5.**`

---

ext/REPLExt/precompile.jl

Minor precompiles but should help snappiness
Based on https://github.com/JuliaLang/julia/pull/54594

Precompile the pkg tab completion hint

---

ext/REPLExt/REPLExt.jl
ext/REPLExt/completions.jl
src/REPLMode/command_declarations.jl

the result of hint auto complete is only used if a unique entry is returned
fixes #3909

abort querying more packages for hint auto complete

---

src/REPLMode/command_declarations.jl

my usual workflow is not documented well.  this PR fixes that, borrowing text from the REPL docstring.

update docs for test in pkg mode

---

ext/REPLExt/REPLExt.jl
ext/REPLExt/completions.jl
src/REPLMode/command_declarations.jl
src/Registry/registry_instance.jl
src/Types.jl

Backports release-1.11

---

src/Types.jl

Hoping to address https://github.com/JuliaLang/Pkg.jl/issues/2875
Assumes something's going wrong in the writing of the file.
Fixes https://github.com/JuliaLang/Pkg.jl/issues/2875

check parse before moving usage file into place

---

src/Pkg.jl

Fix codeblock language and prompt in Pkg.status() docstring

---

src/Operations.jl

Seen on https://github.com/JuliaLang/Pkg.jl/pull/3965
Followup to https://github.com/JuliaLang/Pkg.jl/pull/3851

check `project_file` isa String

---

src/Operations.jl

[release-1.11] Backports 1.11

---

.github/workflows/test.yml
test/artifacts.jl
test/utils.jl

Found fixing https://github.com/JuliaLang/Pkg.jl/pull/3807 but thought these should be separate

Test fixes

---

.github/workflows/test.yml
src/PlatformEngines.jl
src/Registry/Registry.jl
test/new.jl

[release-1.10] Backports 1.10

---

src/Operations.jl

Reverts JuliaLang/Pkg.jl#3982
This caused a scary failure mode where a devved package seems to not actually be the one getting used when testing stuff:
```
(1.10dev) pkg> st
Status `~/PkgEval/1.10dev/Project.toml`
[31c24e10] Distributions v0.25.110
[b5a8929a] RiskMeasures v0.4.0 `~/.julia/dev/RiskMeasures`
(1.10dev) pkg> test RiskMeasures
Testing RiskMeasures
Status `/tmp/jl_wsLGsE/Project.toml`
⌃ [31c24e10] Distributions v0.25.104
⌃ [b5a8929a] RiskMeasures v0.3.0
```
Note how RiskMeasures is devved but we use RiskMeasures 0.3.0 anyway in the testing.
A new 1.10 needs to go out soon so I will just revert this but we should look more into what is going on here (and add a test for it).

Revert "Backport #3276 to 1.10"

---

src/MiniProgressBars.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/3992.
Fixes https://github.com/JuliaLang/Pkg.jl/issues/3581
Sigh.

fix flickering of progress bar on package installation

---

src/MiniProgressBars.jl

See https://github.com/JuliaLang/julia/pull/55588#discussion_r1736101435

fix double space before progress bar

---

src/REPLMode/REPLMode.jl
test/repl.jl

In line with how e.g. `]add` works.

Allow comma separated packages for ]dev

---

src/REPLMode/command_declarations.jl
test/new.jl

fix precompiling packages specifically

---

ext/REPLExt/REPLExt.jl

Fixes https://github.com/JuliaLang/julia/issues/56003
Counterpart to https://github.com/JuliaLang/julia/pull/56251

REPLExt: run repl hint generation for modeswitch chars when not switching

---

ext/REPLExt/completions.jl

Fixes https://github.com/JuliaLang/julia/issues/56171
Fixes https://github.com/JuliaLang/julia/issues/56037

REPLExt: use Base.isaccessibledir rather than isdir in completions

---

src/MiniProgressBars.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/4046
Dark example #3 in https://github.com/JuliaLang/Pkg.jl/issues/4046#issuecomment-2409752191.

do not show right hand progress without colors

---

test/artifacts.jl

1.11 backports

---

docs/src/getting-started.md

Just fixing a typo. Nothing more.

Remove duplicated word "different"

---

src/precompilation.jl

Backport of https://github.com/JuliaLang/julia/pull/56905

[release-1.10] Remove bad CI env var check

---

src/GitTools.jl

Just an observation. I'm not aware of any issues this caused

Don't set up LibGit2 callbacks if using cli git

---

test/runtests.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/4154

tests: make sure we're in an active project and that it's clean

---

test/new.jl

See errors in https://github.com/JuliaLang/julia/pull/57601

Test fix: handle if tested Pkg is shipped version

---

src/Operations.jl

Fixes issue reported here https://github.com/JuliaLang/Pkg.jl/pull/4180#issuecomment-2715408525
cc. @maleadt

Store temp packages in packages/temp

---

docs/src/toml-files.md

allow authors to be a TOML array

---

test/new.jl

Provide more info to try and figure out https://buildkite.com/organizations/julialang/analytics/suites/julialang-base/tests/08330e30-d0e2-818a-b943-5bb73de92b14?period=7days&tags=scm.branch%3Amaster#flaky

help debug freebsd test failure

---

src/Operations.jl

just some random things I saw when looking at something

some small `Box` removals from `download_artifacts` code

---

src/Types.jl
test/subdir.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/4269
This PR was written by a human 👨

fix what project file to look at when package without path but with a subdir is devved by name

---

src/Apps/Apps.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/4273

copy the app project instead of wrapping it

---

src/Operations.jl
test/pkg.jl

Closes https://github.com/JuliaLang/Pkg.jl/issues/2191
Closes https://github.com/JuliaLang/Pkg.jl/issues/3523

Add more info when package is missing

---

CHANGELOG.md
ext/REPLExt/REPLExt.jl
ext/REPLExt/compat.jl
src/API.jl
src/REPLMode/command_declarations.jl
test/new.jl

Edit: Renamed to `compat --current`
---
Closes https://github.com/JuliaLang/Pkg.jl/issues/3260
cc. @cossio @ericphanson

add `pkg> compat --current` mode

---

src/Registry/Registry.jl

Update registry update log also when adding a registry by copying or symlinking.
Followup to https://github.com/JuliaLang/Pkg.jl/pull/4300#issuecomment-3050109479.

Fix registry status test

---

src/REPLMode/argument_parsers.jl
test/new.jl

Fixes https://github.com/JuliaLang/Pkg.jl/issues/4323

fix parsing of multiple packages with modifiers on some of them

---

.github/workflows/test.yml
ext/REPLExt/REPLExt.jl
ext/REPLExt/compat.jl

Actually avoid depwarn, and enable --depwarn=error in CI

---

docs/src/api.md
docs/src/toml-files.md
src/API.jl
src/Operations.jl
src/Pkg.jl
src/Types.jl
src/project.jl
test/new.jl

fixes https://github.com/JuliaLang/Pkg.jl/issues/4041

also check `readonly` from entry point Pkg commands (e.g. `Pkg.add`) and also add an API to enable/disable it

---

src/Operations.jl
test/api.jl

@giordano I believe this should fix the lbt_jll issue building for 1.13 on https://github.com/JuliaPackaging/Yggdrasil/pull/12226

Make julia compat checking respect julia_version
