JuliaLang/Pkg.jl

- src/API.jl
- src/Operations.jl
This gives users a way to guarantee that the package versions in their `Manifest.toml` file are exactly the package versions that will be used during `Pkg.test`.
This is not public and therefore is not documented.
> Add the ability to disable re-resolving during `Pkg.test`

- src/project.jl
In the Pkg.jl codebase, `pkgerror(message)` is a more idiomatic way of throwing exceptions.
> Replace `throw(ErrorException(message))` with `pkgerror(message)`

- src/Pkg.jl
- src/REPLMode/REPLMode.jl
- test/repl.jl
Paired with https://github.com/JuliaLang/julia/pull/39026
Adds hooks into REPL to prompt to install packages if missing, and available in registry
> Add REPL hook to prompt to install missing packages, if available in registry

- src/REPLMode/REPLMode.jl
- test/repl.jl
This typo slipped into #2307 :/ 
It would be nice to be able to test  more of the prompt by passing `y/n` into stdin, but I don't know how to do that in CI.
> Fix module reference typo in #2307

- src/Artifacts.jl
I don't think there's a good way currently to identify which errors the artifact downloads should report/throw, so this is a stop-gap to allow debugging errors in the wild.
> add `@debug` logs for artifact download failures

- docs/src/toml-files.md
I think we should update this (old?) falsely restrictive information.
I realized this while reading the documentation for another detail, knowing that some personal project names are not limited to ASCII (see this [old error](https://github.com/JuliaLang/Pkg.jl/issues/1846)).
> Small documentation update for valid package/project names.

- src/API.jl
- src/Pkg.jl
- src/REPLMode/command_declarations.jl
Fixes https://github.com/JuliaLang/Pkg.jl/issues/2404
Note that users can still override this via setting `ENV["JULIA_NUM_PRECOMPILE_TASKS"]`
> Precompilation: Limit the default number of tasks to 16

- src/Pkg.jl
These two docstrings are right next to each other in the manual. However, if you are just looking at the `Pkg.add` docstring in the REPL (e.g. `?Pkg.add`), you won't see any mention of `Pkg.develop`. This PR fixes that.
The motivation is as follows: sometimes, users will try to `Pkg.add` a path that is not a Git repo. This throws an error. The solution is to instead `Pkg.develop` the desired path. However, currently, the `Pkg.add` docstring does not mention `Pkg.develop`.
> Docstrings: add references from `Pkg.add` to `Pkg.develop` and vice versa

- test/new.jl
In this particular test set, for a given package `name`, there should be exactly one corresponding manifest block.
> Test suite: replace one use of `first(...)` with `only(...)`

- src/REPLMode/REPLMode.jl
- src/utils.jl
- Switches the default to `y`
- Add text wrapping to improve the formatting in narrow terminals
> Missing package prompt: Switch default to `y`. Add text wrapping in prompt

- src/API.jl
1. Use the EnvCache-ed manifest instead of re-reading the manifest file
2. If the cachefile isn't stale, update its mtime. This is already done in base. 
https://github.com/JuliaLang/julia/blob/0bd886297d2757adf75d346a7dbb438fd839f8e6/base/loading.jl#L753-L756
While I'm not sure why it was originally added, now that cachefiles are sorted by mtime during evaluation, there is the additional benefit of keeping the `mtime` of valid cache files up to date
More info: the cache file is `touch`-ed in base during code load to make the `mtime` of the cache more representative of last used time. So it does make sense to update it here too, I think.
> Precompilation: Adjustments for efficiency

- src/API.jl
If we failed to delete this tree, don't include its size in our space savings.
Closes https://github.com/JuliaLang/Pkg.jl/issues/1872
> Don't count deletion failures in `gc` space savings

- src/API.jl
- src/Operations.jl
- src/Registry/Registry.jl
- src/Types.jl
Fixes #2555.
When instantiate fails to find a package in the registry it calls `Registry.update()`, but all that does is to update the registry files on disk. This PR also reads the updated registry before proceeding.
Reviewing the other calls to `Registry.update()`, it seems like there may be a few more instances that expects the updated registry to be read in and possibly that should actually happen within `Registry.update()`.
> Reread registry after updating it.

- src/Operations.jl
Fix #2476 
This change is meant to provide a more detailed error message and also suggests a copy-pasteable command to fix the situation. It seems there was also a typo in the original code which results in a confusing error message (`pkg.name` should have been `name` in the second error message).
> Provide more detailed error message when a pkg overwrite is detected

- CHANGELOG.md
- src/Registry/Registry.jl
- src/Registry/registry_instance.jl
- test/registry.jl
- test/utils.jl
Example:
```
julia> readdir(joinpath(homedir(), ".julia/registries")) # empty
String[]
(Pkg) pkg> add Example
Installing known registries into `~/.julia`
Installed Example ─ v0.5.3
julia> readdir(joinpath(homedir(), ".julia/registries/General"))  # only the tar file and an info file with uuid, filename, tree hash
2-element Vector{String}:
".registry_info.toml"
"General.tar.gz"
``` 
- Discuss possible implications of not having the registry files available.
> Read the registry straight from the tarball

- src/API.jl
- src/Operations.jl
- src/Types.jl
- test/force_latest_compatible_version.jl
This pull request improves the behavior of the following two keyword arguments to the `Pkg.test` function:
1. `force_latest_compatible_version::Bool`
2. `allow_earlier_backwards_compatible_versions::Bool`
These two keyword arguments are:
1. Not part of the public API
2. Only intended for use by CI services that implement auto-detection of CompatHelper/Dependabot pull requests (see e.g. https://github.com/julia-actions/julia-runtest/pull/20 and https://github.com/JuliaRegistries/CompatHelper.jl/issues/298)
Here is the current behavior:
1. `Pkg.test` creates the temporary sandbox environment.
2. `Pkg.test` runs the resolver.
3. We iterate over each direct dependency that has a `[compat]` entry and check that the direct dependency is at its latest compatible version. If at least one direct …
> Improve the implementation of `force_latest_compatible_version`

- src/project.jl
> Refactor `write_project`, and add a method for `write_project` that prints the project to an IO

- docs/src/managing-packages.md
I'm very positive that this isn't complete, but just propose a section for this. When I tell others how to set/switch pkg server, I don't really want to point them to the epic #1377 design. The contents mainly come from questions when we advertise the pkg server feature in the Chinese community.
I haven't tried a private pkg server with authentication, so I didn't document this part. Also, feel free to rephrase or drop these words as I'm not a native English speaker.
> [docs] add a section to pkg server feature

- src/API.jl
The error in https://github.com/JuliaLang/Pkg.jl/issues/2560 is unhelpful because 
1) a more insightful message from stderr is suppressed 
2) the error aborts the entire precomp process 
This PR fixes both of those
```
(test) pkg> precompile
Updating git-repo `https://github.com/JuliaRegistries/General.git`
No Changes to `~/test/Project.toml`
No Changes to `~/test/Manifest.toml`
✗ test
0 dependencies successfully precompiled in 2 seconds
ERROR: The following 1 direct dependency failed to precompile:
test [08419116-8e91-4029-9e54-f56135b4ba74]
ArgumentError: Invalid header in cache file /Users/ian/.julia/compiled/v1.7/test/jl_stYIsR.
WARNING: --output requested, but no modules defined during run
(test) pkg> 
``` …
> Precompile: Improve handling of packages that are missing modules

- src/Types.jl
Fixes #2587 
With this PR: 
```julia
julia> x = Pkg.PackageSpec(; name = "Example", uuid = "7876af07-990d-54b4-ab0e-23690620f79a")
PackageSpec(
name = Example
uuid = 7876af07-990d-54b4-ab0e-23690620f79a
version = *
)
julia> typeof(x.uuid)
Base.UUID
```
> Allow `PackageSpec` to accept an `AbstractString` for `uuid`

- .ci/change_uuid.jl
- .ci/test_uuid_is_unchanged.jl
- .github/workflows/test.yml
- test/runtests.jl
I want to standardize the CI workflow for checking and changing the UUID, so that it is exactly the same across all stdlibs that live in external repos.
That way, it is really easy for someone to set this up on a new external stdlib:
1. Copy two lines from the `.github/workflows/ci.yml` file in an existing external stdlib and paste those two lines into the `.github/workflows/ci.yml` file  in your new external stdlib
2. Copy two files from the `.ci/` directory in an existing external stdlib and paste those two lines into the `.github/workflows/ci.yml` file  in your new external stdlib
3. In the `.ci/test_uuid_is_unchanged.jl` file in your new external stdlib, change line 8 (`correct_uuid = "..."`) to contain the correct UUID for new external stdlib
> Standardize the CI workflow for checking and changing the UUID

- test/api.jl
Add tests for #2589 (test that `Pkg.PackageSpec` accepts `Union{UUID, AbstractString, Nothing}` for `uuid`)
> Add tests for #2589 (test that `Pkg.PackageSpec` accepts `Union{UUID, AbstractString, Nothing}` for `uuid`)

- .github/workflows/test.yml
- src/Operations.jl
- src/Types.jl
- src/manifest.jl
- test/manifest/formats/v1.0/Manifest.toml
- test/manifest/formats/v1.0/Project.toml
- test/manifest/formats/v2.0/Manifest.toml
- test/manifest/formats/v2.0/Project.toml
- test/manifest/formats/v3.0_unknown/Manifest.toml
- test/manifest/formats/v3.0_unknown/Project.toml
- test/manifests.jl
- test/new.jl
- test/runtests.jl
- test/test_packages/BuildProjectFixedDeps/deps/build.jl
Initial discussion in #2557 
This is Part 1, which is intended to be backported to 1.6.2
- Teach Pkg new manifest format with `julia_version` and `manifest_format` metadata fields, and package deps nested under a `deps` field
- Still defaults to old format
- Maintains format of any existing Manifest.toml
- Warn if unknown `manifest_format` version is detected
Part 2: https://github.com/JuliaLang/Pkg.jl/pull/2580
> New Manifest.toml format: Pt 1. Teach Pkg new format, but default to old format

- src/API.jl
- src/Pkg.jl
- src/Types.jl
- src/manifest.jl
- test/manifests.jl
New Manifest.toml format: Pt 2. (For 1.7 only, not to be backported to 1.6.2)
- Defaults to the new manifest format
- Warns the user (once) if an old format manifest is being maintained
Continuation after part 1 (https://github.com/JuliaLang/Pkg.jl/pull/2561)
Fixes #1458 
Fixes #2508 
Closes #2557
> New Manifest.toml format: Pt 2. Default to new format, warn if old format is being maintained

- src/API.jl
- src/Pkg.jl
- test/new.jl
We want to call `Pkg.gc()` every now and then, so let's automatically
call it after operations that can themselves result in orphaned package
versions (e.g. `rm` or `up`).  We wait the default GC collect interval,
using `mtime(orphanage_path)` as our marker of the last time we have
collected.  After each of the above operations, we query the current
time as compared to the last known GC time, hitting the filesystem only
when there is a possibility that we might need to GC.
Also, we now always write out an orphanage file (even if it's empty) to
ensure that the timestamp is always available.
> Automatically call `Pkg.gc()` after `up`, `pin`, `free` and `rm`

- src/manifest.jl
- test/manifests.jl
> New manifest format: Fix `upgrade_manifest` and raw dict entry for nothing

- src/manifest.jl
Discussed here https://github.com/JuliaLang/Pkg.jl/issues/2609#issuecomment-858662575
> New Manifest.toml format: Don't write julia_version to manifest if nothing

- src/Operations.jl
https://github.com/JuliaLang/Pkg.jl/pull/2617 was supposed to fix this but I just tried `Pkg.test` a random package and the warning still showed up. In my opinion, this manifest upgrade should happen unconditionally, and not just when testing the active project.
> fix not warning about old manifest during Pkg.test

- src/Operations.jl
- src/Types.jl
- test/new.jl
- test/resolve.jl
Fixes #2479
When installing stdlibs, if we are requesting a versioned stdlib, record
its version in the manifest and download/install it.  This allows for
tools such as BinaryBuilder to download the correct JLL for e.g.
`GMP_jll` when targeting Julia v1.6, for example.
This does slightly change manifest writing; `Manifest.toml` files now
record the version of versioned stdlibs (such as `Pkg`, `Tar`, all JLL
stdlibs, `NetworkOptions`, etc...) however this has no impact on code
loading (as they still do not contain `git-tree-sha1` entries).
> Enable installation of versioned historical stdlibs

- src/API.jl
- src/Operations.jl
- src/Types.jl
- src/manifest.jl
- test/manifests.jl
- test/new.jl
- test/repl.jl
The intention is to use the new manifest format `julia_version` to guide the user when the manifest is (potentially) incompatible with the julia version.
- The `julia_version` field in the manifest is now only set during resolve
- Adds a `@warn` (maxlog = 1 per manifest path) when loading the manifest (any action that uses `Context()` plus a direct instantiate of a manifest)
For old format manifests:
```
┌ Warning: The active manifest file is an older format with no julia version entry. Dependencies may have been resolved with a different julia version.
└ @ ~/Documents/GitHub/Pkg.jl/test/manifest/formats/v1.0/Manifest.toml:0
```
For new format manifests with the `julia_version` field:
```
┌ Warning: The active manifest file has dependencies that were resolved with a different julia …
```
> New manifest: Set `julia_version` during resolve only, and warn if instantiating a manifest that was resolved in a different or unknown julia version

- src/API.jl
- src/Operations.jl
Fixes https://github.com/JuliaLang/Pkg.jl/issues/2624
```
(jl_SWIdMW) pkg> st
Status `/private/var/folders/_6/1yf6sj0950vcg4t91m9ltb5w0000gn/T/jl_SWIdMW/Project.toml`
→ [f67ccb44] HDF5 v0.15.5
Info packages marked with → not downloaded, use `instantiate` to download
(jl_SWIdMW) pkg> build
Installing known registries into `/tmp/fdsfsd`
Added registry `General` to `/tmp/fdsfsd/registries/General`
Installed Lz4_jll ───── v1.9.3+0
Installed Blosc_jll ─── v1.21.0+0
Installed HDF5_jll ──── v1.12.0+1
Installed Preferences ─ v1.2.2
Installed Compat ────── v3.30.0
Installed Requires ──── v1.1.3
Installed JLLWrappers ─ v1.3.0
Installed HDF5 ──────── v0.15.5
Installed OpenSSL_jll ─ v1.1.10+0
Installed Zstd_jll ──── v1.5.0+0
Installed Blosc ─────── v0.7.0
Downloaded artifact: HDF5
Downloaded …
```
> `Pkg.build`: Don't build and precompile an uninstantiated environment twice

- src/REPLMode/REPLMode.jl
I made the mistake of not trying #2631 before opening it. 
Just needed a newline otherwise the error printed on the same line as the prompt.
This PR
```
julia> using Flux
│ Package Flux not found, but a package named Flux is available from a registry. 
│ Install package?
│   (Pkg) pkg> add Flux 
└ (y/n) [y]: ^D
ERROR: ArgumentError: Package Flux not found in current path:
- Run `import Pkg; Pkg.add("Flux")` to install the Flux package.
Stacktrace:
[1] require(into::Module, mod::Symbol)
@ Base ./loading.jl:967
```
> Cancel pkg install prompt when ^D is entered - Add a missing newline

- .github/workflows/test.yml
The default GitHub Actions timeout is 6 hours, which I think is too long.
This PR sets the timeout to 60 minutes, but we could even consider decreasing it further to e.g. 40 minutes or 30 minutes.
> CI: set a max timeout of 60 minutes

- src/Operations.jl
- src/Types.jl
- test/new.jl
- test/resolve.jl
This reverts commit e9b6ffb5bf67a6bb0a590f8ed8ddb72cc83d8f2e.
Adding `version` fields to all stdlibs is too scary to add this late in the release process (ref https://github.com/JuliaLang/julia/issues/41266). I will revert this on 1.7 and then we could potentially add it back if it could be done in a way that does not change the manifest.
> release1.7: Revert "Enable installation of versioned historical stdlibs (#2614)"

- src/API.jl
> When deciding whether to set an undo point, ignore manifest metadata

- src/Operations.jl
- src/PlatformEngines.jl
- src/Types.jl
- test/artifacts.jl
- test/platformengines.jl
- test/utils.jl
- Remove an unused import.
- Remove a try/catch that is no longer needed: The try/catch was introduced to deal with https://github.com/JuliaLang/Pkg.jl/issues/190 which is closed and is now handled automatically by `Tar.extract` which automatically detects whether it can create symlinks or not and simulates symlinks by copying when it can't create them.
- Move `list_tarball_files` into test utils since it's only used in tests
> download/unpack: some code cleanup

- src/Versions.jl
If I understand correctly, the current definitions of `Pkg.Versions.:≳` are incorrect, right?
Right now, `≳` is defined as such:
- `v ≳ b` if and only if `v ≲ b`
- `b ≳ v` if and only if `b ≲ v`
This PR instead defines `≳` as such:
- `v ≳ b` if and only if `b ≲ v`
- `b ≳ v` if and only if `v ≲ b`
> Delete the `Pkg.Versions.:≳` function

- src/Types.jl
Fixes https://github.com/JuliaLang/Pkg.jl/issues/2633
As per @StefanKarpinski's suggestion in https://github.com/JuliaLang/Pkg.jl/issues/2633#issuecomment-865861720
> Make `write_env_usage` atomic

- src/REPLMode/REPLMode.jl
Handles if the user adds a space after "y " which would be treated currently as "n"
I kept this separate from #2669 in case that doesn't get resolved before 1.7 goes out
> Missing package install prompt: Strip any rogue spaces from user input

- src/REPLMode/REPLMode.jl
Adds two options and a help mode, while intending to not take up more room or overload with information.
@StefanKarpinski @oxinabox would you mind giving this a go? The experience is a little hard to capture fully in screenshots.
Also, is there a better way to show the `LOAD_PATH` and a function to do the conversion? 
i.e. instead of `["@", "@v#.#"]` show `["/path/to/MyProject", "@v1.8"]`
Note that I dropped `@stdlib` from the options
> Extend install prompt functionality

- src/Registry/registry_instance.jl
`RegistryInstance` has a field `url` that is filled in from the corresponding entry in `Registry.toml` if it exists. However, it is unclear what purpose this is supposed to have and it doesn't exist in General, nor in any other registry I've seen.
This PR just removes it. The `repo` field remains, which does exist in General and other registries.
> Remove superfluous field url from RegistryInstance.

- src/API.jl
- src/Pkg.jl
- src/REPLMode/argument_parsers.jl
- src/utils.jl
- test/new.jl
Adds `pkg> activate -` and `Pkg.activate(prev=true)` to switch to the previously active environment. Matches `cd -` and `git checkout -` behavior.
There was a suggestion to instead do this with a blank `pkg> activate` but for me at least that's muscle memory for getting to the `@x.x` env.
```julia
Activating new project at `/var/folders/_6/1yf6sj0950vcg4t91m9ltb5w0000gn/T/jl_d8KZ5n`
(jl_d8KZ5n) pkg> activate -
Activating project at `~/Documents/GitHub/Pkg.jl`
(Pkg) pkg> activate -
Activating new project at `/var/folders/_6/1yf6sj0950vcg4t91m9ltb5w0000gn/T/jl_d8KZ5n`
(jl_d8KZ5n) pkg> activate
Activating project at `~/.julia/environments/v1.8`
(@v1.8) pkg> activate -
Activating new project at `/var/folders/_6/1yf6sj0950vcg4t91m9ltb5w0000gn/T/jl_d8KZ5n`
(jl_d8KZ5n) …
```
> Enable switching to the previous environment

- LICENSE.md
Other places in our stdlibs give a few contributors then a list.
It seemed odd that this mentioned only @StefanKarpinski .
Contrast [Statistics.jl](https://github.com/JuliaLang/Statistics.jl/blob/master/LICENSE.md)
> Copyright (c) 2012-2016: Jeff Bezanson, Stefan Karpinski, Viral B. Shah, Dahua Lin, Simon Byrne, Andreas Noack, Douglas Bates, John Myles White, Simon Kornblith, and other contributors.
and
[Julia itself](https://github.com/JuliaLang/julia/blob/master/LICENSE.md):
> Copyright (c) 2009-2021: Jeff Bezanson, Stefan Karpinski, Viral B. Shah, and other contributors: https://github.com/JuliaLang/julia/contributors
Could go and list a whole bunch of names.
But  @KristofferC  and  @StefanKarpinski   are by a nontrivial margin the largest contributors, on all metrics.
After that it is …
> Mention other contibutors in LICENSE

- src/Pkg.jl
Fix of formatting error in [PackageSpec](https://pkgdocs.julialang.org/dev/api/#Pkg.PackageSpec) docstring breaking the list layout
> Fix list formatting in PackageSpec documentation

- docs/src/api.md
See https://pkgdocs.julialang.org/dev/api/#Artifacts-Reference
> remove artifact docstrings from manual that does not exist

- src/Operations.jl
- src/Registry/Registry.jl
- test/utils.jl
Prevents "leaking" private UUIDs and git tree SHAs to the package server.
This should also be done for artifacts but can be done in a follow up PR.
> only attempt to use Pkg server for package downloads if the server tracks a registry containing that package

- src/API.jl
- src/GitTools.jl
- src/Types.jl
xref https://github.com/JuliaGraphs/LightGraphs.jl/pull/1581
These are mostly julia#15276-related, with some julia#36454 thrown in for good measure.
> Fix invalidations from `Pair(obj)` methods

- src/Operations.jl
- src/REPLMode/command_declarations.jl
- test/new.jl
This is mainly just one docstring fix that was missed in the switch in #2284, 
but also some comment changes given that "compat" may be used to mean another thing in the status API shortly
> Some missed compat -> outdated replaces from #2284

- src/Operations.jl
- test/new.jl
Since stdlibs are versioned now, the presence of a version cannot be used to determine if one wants to treat an stdlib as a normal package.
Fixes https://github.com/JuliaLang/Pkg.jl/issues/2698
> ensure stdlibs do not take dependencies from the registry

- docs/src/api.md
If a feature is not in the docs, does it even exist?
> add offline mode to API docs

- src/Types.jl
Fixes https://github.com/JuliaLang/Pkg.jl/issues/1956
```
(@v1.8) pkg> dev LightGraphs
ERROR: could not find project file in package at `/Users/ian/.julia/dev/LightGraphs` maybe `subdir` needs to be specified
```
cc. @Keno
> Improve error message for already dev'ed package that doesn't have a Project.toml

- src/Types.jl
This reverts commit 9f74abef301fabc7fbcf73afcf166b87a9e23703.
While this was supposed to increase the reliability of multiple Pkg instances running at the same time, it made the situation worse (https://github.com/JuliaLang/julia/pull/42253#issuecomment-920346866). Since the release is imminent, I will revert this and it can be improved on master.
cc @Sacha0
> release-1.6: Revert "Make `write_env_usage` atomic (#2661)"

- .github/workflows/test.yml
- src/Types.jl
This reverts commit ebac45fdb43621a3009bd5cf09ee1f53d8b3122f.
While this was supposed to increase the reliability of multiple Pkg instances running at the same time, it made the situation worse (https://github.com/JuliaLang/julia/pull/42253#issuecomment-920346866). Since the release is imminent, I will revert this and it can be improved on master.
cc @Sacha0
> release-1.7 Revert "Make `write_env_usage` atomic (#2661)"

- src/generate.jl
A nit, but the mixed slashes here don't look so pretty:
```
(jl_Nd3gOk) pkg> generate MyPackage
Generating  project MyPackage:
MyPackage\Project.toml
MyPackage\src/MyPackage.jl
```
I checked and the `genfile` function defined higher in the same file doesn't care whether this dir is in the second or third argument.
> generate: use joinpath instead of /

- CHANGELOG.md
- src/API.jl
- src/Operations.jl
- src/Pkg.jl
- src/REPLMode/command_declarations.jl
- src/REPLMode/completions.jl
- src/Versions.jl
- test/new.jl
- test/repl.jl
Updated: Was `-e|--edit` and defaulted to the static version.
Adds a Project compat section viewer via `pkg> compat` and an interactive editor via `pkg> compat -l|--list`.
Also some API endpoints
- `Pkg.compat!()`: equivalent to `pkg> compat` (errors early if run in a non-interactive terminal)
- `Pkg.compat()`: equivalent to `pkg> compat -l`
- `Pkg.compat("Foo")`: Return compat entry for Foo (`nothing` if no entry)
- `Pkg.compat!("Foo", "1.2")`: Set entry for Foo (use `nothing` or `""` to remove the entry)
I think there a few benefits to adding this:
- compat entries can be edited without leaving the repl
- it validates that new entries are valid compat version specifiers before they're written to file
- could be expanded to do more stuff i.e.
- an option to add the current installed …
> Add project compat entry viewing & editing

- src/API.jl
- src/Operations.jl
- src/Pkg.jl
Issue from @fredrikekre. When running `Pkg.test`, if the module being tested is loaded, but modified, the test process will warn with `1 dependency precompiled but a different version is currently loaded. Restart julia to access the new version` even though `test` is about to run the package in a new process and use the new version, which is a bit confusing.
```
$ cd $(mktemp -d) && pkg generate A && mkdir A/test && touch A/test/runtests.jl && julia --project=A -e 'using A; touch("A/src/A.jl"); using Pkg; Pkg.test("A")'
Generating  project A:
A/Project.toml
A/src/A.jl
Updating registry at `~/.julia/registries/Staging`
Updating git-repo `https://github.com/fredrikekre/Staging.git`
No Changes to …
```
> Don't warn about loaded modules during pre-test precomp, given new process will be used for tests

- src/Resolve/Resolve.jl
- test/resolve.jl
According to my tests this fixes #2740.
It was an issue with an assumption made in the local optimizer, I managed to reduce the problem to an easy test case (which is now included in the tests).
For the record, the problem went like this: say we try to bump package A, say from v1 to v2. Package A depends on B and D. The bump to A requires to bump package B, while D must be left alone. In turn, however, the bump to B now requires bumping D too, which would make it incompatible with A. But the previous code did not check back on the dependency between A and D because it erroneously considered it to have been checked already. The new code keeps looking around the graph until no further changes are done (or an inconsistency is found, like in this example).
> Fix resolver's bug #2740

- .github/workflows/check_hsg.yml
This job keeps timing out. It's not particularly helpful to have a CI job that always times out.
We can re-enable this job once we fix the timeouts.
> [CI] For now, disable the "Check Historical Stdlib Generator" CI check

- src/PlatformEngines.jl
> If `Base.DEPOT_PATH` is empty, `Pkg.PlatformEngines.get_server_dir` should return `nothing` (instead of erroring)

- src/REPLMode/REPLMode.jl
Might help guide lost newcomers to the help docs.
```
(v1.8) pkg> version Foo
ERROR: Could not determine command. Type ? for help with available commands
```
For reference, this is what help shows
```
(v1.8) pkg> ?
Welcome to the Pkg REPL-mode. To return to the julia> prompt, either press backspace when the input line
is empty or press Ctrl+C.
Synopsis
pkg> cmd [opts] [args]
Multiple commands can be given on the same line by interleaving a ; between the commands. Some commands
have an alias, indicated below.
Commands
activate: set the primary environment the package manager manipulates
add: add packages to project
build: run the build script for packages
compat: edit compat entries in the current Project
develop, dev: clone the full package repo locally for development
free: undoes a pin, …
```
> Point to help when command isn't recognized

- test/runtests.jl
- test/utils.jl
In certain situations (e.g. when we download the Julia binaries at the beginning of the Buildkite `tester_*` jobs), the `stdlib/Pkg` directory may be read-only. So instead of trying to write to the `stdlib/Pkg/test` directory, let's just use a temp directory instead.
> Pkg test suite: do not try to write to or modify the directory containing the Pkg source code

- src/Types.jl
- src/Versions.jl
- test/misc.jl
Fixes what must be unused hash methods and adds explicit tests
```
julia> hash(Pkg.Types.Project())
ERROR: UndefVarError: t not defined
Stacktrace:
[1] #16
@ ./none:0 [inlined]
[2] iterate
@ ./generator.jl:47 [inlined]
[3] collect(itr::Base.Generator{NTuple{9, Symbol}, Pkg.Types.var"#16#17"})
@ Base ./array.jl:678
[4] hash(x::Pkg.Types.Project, h::UInt64)
@ Pkg.Types /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:201
[5] hash(x::Pkg.Types.Project)
@ Base ./hashing.jl:18
[6] top-level scope
@ REPL[3]:1
julia> hash(Pkg.Types.VersionBound())
ERROR: MethodError: no method matching hash(::UInt64, ::Int64)
hash(::UInt64, ::UInt64) at hashing.jl:72
hash(::Real, ::UInt64) at float.jl:489
hash(::Any) at hashing.jl:18
... …
```
> Fix two `Base.hash` methods and add tests

- test/test_packages/TestArguments/test/runtests.jl
> Pkg test suite: in the `TestArguments` test package, relax the assertion that `Base.JLOptions().depwarn` is `1`

- .github/workflows/test.yml
- test/new.jl
Currently, our "32-bit" CI jobs are not actually using 32-bit builds of Julia.
> [CI] Actually use the correct arch when downloading Julia, and update one of the tests to use Permutations v0.4.9

- src/API.jl
- src/Pkg.jl
Calling `Pkg.instantiate` automatically calls `Pkg.precompile` which calls `Pkg.instantiate` (which then knows not to call `Pkg.precompile` again)
This tells precompile that instantiate has already been called
> Precompile: don't instantiate again after an instantiate

- src/Operations.jl
@staticfloat I believe this might be a bug, and should be `nothing` by default?
See discussion in https://github.com/JuliaRegistries/General/issues/47158
> Always allow stdlibs to update during a resolve

- test/artifacts.jl
I'm not 100% certain why this worked before and doesn't now, I suspect a change in Julia internals around loading.
Fixes #2806
Closes #2810
Closes #2823
> More forcefully encourage `ArtifactOverrideLoading` to recompile when loaded the second time

- src/Operations.jl
- src/Registry/Registry.jl
`Registry.pkg_server_registry_info()` gets spammed by `Operations.download_source` even if it's a no-op during CI tests, and each time it takes ~0.2 seconds (on my local connection)
This change lets a cache be used, unless the registry is being actively updated by `Pkg.update`
Timing of the non-cached version
```
julia> for i in 1:15
@time i Pkg.Registry.pkg_server_registry_info()
end
1 ->  0.407793 seconds (1.76 k allocations: 99.586 KiB)
2 ->  0.210918 seconds (1.64 k allocations: 97.094 KiB)
3 ->  0.228319 seconds (1.64 k allocations: 97.094 KiB)
┌ Warning: could not download https://pkg.julialang.org/registries
│   exception = HTTP/1.1 502 Bad Gateway while requesting https://pkg.julialang.org/registries
└ @ Pkg.Registry ~/Documents/GitHub/Pkg.jl/src/Registry/Registry.jl:76
4 -> …
```
> Cache pkg_server_registry_info

- test/manifest/good/not_unique_names.toml
- test/manifest/good/simple.toml
- test/manifest/noproject/Manifest.toml
- test/manifest/unpruned/Manifest.toml
- test/test_packages/A/Manifest.toml
- test/test_packages/ActiveProjectInTestSubgraph/Manifest.toml
- test/test_packages/ArtifactInstallation/Manifest.toml
- test/test_packages/BasicSandbox/Manifest.toml
- test/test_packages/BuildProjectFixedDeps/Manifest.toml
- test/test_packages/CompatOutOfSync/Manifest.toml
- test/test_packages/DependsOnExample/Manifest.toml
- test/test_packages/ExtraDirectDep/Manifest.toml
- test/test_packages/NotUpdated/Manifest.toml
- test/test_packages/SameNameDifferentUUID/Manifest.toml
- test/test_packages/SandboxFallback2/Manifest.toml
- test/test_packages/Sandbox_PreserveTestDeps/Manifest.toml
- test/test_packages/ShouldPreserveAll/Manifest.toml
- test/test_packages/ShouldPreserveDirect/Manifest.toml
- test/test_packages/ShouldPreserveNone/Manifest.toml
- test/test_packages/ShouldPreserveSemver/Manifest.toml
- test/test_packages/Status/Manifest.toml
- test/test_packages/TestSubgraphTrackingRepo/Manifest.toml
- test/test_packages/TransferSubgraph/Manifest.toml
- test/test_packages/Unpruned/Manifest.toml
- test/test_packages/UnregisteredUUID/Manifest.toml
Upgrades the valid reference manifests to 2.0 format, to reduce the log noise in the test suite that was warning about them being the older format.
All automatically upgraded via `Pkg.upgrade_manifest(manifest_path)`
I didn't update the "bad" manifests as they likely most won't automatically parse so would require manual conversion, which isn't quick.
> Upgrade valid reference manifests to 2.0 format

- src/Types.jl
- test/new.jl
- test/project/good/withcompat.toml
The compat field of a Project appears to breaking equality even when the projects are identical.
```julia
julia> Pkg.Types.Compat(Pkg.Types.VersionSpec("0.1"), "0.1") == Pkg.Types.Compat(Pkg.Types.VersionSpec("0.1"), "0.1")
false
```
This was observed in https://github.com/JuliaRegistries/General/pull/47659#issuecomment-961932857 where an unchanged Project was being re-written to disk, without any actual changes to the file even though [this check](https://github.com/JuliaLang/Pkg.jl/blob/6f8e36db88ed0c7727b5616b2baa58787cdc4e95/src/Types.jl#L1014) should prevent that 
I'm adding the tests first to prove the problem exists first.
Also, @staticfloat the pkgserver tests are failing with
```
┌ Warning: could not download https://pkg.julialang.org/registries
│   exception = HTTP/1.1 502 Bad …
```
> Fix Project equality when compat entries are present

- test/new.jl
These tests caused a bit of an awkard circularity given Base CI now runs Pkg tests, so bumping a stdlib on base made these tests fail until you update Pkg, which wouldn't happen in that PR.
https://buildkite.com/julialang/julia-master/builds/5729
Given we have https://github.com/JuliaLang/Pkg.jl/blob/master/.github/workflows/check_hsg.yml running routinely here which is a more comprehensive test, just run that here and remove these tests.
> Remove "STDLIBS_BY_VERSION up-to-date" test

- src/Operations.jl
Should fix the same problem as https://github.com/JuliaLang/Pkg.jl/pull/2827 tried to address so perhaps the cache can be removed now? It should be ok to ask the PkgServer for this given that we are going to go and download a full package anyway? @IanButterworth?
> return early if no packages to install

- src/generate.jl
Change the trailing comment produced by `generate` to use the explicit module name.
This might be helpful to avoid confusion when scanning the file,
e.g. if there are submodules.
> Use explicit module name in trailing comment

- src/Registry/Registry.jl
Fixes `@error`'s being used where proceeding isn't possible, and instead throws formatted pkgerrors
Currently:
```
(jl_iVmdM3) pkg> up
Updating registry at `~/.julia/registries/General.toml`
┌ Error: could not download https://pkg.julialang.org/registry/23338594-aafe-5451-b93e-139f81909106/476c29fc17d4642f0e27bfc8addbd5fed45b9b31
│   exception = HTTP/1.1 502 Bad Gateway while requesting https://pkg.julialang.org/registry/23338594-aafe-5451-b93e-139f81909106/476c29fc17d4642f0e27bfc8addbd5fed45b9b31
└ @ Pkg.Registry /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.8/Pkg/src/Registry/Registry.jl:365
ERROR: IOError: open("/var/folders/_6/1yf6sj0950vcg4t91m9ltb5w0000gn/T/jl_jOfglp", 0, 0): no such file or directory (ENOENT)
Stacktrace:
[1] uv_error
@ ./libuv.jl:97 …
```
> Improve error handling when registry downloads fail

- CHANGELOG.md
- src/API.jl
- src/Operations.jl
- src/Pkg.jl
- src/Types.jl
- test/manifests.jl
One of the reasons I was a fan of adding extensible metadata to the manifest was to be able to save a hash of the project state in the manifest, to make it easy to identify when the manifest and project are out of sync. i.e. a project dep entry has been manually added/removed in the toml file, or a compat entry added/changed/removed
Note that the project hash used here only hashes the deps and compat fields of the project, the rest shouldn't affect a resolve, so should be free to change.
One thing this would allow is CI to easily check whether checked-in manifests are valid, as it's easy to forget to update them.
Currently Pkg.instantiate doesn't check compat bounds and just does what the manifest says. This adds a warning.
Todo:
```
[ Info: Precompiling Pkg …
```
> Add project hash to manifest metadata and warn when manifest and project are out of sync

- docs/src/managing-packages.md
There is currently no example for deving a local package via its file path. This simple example adds one. We can switch this to show Kristoffer's file path if we want as well.
> Add example of deving local file path

- src/REPLMode/REPLMode.jl
I think the current behavior could be a bit unfriendly to newcomers that read about how in 1.7 you just need to `using Foo` to install the package, because if that's the first think they try they won't have a registry installed
In a fresh depot:
```
julia> using CSV
ERROR: ArgumentError: Package CSV not found in current path.
- Run `import Pkg; Pkg.add("CSV")` to install the CSV package.
Stacktrace:
[1] macro expansion
@ ./loading.jl:1007 [inlined]
[2] macro expansion
@ ./lock.jl:221 [inlined]
[3] require(into::Module, mod::Symbol)
@ Base ./loading.jl:988
```
```
julia> using CSV
Installing known registries into `/tmp/54234dsds`
│ Package CSV not found, but a package named CSV is available from a registry. 
│ Install package?
│   (Pkg) pkg> add CSV 
└ (y/n/o) [y]: 
```
> Add default registry if none available during pkg install prompt

- src/REPLMode/REPLMode.jl
Redo at #2862 
This instead warns once if no registries are installed.
If someone is operating in a mode where they intentionally have no registry installed (I assume quite rare?), they could hide this always with `import Pkg; Pkg.REG_WARNED[] = true`
```
julia> using CSV
│ Attempted to search for missing packages in Pkg registries but no registries are installed.
└ Use Pkg mode to install a registry. Both `pkg> add` and `pkg> update` will install the default registries.
ERROR: ArgumentError: Package CSV not found in current path.
- Run `import Pkg; Pkg.add("CSV")` to install the CSV package.
Stacktrace:
[1] macro expansion
@ ./loading.jl:1007 [inlined]
[2] macro expansion
@ ./lock.jl:221 [inlined]
[3] require(into::Module, mod::Symbol)
@ Base ./loading.jl:988
julia> using CSV
ERROR: …
```
> Warn if no registry is available during pkg install prompt

- test/runtests.jl
I think it's helpful to show the test summary at the end.
Pushing a verbose version first to show timing. I'll turn verbose off once that's run
> tests: use parent testsets to summarize tests

- src/GitTools.jl
- test/new.jl
If we have a symlink that contains a name that is a prefix of another
file within a directory, the ordering of treehashing changed between
v1.6.X and v1.7.0.  This is a problem, as it makes certain (rare) cases
hash to invalid treehashes.
This is because when `tree_hash()` was refactored in `v1.7`, I
simplified `git_mode(f) == mode_dir` to `isdir(f)`, but it turns out
that `isdir(f)` can return true if a symlink points to a directory.
This in turn prevents `/` from being appended to the filenames when
they are sorted, which is what causes the potential ordering change.
This only happens when the symlink has a name such as `5.28` which is a
prefix of another file, say `5.28.1`, and the next character sorts
higher than `/`, as `.` does.  Therefore, on `v1.6.4`, we would get:
```julia
julia> …
```
> Fix rare git treehashing bug

- src/GitTools.jl
- test/new.jl
If we have a symlink that contains a name that is a prefix of another
file within a directory, the ordering of treehashing changed between
v1.6.X and v1.7.0.  This is a problem, as it makes certain (rare) cases
hash to invalid treehashes.
This is because when `tree_hash()` was refactored in `v1.7`, I
simplified `git_mode(f) == mode_dir` to `isdir(f)`, but it turns out
that `isdir(f)` can return true if a symlink points to a directory.
This in turn prevents `/` from being appended to the filenames when
they are sorted, which is what causes the potential ordering change.
This only happens when the symlink has a name such as `5.28` which is a
prefix of another file, say `5.28.1`, and the next character sorts
higher than `/`, as `.` does.  Therefore, on `v1.6.4`, we would get:
```julia
julia> …
```
> [release-1.7] Fix rare git treehashing bug

- src/REPLMode/REPLMode.jl
This seems to be where @KristofferC and @fredrikekre have settled (https://github.com/JuliaLang/Pkg.jl/pull/2883#issuecomment-989045724)
If we go with this, we should:
- Close #2882 
- Close #2883 
- Backport this and #2865
> Tweak missing registry package warning message

- src/API.jl
- test/new.jl
1.7
```
(@v1.7) pkg> st
Status `~/.julia/environments/v1.7/Project.toml` (empty project)
(@v1.7) pkg> rm --all
ERROR: rm requires at least one package
(@v1.7) pkg> pin --all
ERROR: pin requires at least one package
(@v1.7) pkg> free --all
ERROR: free requires at least one package
```
This PR
```
(@v1.8) pkg> st
Status `~/.julia/environments/v1.8/Project.toml` (empty project)
(@v1.8) pkg> rm --all
No Changes to `~/.julia/environments/v1.8/Project.toml`
No Changes to `~/.julia/environments/v1.8/Manifest.toml`
(@v1.8) pkg> pin --all
No Changes to `~/.julia/environments/v1.8/Project.toml`
No Changes to `~/.julia/environments/v1.8/Manifest.toml`
(@v1.8) pkg> free --all
No Changes to `~/.julia/environments/v1.8/Project.toml`
No Changes to `~/.julia/environments/v1.8/Manifest.toml`
```
> Improve messaging in --all noops

- src/Resolve/maxsum.jl
The new name overrides the old one, which is still kept for compatibility.
Address https://github.com/JuliaLang/Pkg.jl/issues/2705#issuecomment-899720958.
> Rename `JULIA_PKGRESOLVE_ACCURACY` to `JULIA_PKG_RESOLVE_ACCURACY`

- src/Artifacts.jl
- src/GitTools.jl
- src/Pkg.jl
- src/Registry/Registry.jl
- src/utils.jl
Note: this is basically only checking the truthy values, so values like `"truw"` would silently be parsed as a falsy value, but as far as I can tell that's what's happening at the moment anyways, so I don't think there is any practical change.
Address https://github.com/JuliaLang/Pkg.jl/issues/2705#issuecomment-978147571.
> Consistently parse all boolean environment variables

- src/Registry/Registry.jl
This PR adds the no-argument `Pkg.Registry.add()` method, which automatically installs the default registries.
"Functional" API:
```
$ JULIA_DEPOT_PATH=$(mktemp -d) ./julia -e 'import Pkg; Pkg.Registry.add()'
ERROR: MethodError: no method matching add()
add(::Union{String, Pkg.Registry.RegistrySpec}; kwargs...) at ~/Downloads/julia/usr/share/julia/stdlib/v1.8/Pkg/src/Registry/Registry.jl:41
add(::Vector{String}; kwargs...) at ~/Downloads/julia/usr/share/julia/stdlib/v1.8/Pkg/src/Registry/Registry.jl:42
add(::Vector{Pkg.Registry.RegistrySpec}; io) at ~/Downloads/julia/usr/share/julia/stdlib/v1.8/Pkg/src/Registry/Registry.jl:43
Stacktrace:
[1] top-level scope
@ none:1
```
REPL mode:
```
$ JULIA_DEPOT_PATH=$(mktemp -d) ./julia -e 'import Pkg; Pkg.pkg"registry add"'
┌ …
```
> Add the no-argument `Pkg.Registry.add()` method, which automatically installs the default registries

- docs/src/artifacts.md
#2024 didn't make it in time for 1.6 and wasn't backported, so adjust the compat
docs to account for that.
> Correct compat annotation for extended platform selection

- src/API.jl
- src/Operations.jl
- test/api.jl
- test/manifests.jl
A resolve was previously added to direct calls of `Pkg.precompile` to try to prevent the unexpected behavior users saw when the manifest was out of sync with the project.
The manifest out of sync warning introduced in https://github.com/JuliaLang/Pkg.jl/pull/2815 actually serves as a warning if the manifest isn't resolved/in-sync with the project, so this resolve can be removed.
Closes #2904 
But removing the resolve does expose the risk of not detecting circular deps fully, as demonstrated by two resolves needing to be added to the circular dep tests.
> Remove precompile resolve

- src/API.jl
- src/REPLMode/command_declarations.jl
With the new `pkg> compat` entry method, and the project/manifest sync checking (#2815) I think it makes sense to automatically resolve after changing the compat entry via that interface
For instance
```
(@v1.8) pkg> st
Status `~/.julia/environments/v1.8/Project.toml`
[336ed68f] CSV v0.8.0
(@v1.8) pkg> compat CSV 0.9
Compat entry set:
CSV = "0.9"
Resolve checking for compliance with the new compat rules...
Error empty intersection between CSV@0.8.0 and project compatibility 0.9
(@v1.8) pkg> up
...
(@v1.8) pkg> compat CSV 0.9
Compat entry set:
CSV = "0.9"
Resolve checking for compliance with the new compat rules...
No Changes to `~/.julia/environments/v1.8/Project.toml`
No Changes to `~/.julia/environments/v1.8/Manifest.toml`
```
> Resolve after setting compat via Pkg.compat

- src/Registry/registry_instance.jl
Fix a spelling mistake ("inconsistend"), and give a hint as to which package is causing the error message.
> fix typo and improve error message

- .codecov.yml
Replaces #2887
With this pull request, Codecov commit statuses will continue to be shown on pull requests. However, they will not be shown on master.
> Only show the Codecov commit statuses on pull requests

- docs/src/environments.md
This came up recently on discourse. Though the dot is reasonably visible, it may be skimmed over or disregarded if there's no mention of why it is important.
> Docs: add comment for what `.` in `activate .` means

- docs/src/compatibility.md
This PR expands on two minor points that had contributed to my confusion about how compat worked for patch versions.
- The caret section doesn't specify that caret is the default. It is listed a few paragraphs above - but it is easy to miss the connection when you are reading the caret docs specifically.
- According to PackageCompatUI equality can specify multiple distinct specific versions. The docs only had examples for specifying one version, which made it appear to not be possible to specify multiple versions explicitly, as other specifiers all have multiple examples.
> Tweak compatability documentation

- src/API.jl
This resolve isn't needed as the inner compat calls resolve
> Remove duplicate resolve in `pkg> compat`

- test/test_packages/ArtifactOverrideLoading/src/ArtifactOverrideLoading.jl
This pull request fixes the following two warnings:
```
┌ Warning: Module Pkg with build ID 159589902205 is missing from the cache.
│ This may mean Pkg [54cfe95a-1eb2-52ea-b672-e2afdf69b78f] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:1160
┌ Warning: Module Pkg with build ID 159589902205 is missing from the cache.
│ This may mean Pkg [54cfe95a-1eb2-52ea-b672-e2afdf69b78f] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:1160
```
Ref https://github.com/JuliaLang/Pkg.jl/pull/2919#issuecomment-1005366034
---
> Set `__precompile__(false)` in the `ArtifactOverrideLoading` test package

- src/Operations.jl
Trying to fix #2925 
I didn't manage to understand why this was happening, but it seems ok to continue if the uuid isn't found?
Seems like this could do with a test to make sure it's not breaking anything, but again I'm not sure what the root problem is.
@KristofferC any idea?
> Fix `status_compat_info()` throws "UUID not found" error

- src/Operations.jl
Fixes
```
(jl_uUTw8F) pkg> st --outdated -m
Status `/tmp/jl_uUTw8F/Manifest.toml`
⌃ [78c3b35d] Mocking v0.7.3 (<v0.7.4)
⌅ [88634af6] SaferIntegers v2.5.5 (<v3.0.3): FHIRClient
(jl_uUTw8F) pkg> add Mocking@0.7.4
ERROR: Unsatisfiable requirements detected for package Mocking [78c3b35d]:
Mocking [78c3b35d] log:
├─possible versions are: 0.5.6-0.7.3 or uninstalled
└─restricted to versions 0.7.4 by an explicit requirement — no versions left
```
> disregard yanked versions when showing outdated packages

- src/manifest.jl
- test/manifests.jl
I realized in https://github.com/JuliaLang/Pkg.jl/pull/2666 that there's a bug preventing the manifest julia version mismatch log from showing.
#2666 takes care of the 1.6 backport
> Fix manifest version check bug

- test/subdir.jl
Follow-up to #2946
Replaces and closes #2948
After we make the first commit to a new repository, we check and see what the branch name is. If the branch name is `master`, we do nothing. If the branch name is not `master`, we run the following commands:
1. `git branch -f master`
2. `git checkout master`
3. `git branch -D $(old_branch_name)`
After running this command, the branch name is now `master`.
This supports Git 1.2.0+ and Git 2.0.0+. If someone really needs to support a version of Git older than 1.2.0, then we'll need to rewrite these tests to use the LibGit2 stdlib instead.
https://github.com/git/git/blob/v1.2.0/Documentation/git-branch.txt#L28-L29
```
-f::
Force a reset of <branchname> to <start-point> (or current head).
``` …
> Make tests robust against Git's `init.defaultBranch` option being set, while still supporting Git 1.2.0+ and Git 2.0.0+

- src/Registry/Registry.jl
This is documenting #2898, which would make it the first-and-only public API to install the default registries. Yay!
Feel free to edit the PR to change the wording, I mostly wanted to get the ball rolling.
> Docs: document `Registry.add()` from #2898

- src/API.jl
- src/manifest.jl
- test/manifests.jl
As discussed in https://github.com/JuliaLang/Pkg.jl/issues/2665 I think it would be helpful for 1.6.2 to have something like this. Otherwise the user will get unactionable errors with no warning.
This is a 1.6-appropriate modification of the warning that was omitted in #2620 when backported in #2628
> [release-1.6] Add manifest julia_version difference warning

- src/Operations.jl
Allows us to continue after a failed download from the PkgServer (e.g. from https://github.com/JuliaPackaging/PkgServer.jl/issues/126). Was removed in https://github.com/JuliaLang/Pkg.jl/commit/67ed9cb3541368e3f98867ed809de7c6db32f4cc#diff-6dfb4e40705b22a427451362ea83b4e3a763028e3dcaa3b9b1846aa1ec84370fL501
> restore try catch for unpacking archive

- src/API.jl
- src/Artifacts.jl
- src/Operations.jl
- src/PlatformEngines.jl
- src/REPLMode/REPLMode.jl
- src/Registry/Registry.jl
- src/project.jl
These stem from julia#15276, i.e.,
https://docs.julialang.org/en/v1/manual/performance-tips/#man-performance-captured
They were identified by scanning all compiled MethodInstances with
`hasbox` in the newly-released MethodAnalysis 0.4.5.
`Core.Box` often causes "follow-on" inference problems,
but for these cases there were relatively few, which may be why
these didn't show up earlier during the Great Invalidation Hunt.
Still, there doesn't seem to be any particular reason not to fix them.
> Inferrability: eliminate more Core.Box

- .github/workflows/test.yml
This PR makes the CI output quiet.
If a user is trying to debug a PR, they can always change this value back to `"false"` on their PR branch, and then the PR CI will be verbose.
> CI: make the CI output quiet

- Project.toml
- src/Operations.jl
- test/artifacts.jl
- test/sandbox.jl
- test/test_packages/AugmentedPlatform/.pkg/platform_augmentation.jl
- test/test_packages/Sandbox_PreservePreferences/Manifest.toml
- test/test_packages/Sandbox_PreservePreferences/Project.toml
- test/test_packages/Sandbox_PreservePreferences/dev/Foo/Manifest.toml
- test/test_packages/Sandbox_PreservePreferences/dev/Foo/Project.toml
- test/test_packages/Sandbox_PreservePreferences/dev/Foo/src/Foo.jl
- test/test_packages/Sandbox_PreservePreferences/dev/Foo/test/LocalPreferences.toml
- test/test_packages/Sandbox_PreservePreferences/dev/Foo/test/Project.toml
- test/test_packages/Sandbox_PreservePreferences/dev/Foo/test/runtests.jl
- test/test_packages/Sandbox_PreservePreferences/src/Sandbox_PreservePreferences.jl
Fixes #2500, when we set up the preferences for test/build we want
to propagate the preferences from either `test/LocalPreferences.toml` if `test/Project.toml` exists
or from `Project.toml` if the old style is being used. We gather the dependencies up and then write
them out to the temp directory. 
Similarily for the `.pkg/select_artifacts.jl` functionality we need to make the current preferences
available so that we can augment the platform we are downloading.
Co-authored-by: @staticfloat
> Improve handling of preferences for sandboxes used in Pkg

- src/manifest.jl
(trivial change, see [discussion](https://discourse.julialang.org/t/julia-version-lower-bound-for-new-manifest-format/76152/))
> Inform user about Julia versions that support new manifest in warning msg.

- src/API.jl
- src/Operations.jl
- src/Types.jl
- test/new.jl
When a package isn't found by name this adds a number of ranked matches (depending on the result scores and terminal width), via the same fuzzyscore search that `REPL` does for help mode.
If there are no match scores above zero, no suggestions are shown.
It seems like the search could be improved in REPL because it's unfortunate that the diffeq spelling mistake isn't found.
Also the `fuzzysort` method tweak could be upstreamed.
It adds a bit of slowness, but I think that's ok for this kind of user feedback (this is with 3 registries including General)
master
```
julia> @time try Pkg.add("Image"); catch  end
0.009007 seconds (23.61 k allocations: 2.039 MiB)
julia> @time try Pkg.add("Image"); catch  end
0.008462 seconds (23.62 k allocations: 2.040 MiB)
```
this PR
```
julia> @time try …
```
> add ranked suggestions to `add` error

- src/Operations.jl
- test/manifest/formats/v2.0/Manifest.toml
- test/manifest/formats/v3.0_unknown/Manifest.toml
- test/manifests.jl
Having the full build info was proving too noisy for checked-in manifests on master
> Drop build info from julia version stored in manifest

- CHANGELOG.md
- docs/src/api.md
- src/Operations.jl
- src/Pkg.jl
- src/Resolve/graphtype.jl
- src/Types.jl
- test/new.jl
I created a sysimage with an outdated Plots versions, loaded Julia with that sysimage and created a temp repo and added Plots:
```
Activating new project at `/var/folders/26/gw1dqz6n5zsbkp72mktkhz3c0000gn/T/jl_hr2NH5`
(jl_hr2NH5) pkg> add Plots
Updating registry at `~/.julia/registries/General.toml`
Updating `/private/var/folders/26/gw1dqz6n5zsbkp72mktkhz3c0000gn/T/jl_hr2NH5/Project.toml`
⌃ [91a5bcdd] + Plots v1.24.3
Updating `/private/var/folders/26/gw1dqz6n5zsbkp72mktkhz3c0000gn/T/jl_hr2NH5/Manifest.toml`
[79e6a3ab] + Adapt v3.3.3
[d360d2e6] + ChainRulesCore v1.12.2
(jl_hr2NH5) pkg> st --outdated -m
Status `/private/var/folders/26/gw1dqz6n5zsbkp72mktkhz3c0000gn/T/jl_hr2NH5/Manifest.toml`
⌅ [28b8d3ca] GR v0.62.1 (<v0.64.0): Plots
⌅ …
```
> respect versions in sysimage

- test/utils.jl
Let's see if this fixes the CI failures when trying to put Pkg master into Julia
> dont respect sysimage versions when devving Pkg in artifact test

- src/Pkg.jl
I really like this new feature available in Julia v1.8. I tried to improve the docstring of `Pkg.status` a bit to make the new keyword `outdated` more clear, at least for me.
> list outdated kwarg of Pkg.status

- .github/workflows/test.yml
linux32 nightlies are stuck at `commit 5b2a4b1e45 (2022-02-13 06:27 UTC)` and as far as I know, will likely be for a while yet.
This blocks merging PRs that need changes in the base repo like https://github.com/JuliaLang/Pkg.jl/pull/2793 and https://github.com/JuliaLang/Pkg.jl/pull/3021 
So I'm proposing excluding linux32 from CI until nightlies recover
We have Pkg tests run on Base now for linux32, I believe.. so regressions will be picked up after updating the Pkg commit in base
cc. @staticfloat @DilumAluthge
> Temporarily exclude linux32 from CI

- CHANGELOG.md
- src/Operations.jl
Uses the new path-specific code coverage option (https://github.com/JuliaLang/julia/pull/44359) to make code coverage tracking more efficient
> Use new directory-specific codecov tracking

- test/repl.jl
Replaces `println(stdin.buffer, ...)` with a `redirect_stdin` approach.
@vtjnash Could you check the `stdin` redirection? I couldn't make it work with `Base.BufferStream`. 
Fixes #2961
> Tests: Don't touch `stdin.buffer`

- src/REPLMode/REPLMode.jl
Filtering of `expanded_envs` caused that `envs[i]` and `editable_envs[i]` did not correspond to the same environment.
Before:
```
julia> insert!(LOAD_PATH, 2, mktempdir())
4-element Vector{String}:
"@"
"/tmp/jl_DRt9jd"
"@v#.#"
"@stdlib"
julia> using PyPlot
│ Package PyPlot not found, but a package named PyPlot is available from a registry. 
│ Install package?
│   (@v1.9) pkg> add PyPlot 
└ Select environment:
> 1: `/tmp/jl_DRt9jd` (@)
2: `~/.julia/environments/v1.9/Project.toml` (/tmp/jl_DRt9jd)
```
With the PR:
```
julia> insert!(LOAD_PATH, 2, mktempdir())
4-element Vector{String}:
"@"
"/tmp/jl_x6zoyq"
"@v#.#"
"@stdlib"
julia> using PyPlot
│ Package PyPlot not found, but a package named PyPlot is available from a registry. 
│ Install package?
│   (@v1.9) pkg> add PyPlot 
└ Select …
```
> REPL: Fix labels in env selection

- test/artifacts.jl
- test/new.jl
- test/test_packages/ArtifactInstallation/Artifacts.toml
- test/test_packages/ArtifactInstallation/src/ArtifactInstallation.jl
When we test that the old version of GMP_jll gets installed properly, we
need to realize that the old version of GMP_jll may not have an artifact
for some of our newer platforms.
> Fix Artifacts test on aarch64-apple-darwin14

- src/REPLMode/REPLMode.jl
- test/repl.jl
This PR allows passing a comma-separated list of packages to `]status`.
Resolves #3049.
Also, I originally put the test [here](https://github.com/JuliaLang/Pkg.jl/blob/f81efda695d4c227fc81617c1400b1e067a36af1/test/repl.jl#L651) but then the error did not show up even when it should. Is that expected?
> REPL: Status for comma-separated list of packages

- test/pkg.jl
- test/utils.jl
I'm hoping that this will fix the non-deterministic (but frequent) `Pkg` failures that I'm seeing in the `rr-net` job.
> Before running the "test atomicity of write_env_usage" testset, make sure that the General registry has been installed

- src/API.jl
This was hitting the following, when trying to show the resolver error
```
(@v1.8) pkg> compat ProfileView
Compat entry removed for ProfileView
Resolve checking for compliance with the new compat rules...
ERROR: MethodError: no method matching printpkgstyle(::Base.TTY, ::Symbol, ::SubString{String}; color=:yellow)
printpkgstyle(::IO, ::Symbol, ::String) at ~/Documents/GitHub/Pkg.jl/src/utils.jl:2 got unsupported keyword argument "color"
printpkgstyle(::IO, ::Symbol, ::String, ::Bool; color) at ~/Documents/GitHub/Pkg.jl/src/utils.jl:2
Stacktrace:
[1] compat(ctx::Pkg.Types.Context, pkg::String, compat_str::Nothing; io::Nothing, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
@ Pkg.API ~/Documents/GitHub/Pkg.jl/src/API.jl:1816
...
```
> Minor compat edit mode error show fix

- .gitignore
- src/Operations.jl
- test/sandbox.jl
When calling `Pkg.test("Foo")`, some information from the calling
environment is incorporated into the tests of `Foo`; for example, if the
calling environment places restrictions on the package versions of
`Bar`, a dependency of `Foo`, those restrictions will be honored when
resolving the dependencies of the test environment for `Foo`.
Similarly, we should honor preferences set within the calling
environment.  The easiest way to do this is to layer the test
environment onto the end of the current `LOAD_PATH` instead of wholesale
replacing it, as we were doing when copying preferences over for the
test environment.
With this change it is now viable to test alternate configurations of a
package without dev'ing it out and modifying it directly.  If a package
`Foo` uses preference to alter …
> Ensure that test preferences are properly stacked

- .github/workflows/test.yml
> CI: Re-enable testing on `i868-linux-gnu`

- src/REPLMode/REPLMode.jl
https://github.com/JuliaLang/Pkg.jl/pull/3038 broke the extended `o` prompt options
```
julia> using ProfileView
│ Package ProfileView not found, but a package named ProfileView is available from a registry. 
│ Install package?
│   (Pkg) pkg> add ProfileView 
└ Select environment:
1: `~/Documents/GitHub/Pkg.jl/Project.toml` (@)
> 2: `~/.julia/environments/v1.9/Project.toml` (@v#.#)
ERROR: UndefVarError: envs not defined
Stacktrace:
[1] try_prompt_pkg_add(pkgs::Vector{Symbol})
@ Pkg.REPLMode /Applications/Julia-1.9.app/Contents/Resources/julia/share/julia/stdlib/v1.9/Pkg/src/REPLMode/REPLMode.jl:747
...
```
Obviously that means the prompt needs better tests (https://github.com/JuliaLang/Pkg.jl/issues/3083)
This PR just fixes the immediate issue
> Fix extended missing package add prompt

- src/Pkg.jl
1. Make `Pkg.test(; allow_reresolve)` part of the public API
2. Document the `allow_reresolve` kwarg in the docstring for the `Pkg.test` function.
3. In the docstring for `Pkg.test`, add a note explaining that unless `allow_reresolve` is set to `false`, there is no guarantee that the versions in the `Manifest.toml` file will be the same versions used in the tests.
> Make `Pkg.test(; allow_reresolve)` part of the public API

- src/utils.jl
- test/misc.jl
This commit prevents stack overflow when `safe_realpath` is called with
a non-existing path that does not start with a `/`, such as
"D:\ProjectA" (on a Windows machine without drive D:)
""
"non-existing-path"
Resolves #3085
> safe_realpath: fix stack overflow

- src/Registry/Registry.jl
- test/registry.jl
Matching many other `Pkg` functions, we allow `update()` here to operate
on a custom set of depots, and `add()` to operate on a single specificed
depot.  This is useful for manipulating registries inside of depots that
are not currently on the `DEPOT_PATH`.
> Allow `Registry.{add,update}()` to target specific depots

- src/Operations.jl
Updated: See https://github.com/JuliaLang/Pkg.jl/pull/3099#issuecomment-1146979195
> Make `--outdated` tip coordinate with status mode

- docs/generate.jl
I had missed that this was how repl mode docs are generated
> Add missing compat repl mode docs

- src/Operations.jl
Even if a user runs with `--startup-file=1`, it can cause problems to run this with the startup file enabled since the process collects output from stdout. This causes for example https://github.com/JuliaLang/julia/issues/45583.
Also, in case the script outputs invalid TOML, it was hard to know what package caused this. Now it would write the error as:
```
ERROR: failed to parse TOML output from running "/home/kc//Pkg.jl/DynamicArtifact/.pkg/select_artifacts.jl", got: 
TOML Parser error:
none:1:6 error: expected equal sign after key
Setup successful
^ 
```
> enforce not running with startup file when selecting dynamic artifacts and improve error message

- CHANGELOG.md
- docs/src/api.md
- src/API.jl
- src/Pkg.jl
- src/REPLMode/command_declarations.jl
- src/REPLMode/completions.jl
- test/new.jl
- test/repl.jl
Don't know if the "Who required Package" is useful... I just took it from https://www.npmjs.com/package/npm-why.
We could also add some compat info here, for example, if a package is being upper bounded by another one but one step at a time.
> implement why, showing why a package is in the manifest

- src/PlatformEngines.jl
- test/platformengines.jl
> Modify the `PlatformEngines.get_server_dir` function to convert `domain:port` to `domain_port`

- src/PlatformEngines.jl
This is a follow-up to #3131.
We want to backport #3131 to Julia 1.6. However, iterating over `RegexMatch` does not work in Julia 1.6, so if `m` is a `RegexMatch`, we can't do `only(m)`. Instead, we have to do `only(m.captures)`.
> Iterating over `RegexMatch` does not work in Julia 1.6

- src/manifest.jl
Since `Pkg` is not imported by default in the REPL, this might help new users
> Add `import Pkg` to manifest warning

- src/API.jl
- src/Operations.jl
- src/Pkg.jl
- src/REPLMode/command_declarations.jl
- test/new.jl
This PR is intended to implement https://github.com/JuliaLang/Pkg.jl/issues/2344#issuecomment-942226805.
Here is an example of usage:
Setup:
```
Activating new project at `/tmp/jl_BxVsSw`
(jl_pV0GRk) pkg> add Plots@1.24 StructArrays@0.6.4 PlotThemes@2.0.0
Updating `/tmp/jl_pV0GRk/Project.toml`
⌃ [ccf2f8ad] + PlotThemes v2.0.0
⌃ [91a5bcdd] + Plots v1.24.3
⌃ [09ab397b] + StructArrays v0.6.4
...
(jl_pV0GRk) pkg> rm PlotThemes
Updating `/tmp/jl_pV0GRk/Project.toml`
[ccf2f8ad] - PlotThemes v2.0.0
No Changes to `/tmp/jl_pV0GRk/Manifest.toml`
...
```
We now have two outdated packages in the Project:
```
(jl_pV0GRk) pkg> st --outdated
Status `/tmp/jl_pV0GRk/Project.toml`
⌃ [91a5bcdd] Plots v1.24.3 (<v1.25.11)
⌃ [09ab397b] StructArrays …
```
> allow `--preserve` to be used in `up`

- src/REPLMode/REPLMode.jl
Fixes https://github.com/JuliaLang/Pkg.jl/issues/2570
I used a catch because if we can't form a `Context()` it might just be good to abort.
Or is there a narrower but reliable check we could make?
> Exit missing package prompt early if no active project

- test/runtests.jl
Sometimes the cleanup takes too long and Base CI thinks it's hanging and kills the process.
> Cleanup before exit after tests

- src/API.jl
This should hopefully fix some invalidations coming from Static.jl.
<details>
<summary>
Here is the code:
</summary>
```julia
_
_       _ _(_)_     |  Documentation: https://docs.julialang.org
(_)     | (_) (_)    |
_ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
| | | | | | |/ _` |  |
| | |_| | | | (_| |  |  Version 1.8.0 (2022-08-17)
_/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |
(@v1.8) pkg> activate --temp
(jl_PDrBpd) pkg> add Static
Updating registry at `~/.julia/registries/General.toml`
Updating `/tmp/jl_PDrBpd/Project.toml`
[aedffcd0] + Static v0.7.6
Updating `/tmp/jl_PDrBpd/Manifest.toml`
[615f187c] + IfElse v0.1.1
[aedffcd0] + Static v0.7.6
julia> using SnoopCompileCore
julia> invalidations = …
```
> fix API invalidations from Static.jl

- src/API.jl
This required a bit of hunting an I'm not completely sure whether it fixes the problem, so please help me understand this better.
I ran SnoopCompile and found
```
inserting extrema(f::AbstractFFTs.Frequencies) in AbstractFFTs at ~/.julia/packages/AbstractFFTs/Wg2Yf/src/definitions.jl:456 invalidated:
backedges: 1: superseding extrema(a::AbstractArray; dims, kw...) in Base at reducedim.jl:994 with MethodInstance for extrema(::AbstractVector) (30 children)
9 mt_cache
```
Running
```julia
...
Choose a call for analysis (q to quit):
extrema(::AbstractVector)
#sort!#8(::Base.Sort.Algorithm, ::typeof(isless), ::typeof(identity), ::Nothing, ::Base.Order.ForwardOrder
(::Base.var"#sort!##kw")(::NamedTuple{(:by,), Tuple{typeof(identity)}}, ::typeof(sort!), ::AbstractVecto
#_print#10(::Int64, …
```
> hopefully fix invalidations in API from AbstractFFTs

- src/manifest.jl
This is based on the following code:
```julia
julia> using Pkg; Pkg.activate(temp=true); Pkg.add("Static")
julia> using SnoopCompileCore; invalidations = @snoopr(using Static); using SnoopCompile
julia> trees = invalidation_trees(invalidations)
inserting !(::False) in Static at ~/.julia/packages/Static/sVI3g/src/Static.jl:427 invalidated:
...
77: signature Tuple{typeof(!), Any} triggered MethodInstance for Pkg.Types.Manifest(::Dict{String, Any}, ::String) (97 children)
...
```
I suggest the labels `latency` and `backport-1.8`.
> fix invalidations from Static.jl

- test/pkg.jl
If the user has opted out of the Pkg server, then `Pkg.Registry.add()` will always do a Git clone of the General registry, even if the depot already contains the General registry. In the CI for this repo, in the macOS CI job that uses Julia nightly and does not use the Pkg server, we are seeing frequent Git clone errors during this line, which perhaps is due to bad network connectivity on GitHub's macOS machines. However, because this line is inside a `temp_pkg_dir`, it is likely that the depot has already been initialized with the General registry, and thus this line is unnecessary. To be safe, instead of deleting the line entirely, we modify it so that the Git clone is only performed if no registries are found in the depot.
> Test suite: skip the "ensure registry is installed" step if `Pkg.Registry.reachable_registries()` is not empty

- src/API.jl
- src/manifest.jl
I backported two PRs with invalidation fixes (merged into `master`) to `release-1.8`. They fix a few hundred invalidations when loading Static.jl, ArrayInterface.jl or anything using that (basically everything from JuliaSIMD with LoopVectorization.jl, SciML with OrdinaryDiffEq.jl etc.).
> backport invalidation fixes to 1.8

- src/Operations.jl
It seems `projectfile_path` can return either a `String` or `Nothing` but here, it really must return a `String` (at least, there are no methods of `with_load_path` that accept a vector with `Nothing` entries).
Previously, this was causing a specialization of `vect(::Nothing, ::Vararg(String))` which then gave rise to a bunch of invalidations in StaticArrays due to its overloading of `getindex`. I think this should fix about ~100 of them.
> fix invalidations due to `vect(::Nothing, Vararg{String}}` call

- src/REPLMode/REPLMode.jl
I improved type stability to fix some invalidations. This is based on the following code:
```julia
julia> using Pkg; Pkg.activate(temp=true); Pkg.add("ArrayInterface")
julia> using SnoopCompileCore; invalidations = @snoopr(using ArrayInterface); using SnoopCompile
julia> trees = invalidation_trees(invalidations)
...
inserting !(::Static.False) in Static at ~/.julia/packages/Static/sVI3g/src/Static.jl:427 invalidated:
...
```
The problem here is that `arguments` is only inferred as `Any`. I do not know whether we can assert something better (which may also fix the invalidations).
I suggest the labels `latency` and `backport-1.8`.
> improve type stability of `Command(statement::Statement)`

- src/Resolve/graphtype.jl
I improved type stability to fix some invalidations. This is based on the following code:
```julia
julia> import Pkg; Pkg.activate(temp=true); Pkg.add("HDF5")
julia> using SnoopCompileCore; invalidations = @snoopr(using HDF5); using SnoopCompile
julia> length(uinvalidated(invalidations))
168
julia> trees = invalidation_trees(invalidations)
...
inserting convert(::Type{I}, ::Type{F}) where {I<:Integer, F<:HDF5.Filters.Filter} in HDF5.Filters at ~/.julia/packages/HDF5/T4H0V/src/filters/filters.jl:428 invalidated:
...
backedges: 1: superseding convert(::Type{Union{}}, x) in Base at essentials.jl:213 with MethodInstance for convert(::Core.TypeofBottom, ::Any) (164 children)
```
I suggest the labels `latency` and `backport-1.8`. With a recent build of Pkg based on the `release-1.8` branch and …
> improve inferrability of `prune_graph!`

- ext/LazilyInitializedFields/LazilyInitializedFields.jl
- src/Artifacts.jl
- src/Registry/registry_instance.jl
Similar to #3207, but just running with `report_package(Pkg; target_defined_modules=true, mode=:typo)`.
After this (and with #3207), there's just 2 `:typo`-issues remaining (one is https://github.com/JuliaLang/Pkg.jl/pull/2569#issuecomment-1251931205 and the other I don't understand):
```jl
═════ 2 possible errors found ═════
┌ @ /home/tchr/dev/julia-pkgs/Pkg.jl/src/Operations.jl:2099 Pkg.Operations.is_tracking_repo(new)
│┌ @ /home/tchr/dev/julia-pkgs/Pkg.jl/src/Operations.jl:230 pkg.repo
││┌ @ Base.jl:37 Base.getfield(x, f)
│││ type Pkg.Types.EnvCache has no field repo
││└──────────────
┌ @ /home/tchr/dev/julia-pkgs/Pkg.jl/src/API.jl:1350 Pkg.API.touch(Pkg.API.path_to_try)
│ variable Pkg.API.path_to_try is not defined
└────────────────────────────────────────────────────
```
This also …
> fixes for JET's `mode=:typo` report

- src/Resolve/Resolve.jl
- src/Resolve/graphtype.jl
- test/resolve.jl
- test/resolve_utils.jl
This closes #3125 and it's an alternative implementation to #3204.
It does not change `VersionSet` so it does not have any of the associated difficulties there. 
It adds a keyword argument to the `GraphType` constructor instead ([here](https://github.com/carlobaldassi/Pkg3.jl/blob/56f5fdc9419b3a9ddc10cac5f73dc6da05d55734/src/Resolve/graphtype.jl#L245)). The type is `Dict{UUID,Dict{VersionNumber,Set{UUID}}}`.
@KristofferC this is what was discussed [here](https://github.com/JuliaLang/Pkg.jl/pull/3204#issuecomment-1251017819).
The building of the structure is a little cumbersome, an example can be seen [here](https://github.com/carlobaldassi/Pkg3.jl/blob/56f5fdc9419b3a9ddc10cac5f73dc6da05d55734/test/resolve_utils.jl#L76-L79).
This still needs testing, just as much as #3204 did.
> Allow optional dependencies in the resolver (without changing VersionSet)

- src/API.jl
As noted https://github.com/JuliaLang/Pkg.jl/pull/2569#issuecomment-1251814774 this touch was silently broken, meaning that the identified cache files weren't promoted to the front of the queue during load time. This may speed up load times.
Thanks @thchr !
> Precompile: Fix touch on cache files to make sure latest is used first during load

- docs/src/registries.md
I think it would be a good idea to advertise a bit more the fact that (1) a package server can advertise additional registries, and (2) how to then add them automatically.
> Mention package server registries on Registries doc page

- src/API.jl
@KristofferC noticed this error introduced in https://github.com/JuliaLang/Pkg.jl/pull/3213 in PkgEval 
https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/9dd9458_vs_d0156b5/SnoopCompile.primary.log
```
┌ Warning: The active manifest file has dependencies that were resolved with a different julia version (1.6.3-pre.1). Unexpected behavior may occur.
└ @ ~/.julia/packages/SnoopCompile/Q8zUg/test/testmodules/Stale/Manifest.toml:0
Activating┌ Error: Pkg.precompile error
│   exception =
│    UndefVarError: `IOError` not defined
│    Stacktrace:
│     [1] _is_stale(paths::Vector{String}, sourcepath::String)
│       @ Pkg.API /opt/julia/share/julia/stdlib/v1.10/Pkg/src/API.jl:1042
...
│       @ Pkg.API ./task.jl:514
└ @ Pkg.API …
```
> Fix reference to IOError on error path

- docs/src/basedocs.md
- docs/src/managing-packages.md
The linking in the base docs broke because getting-started linked out to pages not included in base docs
```
┌ Error: reference for 'Managing-Packages' could not be found in src/stdlib/Pkg.md.
└ @ Documenter.CrossReferences /usr/home/julia/buildbot/w1_builder/package_freebsd64/build/doc/deps/packages/Documenter/yf96B/src/Utilities/Utilities.jl:32
┌ Error: reference for 'Working-with-Environments' could not be found in src/stdlib/Pkg.md.
└ @ Documenter.CrossReferences /usr/home/julia/buildbot/w1_builder/package_freebsd64/build/doc/deps/packages/Documenter/yf96B/src/Utilities/Utilities.jl:32
```
> Fix basedocs

- src/Registry/Registry.jl
- test/new.jl
The use of setting the `reg.url` rather than `reg.path` was forcing a git clone of a local repo, rather than the reg symlink that `isolate` does by default (kwarg `linked_reg`)
Should fix the latter issue in #3238 
Also fixes a leaky env var
https://buildkite.com/julialang/julia-master/builds/17451#01840d41-5812-480a-af01-b67b5fce2501/477-979
```
Error During Test at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-aarch64-2.0/build/default-macmini-aarch64-2-0/julialang/julia-master/julia-c69dca46bf/share/julia/stdlib/v1.9/Pkg/test/new.jl:2839
  | Got exception outside of a @test
  | git repository not found at `/private/var/tmp/agent-tempdirs/default-macmini-aarch64-2.0/tmp/jl_TlE4la/registry_depot/registries/General`
  | Stacktrace:
  | …
```
> Fix isolate reg symlink override in test, avoid unnecessary and buggy local git clone

- test/runtests.jl
This should fix the timeout errors we see on release-1.8 on windows, where the filesystem is so slow that cleanups are exceeding our 30s worker exit timeout.
Co-authored-by: Dilum Aluthge <dilum@aluthge.com>
Co-authored-by: Ian Butterworth <i.r.butterworth@gmail.com>
(cherry picked from commit 5b365c3c02ec718680ba744a9f48900fb5304951)
> [release-1.8] Cleanup before exit after tests (#3176)

- src/REPLMode/command_declarations.jl
This was documented in `Pkg.add` but the syntax in ReplMode was not clear. This adds an example.
cc @oscardssmith
> add documentation to add subproject in REPLMode

- docs/make.jl
- docs/src/creating-packages.md
- src/API.jl
- src/Operations.jl
- src/Pkg.jl
- src/Registry/registry_instance.jl
- src/Resolve/graphtype.jl
- src/Types.jl
- src/manifest.jl
- src/project.jl
- test/gluedeps.jl
- test/resolve_utils.jl
- test/runtests.jl
- test/test_packages/GluePkgExamples/HasDepWithGluePkgs.jl/Manifest.toml
- test/test_packages/GluePkgExamples/HasDepWithGluePkgs.jl/Project.toml
- test/test_packages/GluePkgExamples/HasDepWithGluePkgs.jl/src/HasDepWithGluePkgs.jl
- test/test_packages/GluePkgExamples/HasDepWithGluePkgs.jl/test/runtests.jl
- test/test_packages/GluePkgExamples/HasGluePkgs.jl/Manifest.toml
- test/test_packages/GluePkgExamples/HasGluePkgs.jl/Project.toml
- test/test_packages/GluePkgExamples/HasGluePkgs.jl/glue/GlueOffsetArrays.jl
- test/test_packages/GluePkgExamples/HasGluePkgs.jl/src/HasGluePkgs.jl
- test/test_packages/GluePkgExamples/HasGluePkgs.jl/test/runtests.jl
Builds on #3264 
(While I was here I added some comments to Pkg.precompile too, in a separate commit)
```
shell> rm -rf ~/.julia/compiled/v1.10
[ Info: Precompiling Pkg [44cfe95a-1eb2-52ea-b672-e2afdf69b79f]
(Pkg) pkg> activate /Users/ian/Documents/GitHub/GluePkgExamples.jl/HasDepWithGluePkgs.jl
Activating project at `~/Documents/GitHub/GluePkgExamples.jl/HasDepWithGluePkgs.jl`
(HasDepWithGluePkgs) pkg> precompile
Precompiling environment...
6 dependencies successfully precompiled in 3 seconds
julia> using HasDepWithGluePkgs
julia> HasDepWithGluePkgs.do_something()
[ Info: First do something with the basic array support in B
┌ Info: HasGluePkgs.jl: A custom logging method for AbstractArray
│   x =
│    2-element Vector{Float64}:
│     0.22960852293312484
└ …
```
> Make `Pkg.precompile` work with glue packages

- src/REPLMode/REPLMode.jl
- src/REPLMode/argument_parsers.jl
- src/REPLMode/completions.jl
- test/repl.jl
Resolves #3215 
The individual commits are standalone, one addresses `APIOptions` and the other `PackageToken`, so they don't have to be squashed.
> Remove weird constructors

- src/HistoricalStdlibs.jl
- src/Types.jl
This fixes invalidations from loading JuliaData ecosystem packages (CSV and DataFrames). I can't remember if it's these changes or some I'll submit to Base shortly, but the invalidations fixed include `Base.require` which tank package load time. It's possible that accounts for the outlier noticed in https://github.com/JuliaLang/julia/pull/47184#issuecomment-1337118968, CC @giordano.
> Fix inference for STDLIBS_BY_VERSION

- src/API.jl
This will likely be needed before https://github.com/JuliaLang/julia/pull/47797 can be merged, to avoid overloading the system.
This leaves speed improvements on the table, but figuring out the load balancing here shouldn't block that PR IMO.
> Disable parallel LLVM image generation for now

- .github/workflows/test.yml
- src/Operations.jl
- test/extensions.jl
- test/pkg.jl
- test/test_packages/ExtensionExamples/HasDepWithExtensions.jl/src/HasDepWithExtensions.jl
- test/test_packages/ExtensionExamples/HasExtensions.jl/ext/OffsetArraysExt.jl
- test/test_packages/ExtensionExamples/HasExtensions.jl/test/runtests.jl
- test/utils.jl
~~It's not clear to me why this didn't fail in #3281 .~~ Urgh.. it was picking up a function and string-ing the name 🤦‍♂️
```
julia> Pkg.Operations.source_path
source_path (generic function with 2 methods)
julia> string("@", Pkg.Operations.source_path)
"@source_path"
```
----
This fixes a rather nasty missing local var bug introduced by #3281 that broke coverage generation in `Pkg.test`, and reinstates and expands testing for coverage files where they should and shouldn't be generated
> Fix broken source_path handling. Explicitly test for coverage files

- docs/src/creating-packages.md
The final quote in `include("../ext/ContourExt.jl)` is missing, which is incorrect and makes the following syntax highlighting slightly funky.
> Quick Fix: Typo in weakdeps Requires.jl fallback example

- docs/src/creating-packages.md
Noticed a tiny typo in the creating packages docs. Figured I'd fix it immediately instead of postponing and looking for more.
> Fix minor typo in extensions section

- .github/workflows/test.yml
- src/REPLMode/command_declarations.jl
- src/generate.jl
- test/new.jl
> release-1.6: undeprecate `generate`

- Project.toml
I'm thinking after this, release-1.9 is branched off this merge commit, then immediately changed on master to 1.10.0-DEV?
Using -DEV might make it easier to keep in step with julia?
> Set version to 1.9.0

- src/API.jl
- src/Operations.jl
- src/Types.jl
- test/project_manifest.jl
- test/runtests.jl
- test/test_packages/monorepo/Project.toml
- test/test_packages/monorepo/packages/B/Project.toml
- test/test_packages/monorepo/packages/B/src/B.jl
- test/test_packages/monorepo/packages/C/Project.toml
- test/test_packages/monorepo/packages/C/src/C.jl
- test/test_packages/monorepo/packages/C/test/runtests.jl
- test/test_packages/monorepo/packages/D/Project.toml
- test/test_packages/monorepo/packages/D/src/D.jl
- test/test_packages/monorepo/src/A.jl
- test/test_packages/monorepo/test/runtests.jl
I recently discovered that loading in Base supports specifying an alternative `Manifest.toml` in a `Project.toml`. While playing around with this though, I discovered that Pkg.jl doesn't play as nice with this. It supports the parsing/storing of it, but gets confused often because so many path calculations are made relative to the _project file_ instead of the now-different manifest file.
This is relevant when there are devv-ed packages in the specified Manifest and the relative path calculations should be made wrt to the _manifest_ not the _project_.
The changes here, hence, are mainly about auditing uses of `env.project_file` and changing them to `env.manifest_file` if necessary. The cases where `manifest_file` should be used, as far as I understand, are where the `PackageSpec` we're …
> Respect manifest if provided in Project.toml

- src/API.jl
I noticed a case (which I can't repro now) where `pkg> precompile` considered everything precompiled, but loading the package still had to recompile. When I debugged, I saw that the check at https://github.com/JuliaLang/julia/blob/fec8304a8c6e2157759b76d20339b426201a5f61/base/loading.jl#L2602-L2606 failed which caused Julia to recompile the package.
However, in Pkg, we only call the 2-arg version of `stale_cachefile` which disables this check https://github.com/JuliaLang/julia/blob/fec8304a8c6e2157759b76d20339b426201a5f61/base/loading.jl#L2554-L2556
This PR copies the recursive checks for staleness in https://github.com/JuliaLang/julia/blob/79ceb8dbeab1b5a47c6bd664214616c19607ffab/base/loading.jl#L1309-L1336 but it adds some caching to prevent checking this for the same package multiple …
> also check build ids when checking for staleness of precompile files

- test/pkg.jl
The julia args (or lack of) need to match here and in the test for pkgimages caches to work
> Fix atomic test for pkgimages

- src/API.jl
If package developers don't use code loading precompilation they currently miss any warnings during precompilation. 
This makes those warnings noisy again.
> precompile: collect and show any stderr output as warnings

- src/Pkg.jl
We quite frequently see Pkg be a source of invalidations in other packages. This should reduce the likelihood of that. The cost is worse inference in Pkg in presence of non precise type information. However, running a workload with:
```
using Pkg, BenchmarkTools
ENV["JULIA_PKG_PRECOMPILE_AUTO"]=0
Pkg.activate(; temp=true)
@btime Pkg.add("DifferentialEquations")
```
I cannot see any difference between master and this PR.
> RFC: set `max_methods` to 1 in Pkg

- src/API.jl
The Pkg scratchspace on my machine had accumulated 3258 of these precompile state cache files, even though they're specific to active project & VERSION.
- Be tidier.. only save them if they have content (🤦‍♂️)
- Let Pkg.gc tidy them up if older than 1 day
```
[ Info: Precompiling Pkg [44cfe95a-1eb2-52ea-b672-e2afdf69b79f]
julia> Pkg.gc()
Active manifest files: 85 found
Active artifact files: 230 found
Active scratchspaces: 41 found
Deleted no artifacts, repos, packages or scratchspaces
julia> using Dates
julia> Pkg.gc(; collect_delay = Dates.Second(1))
Active manifest files: 85 found
Active artifact files: 230 found
Active scratchspaces: 41 found
Deleted 11 artifact installations (148.874 MiB)
Deleted 3258 scratchspaces (236.042 KiB)
```
> Precompile: tidier state cache file handling

- docs/src/creating-packages.md
I'm writing my first package extension, many thanks to @KristofferC and anyone else who help make weakdeps happen. This PR has two independent components:
- some tweaks I made to wording in the existing documentation
- a new subsection that describes ways to handle another mode of extension
Obviously you can pick and choose what you want from this. Also, writing documentation is often a moment for reflection about design, and if you don't like how the 2nd commit reads then perhaps we could talk about alternatives. (I think it's mostly fine, but `register_error_hint` makes things more complicated, and perhaps we could handle this automatically in some way.)
> Docs: polish & expand weakdeps

- test/runtests.jl
Just to reduce noise in julia repo tests
> Make HistoricalStdlibVersions install quiet in tests

- src/GitTools.jl
this might mess up the state of the terminal as described in https://github.com/JuliaLang/Pkg.jl/issues/3068
Should hopefully fix https://github.com/JuliaLang/Pkg.jl/issues/3068.
> prevent passing stdout to git commands

- CHANGELOG.md
- src/API.jl
- src/Pkg.jl
- test/api.jl
Closes #3328 
Uses the non-fancyprint mode to retain rows. It's still parallel, just doesn't show what's currently active, like in CI mode.
```
julia> Pkg.precompile(timing=true)
968.5 ms  ✓ DataValueInterfaces
967.9 ms  ✓ IteratorInterfaceExtensions
993.8 ms  ✓ Zlib_jll
1081.8 ms  ✓ DataAPI
1132.7 ms  ✓ WorkerUtilities
1173.0 ms  ✓ Compat
1252.1 ms  ✓ OrderedCollections
668.9 ms  ✓ TableTraits
1675.4 ms  ✓ TranscodingStreams
881.1 ms  ✓ PooledArrays
670.3 ms  ✓ CodecZlib
2687.1 ms  ✓ SentinelArrays
1117.8 ms  ✓ Tables
1628.8 ms  ✓ FilePathsBase
5431.9 ms  ✓ Preferences
519.7 ms  ✓ SnoopPrecompile
31703.1 ms  ✓ Parsers
1055.2 ms  ✓ InlineStrings
997.5 ms  ✓ WeakRefStrings
29869.7 ms  ✓ CSV
20 dependencies successfully precompiled in 70 seconds
```
cc. @anandijain, …
> precompile: add timing mode

- test/runtests.jl
This isn't tested on Pkg CI, and showed up on julia tests
> Fix hsv install bug

- CHANGELOG.md
- src/API.jl
- src/Operations.jl
- src/Pkg.jl
- src/REPLMode/command_declarations.jl
- test/new.jl
Alternative to https://github.com/JuliaLang/Pkg.jl/pull/3336
This behavior here seems to make more sense as a bug fix for `--all` rather than a new mode.
> make `pin/free --all` apply to all deps

- src/Types.jl
This is due to an oversight on my part in https://github.com/JuliaLang/Pkg.jl/pull/3303 where I didn't realize you could be in a different directory than the currently activated environment. In such a setup, and if the project manually specified a manifest to use, we weren't getting the manifest file path _relative_ to the project directory if the provided path was indeed relative. The fix here is to first check if the manually provided manifest path is already abspath, and if not, ensure we get the abspath _relative_ to the the project directory.
> Fix a minor manifest file detection issue

- src/API.jl
- test/api.jl
Longer is more likely to wrap around and mess up the printing
> precompile: shorten trailing task warning

- docs/src/creating-packages.md
Clarify confusion about directories, make the tutorial more easy to follow by automatically generating the files that are otherwise supposed to be manually created by the user.
Fix #3379.  CC: @owainkenwayucl
> Some improvements to documentation about creating packages

- docs/src/creating-packages.md
- The breaking-changing note was too harsh IMO. It is unlikely that moving to an extension is breaking, at least in the typical usage of extensions.
- Suggest the name of the extension to be `[Parent][Weakdep]Ext`. Having the parent in the name will likely avoid ambiguities when the module is printed in various contexts.
> Various updates to extension documentation

- src/API.jl
- src/Operations.jl
- src/Pkg.jl
- test/new.jl
Alternative to https://github.com/JuliaLang/Pkg.jl/pull/3368. This is a bit of a more "surgical" fix to the issue of jlls getting updated from e.g. `Pkg.add` than trying to fully support build numbers in the resolver etc.
> fixup jll versions that are supposed to stay fixed during e.g Pkg.add

- test/binaryplatforms.jl
These are tested more extensively in `Base`, and we do not need to test specifics of the behaviors of these objects, just that the compatibility wrappers continue to function
> Drop `select_platform()` tests

- docs/src/creating-packages.md
Doing both a top level in a single block yields a `LoadError: UndefVarError: @require not defined` (`@static` doesn't help there).
> Fix usage instructions of weak deps with Requires.jl

- src/Artifacts.jl
- src/utils.jl
- test/artifacts.jl
On windows, `filemode()` doesn't include executable bits.  This is already worked around in `gitmode()` but we don't quite want to do something as intrusive as `gitmode()` in `set_readonly()`; let's just work around this one platform-specific foible.
This fixes problems like executable permissions disappearing when creating artifacts on Windows, packages that contain executable files losing those permissions on install, etc...
> Don't clear executable bits in `set_readonly()` on Windows

- src/API.jl
Bad behavior from unrestricting LLVM image parallelism hasn't really been noticed, since the time spent in the parallel portion is so short and packages that benefit are typically at the tail end of precompilation. Therefore it should be a general speedup to simply allow LLVM to use as many threads as it wants, regardless of external parallelism. If bad behavior is noticed, setting `JULIA_IMAGE_THREADS=1` will return LLVM image compilation back to the original serial mode.
> Revert #3273, unrestrict LLVM parallelism

- src/API.jl
- src/Registry/Registry.jl
I think it is fine to only do the auto registry update on `Pkg.add` ~ once per day.
> only auto update registries on `add` once per day

- src/API.jl
Fixes #3403 
Bug introduced in #3353 #3359 
FYI @fonsp
> precompile: fix `_is_stale` not always ignoring loaded modules

- CHANGELOG.md
- src/API.jl
- src/Operations.jl
- src/Pkg.jl
- src/REPLMode/argument_parsers.jl
- src/REPLMode/command_declarations.jl
- src/Types.jl
- test/new.jl
Updated:
New `PRESERVE_ALL_INSTALLED` preserve strategy that is like `PRESERVE_ALL` except it also only selects installed versions of the new packages. 
New `PRESERVE_TIERED_INSTALLED` strategy that tries `PRESERVE_ALL_INSTALLED` first.
To opt-in to `PRESERVE_TIERED_INSTALLED` being the default set the env var `JULIA_PKG_PRESERVE_TIERED_INSTALLED=true` 
Discussion in:
- https://discourse.julialang.org/t/first-pluto-notebook-launches-are-slower-on-julia-1-9-beta-3/93429/158
- https://github.com/JuliaLang/Pkg.jl/issues/3369
> Add `PRESERVE_ALL_INSTALLED` and `PRESERVE_TIERED_INSTALLED` strategies

- src/PlatformEngines.jl
- src/Registry/Registry.jl
This patch adds verification of registries downloaded from Pkg server when using the default method of keeping registries as compressed tarballs. This verification is done before the registry is moved in place to ensure that a Pkg server that serves bad content does not also poison the users local machine.
> Verify git-tree-sha1 of registry downloads

- CHANGELOG.md
- docs/src/creating-packages.md
- src/API.jl
- src/Operations.jl
- src/Pkg.jl
- src/PlatformEngines.jl
- src/REPLMode/argument_parsers.jl
- src/REPLMode/command_declarations.jl
- src/Registry/Registry.jl
- src/Registry/registry_instance.jl
- src/Types.jl
- test/api.jl
- test/new.jl
> Backports release 1.9

- src/REPLMode/REPLMode.jl
When someone picks "o" from the y/n/o choices, they are explicitly skipping the first environment in the load path, so we should start at the second writable environment in the load path since that's usually the one someone wants to add the package to.
> try_prompt_pkg_add: on "other" default to 2nd env

- src/API.jl
This was fixed in the non-pretty print version but missed here. Just prints `Precompiling Foo` when `pkg> precompile Foo` is requested
> precompile: fix minor print bug

- src/API.jl
- test/extensions.jl
Previously when specifying packages activated extensions were left off.
```
(@v1.10) pkg> precompile CSV
Precompiling environment...
19 dependencies successfully precompiled in 30 seconds. 1 already precompiled.
julia> using CSV
[ Info: Precompiling CompatLinearAlgebraExt [dbe5ba0b-aecc-598a-a867-79051b540f49]
julia> 
```
This PR
```
(@v1.10) pkg> precompile CSV
Precompiling environment...
20 dependencies successfully precompiled in 30 seconds. 1 already precompiled.
julia> using CSV
julia> 
```
> precompile: include extensions when packages are specified

- src/Artifacts.jl
- test/artifacts.jl
This got broken in #3235.
Fixes simeonschaub/ArtifactUtils.jl#19
> fix handling of relative paths in `bind_artifact!`

- src/API.jl
- test/api.jl
Fixes two bugs:
1. Not erroring if the requested package can't be found if the env is empty
```
(@v1.8) pkg> activate --temp
Activating new project at `/var/folders/_6/1yf6sj0950vcg4t91m9ltb5w0000gn/T/jl_COUhTY`
(jl_COUhTY) pkg> precompile DoesNotExist
No Changes to `/private/var/folders/_6/1yf6sj0950vcg4t91m9ltb5w0000gn/T/jl_COUhTY/Project.toml`
No Changes to `/private/var/folders/_6/1yf6sj0950vcg4t91m9ltb5w0000gn/T/jl_COUhTY/Manifest.toml`
(jl_COUhTY) pkg> precompile DoesNotExist
(jl_COUhTY) pkg> 
```
2. Claiming to not find a direct dep but not explaining that its because it was in the sysimage
```
(jl_ucKMh9) pkg> st
Status `/private/var/folders/_6/1yf6sj0950vcg4t91m9ltb5w0000gn/T/jl_ucKMh9/Project.toml`
[9a3f8284] Random
(jl_ucKMh9) pkg> precompile Random
ERROR: No direct …
```
> precompile: improve no match error messaging

- src/Artifacts.jl
- src/PlatformEngines.jl
Helps debug where artifacts are coming from etc.
```
Downloaded artifact: CUDA_Driver
┌ Debug: Downloading artifact from Pkg server
│   name = "CUDA_Runtime"
│   artifacts_toml = "/home/ian/.julia/packages/CUDA_Runtime_jll/F1mcT/Artifacts.toml"
│   platform = Linux x86_64 {cxxstring_abi=cxx11, julia_version=1.10.0, libc=glibc, libgfortran_version=5.0.0, libstdcxx_version=3.4.30}
│   url = "https://pkg.julialang.org/artifact/ebadc1bf983003ca3f714f062af4451365761171"
└ @ Pkg.Artifacts ~/Documents/GitHub/Pkg.jl/src/Artifacts.jl:376
Downloading artifact: CUDA_Runtime
┌ Debug: download and verify failed
│   err = RequestError: HTTP/2 200 (HTTP/2 stream 9 was not closed cleanly: INTERNAL_ERROR (err 2)) while requesting https://pkg.julialang.org/artifact/ebadc1bf983003ca3f714f062af4451365761171 …
```
> add debug info to artifact downloads

- docs/src/creating-packages.md
This is based on a discussion with @KristofferC.
Closes https://github.com/JuliaLang/julia/issues/49497
> update note on package extensions

- src/API.jl
Try again.
Fixes https://github.com/JuliaLang/Pkg.jl/issues/3443
With this `OrdinaryDiffEq` precompiles. It was reported not to by @gbaraldi before revert.
No exts
```
Foo => []
Bar => [Foo]
```
With Exts
```
Foo => []
Foo.Ext1 => [Foo]
Foo.Ext2 => [Foo]
Bar => [Foo.Ext1, Foo.Ext2]
```
Previously we had a racy situation
```
Foo => []
Foo.Ext1 => [Foo]
Foo.Ext2 => [Foo]
Bar => [Foo]
```
where Bar would start up and race to compile the exts with the jobs for Foo.Ext1 & 2
> Reland "precompile: fix race in precompiling exts (#3456)"

- src/REPLMode/REPLMode.jl
When someone picks "o" from the y/n/o choices, they most likely want to choose a different environment than the env affected by the default "y" choice. So, we should start at the first non-default writable environment in the load path.
Recently, #3429 changed the preselection from first to second item. Depending on the LOAD_PATH order, that could select the same env as affected by pressing `y`.
> try_prompt_pkg_add: on "other" preselect the first non-default env

- src/Operations.jl
Fixes https://github.com/JuliaLang/Pkg.jl/issues/3395.
> Use correct threads specification for subprocess

- docs/src/creating-packages.md
- src/API.jl
- src/Operations.jl
- src/Pkg.jl
- src/REPLMode/REPLMode.jl
> [release-1.9] 1.9.1 Backports

- src/API.jl
Reverts JuliaLang/Pkg.jl#3465
There are 600 packages that encounter this on PkgEval which is a bit too many. It suggests something is a bit off here.
> Revert "Reland "precompile: fix race in precompiling exts (#3456)""

- src/Operations.jl
We don't do this, so remove it. Ref: [comment](https://github.com/JuliaLang/julia/pull/49942#issuecomment-1560153612).
> Remove `VERSION` check for threadpools

- src/REPLMode/completions.jl
I think `path_completions` should use shell mode escapes, as Pkg repl mode is shell-like in argument splitting. At least, that's what the four trailing backslashes in the tests seem to indicate at https://github.com/JuliaLang/Pkg.jl/blob/9c01707a20478b859e6fd995b5e16c82e7096d92/test/repl.jl#L388
The current `REPLCompletions.path_completions` has a bug where the trailing double-escaped backslashes will be appended regardless of whether `shell_mode=true` or not. As part of fixing that bug which was exposed by the new parser in https://github.com/JuliaLang/julia/pull/46372 I found this bug in Pkg and now everything is hopelessly entangled because the Pkg tests are now failing over there. Yea, it's a long story :-(
> Ensure `path_completions` uses shell mode escapes

- docs/src/compatibility.md
Currently, `Pkg.jl`'s documentation does not make it clear that package registration in the General Registry requires upper bounds. I think it's worth it to include that information here, since often packages are developed with registration in mind.
This is an updated version of https://github.com/JuliaLang/Pkg.jl/pull/1852
[skipci]
> Docs: Specify that package registration requires compat upper bounds

- src/API.jl
- test/api.jl
Follow-up to https://github.com/JuliaLang/julia/pull/49052
Depends on
- https://github.com/JuliaLang/julia/pull/50214
- https://github.com/JuliaLang/julia/pull/50218
- https://github.com/JuliaLang/julia/pull/50254
> precompile: respect and report cache pidlocking

- test/api.jl
`setenv` -> `addenv` is the main fix
> Fix precompile pidlock test failure on Base CI

- docs/src/compatibility.md
I didn't like the sentence 
> Similar to other package managers, the Julia package manager respects [semantic versioning](https://semver.org/) (semver). As an example, a version specifier given as...
because, strictly speaking, it is false and folks who do not read on to the next paragraph may falsely believe that 0.1.0 and 0.1.1 are incompatible versions.
> Note the exception to SymVer for leading zeros again

- .github/workflows/test.yml
- src/GitTools.jl
- test/new.jl
Without this if you're offline and using the git cli
```
(Pkg) pkg> up
┌ Warning: could not download https://pkg.julialang.org/registries
│   exception = RequestError: Could not resolve host: pkg.julialang.org while requesting https://pkg.julialang.org/registries
└ @ Pkg.Registry ~/Documents/GitHub/julia/usr/share/julia/stdlib/v1.11/Pkg/src/Registry/Registry.jl:69
Updating registry at `~/.julia/registries/HolyLabRegistry`
Updating git-repo `git@github.com:HolyLab/HolyLabRegistry`
ssh: connect to host github.com port 22: Undefined error: 0
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
ERROR: failed process: Process(`git fetch -q git@github.com:HolyLab/HolyLabRegistry …
```
> handle git cli errors as pkgerrors

- src/REPLMode/command_declarations.jl
The API status function documentation (https://pkgdocs.julialang.org/v1/api/#Pkg.status) has a full stop after the first sentence of the 1.8 box, but in the REPL docs page it was missing.
> command_declarations.jl: add missing full stop in status command

- src/API.jl
- src/MiniProgressBars.jl
Fixes https://github.com/JuliaLang/Pkg.jl/issues/3560 
Or more accurately makes it a lot less likely by truncating the lines during the fancy printing to a little less than terminal width.
> precompile: try to prevent wrapping-caused mess during pretty printing

- src/API.jl
Fixes https://github.com/JuliaLang/Pkg.jl/issues/3571
Before
```
shell> rm -rf ~/.julia/compiled/v1.11
(@v1.11) pkg> st
Status `~/.julia/environments/v1.11/Project.toml`
[34da2185] Compat v4.9.0
(@v1.11) pkg> precompile
1 dependency successfully precompiled in 1 seconds
julia> using Compat
[ Info: Precompiling CompatLinearAlgebraExt [dbe5ba0b-aecc-598a-a867-79051b540f49]
```
This PR
```
shell> rm -rf ~/.julia/compiled/v1.11
(@v1.11) pkg> st
Status `~/.julia/environments/v1.11/Project.toml`
[34da2185] Compat v4.9.0
(@v1.11) pkg> precompile
2 dependencies successfully precompiled in 1 seconds
julia> using Compat
julia> 
```
> precompile: also consider sysimage modules that activate extensions

- src/API.jl
- src/Types.jl
It seems the way auto-precompilation only summarizes which packages errored not the verbose error details is unpopular so this ~makes autoprecompilation show errors the way an explicit `Pkg.precompile` does.~
Updated: Now autoprecompilation pipes any errors to `Main.err`
```
✗ PNGFiles
0 dependencies successfully precompiled in 1 seconds. 38 already precompiled.
To see a full report use `julia> err`
julia> err
The following 1 direct dependency failed to precompile:
PNGFiles [f57f5aa1-a3ce-4bc8-8ab9-96f992907883]
Failed to precompile PNGFiles [f57f5aa1-a3ce-4bc8-8ab9-96f992907883] to "/Users/ian/.julia/compiled/v1.11/PNGFiles/jl_X0edfU".
ERROR: LoadError: 
Stacktrace:
[1] error()
@ Base ./error.jl:44
[2] top-level scope
@ …
```
> precompile: pipe error messages during autoprecompilation to Main.err for easier inspection

- docs/src/creating-packages.md
As I understand, installing Requires on new versions isn't needed, so it would make sense to `weakdep` it.
> recommend adding Requires to weakdeps

- src/API.jl
Fixes https://github.com/JuliaLang/Pkg.jl/issues/3566
> precompilation: `warnings` -> `output`

- src/API.jl
Follow up to https://github.com/JuliaLang/Pkg.jl/pull/3536
Given autoprecompilation won't retry things that errored it's helpful to keep a tip here for people to explicitly try `precompile`
> precompile: add retry message

- src/Pkg.jl
- src/REPLMode/command_declarations.jl
- test/api.jl
- test/new.jl
- test/repl.jl
The concept of “home project” was removed in JuliaLang/julia#36434. Also see #1891.
Fixes #3127.
> Remove mentions of “home project” in documentation and comments

- src/API.jl
Somewhere throwing when internal errors occur was lost. This fixes that.
> precompile: stop swallowing internal errors

- src/API.jl
Fixes https://github.com/JuliaLang/Pkg.jl/issues/3548
@vtjnash in particular is the use of a single BufferStream `iob` ok here or should it use two buffers?
> precompilation: capture stdout as well as stderr

- src/Types.jl
- test/misc.jl
Fixes https://github.com/JuliaLang/Pkg.jl/issues/3577
> fix inference of PackageSpec constructor in presence of imprecise input types

- src/API.jl
Fixes https://github.com/JuliaLang/Pkg.jl/issues/3487
@vtjnash something like this, perhaps?
> precompile: if a single package is requested, show output live

- src/Operations.jl
- test/project_manifest.jl
Instead of just skipping manifest pruning all together (which is tricky because we're often _not_ operating in a root-level context which would _correctly_ prune everything), we can at least update the dependency list of the currently activated project in the root-level manifest.
> Update manifest entry of project for non-local manifests

- docs/src/glossary.md
- src/Pkg.jl
Missed a few off because these PRs are older than the backporter was searching for
> [release-1.10] Backports for 1.10

- docs/src/glossary.md
- src/Pkg.jl
> [release-1.9] Backports for 1.9

- src/Types.jl
- test/subdir.jl
If a package we're altering is already in the manifest, we try to load some information from the manifest, but we forgot to load `subdir` in these two cases.
This fixes #3391.
> Fix lacking `subdir` information when altering packages

- src/API.jl
Related to https://github.com/JuliaLang/Pkg.jl/pull/3600
This is one place where it seems good to add the extension parent name as it's shown in the precompile output.
This also removes the uuid from the report to avoid being too long.
```
(@v1.11) pkg> precompile
10 dependencies successfully precompiled in 6 seconds. 22 already precompiled.
2 dependencies had output during precompilation:
┌ PGFPlotsX → ColorsExt
│  some stdout
│  some stderr
└  
┌ PGFPlotsX
│  some other stdout
│  some other stderr
└  
```
> precompile: show ext parent in output report

- src/Operations.jl
Update: Now just a slight tweak to the original message to avoid duplication.
___
The combined Info tip skipped the key word "may" in `may be upgradable` which has been a common source of confusion.
I think it might just be better to show each tip individually if both symbols are present?
Before
This PR
> status: expand 2 symbol upgrade note to highlight *may* be upgradable

- docs/src/creating-packages.md
Alternative proposal to https://github.com/JuliaLang/Pkg.jl/pull/3533
Closes https://github.com/JuliaLang/Pkg.jl/issues/3535
> Tweak test dep docs

- src/Pkg.jl
- src/REPLMode/command_declarations.jl
As discussed in #3547, this adds some clarification on how `LOAD_PATH` is used to set the active project when using the no-argument form of `Pkg.activate()`.
> Clarify handling of `LOAD_PATH` in docstring and REPL help

- src/Versions.jl
- test/pkg.jl
It is an unfortunate coincidence that if you try to print out a `VersionSpec` to a project's `compat` field, it can be in a format that `semver_spec()` rejects due to the ambiguity of `1.2.0-1.4.0` being either a prerelease with a very strange prerelease tag, or a range of versions.  We reduce the ambiguity by changing `VersionSpec` to always print its bounds with a separating space.
> Ensure that `string(::VersionSpec)` is compatible with `semver_spec()`

- src/Operations.jl
This is to prevent https://github.com/JuliaLang/Pkg.jl/issues/3442 when moving Pkg out of the sysimage.
> tweak how Pkg is loaded for precompiling when testing

- docs/src/creating-packages.md
This PR is an extension of https://github.com/JuliaLang/julia/pull/50105 and should be merged or closed simultaneously.
The key sentence is 
> Unless you note otherwise, the public API of your package is defined as all the behavior you
describe about exported symbols
And the reason this definition is viable is that scoped exports allow you to export symbols without the namespace implications.
> Document how public API is defined (depends on scoped export)

- src/API.jl
- src/Pkg.jl
The new `UnstableIO` is good for latency but it seems to be a bit too big runtime penalty for precompile which outputs a lot of text to the terminal.
> make precompile unwrap UnstableIO

- src/Operations.jl
- src/Types.jl
- test/manifest/old/Manifest.toml
- test/manifest/old/Project.toml
- test/new.jl
This should prevent errors like:
```
ERROR: Could not locate the source code for the DelimitedFiles package. Are you trying to use a manifest generated by a different version of Julia?
```
When using older manifests that list DelimitedFiles in the stdlib format even though DelimitedFiles now is upgradable and has e.g. a `git-tree-sha1` entry when generated with current Pkg
> Make Pkg more resilient to reading older manifests where ex-stdlibs are listed

- src/Operations.jl
this should not be needed after https://github.com/JuliaLang/julia/pull/39572 (I think)
Backporting because this fixes an issue that occurs when doing package management operations inside a test process for julia versions where an upgradable stdlib was a standard stdlib without a version entry.
> remove writing out explicit stdlib paths for the temporary testing manifest

- .github/workflows/test.yml
- src/API.jl
- src/Operations.jl
- src/Types.jl
- test/manifest/old/Manifest.toml
- test/manifest/old/Project.toml
- test/new.jl
> [release-1.10] Backports 1.10

- src/Pkg.jl
Otherwise this reenabled it during the first pkg repl switch
> Respect if load-time precompile is disabled

- src/API.jl
In the same project as #3651, this code was also having trouble because of the rapidly growing alldeps, which would end up with many repeated entries. Switch the data structure to fix the algorithmic complexity here also.
> Switch datastructure Vector -> Set for algorithmic complexity

- src/API.jl
The circular dependency detection in `precompile` has poor algorithmic complexity. In a project with deep and broad dependency trees of hundreds of packages, this introduces a significant delay before the start of precompilation work. Fix that by switching the cycle detection to a simple open-coded DFS walk.
> Fix algorithmic complexity of cycle detection

- test/api.jl
x-ref: https://github.com/JuliaLang/julia/pull/51432#issuecomment-1758460235
> Remove test that depends on Random being in the sysimg

- src/precompile.jl
> Precompilation workload: set `"JULIA_PKG_UNPACK_REGISTRY" => nothing`

- src/REPLMode/command_declarations.jl
- src/REPLMode/completions.jl
- test/repl.jl
> Only complete fixed packages for `pkg> free`

- .github/workflows/test.yml
- src/API.jl
- src/Operations.jl
- test/new.jl
> [release-1.9] 1.9 backports

- .github/workflows/test.yml
- src/API.jl
- src/Operations.jl
- src/Pkg.jl
- test/new.jl
> [release-1.10] 1.10 backports

- Project.toml
- test/runtests.jl
- test/utils.jl
Both GitHub CI here and buildkite CI on the julia repo restore the fs to a clean state, likely faster than doing it within the julia process, so we don't need to spend time tidying up.
> Don't clean test temp files

- src/API.jl
This check forced packages to recompile if triggers for extensions of their dependencies were added.
This could be reproduced the following way:
- Add `ColorSchemes`
- Precompile
- Add `SpecialFunctions`
- Notice that `ColorSchemes` now required precompilation again because the extension of SpecialFunctions in ColorVectorSpace is now "active".
The last step doesn't make sense because the extension SpecialFunctions doesn't influence ColorSchemes in any way.
This check should in theory just be removable since `Base.isprecompiled` should handle checking that all dependencies are valid for the package being precompiled.
> remove recompilation dependency check in Pkg.precompile

- src/precompile.jl
This deletes the two commented `end` statements and then reindents the `withenv` block.
> Fix indentation in precompile.jl

- src/API.jl
Co-authored-by: Ian Butterworth <i.r.butterworth@gmail.com>
(cherry picked from commit debc38b9a2d800f035a17f42a01c14a3775fa859)
> Backport 1.9: remove recompilation dependency check in Pkg.precompile (#3696)

- docs/src/creating-packages.md
Not sure why this breaks the docs but we can't merge anything without the docs building so just do the easy "fix".
> fix doc build by not `@ref`fing `Base.get_extension`

- src/Operations.jl
Fixes https://github.com/JuliaLang/Pkg.jl/issues/3687 (identified by @KristofferC on Slack)
Before:
```julia
(@v1.10) pkg> build ModernGL
Building ModernGL → `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/b76ea40b5c0f45790ae09492712dd326208c28b2/build.log`
ERROR: Error building `ModernGL`: 
ERROR: LoadError: ArgumentError: Package LinearAlgebra not found in current path.
- Run `import Pkg; Pkg.add("LinearAlgebra")` to install the LinearAlgebra package.
Stacktrace:
[1] macro expansion
@ Base ./loading.jl:1766 [inlined]
[2] macro expansion
@ Base ./lock.jl:267 [inlined]
[3] __require(into::Module, mod::Symbol)
@ Base ./loading.jl:1747
[4] #invoke_in_world#3
@ Base ./essentials.jl:921 [inlined]
[5] invoke_in_world
@ Base ./essentials.jl:918 [inlined]
[6] require(into::Module, …
```
> Use `startup=no` during `build` unless julia session explicitly set `startup=yes`

- Project.toml
- docs/src/managing-packages.md
- src/API.jl
I think this should be emphasized as "the" way to get the versions you want. Many times folks fight with the resolver to get it to resolve they way they want, when the declarative approach with compat is better. Therefore I think `compat` belongs in the basic starting instructions.
> Suggest using `compat` to choose versions of packages

- .github/workflows/test.yml
- test/new.jl
- test/runtests.jl
Best I can do is only this leaking.
```
Username for 'https://github.com/': Username for 'https://github.com/':
```
To do better than that we would need to reduce test coverage, or fix git cli https auth on CI, which seems difficult to figure out.
Otherwise everything is now piped into the Pkg.log which is uploaded as matrix-specific artifacts here and similar on buildkite.
> Make tests almost entirely quiet

- docs/src/glossary.md
- src/Types.jl
Reverts https://github.com/JuliaLang/Pkg.jl/pull/3000
and adapts for the latest https://github.com/JuliaLang/julia/pull/43845
Because the lengths of the `Base.project_names` and `Base.manifest_names` tuples have diverged, we can no longer rely on idx lookups, so this just does a bit more hardcoding.
> fix preferential Manifest.toml naming

- src/API.jl
- src/Pkg.jl
- test/manifests.jl
The API function `is_manifest_current` was not working as intended and was mostly useless for its intended purpose of verifying in tests that the manifest and project files of a package were synchronized. See 
https://github.com/JuliaLang/Pkg.jl/pull/2815#issuecomment-1819237619 for details.
This PR removes the zero-argument method of `is_manifest_current` and adds a new `is_manifest_current(::AbstractString)` method that can be used in tests in, e.g., the form
```
using Pkg, Test, Package
@test Pkg.is_manifest_current(pkgdir(Package))
```
> Revise the API of is_manifest_current.

- docs/src/environments.md
1.8 -> 1.9, 1.8.2 -> 1.9.4 (current version)
> docs/src/environments.md: update Julia version

- src/Operations.jl
Fixes https://github.com/JuliaLang/Pkg.jl/issues/3737
`julia_cmd()` now handles this
https://github.com/JuliaLang/julia/blob/abb7e3074b75c85b409320ccc7d9f5e9e9adb4a3/base/util.jl#L208-L209
@maleadt
> rm old manual handling of `--compiled-modules`

- CHANGELOG.md
- src/Operations.jl
- src/Pkg.jl
- src/REPLMode/command_declarations.jl
- test/new.jl
- test/repl.jl
Closes https://github.com/JuliaLang/Pkg.jl/issues/776
If the current environment is a package this makes `pkg> add` auto add compat entries for the new direct dependencies.
I don't think we'd want to make this standard practice for the default envs, hence being specific to packages, but maybe there's an argument that it should be done for unnamed environments other than the defaults? Like the envs stored alongside scripts.
The compat entries are set to be lower-bounded by the installed patch version (which makes this work for JLLs).  
It feels safer than relying on semver and setting it to `Base.thisminor(v)`.
> Automatically add compat entries when adding deps to a package

- CHANGELOG.md
- src/API.jl
- src/Operations.jl
- src/Pkg.jl
- src/REPLMode/command_declarations.jl
- src/Types.jl
- test/extensions.jl
- test/new.jl
> add `add --weak/extra Foo` to add to [weakdeps] or [extras]

- test/runtests.jl
So that `make testall` is reasonable by default
> Send verbose test output to devnull by default

- src/Artifacts.jl
- test/artifacts.jl
Step one of addressing https://github.com/JuliaLang/Pkg.jl/issues/3643. I implemented this by providing a default for the `ignore_hash` value in `download_artifact`, namely the default value is false unless the OS is Windows and the user cannot create symlinks in the artifact directory, in which case we default `ignore_hash` to true instead. This still emits a warning, which seems desirable based on the discussion in #3643.
> ignore tree hashes on Windows w/o symlink capability

- src/Artifacts.jl
- test/artifacts.jl
Followup to https://github.com/JuliaLang/Pkg.jl/pull/3764
Fixes bug reported in https://github.com/JuliaLang/Pkg.jl/issues/3643#issuecomment-1905048298
This PR modifies `download_artifact` to avoid calling `mv(src, dst; force=true)` where `src` and `dst` are both possible valid artifacts.
The main steps of `download_artifact` are
1. Return `true` if the artifact already exists.
1. Determine the expected artifact path and parent directory.
2. Make a temporary directory.
3. `download_verify_unpack` into the temporary directory.
4. Calculate the tree hash of the temporary directory.
5. If the tree hash doesn't match, either throw an error or log an error, depending on the enviroment.
6. Atomically move the temporary directory to the expected path.
7. Try to clean up the temporary directory. …
> Avoid deleting existing artifacts when ignoring hashes.

- src/API.jl
Fixes https://github.com/JuliaLang/Pkg.jl/issues/3466
Before
```
(@v1.11) pkg> why Sockets
Sockets
```
This PR
```
(@v1.11) pkg> why Sockets
PreallocationTools → ForwardDiff → DiffRules → SpecialFunctions → OpenSpecFun_jll → Pkg → REPL → Sockets
PreallocationTools → ForwardDiff → SpecialFunctions → OpenSpecFun_jll → Pkg → REPL → Sockets
Revise → Distributed → Sockets
Revise → Pkg → REPL → Sockets
Revise → REPL → Sockets
Sockets
Symbolics → DiffRules → SpecialFunctions → OpenSpecFun_jll → Pkg → REPL → Sockets
Symbolics → Distributions → SpecialFunctions → OpenSpecFun_jll → Pkg → REPL → Sockets
Symbolics → Distributions → StatsFuns → HypergeometricFunctions → DualNumbers → SpecialFunctions → OpenSpecFun_jll → Pkg → REPL → Sockets
Symbolics → Distributions → StatsFuns → …
```
> why: show all paths when package is both a direct and indirect dep

- test/new.jl
This feature is buggy (see https://github.com/JuliaLang/julia/pull/51869#issuecomment-1919283187 for an explanation) and it is preventing us from adding any new dependencies (that didn't exist in old Julia versions) to stdlibs.
cc @staticfloat
> disable `julia_version` tests

- src/Pkg.jl
- src/Registry/Registry.jl
- test/extensions.jl
- test/new.jl
- test/registry.jl
From https://github.com/JuliaLang/Pkg.jl/pull/1358#issue-490784060:
>  ideally this should be added for the Pkg.Registry module as well but that might be a later project...
Well, here it is.
This is done without metaprogramming since there are only three functions and the method for interpreting a vector of named tuples as a vector of `RegistrySpec` is not included, and I'm not sure it's worth adding it for the `Registry` functions.
> Simplify Pkg.Registry APIs.

- .github/workflows/test.yml
It feels a little bit excessive to me to test both arm and intel on mac since there isn't really many code paths in Julia (and especially Pkg) that are architecture dependent like this
> RFC: stop testing non-ARM on mac on CI

- ext/REPLExt/REPLExt.jl
Previously, `prepare_cmd` was outside the lock.
fixes https://github.com/JuliaLang/Pkg.jl/issues/3787
> Prevent repl crash on invalid command

- src/API.jl
- src/Operations.jl
- test/test_packages/SandboxFallback2/Manifest.toml
- test/test_packages/SandboxFallback2/dev/Unregistered/Manifest.toml
- test/test_packages/SandboxFallback2/dev/Unregistered/test/Manifest.toml
- test/test_packages/Sandbox_PreserveTestDeps/dev/Foo/test/Manifest.toml
Requires https://github.com/JuliaLang/julia/pull/53316
> do not start a new process for precompiling the test env

- ext/REPLExt/precompile.jl
- src/precompile.jl
Avoids 
```
JULIA stdlib/REPLExt.release.image
JULIA stdlib/LazyArtifacts.release.image
JULIA stdlib/LazyArtifacts.release.image
│ Attempted to find missing packages in package registries but no registries are installed.
└ Use package mode to install a registry. `pkg> registry add` will install the default registries.
JULIA stdlib/REPLExt.release.image
│ Attempted to find missing packages in package registries but no registries are installed.
└ Use package mode to install a registry. `pkg> registry add` will install the default registries.
```
Pkg.jl precompile.jl does this, which is why it didn't show before, I believe.
I guess it means the registry stuff isn't baked in properly.. but that would need a better fix i.e. https://github.com/JuliaLang/Pkg.jl/pull/2833
> avoid registry warning during precompile

- test/artifacts.jl
This was breaking `mktemp` & `mktempdir` in the subprocess because it meant the `TMPDIR` env var wasn't set.
> Fix incorrect use of `setenv` in Artifact tests

- CHANGELOG.md
- docs/src/toml-files.md
- src/API.jl
- src/Operations.jl
- src/Types.jl
- src/precompile.jl
- src/project.jl
- test/runtests.jl
- test/sources.jl
- test/test_packages/WithSources/BadManifest.toml
- test/test_packages/WithSources/LocalPkg/Project.toml
- test/test_packages/WithSources/LocalPkg/src/LocalPkg.jl
- test/test_packages/WithSources/Project.toml
- test/test_packages/WithSources/TestWithUnreg/Project.toml
- test/test_packages/WithSources/TestWithUnreg/src/TestWithUnreg.jl
- test/test_packages/WithSources/TestWithUnreg/test/runtests.jl
Extracted and tweaked based on https://github.com/JuliaLang/Pkg.jl/pull/3263.
Currently requires https://github.com/JuliaLang/julia/pull/53233
Some questions:
- What happens if you have a source for a URL and then you `add` the package with another URL? Error or update the source?
- Same as above but with a `path`.
- What should `free` do when there is a source specified.
TODO:
> Support a `[sources]` section in Project.toml for specifying paths and repo locations for dependencies

- src/API.jl
Annoying to have this error when using a slightly old julia version.
> make `delayed_delete_dir` usage a bit more backwards compatible

- src/Operations.jl
Fixes https://github.com/JuliaLang/julia/issues/53572
> test env precompile: move threads assignment after precompilation

- src/API.jl
- src/Operations.jl
`flags_cacheflags` was deprecated to `configs` which can also now be a vector of configs
> precompile: update kwargs

- src/API.jl
- src/Operations.jl
Should fix docs build on https://github.com/JuliaLang/julia/pull/53543
> [release-1.11] 1.11 Backports

- src/Operations.jl
- src/Types.jl
- test/extensions.jl
- test/test_packages/TestWeakDepProject/Project.toml
Fixes https://github.com/JuliaLang/Pkg.jl/issues/3814
Need to add a test (and fix CI apparently).
> collect e.g. weak deps from project even if it is not a package

- README.md
The comment about changing the UUID no longer applies.
It may also be worth removing these bullet points entirely since the Pkg dev workflow seems to be the same as every other package (except the paragraph about the julia source build with custom Pkg).
> Remove outdated UUID instructions

- src/Artifacts.jl
Previously, an artifact that failed to download might print like this:
```
(proj) pkg> instantiate
Downloaded artifact: Example
Downloaded artifact: Example
ERROR: Unable to automatically download/install artifact 'Example' from sources listed in ...
```
With this change, that becomes:
```
(proj) pkg> instantiate
Failure artifact: Example
Failure artifact: Example
ERROR: Unable to automatically download/install artifact 'Example' from sources listed in ...
```
> Report failures to download artifacts as failures

- src/Operations.jl
- test/extensions.jl
Fixes https://github.com/JuliaLang/Pkg.jl/issues/3797
> make `add` and `dev` on a package remove it from the set of weak dependencies

- src/Operations.jl
Fixes the manifest pruning issue in https://github.com/JuliaLang/Pkg.jl/issues/3863.
Before we run this fixup code we do not know which deps are weak and not (all are considered normal deps). Or well, we kind of know but we don't have the information easily retrievable. Manifest pruning before this stage will not prune orphan entries which are weak deps of some package which is why in #3863 Enzyme was not pruned away (it is a weak dep of DiffEqBase).
Solve this by just pruning after we have categorized things into weak/normal deps.
> prune manifest after the set of some deps have been "demoted" to weakdeps

- ext/REPLExt/REPLExt.jl
- src/API.jl
- src/Operations.jl
@Keno was annoyed that calling `using` on some small package and having it auto install compiled the whole env. This disables that. I still think https://github.com/JuliaLang/Pkg.jl/pull/3848 is better but since that has some push back, this solves the immediate issue.
> do not precompile full env on `using` callback from REPL

- ext/REPLExt/completions.jl
Fixes https://github.com/JuliaLang/julia/issues/54154
> guard against isdir EACESS in completions

- ext/REPLExt/REPLExt.jl
Unused here currently, but https://github.com/JuliaLang/julia/pull/54311 introduces it as part of the completion API
> REPLExt: add hint kwarg to `complete_line`

- src/API.jl
Reduces code duplication and fixes lack of pluralization when trying to pretty print 2-1024 bytes.
Closes https://github.com/JuliaLang/Pkg.jl/pull/3799.
> Use `Base.format_bytes`

- ext/REPLExt/REPLExt.jl
- ext/REPLExt/precompile.jl
- src/precompile.jl
Measurement:
```
julia> using Pkg, REPL
julia> const REPLExt = Base.get_extension(Pkg, :REPLExt)
REPLExt
julia> @time @eval REPLExt.do_cmds(Base.active_repl, "st")
Project Pkg v1.12.0
Status `~/JuliaPkgs/Pkg.jl/Project.toml`
[56f22d72] Artifacts v1.11.0
[ade2ca70] Dates v1.11.0
[f43a241f] Downloads v1.6.0
[7b1f6079] FileWatching v1.11.0
[76f85450] LibGit2 v1.11.0
[8f399da3] Libdl v1.11.0
[56ddb016] Logging v1.11.0
[d6f4376e] Markdown v1.11.0
[de0858da] Printf v1.11.0
[9a3f8284] Random v1.11.0
[ea8e919c] SHA v0.7.0
[fa267f1f] TOML v1.0.3
[a4e569a6] Tar v1.10.0
[cf7118a7] UUIDs v1.11.0
[3f19e933] p7zip_jll v17.5.0+0
```
Before:
```
1.232465 seconds (4.30 M allocations: 254.177 MiB, 7.91% gc time, 79.78% compilation time: 3% of which was recompilation)
```
After
```
0.629539 seconds (1.92 M …
```
> improve precompilation for `st` in the Pkg REPL

- src/Operations.jl
For example:
```
~/.julia/packages/CUDA_Runtime_jll/bmudn/.pkg
❯ julia +1.11 -e '@time include("select_artifacts.jl")'              
0.683743 seconds (1.76 M allocations: 89.895 MiB, 4.46% gc time, 92.52% compilation time)
~/.julia/packages/CUDA_Runtime_jll/bmudn/.pkg
❯ julia +1.11 --compile=min -e '@time include("select_artifacts.jl")'
0.068991 seconds (66.94 k allocations: 3.780 MiB, 18.29% compilation time)
```
However, this speedup is only achieved when this line fails: https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/blob/03e87cefa86f0d91b4a3fdf068c5474bdb13c4a1/.pkg/platform_augmentation.jl#L95-L99.
When this succeeds we get:
```
julia +1.11 --compile=min -e '@time include("select_artifacts.jl")'
...
0.423333 seconds (612.17 k allocations: 36.343 MiB, 14.89% compilation …
```
> run artifact selection code with minimal compilation

- src/Registry/registry_instance.jl
- src/Types.jl
This assumption will be broken by #54739 and not recoverable, so we need to first fix this Pkg bug. Since print is only in TOML (the stdlib), this still needs the TOML package as well. Since some of the helpers are only in TOML, this only changes the places that use Base.TOMLCache features directly (not upgradable) with added Dates support, but uses TOML for everything else.
Fixes JuliaLang/julia#53196
> use the correct TOML.Parser coupled to Base.TOMLCache

- ext/REPLExt/completions.jl
Should fix #3916 (haven't tested)
> avoid returning empty completion when aborting to not have it inline directories

- test/runtests.jl
Fixes https://github.com/JuliaLang/Pkg.jl/issues/3929
Given this branch isn't touched on this CI
```
% julia  
_
_       _ _(_)_     |  Documentation: https://docs.julialang.org
(_)     | (_) (_)    |
_ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
| | | | | | |/ _` |  |
| | |_| | | | (_| |  |  Version 1.10.4 (2024-06-04)
_/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |
(@v1.10) pkg> activate --temp
Activating new project at `/var/folders/1z/jf841bdj73bdj3vk7kc7f_3w0000gn/T/jl_0iHV55`
julia> Pkg.add(name="HistoricalStdlibVersions", version="1.2")
Updating `/private/var/folders/1z/jf841bdj73bdj3vk7kc7f_3w0000gn/T/jl_0iHV55/Project.toml`
⌃ [6df8b67a] + HistoricalStdlibVersions v1.2.4 …
```
> Fix HistoricalStdlibVersions install to version

- ext/REPLExt/REPLExt.jl
Re. https://github.com/JuliaLang/Pkg.jl/issues/3933#issuecomment-2184088297
This was here because I wasn't sure whether it was possible for the `__init__` to be run multiple times. But that seems to be guaranteed to not be allowed.
> rm `empty!` on `install_packages_hooks`

- src/Types.jl
Before
```
(@v1.12) pkg> activate /Users/ian/Documents/Foo.jl/Manifest.toml
Activating project at `~/Documents/Foo.jl`
ERROR: MethodError: Cannot `convert` an object of type Vector{Any} to an object of type UInt128
The function `convert` exists, but no method is defined for this combination of argument types.
convert(::Type{T}, ::T) where T<:Number
@ Base number.jl:6
convert(::Type{T}, ::T) where T
@ Base Base.jl:126
convert(::Type{T}, ::Number) where T<:Number
@ Base number.jl:7
...
Stacktrace:
[1] Base.UUID(value::Vector{Any})
@ Base ./uuid.jl:9
[2] read_project_deps(raw::Dict{String, Any}, section_name::String)
@ Pkg.Types ~/Documents/GitHub/julia/usr/share/julia/stdlib/v1.12/Pkg/src/project.jl:52
[3] Pkg.Types.Project(raw::Dict{String, Any}; file::String)
@ …
```
> catch if the active project is erroneously set to a manifest file

- src/Operations.jl
Fixes https://github.com/JuliaLang/Pkg.jl/issues/3789
Simplifies by calling `up` on the temp env, and shows the diff.
There are two status prints if this happens. 
```
(Foo) pkg> test
Testing Foo
Sandbox Could not use exact versions of packages in manifest. Re-resolving dependencies
Updating `/private/var/folders/1z/jf841bdj73bdj3vk7kc7f_3w0000gn/T/jl_BtmYKR/Project.toml`
[5d742f6a] + CSVFiles v1.0.2
[324d217c] + ReferenceTests v0.10.3
[860ef19b] + StableRNGs v1.0.1
Updating `/private/var/folders/1z/jf841bdj73bdj3vk7kc7f_3w0000gn/T/jl_BtmYKR/Manifest.toml`
[fbe9abb3] + AWS v1.90.4
...
⌃ [b22a6f82] ↓ FFMPEG_jll v4.4.4+1 ⇒ v4.4.2+2
⌃ [0234f1f7] ↓ HDF5_jll v1.14.2+1 ⇒ v1.12.2+2
[e33a78d0] - Hwloc_jll v2.10.0+0
[7cb0a576] - MPICH_jll v4.1.2+1
[f1f71cc9] - MPItrampoline_jll v5.3.1+1
⌅ …
```
> if re-resolve is needed instead run update and show diff

- src/PlatformEngines.jl
Fixes https://github.com/JuliaLang/Pkg.jl/issues/2928
The error that Downloads.download throws when out of space (on a Mac) is 
```
julia> Downloads.download("https://julialang-s3.julialang.org/bin/mac/aarch64/1.10/julia-1.10.4-macaarch64.dmg", "/Volumes/RAMDisk/file")
ERROR: SystemError: flush: No space left on device
Stacktrace:
[1] systemerror(p::String, errno::Int32; extrainfo::Nothing)
@ Base ./error.jl:176
[2] systemerror
@ ./error.jl:175 [inlined]
[3] flush(s::IOStream)
@ Base ./iostream.jl:70
[4] arg_write(f::Downloads.var"#8#17"{Base.DevNull, Nothing, Vector{…}, Float64, Nothing, Bool, Nothing, Bool, String, Bool, Bool}, arg::IOStream)
@ ArgTools ~/.julia/juliaup/julia-1.10.4+0.aarch64.apple.darwin14/share/julia/stdlib/v1.10/ArgTools/src/ArgTools.jl:136
[5] #7
@ …
```
> Don't retry artifact downloads on `SystemError`, like `no space left on device`

- src/BinaryPlatforms_compat.jl
Currently, Pkg.BinaryPlatforms does `using Base.BinaryPlatforms`. This pull request itemizes the symbols used explicitly.
> Pkg.BinaryPlatforms: Explicitly itemize Base.BinaryPlatforms usage

- ext/REPLExt/completions.jl
- src/HistoricalStdlibs.jl
- src/Operations.jl
- src/Types.jl
- test/Project.toml
- test/new.jl
- test/resolve.jl
- test/runtests.jl
This makes use of the new functionality in HistoricalStdlibVersions [0]
to properly pull out the dependency information in old stdlibs.  This
fixes https://github.com/JuliaPackaging/HistoricalStdlibVersions.jl/issues/9.
[0] https://github.com/JuliaPackaging/HistoricalStdlibVersions.jl/pull/23
> Use historical stdlib dependency information

- CHANGELOG.md
Move the remark in the changelog to 1.11
According to Kristoffer Carlsson at State of Julia 2024, this is in 1.11.
Confirmed by testing with 1.11-rc1
> [sources] is available in 1.11

- test/runtests.jl
@staticfloat I think this was needed in #3911
The `test/Project.toml` compat was updated but Base julia uses this to install HSV
> Fix HSV version

- docs/src/environments.md
- src/Pkg.jl
- src/PlatformEngines.jl
- src/REPLMode/command_declarations.jl
- src/REPLMode/completions.jl
- src/Types.jl
- test/runtests.jl
> [release-1.10] Backports release 1.10

- src/PlatformEngines.jl
Fixes the issue where downloading i.e. MKL during precompilation causes the trailing task warning.
It's already fixed on 1.11+ because finalizers (the global Downloader finalizer) runs before the trailing task detector on 1.11+
> [release-1.10] Fix the trailing task warning on lazy artifacts

- src/Operations.jl
- src/Pkg.jl
Without this artifact downloads have not been printed...
> fix artifact printing quiet rule

- ext/REPLExt/completions.jl
- src/Operations.jl
- src/REPLMode/REPLMode.jl
- src/REPLMode/command_declarations.jl
Fixes https://github.com/JuliaLang/julia/issues/54906
The problem was that `get_extension` is failing to find REPLExt when Pkg is loaded via `require_stdlib`.
> don't use `get_extension` to bridge REPLExt to REPLMode

- src/Pkg.jl
Should have been documented in https://github.com/JuliaLang/Pkg.jl/pull/3178
> Pkg.test: document that coverage can be a string

- test/runtests.jl
Fixes #3940. HistoryicalStdlibVersions has no dependencies, so the registry should not be required to install it.
> Use more internal Pkg.add api to bypass auto-registry-install

- src/Types.jl
> Make manifest usage log errors non-fatal

- docs/src/environments.md
- ext/REPLExt/REPLExt.jl
- ext/REPLExt/completions.jl
- src/Operations.jl
- src/Pkg.jl
- src/PlatformEngines.jl
- src/REPLMode/REPLMode.jl
- src/REPLMode/command_declarations.jl
- src/Registry/Registry.jl
- src/Types.jl
> Backports release 1.11

- src/Types.jl
- src/fuzzysorting.jl
Fixes https://github.com/JuliaLang/Pkg.jl/issues/3958
IIUC `FuzzySorting.printmatches` uses a threshold of < 0.5 to ignore results, not zero.
https://github.com/JuliaLang/Pkg.jl/blob/a66ab60b9bd5e9ed5c147a82e0130d72863e40a8/src/fuzzysorting.jl#L144
```
(Pkg) pkg> up nomatchname
Updating registry at `~/.julia/registries/General.toml`
ERROR: The following package names could not be resolved:
* nomatchname (not found in project or manifest)
```
```
(jl_uMrfTz) pkg> add VideoIOI
ERROR: The following package names could not be resolved:
* VideoIOI (not found in project, manifest or registry)
Suggestions: VideoIO FileIO GeoIO
```
> fix suggestions threshold for printing

- test/artifacts.jl
- test/extensions.jl
- test/new.jl
- test/pkg.jl
- test/registry.jl
- test/repl.jl
- test/test_packages/ArtifactOverrideLoading/Project.toml
- test/test_packages/ArtifactOverrideLoading/src/ArtifactOverrideLoading.jl
- test/utils.jl
- test/workspaces.jl
Fixes https://github.com/JuliaLang/Pkg.jl/issues/3969
I am thinking we might be precompiling stdlibs over and over since we won't find the precompile files for those if we do not have the bundled depots in the depot path.
If this is useful this should have a bit smaller CI runtime.
> Append bundled depots to places where we empty it during tests

- src/Registry/registry_instance.jl
- src/Types.jl
Adapting to https://github.com/JuliaLang/julia/pull/54755/ and https://github.com/JuliaLang/julia/pull/55017
> Use `Base.TOML.Parser{Dates}` for TOML parsing w/ Dates support

- src/PlatformEngines.jl
:embarassing-bugfix:
Fixes bug introduced in https://github.com/JuliaLang/Pkg.jl/pull/3932
This needs to get into 1.10.5 as  https://github.com/JuliaLang/Pkg.jl/pull/3932 is queued up on https://github.com/JuliaLang/julia/pull/54851 @KristofferC
> fix always repeating downloads 3 times

- src/PlatformEngines.jl
- src/Registry/Registry.jl
1) There was no confirmation after the compressed registry was downloaded
Fixes https://github.com/JuliaLang/Pkg.jl/issues/3747
___
2) Downloads.jl shortcuts creating an async task if progress == nothing  https://github.com/JuliaLang/Downloads.jl/blob/29954592f49052159af2cce536f0f4e11efe540b/src/Downloads.jl#L400
___
3) Skip showing the progress bar during the initial header download to prevent it looking glitchy
Fixes #3977
> Download progress fixes. Show compressed registry add confirmation.

- src/Operations.jl
Following a discussion on Slack with @KristofferC and @MasonProtter, it would be good to have better test env merging in the future LTS.
This PR takes the changes of #3276 and adds them to the `release-1.10` branch. Disclaimer: I have zero clue what this code does, this is pure copy-pasting.
> Backport #3276 to 1.10

- src/API.jl
1.10 version of https://github.com/JuliaLang/julia/pull/55432
```
(@v1.10) pkg> precompile
✗ SimpleLooper
0 dependencies successfully precompiled in 1 seconds. 7 already precompiled.
ERROR: The following 1 direct dependency failed to precompile:
SimpleLooper [ff33fe5b-d8e3-4cbd-8bd9-3d2408ff8cab]
Failed to precompile SimpleLooper [ff33fe5b-d8e3-4cbd-8bd9-3d2408ff8cab] to "/Users/ian/.julia/compiled/v1.10/SimpleLooper/jl_y7CN8M".
ERROR: LoadError: 
Stacktrace:
[1] error()
@ Base ./error.jl:44
[2] top-level scope
@ ~/Documents/GitHub/SimpleLooper.jl/src/SimpleLooper.jl:3
```
```
(@v1.10) pkg> precompile
^C Interrupted: Exiting precompilation...            ]  0/1
◑ SimpleLooper
1 dependency had output during precompilation:
┌ SimpleLooper
│ …
```
> [release-1.10] fix swallowing internal errors in Pkg.precompile

- src/API.jl
Should hopefully fix one of the causes of https://github.com/JuliaLang/Pkg.jl/issues/3984.
> backport extension dependency modeling from Base 1.11 to Pkg 1.10

- src/Operations.jl
Resolves https://github.com/JuliaLang/Pkg.jl/issues/3885.
I could use a bit of help to add an appropriate test - Looks like this was regressed in https://github.com/JuliaLang/Pkg.jl/pull/3732
> Fix handling of `PackageSpec` with un-specified version

- src/API.jl
Fixes https://github.com/JuliaLang/Pkg.jl/issues/3935
> [release-1.10] Pkg.precompile: Handle when the terminal is very short

- src/API.jl
- src/Artifacts.jl
- src/MiniProgressBars.jl
- src/Operations.jl
- src/PlatformEngines.jl
- test/artifacts.jl
```
% JULIA_DEPOT_PATH=$(mktemp -d): JULIA_PKG_PRECOMPILE_AUTO=0 ./julia --project=../Pkg.jl -t1 -e 'import Pkg; Pkg.activate(temp=true); @time Pkg.add("FFMPEG")'
...
12.999424 seconds (9.81 M allocations: 915.741 MiB, 2.30% gc time, 73 lock conflicts, 11.69% compilation time: 16% of which was recompilation)
```
```
% JULIA_DEPOT_PATH=$(mktemp -d): JULIA_PKG_PRECOMPILE_AUTO=0 ./julia-t1 -e 'import Pkg; Pkg.activate(temp=true); @time Pkg.add("FFMPEG")'
...
23.540455 seconds (9.37 M allocations: 887.289 MiB, 0.82% gc time, 123 lock conflicts, 5.85% compilation time: 18% of which was recompilation)
```
https://github.com/user-attachments/assets/8f1024d6-f255-420c-a70e-becdbfa1dd86
Todo
> Parallelize artifact downloads. Update progress bar styling.

- test/new.jl
https://github.com/JuliaLang/julia/pull/55614 is failing because Downloads added some `@debug` statements, and `@test_logs` sets `min_level` globally, so these tests started picking them up.
> make some test_logs match any because of new Downloads debugs

- src/API.jl
- src/Pkg.jl
- src/REPLMode/command_declarations.jl
- src/manifest.jl
- test/manifests.jl
This PR adds a new kwarg to `instantiate`, `manifest_version_check_mode`, which can be used to turn the existing manifest version warnings into errors. We keep strict control over our Julia versions and dependencies, and never want to have a mismatch between the running Julia version and the manifest's Julia version. This kwarg would greatly simplify this behavior for that use case.
I'm not tied to this exact implementation; I could also implement the kwarg as a bool, or add a `:none` mode, etc.
> Add `julia_version_strict` option to `instantiate`

- src/Artifacts.jl
- src/MiniProgressBars.jl
- src/Operations.jl
- src/PlatformEngines.jl
This PR replaces the artifact download progress bar with a status message if an installation step takes over half a second.
Here the unpacking step for Qt6Base takes over half a second.
This is required for #4001, where installing may take up to 60 seconds on some systems.
https://github.com/user-attachments/assets/5756c92f-0fca-40e2-9f4f-4e613647aa5b
> Add status messages for artifact installation

- docs/src/creating-packages.md
Based on a recent discussion on slack, this PR adds a guide to capitalisation. Since I saw the `_jll` idea is not mentioned, I added that as well.
> Update naming conventions for packages

- src/Artifacts.jl
Hopefully fixes #3822 
This uses a strategy from https://github.com/isaacs/node-graceful-fs/blob/234379906b7d2f4c9cfeb412d2516f42b0fb4953/polyfills.js#L87-L95 to retry the rename for about a minute to work around anti-virus software temporarily locking a directory with newly created files. This strategy is also used in vscode, Ref: https://github.com/microsoft/vscode/pull/188899
I am not restricting this fix to only Windows, because similar issues can happen on Linux, Ref: https://github.com/isaacs/node-graceful-fs/issues/133
> Retry artifact rename if it fails

- docs/src/getting-started.md
"Only using" tends to (incorrectly) emphasize the notion that the action of using is the only action being done.  Changing to "Using only" more correctly emphasizes the restriction to using only the one thing being mentioned (the global environment). Discussed at https://textranch.com/c/using-only-or-only-using/
> Tweak sentence syntax in getting-started.md

- src/precompile.jl
Without this: (exposing `pkg_precompile` which it usually isn't)
```
julia> @time Pkg.pkg_precompile()
1.796371 seconds (2.23 M allocations: 125.344 MiB, 4.53% gc time, 66.34% compilation time: 9% of which was recompilation)
```
With
```
julia> @time Pkg.pkg_precompile()
0.929547 seconds (555.18 k allocations: 35.390 MiB, 2.02% gc time, 29.93% compilation time: 32% of which was recompilation)
```
The code is quite small. Do we want to make a utility in Base or just copy it here?
> Use same PrecompileTools.jl approach as REPL to precompile

- docs/src/creating-packages.md
As discussed in https://github.com/JuliaLang/Pkg.jl/pull/3600, Pkg output always displays the parent package name next to the extension name. The naming from the current pkg docs example (`PlottingContourExt`) makes Pkg output super verbose, like `Plotting -> PlottingContourExt`. Especially for longer package names, it can easily exceed typical line length.
Here, I update the docs to show shorter nonredundant naming, `ContourExt` (leading to `Plotting -> ContourExt` output). Many packages already follow this short naming, and presumably more will do if it becomes the official recommended way.
> update package extension naming docs

- src/Registry/Registry.jl
Seeing https://discourse.julialang.org/t/adding-package-to-new-environment-takes-long-time/119518/5 makes me wonder how many people out there might be stuck with General installed via the old methods, so this adds a note if so.
~~I can't imagine anyone intentionally uses either on newer versions for General..~~
If anyone is intentionally using an old format this check can be disabled via
`JULIA_PKG_GEN_REG_FMT_CHECK=0`
> warn if General is installed via the old slow methods

- src/REPLMode/REPLMode.jl
Fixes 3x PythonCall startup regression because of: https://github.com/JuliaPy/CondaPkg.jl/issues/145 (at least least if backported to 1.11).
```
$ julia +1.11 --compile=min
julia> @time Pkg.REPLMode.gen_help()
0.180643 seconds (91.88 k allocations: 2.218 MiB, 17.97% compilation time)
vs.
julia> @time Pkg.REPLMode.gen_help()
2.129547 seconds (871.64 k allocations: 44.875 MiB, 5.32% gc time, 99.94% compilation time)
```
That one function slows down CondaPkg, and therefore also PythoCall, by that amount on 1.11
> REPLMode.jl: set compiler_options optimize = 1

- ext/REPLExt/REPLExt.jl
- test/repl.jl
Replaces `REPLExt.projname` with `REPL.projname` since they are identical.
Will solve https://github.com/JuliaLang/julia/issues/55850 for situations where Pkg is loaded once https://github.com/JuliaLang/julia/pull/55851 is merged.
Test will be covered by https://github.com/JuliaLang/julia/pull/55851.
> Fix julia#55850 by using safe_realpath instead of abspath in projname

- test/new.jl
- test/pkg.jl
- test/repl.jl
See https://buildkite.com/julialang/julia-master/builds/40302#01922f49-90f7-4410-9c2b-53fda2abb7a6/847-875
because https://github.com/JuliaLang/Example.jl/releases/tag/v0.5.5 and https://github.com/JuliaLang/Example.jl/releases/tag/v0.5.4
Our tests assumed that there was a version on the tip of Example master that was unregistered...
> test fixes because Example v0.5.4 and v0.5.5 were registered

- src/Resolve/Resolve.jl
- test/resolve.jl
This fixes #4030. Also adds a reduced test case.
This was a rather simple bug in the greedy resolver that failed to actually account for all of the constraints. It's actually quite surprising how it went unnoticed for so long.
> Fix greedy resolver failure (producing an invalid solution)

- src/Resolve/Resolve.jl
- test/resolve.jl
Fix #4030
(cherry picked from commit e06588db6cc95ab686bf16885ee0081a9087adb6)
> Backport: Fix the greedy resolver (#4032)

- src/REPLMode/REPLMode.jl
- test/repl.jl
I'm investigating. Seems like appending `:` to `JULIA_DEPOT_PATH` hides the bug.
> [release-1.10] Manually backport #4025

- docs/src/toml-files.md
I was just going to replace `ism` with `is`
but I figured a very slight rephrasing  that deletes that word entirely  makes it clearer anyway
> Remove typo in workspaces section

- src/MiniProgressBars.jl
After suggestion by @tecosaur, also use the heavy right box drawing character.  Can be tested with:
```julia
function test_progress(n, dt)
io = stdout
bar = Pkg.MiniProgressBars.MiniProgressBar(; indent=1, header = "Downloading packages", color = Base.info_color(),
mode=:int, always_reprint=true)
bar.max = n
for i in 1:n
bar.current = i
Pkg.MiniProgressBars.show_progress(io, bar)
sleep(dt)
end
end
```
Doing something like `test_progress(1000, 0.001)` shows some difference vs the old behavior.
> smoothen progress bar

- src/MiniProgressBars.jl
Fixed in #4008, then reintroduced in #4005 from what I assume is unfortunate timing.
@IanButterworth
> Re-remove double space before progress bar

- src/API.jl
- src/Operations.jl
- src/Resolve/Resolve.jl
A few things in Pkg rely on inference to figure out (empty) collection types and error if inference can't figure it because the subsequent method signatures are narrow.
I wouldn't really care for any other package, but when working on inference it's not uncommon for it to temporarily be somewhat broken. It's useful to still have Pkg available so that the build finishes and that it is possible to install extra packages for debugging.
> Make Pkg more robust to poor inference

- src/MiniProgressBars.jl
The progress bar would "bounce" by not printing any `:light_black` characters when `n_left == 0` but `n_filled != max_progress_width`.
```
#Before
julia> bar.current=980;show_progress(stdout,bar)
Downloading packages ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺ 980/1000
#After
julia> bar.current=980;show_progress(stdout,bar)
Downloading packages ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 980/1000
```
> Fix end of progress bar

- docs/src/environments.md
- src/Operations.jl
- test/new.jl
- test/resolve.jl
fixes https://github.com/JuliaLang/Pkg.jl/issues/3066
(cc @haberdashPI)
edit: I'll need to update the tests
> Tweak wording to make "no changes" message more accurate

- ext/REPLExt/REPLExt.jl
- ext/REPLExt/completions.jl
> 1.11 backports

- test/artifacts.jl
No need to commit privacy violations here, when we have a API method for doing this for this purpose
> fix Base.unreference_module call

- src/Operations.jl
`pkg_uuids` is unused, and `pkgs` doesn't appear to be mutated after the copy.
> rm dead code

- src/Operations.jl
Fixes https://github.com/JuliaLang/Pkg.jl/issues/4058
> strip out tree_hash for stdlibs that have have been freed in newer julia versions

- ext/REPLExt/REPLExt.jl
I don't think this fixes https://github.com/JuliaLang/julia/issues/56216 but it seems safer given other unsupported repl modes exist.
> REPLExt: check for compliant repl mode during repl init

- src/GitTools.jl
Libgit2's "Resolving Deltas" code is extremely slow (https://github.com/libgit2/libgit2/issues/4674) on larger repositories, so it is important to have an accurate progress bar to avoid users thinking the download is stuck. We had this implemented. However, we were never actually switching to it, because the progress meter thought the progress was jumping backwards and wouldn't actually update because of it. Fix that by resetting it on the first switch to resolving deltas.
> Actually switch to "Resolving Deltas"

- src/API.jl
Don't squash?
I backported them while looking into https://github.com/JuliaConcurrent/Atomix.jl/issues/44 and figured I might as well submit a PR.
> [backports-release-1.10] Backport julia/#55910 and julia/#56621

- src/Artifacts.jl
#4001 was marked with a backport-1.11 label but wasn't part of #4037. It did get in 1.10 with #4036.
This also includes #3827 since it is a related improvement and by adding both it avoids merge conflicts.
As suggested by @IanButterworth in https://discourse.julialang.org/t/error-ioerror-rm-c-users-35879-julia-artifacts-jl-wek1vy-bin-directory-not-empty-enotempty/123142/6?u=visr.
> Backport artifact rename to 1.11

- test/new.jl
`StaticArrays@1.5.0` errors on `julia-1.11` and so does `StaticArrays@≤1.5.16` (https://github.com/JuliaRegistries/General/pull/86950#issuecomment-2403361516)
I tried to restrict `StaticArrays@≤1.5.16` to `julia-1.10` in the General Julia Registry in https://github.com/JuliaRegistries/General/pull/116935, but my PR was reverted in https://github.com/JuliaRegistries/General/pull/117626 due to the Pkg tests failing on `julia-1.11`, explicitly demanding to add `StaticArrays@1.5.0` to test the `why` functionality.
In order to restrict `StaticArrays@≤1.5.16` to `julia-1.10` and preventing the Pkg tests from erroring, we would need to adapt the `StaticArrays` version added in the `why` tests to be higher than `1.5.16` and below `1.6.0`, e.g. `1.5.20`.
Would it be possible to adjust this in the …
> Increase version of `StaticArrays` in `why` tests

- src/Types.jl
Calling these former stdlibs is confusing, I think.
My understanding:
- stdlib - package that ships with julia (no git-tree-sha1 in the manifest)
- upgradable stdlib - package that ships with julia, which can optionally be upgraded (gets a git-tree-sha1 if upgraded)
- former stdlibs - a package that used to be shipped with julia but isn't any longer (no packages yet, AFAIK)
If a julia 2.0 is cut, then upgradable stdlibs are primed to become former stdlibs, i.e. not shipped with julia, but before that it's confusing I think.
Also I don't believe we document that some stdlibs can be upgraded.
> rename FORMER_STDLIBS -> UPGRADABLE_STDLIBS

- CHANGELOG.md
- docs/src/environments.md
- src/Operations.jl
- test/new.jl
See https://github.com/JuliaLang/julia/pull/56769
> status: highlight when deps have different loaded versions

- src/precompile.jl
Before:
```
1.379429 seconds (3.39 M allocations: 211.476 MiB, 2.36% gc time, 60.64% compilation time: 38% of which was recompilation)
```
After:
```
0.963989 seconds (2.83 M allocations: 182.510 MiB, 1.67% gc time, 42.22% compilation time: 75% of which was recompilation)
```
> Improve latency for `Pkg.add`

- src/Operations.jl
- src/Types.jl
> When in doubt, do things in bulk
The timings below will vary depending on the size of the artifact usage log file but I guess my computer is somewhat representative:
```
julia> ENV["JULIA_PKG_PRECOMPILE_AUTO"] = 0
0
julia> Pkg.activate(; temp=true)
julia> @btime Pkg.add("Plots")
618.572 ms (4700447 allocations: 339.36 MiB)
428.434 ms (3376261 allocations: 268.50 MiB)
``` 
Looking at a TimerOutput profile we can see how the runtime for `download_artifacts` changes:
Master:
```
───────────────────────────────────────────────────────────────────────────────────────────────
Time                    Allocations      
───────────────────────   ────────────────────────
Tot / % measured:                   829ms /  99.4%            340MiB /  99.3%    
Section                              ncalls …
```
> avoid writing and reparsing the artifact usage file once per artifact file in the project deps

- src/API.jl
Improves the error seen [here](https://github.com/JuliaLang/julia/pull/56708) from a method error to an error with info.
> Check source path is found when getting package_info

- test/new.jl
It turns out OpenSSL_jll is conditionally loaded, and not loaded at all on Windows, so use `Base.is_stdlib` instead.
On https://github.com/JuliaLang/julia/pull/56708
```
julia> OpenSSL_pkgid = Base.PkgId(Base.UUID("458c3c95-2e84-50aa-8efc-19380b2a3a95"), "OpenSSL_jll")
OpenSSL_jll [458c3c95-2e84-50aa-8efc-19380b2a3a95]
julia> Base.is_stdlib(OpenSSL_pkgid)
true
```
> Fix OpenSSL_jll detection

- src/Resolve/graphtype.jl
Nothing dramatic but trying to grab some low hanging fruits.
```
Resolve.Graph               1    125ms   24.9%   125ms    136MiB   50.8%   136MiB
``` 
vs
```                       
Resolve.Graph               1    102ms   21.0%   102ms    104MiB   44.1%   104MiB
```
> slightly improve memory in resolver code

- src/Operations.jl
Reported here https://github.com/JuliaRegistries/General/pull/122129#issuecomment-2572659866
```
ERROR: KeyError: key v"1.0.11+3" not found
Stacktrace:
[1] getindex
@ ./dict.jl:498 [inlined]
[2] resolve_versions!(env::Pkg.Types.EnvCache, registries::Vector{Pkg.Registry.RegistryInstance}, pkgs::Vector{Pkg.Types.PackageSpec}, julia_version::VersionNumber, installed_only::Bool)
@ Pkg.Operations ~/.asdf/installs/julia/1.10.7/share/julia/stdlib/v1.10/Pkg/src/Operations.jl:452
[3] up(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}, level::Pkg.Types.UpgradeLevel; skip_writing_project::Bool, preserve::Nothing)
@ Pkg.Operations ~/.asdf/installs/julia/1.10.7/share/julia/stdlib/v1.10/Pkg/src/Operations.jl:1546
[4] up
@ ~/.asdf/installs/julia/1.10.7/share/julia/stdlib/v1.10/Pkg/src/Operati …
```
> Fix JLL version fix fix

- test/extensions.jl
- test/new.jl
- test/project_manifest.jl
- test/sources.jl
- test/utils.jl
- test/workspaces.jl
The tests assume the copied files are writable, so this makes this assumption explicit and enforces it. This allows running the Pkg tests as part of Base.runtests of an installed Julia installation, where sources might be readonly.
> Use copy_test_packages in some more places, and ensure that the copied test package is user writable.

- src/precompilation.jl
Fixes this error on 1.10.8 reported by @fredrikekre 
The error was introduced in backport https://github.com/JuliaLang/Pkg.jl/pull/4107 but I'm not sure why tests didn't catch it as we do test for pidlocked precompilation https://github.com/JuliaLang/Pkg.jl/blob/6390ea92bf585e182c96cb5db7529c067874e5f5/test/api.jl#L235-L261
```
◐ PkgServer Being precompiled by another process (pid: 981928, pidfile: /home/fredrik/.julia/compiled/v1.10/PkgServer/6eohG_aD2qu.ji.pidfile)
InfoUnhandled Task ERROR: MethodError: no method matching isprecompiled(::Base.PkgId; ignore_loaded::Bool, flags::Base.CacheFlags)
isprecompiled(::Base.PkgId; ignore_loaded, stale_cache, cachepaths, sourcepath) got unsupported keyword argument "flags"
@ Base loading.jl:1459
Stacktrace:
[1] …
```
> [release-1.10] Remove incomplete support for precompile configs

- ext/REPLExt/REPLExt.jl
Fixes https://github.com/JuliaLang/julia/issues/57243
Missed this in https://github.com/JuliaLang/julia/pull/57192
```
julia> a[1]┌ Error: Error in the keymap
│   exception =
│    UndefVarError: `check_for_hint` not defined in `REPL.LineEdit`
│    Suggestion: check for spelling errors or missing imports.
│    Stacktrace:
│     [1] getproperty
│       @ ./Base_compiler.jl:47 [inlined]
│     [2] (::REPLExt.var"#repl_init##0#repl_init##1"{REPL.LineEdit.Prompt})(::REPL.LineEdit.MIState, ::REPL.LineEditREPL, ::Vararg{Any})
│       @ REPLExt ~/.julia/juliaup/julia-nightly/share/julia/stdlib/v1.12/Pkg/ext/REPLExt/REPLExt.jl:184
│     [3] #invokelatest#1
│       @ ./essentials.jl:1057 [inlined]
│     [4] invokelatest
│       @ ./essentials.jl:1053 [inlined]
│     [5] …
```
> Update LineEdit internal for hints

- src/Pkg.jl
- src/Types.jl
There is a use case where one wants to provide extra "fake" stdlibs after Pkg has been precompiled. Right now, Pkg stores the set of stdlibs during precompile time breaking that use case. This resets it.
> reset caching of STDLIBs reading after precompilation is done

- test/historical_stdlib_version.jl
Originally the tests added here were
```
dependencies = [PackageSpec(; name="CMake_jll", version = v"3.24.3")]
Pkg.add(deepcopy(dependencies); platform, julia_version=nothing)
```
which hit an error, but it turned out to be an incomplete `VersionNumber` that the Resolver wasn't making clear https://github.com/JuliaLang/Pkg.jl/issues/4159
Note `v"3.24.3+0"` exists, but `v"3.24.3"` doesn't.
> Add more tests for BinaryBuilder usage

- src/Operations.jl
Given the TODO and referenced issue https://github.com/JuliaLang/julia/issues/33212 is fixed/closed. Has been since 2020.
cc. @davidanthoff
> Enable windows tree_hash checking within install_archive

- docs/src/toml-files.md
Ref: <https://github.com/JuliaLang/julia/pull/56709>.
> Update docs for versioned manifest

- src/Operations.jl
- src/utils.jl
Fixup #4168 
I missed this detail in https://github.com/JuliaLang/Pkg.jl/pull/4168#discussion_r1970925988
See failures in https://github.com/JuliaLang/julia/pull/57598
> Use temp dir on same filesystem for source install

- src/Operations.jl
Followup on #4180 
Makes me think we should mimic in Pkg CI the temp dir not being on the same filesystem as the depot, like it is in Julia CI
> Followup #4180: Fix the right temp dir

- src/Operations.jl
#4180 introduced using `.julia/tmp`
On reflection, `temp` would probably be more depot style.
> Rename depot tmp dir to temp

- contrib/list_missing_pkg_tags.jl
Output as of now:
```
Git tag commands for missing Pkg.jl versions:
git tag v1.0.5 1609a05aee5d5960670738d8d834d91235bd6b1e
git tag v1.3.1 f71e2c5a119b9c850f9b357fc8c56068f5b51cc0
git tag v1.4.1 9419c70af69153cd5c4276bff90fbb135e0aa3f1
git tag v1.5.4 0c3ccb119efd8b3182c114599abe78bc4f89dd4c
git tag v1.6.2 ab8f6c8e7fbfc86023e45d937b3298c7afdc872b
git tag v1.6.3 12d944551784d6f84446768738d4e917cd857764
git tag v1.6.5 3d41ca188d72e1dc1862e780f31153d629d6a3dd
git tag v1.6.6 30a31381d06d845999314d39005ee8457bd08924
git tag v1.6.7 292c1e637a0a8e15b8b5fa8e6fe14dcc0b0cd6e5
git tag v1.8.3 354530e4c8c3215d92ae15672e7a2bab1db62f76
git tag v1.8.4 b09e05add2442b2ffae9d7bdd7976a7d36949433
git tag v1.8.5 b09e05add2442b2ffae9d7bdd7976a7d36949433
git tag v1.9.1 3fa06b9f96fc8a180f9285447584c84e4d8d8278
git …
```
> Add a helper script for making missing Pkg tags

- src/Artifacts.jl
- test/artifacts.jl
This shows one possible way of adding an optional download size value to an artifact binding.  While this value is not used anywhere yet, it could be used to create warnings when downloading large artifacts, or to feed progress meters when the server does not provide content size headers.
> Artifacts: Add download size to `Artifacts.toml`

- src/utils.jl
This was sometimes breaking up printing so the test failed. i.e.
```
Installed 2025-03-29T21:02:12.769
artifact FFMPEG                10.6 MiB
```
> Lock io within printpkgstyle to avoid print tearing

- ext/REPLExt/completions.jl
Fixes #4200 
https://github.com/JuliaLang/Pkg.jl/pull/3917 wasn't quite the right fix. I think key thing is knowing whether the were path completions before completing packages, and we also need to know whether to skip the stdlib section.
and
> Fix eagerly stopping hint completions

- src/Artifacts.jl
- src/GitTools.jl
- src/utils.jl
- test/artifacts.jl
> Backports release 1.10

- src/Types.jl
- test/new.jl
Fixes https://github.com/JuliaLang/Pkg.jl/issues/4211
>  add some missing hash definitions

- src/REPLMode/argument_parsers.jl
- test/new.jl
Fixes https://github.com/JuliaLang/Pkg.jl/issues/4214
> improve package syntax parsing a bit

- test/new.jl
- test/test_packages/TestThreads/test/runtests.jl
- test/utils.jl
Alternative to https://github.com/JuliaLang/Pkg.jl/pull/4242 that should work for the transition into https://github.com/JuliaLang/julia/pull/57454 being merged.
> Isolate threads test from parent state

- src/API.jl
- src/Operations.jl
- src/manifest.jl
Fixes https://github.com/JuliaLang/Pkg.jl/issues/4086
> don't use tree hash from manifest if the path is set from sources

- src/Operations.jl
- test/historical_stdlib_version.jl
The code here appeared to be untested and broke whenever something actually used it. Example backtrace:
```
julia> JLLPrefixes.collect_artifact_paths(["ripgrep_jll"])
ERROR: MethodError: no method matching haskey(::Vector{Base.UUID}, ::String)
The function `haskey` exists, but no method is defined for this combination of argument types.
haskey(::Pkg.Types.Manifest, ::Any)
@ Pkg ~/.julia/juliaup/julia-nightly/share/julia/stdlib/v1.13/Pkg/src/Types.jl:323
haskey(::REPL.Terminals.TTYTerminal, ::Any)
@ REPL ~/.julia/juliaup/julia-nightly/share/julia/stdlib/v1.13/REPL/src/Terminals.jl:155
haskey(::LibGit2.CachedCredentials, ::Any)
@ LibGit2 ~/.julia/juliaup/julia-nightly/share/julia/stdlib/v1.13/LibGit2/src/types.jl:1357
...
Stacktrace:
[1] …
```
> Fix historical stdlib fixup if `Pkg` is in the Manifest

- src/Operations.jl
- test/pkg.jl
Currently you can get 
```
ERROR: LoadError: expected package `CSV [336ed68f]` to be registered
Stacktrace:
[1] pkgerror(msg::String)
@ Pkg.Types /opt/hostedtoolcache/julia/1.[11](https://github.com/JuliaManifolds/Manopt.jl/actions/runs/15639606087/job/44064155398#step:8:12).5/x64/share/julia/stdlib/v1.11/Pkg/src/Types.jl:68
[2] check_registered
@ /opt/hostedtoolcache/julia/1.11.5/x64/share/julia/stdlib/v1.11/Pkg/src/Operations.jl:[13](https://github.com/JuliaManifolds/Manopt.jl/actions/runs/15639606087/job/44064155398#step:8:14)29 [inlined]
...
```
Which can make the package listed seem special and send the user off on a wild goose chase about that package.
But the problem is that no registry is installed, so explain that.
I kept the list of packages in in case someone is intentionally …
> Explain that no registry is installed when no registry is installed

- src/Operations.jl
- test/new.jl
- test/pkg.jl
When a user attempts to add a package with a correct name but an incorrect UUID, the error message was previously a generic "package not registered". This could leave the user unsure of the root cause.
This commit enhances the error handling to detect this specific scenario. If the provided package name exists in the registry but with a different UUID, the error message will now include the correct UUID(s) found for that package name, guiding the user toward the correct command.
A new test case is added to ensure the new error message is triggered correctly and displays the expected information.
Fixes #4267
This commit was written by an AI assistant.
> feat(errors): Improve error message for incorrect package UUID

- src/API.jl
Fixes https://github.com/JuliaLang/Pkg.jl/issues/3567
> prompt for confirmation before removing compat entry

- docs/src/creating-packages.md
- docs/src/toml-files.md
Clarify that according to the General README these are guidelines *not* rules, and as such may be overridden with sufficient justification.
> Clarify guidelines

- src/GitTools.jl
- Extracted  function to retrieve the remote URL of a Git repository.
- Used  in  to simplify URL retrieval.
- Improved the error message in `check_valid_HEAD` by including the repository URL.
Should fix https://github.com/JuliaLang/Pkg.jl/issues/4257
> Refactor: Extract geturl function and improve error message

- src/precompile.jl
- src/project.jl
Fixes http://github.com/JuliaLang/Pkg.jl/issues/1853
With this:
```
Could not parse compatibility version spec "invalid_version_spec" for dependency `julia` in "/var/folders/1z/jf841bdj73bdj3vk7kc7f_3w0000gn/T/jl_urojiY/Project.toml"
```
> improve error message info for bad compat entries

- src/API.jl
- src/Operations.jl
- src/Pkg.jl
- src/REPLMode/REPLMode.jl
- src/Registry/Registry.jl
- test/repl.jl
When in repl mode this now will show tips with `pkg> add Foo` rather than `import Pkg; Pkg.add("Foo")`
> Make tips show the repl mode when in repl mode

- src/Types.jl
For #3340.
It seems the `ERROR: Did not find a git repository at /path/to/git-submodule.jl` is generated from the code of
```julia
if !isdir(joinpath(pkg.repo.source, ".git"))
...
end
```
Then I suggest that the modification as
```julia
git_info_path   =   (path -> !isfile(path) ? path : joinpath(dirname(path), (last∘split∘readline)(path)))(joinpath(pkg.repo.source, ".git"))
if !isdir(git_info_path)
...
end
```
which can resolve the real path to the directory `.git/` (generally `/path-to-super-git-repository/.git/modules/name-of-git-submodule.jl`) of the git submodule.
I have tested this modification at 
```log
Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
OS: macOS (arm64-apple-darwin21.5.0)
CPU: 8 × Apple M1
WORD_SIZE: 64
LIBM: libopenlibm
LLVM: …
```
> add support for `Pkg.add(path="/path/to/git-submodule.jl")` directly.

- src/Types.jl
Just noticed this happening:
```
(Pkg) pkg> rm CMake_jll
ERROR: FieldError: type Nothing has no field `path`; Nothing has no fields at all.
Stacktrace:
[1] getproperty
@ ./Base_compiler.jl:57 [inlined]
[2] write_env(env::Pkg.Types.EnvCache; update_undo::Bool, skip_writing_project::Bool)
@ Pkg.Types ~/JuliaPkgs/pkg-4159/src/Types.jl:1234
[3] write_env
@ ~/JuliaPkgs/pkg-4159/src/Types.jl:1216 [inlined]
[4] rm(ctx::Pkg.Types.Context, pkgs::Vector{PackageSpec}; mode::PackageMode)
@ Pkg.Operations ~/JuliaPkgs/pkg-4159/src/Operations.jl:1546
[5] rm
```
> prevent error when updating sources with a non-existing manifest

- src/Operations.jl
- src/utils.jl
- test/new.jl
Fixes https://github.com/JuliaLang/Pkg.jl/issues/1738
> fix `status --diff` to work when package is in a non-root path

- src/Registry/Registry.jl
- test/registry.jl
Extend the registry status command to show more information that can be useful for troubleshooting.
Example:
```
Registry Status 
[xxxxxxxx] REDACTED (git@xxx)
git registry, last updated 2025-07-03 14:11:13
[23338594] General (https://github.com/JuliaRegistries/General.git)
packed registry with hash d46462924dc723db4433cdc5cbc163529d12eba0, last updated 2025-07-03 14:11:13
served by https://pkg.julialang.org (eager flavor) - update available
```
Feel free to bikeshed the layout and suggest more information that is useful and can easily be added.
The first commit updates the update log when a registry is first added. Without this the "last updated" information can be wildly wrong if a registry is removed at some point and much later added again.
~~I haven't looked into how this can be …
> More registry status

- .github/workflows/check.yml
- ext/REPLExt/REPLExt.jl
- ext/REPLExt/precompile.jl
- src/API.jl
- src/Apps/Apps.jl
- src/Artifacts.jl
- src/GitTools.jl
- src/MiniProgressBars.jl
- src/Operations.jl
- src/Pkg.jl
- src/PlatformEngines.jl
- src/REPLMode/REPLMode.jl
- src/Registry/Registry.jl
- src/Resolve/Resolve.jl
- src/Types.jl
- src/fuzzysorting.jl
- src/precompile.jl
- test/pkg.jl
- test/repl.jl
There are more `imports` we can move to `using :` but this cleans up quite a bit for now. Also adds some CI to catch future things.
> fix unused imports reported by ExplicitImports.jl

- CHANGELOG.md
- docs/src/api.md
- docs/src/environments.md
- src/API.jl
- src/Pkg.jl
- test/api.jl
i.e. with this it will precompile the env at the end of this, not after every step
```julia
Pkg.precompile() do
Pkg.instantiate()
Pkg.rm("Foo")
Pkg.add("Bar")
Pkg.dev("Baz")
end
```
Also a non-scoped version:
```julia
Pkg.autoprecompilation_enabled(false)
...
Pkg.autoprecompilation_enabled(true)
```
TODO:
> Add more autoprecompilation controls and `Pkg.precompile() do` to delay precompilation until after operations.

- src/API.jl
- src/Operations.jl
Fixes #4158
Fixes https://github.com/JuliaLang/Pkg.jl/issues/4196
I don't really understand the layers of indirection that the IO goes through to cause this, but this evidently fixes the color issue.
> Fix lack of color in CI and don't warn about loaded packages in test Pkg.precompile. 

- CHANGELOG.md
Based on the list of PRs in https://github.com/JuliaLang/julia/pull/58983
Claude made this.
I decided to include things that might be fixes that get backported. I think it gives a more complete update on changes.
> Add missing recent changelogs

- docs/src/toml-files.md
- src/API.jl
- src/Operations.jl
- src/REPLMode/REPLMode.jl
- src/REPLMode/argument_parsers.jl
- src/Types.jl
- src/utils.jl
- test/manifests.jl
- test/misc.jl
- test/new.jl
- test/repl.jl
- test/subdir.jl
- test/test_packages/sources_only_rev/Project.toml
> Backports release 1.12

- src/Operations.jl
- test/api.jl
- test/historical_stdlib_version.jl
Fixes #4334 
```
(jl_TIjQ4O) pkg> add Pkg@1.14
ERROR: Cannot add stdlib `Pkg` with version specification `1.14`.
The current Julia version 1.13.0-DEV.897 uses `Pkg` v1.13.0.
(jl_TIjQ4O) pkg> add Pkg@1.12
ERROR: Cannot add stdlib `Pkg` with version specification `1.12`.
The current Julia version 1.13.0-DEV.897 uses `Pkg` v1.13.0.
```
I think this is also the only time we actually test that upgradable stdlibs are upgradable (downgradable)?
> Error if the stdlib version requested mismatches current version

- ext/REPLExt/compat.jl
- test/repl.jl
Fixes https://github.com/JuliaLang/Pkg.jl/issues/4343
> Fix missed rename of Operations._compat. Add tests for interactive compat menu

- ext/REPLExt/REPLExt.jl
- ext/REPLExt/compat.jl
Fixes failure in https://github.com/JuliaLang/julia/pull/59235
> Avoid deprecated RadioMenu method

- src/Operations.jl
@ericphanson what do you think? The length of the current one is a bit against the Pkg (cargo) prefix styling
Shorter prefix and blue, as green = action, blue = info ?
Currently
This PR
Re. 
https://github.com/JuliaLang/Pkg.jl/issues/3066
https://github.com/JuliaLang/Pkg.jl/pull/3806
> Nicer no changes formatting

- ext/REPLExt/REPLExt.jl
- test/repl.jl
Fixes https://github.com/JuliaLang/julia/issues/58690
Fixes https://github.com/JuliaLang/julia/issues/58103
Using Claude.
> Fix completion at the end of a complete line

- src/Artifacts.jl
- src/Pkg.jl
runic has a heuristic where it indents inside module if there is more stuff outside the module in the file, so move the const alias of the module to outside the file
> make Artifacts.jl code not be indented in module

- src/Operations.jl
When an upgrade is held back because it would require upgrading a dependency, the message in the current master is something like:
```julia-repl
Info Revise can be updated but at the cost of downgrading other packages. To force upgrade to the latest version, try `add Revise@3.9.0`
```
this PR would change that text to:
```julia-repl
Info Revise can be updated but at the cost of upgrading/downgrading other packages. To force upgrade to the latest version, try `add Revise@3.9.0`
```
Which is more correct and less confusing for the user.
> Fix upgrade message (#4087)

- test/pkg.jl
Add cpu number to temporary name inside unique temp dir for atomicity test otherwise it fails on large cpu counts found on Arm.  tempname was likely producing name clashes across CPUs - is it guaranteed to be unique? e.g. thread-safe?  mktempdir made it clear the directory it was counting the files in.
> Fix loop with large number of CPUs in atomicity test
